### ISSUE TITLE
#crash#个别内测玩家反馈，存档读取时会闪退。

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#1]
Zero Fanker created an issue 2018-08-26
根据反馈，目前有两个玩家在读取存档时发生闪退问题，但是存档文件在我本机测试的时候可以被正常读取。

**Comment by shuiping233** [comment]
RN_Admin
changed status to open
仍然在研究中，希望得到更多反馈。

2018-08-26
 Zero Fanker REPORTER
changed status to resolved
由于BuildingClass_Init函数处理Acedamy相关功能时，没有兼容新的ExtPointer，对于Owner的判空检测存在问题，现在已经修复，同样的问题也发生在UnitClass_Init等函数上。

2018-08-26
 Zero Fanker REPORTER
assigned issue to   Zero Fanker

**Comment by Zero-Fanker** [comment]
无效项
