### ISSUE TITLE
#Bug#科技防御炮炮塔不会旋转

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#10]
IEafeoN created an issue 2018-08-29
![image](https://user-images.githubusercontent.com/49360196/56454204-d3632f80-637f-11e9-89c9-34cb3ac76855.png)
 只能向前攻击

**Comment by shuiping233** [comment]
IEafeoN REPORTER
assigned issue to   Zero Fanker
2018-08-29
 Zero Fanker
changed status to open
已经证实。正在排查原因。

2018-08-30
 Zero Fanker
changed status to resolved
问题原因找到了，是法国洛林导弹系统相关的新逻辑，在判断开火时出的问题，顾此失彼了，现在已经修复，增加了一个语句的判定。
