### ISSUE TITLE
#Bug#心灵星标部署后导致条顿残骸满血

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#100]
【现象】：心灵星标部署后，在控制范围内的条顿残骸回满血了

【反馈人】：开学大礼包

【影响范围】：有心灵星标和德国阵营的地图中

【产生原因】：未知
![image](https://user-images.githubusercontent.com/49360196/56077614-ea020780-5e10-11e9-8a6f-6d3fcdc62301.png)

**Comment by Zero-Fanker** [comment]
@shuiping233  该问题是否能复现？我这边复现不了。

**Comment by shuiping233** [comment]
> @shuiping233 该问题是否能复现？我这边复现不了。

好的，我尝试复现

**Comment by shuiping233** [comment]
> @shuiping233 该问题是否能复现？我这边复现不了。

貌似无法复现了

**Comment by shuiping233** [comment]
G0726P版本已证实无法复现
