### ISSUE TITLE
#Bug#普通模式下，法国古巴无法获得秘密实验室额外兵种

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#101]
【现象】：普通模式下，法国无法获得秘密实验室额外兵种，需要盟军兵营才能获得额外兵种；古巴同理，需要苏联兵营才能获得额外兵种。只要拥有基础兵营就能获得额外兵种

【反馈人】：选材大油籽

【影响范围】：玩家游玩手感

【产生原因】：宣传中心和兵营前哨站
![image](https://user-images.githubusercontent.com/49360196/56077600-c63ec180-5e10-11e9-861f-1b8069b142f1.png)
![image](https://user-images.githubusercontent.com/49360196/56077602-c8088500-5e10-11e9-9358-cba080015099.png)
![image](https://user-images.githubusercontent.com/49360196/56077603-cb037580-5e10-11e9-98d6-9870f6928f4d.png)
![image](https://user-images.githubusercontent.com/49360196/56077604-cd65cf80-5e10-11e9-830d-bc8f768bc82c.png)

**Comment by Zero-Fanker** [comment]
H1031已修正，请验证。 @shuiping233  @yuanbanlao  @Renko-ji

**Comment by shuiping233** [comment]
H1031测试结果：法国玩家占领秘密实验室后有时候会给特殊坦克的建造权限，有时候却又什么都没给，待具体测试

**Comment by shuiping233** [comment]
> H1031测试结果：法国玩家占领秘密实验室后有时候会给特殊坦克的建造权限，有时候却又什么都没给，待具体测试

据进一步测试发现，秘密实验室无法给法国提供恐怖分子的建造权限，导致了这个问题

**Comment by Zero-Fanker** [comment]
在0.99.902上再试一下

**Comment by shuiping233** [comment]
0.99.903a2是否包含这个修复？

**Comment by Zero-Fanker** [comment]
理论上有，试试吧------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月18日(星期天) 中午12:03
***@***.***&gt;;
抄送:&nbsp;&quot;Zero ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug#普通模式下，法国古巴无法获得秘密实验室额外兵种 (#101)

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/115139433-6fee6400-a064-11eb-903f-5a3d313f1b83.png)
![Uploading Snipaste_2021-04-18_16-41-39.png…]()

**Comment by shuiping233** [comment]
![Snipaste_2021-04-18_16-41-39](https://user-images.githubusercontent.com/49360196/115139593-4b46bc00-a065-11eb-87c3-68994b2e1652.png)
![Snipaste_2021-04-18_16-41-21](https://user-images.githubusercontent.com/49360196/115139596-4f72d980-a065-11eb-9463-8d3e23d6884f.png)
![Snipaste_2021-04-18_16-37-35](https://user-images.githubusercontent.com/49360196/115139598-50a40680-a065-11eb-8092-521bbb127fae.png)
0.99.903a2测试结果：法国可以获得恐怖分子，古巴则仍然不能获得额外兵种

**Comment by Zero-Fanker** [comment]
看日志，给的是什么------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月18日(星期天) 下午4:45
***@***.***&gt;;
抄送:&nbsp;&quot;Zero ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug#普通模式下，法国古巴无法获得秘密实验室额外兵种 (#101)

**Comment by shuiping233** [comment]
> 看日志，给的是什么------------------&nbsp;原始邮件&nbsp;------------------ ***@***.***&gt; 发送时间:&nbsp;2021年4月18日(星期天) 下午4:45 ***@***.***&gt;; 抄送:&nbsp;&quot;Zero ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug#普通模式下，法国古巴无法获得秘密实验室额外兵种 (#101)

![Snipaste_2021-04-18_19-49-51](https://user-images.githubusercontent.com/49360196/115145109-96bb9300-a082-11eb-9417-fa141aa7b660.png)
