### ISSUE TITLE
#Bug#油井爆炸会伤害到空军，忠武级战列舰的武器也会伤害到空军

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#102]
【现象】：油井爆炸会伤害到经过的飞行器，忠武级战列舰的武器也会伤害到空军。油井爆炸触及到飞行器会导致蜜汁翻滚飞行
。
【反馈人】：SHUIPING

【影响范围】：遭遇战

【产生原因】：武器效果的立体判定缺陷
![image](https://user-images.githubusercontent.com/49360196/56077591-a4453f00-5e10-11e9-98fc-25db5b373719.png)

**Comment by Zero-Fanker** [comment]
@yuanbanlao @shuiping233  @RN-Hydra  G1203P 已调整，请验证。

**Comment by yuanbanlao** [comment]
G1207P已验证，油井和忠武都不再会对空军造成伤害。

**Comment by yuanbanlao** [comment]
G1207P已验证，油井和忠武都不再会对空军造成伤害。
