### ISSUE TITLE
#Bug#rn三阵营有些单位在建造ui里的顺序有问题

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#106]
【现象】：特别盟军和尤里，盟军的光棱和尤里的脑车排序问题突出，出现了t1单位后面就是t3单位的情况

【反馈人】：113

【影响范围】：普通模式

【产生原因】：未知
![image](https://user-images.githubusercontent.com/49360196/56077445-ec636200-5e0e-11e9-9dbb-b780e28fd316.png)
![image](https://user-images.githubusercontent.com/49360196/56077446-eff6e900-5e0e-11e9-8f60-cec819416624.png)
![image](https://user-images.githubusercontent.com/49360196/56077458-0604a980-5e0f-11e9-8455-f8b1810e80ce.png)
![image](https://user-images.githubusercontent.com/49360196/56077460-08ff9a00-5e0f-11e9-9c93-48ef3e904a74.png)

**Comment by shuiping233** [comment]
在rn其他模式下，由于有特殊单位或者特殊情况，单位和建筑顺序会被打乱，但是可能是模式上的设定。这里专门指出普通模式下的情况

**Comment by Zero-Fanker** [comment]
这主要是单位注册顺序的问题

**Comment by Zero-Fanker** [comment]
@yuanbanlao 把你提的那几个单子单号在这里输入一下。
