### ISSUE TITLE
#Bug#在防御建筑栏的核炮和坦克栏的乌克兰核炮价格有差异

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#107]
【现象】：如图所示，在不同版面的价格不一样，防御建筑栏的核炮明显更贵

备注：在只有苏军t4情况下，两边的核炮价格同是2250。当建造了工业工厂后，战争工厂生产的核炮价格降低到1800

【反馈人】：113

【影响范围】：无

【产生原因】：未知

![image](https://user-images.githubusercontent.com/49360196/56077393-4879b680-5e0e-11e9-82ce-bff4dd3b78f7.png)

![image](https://user-images.githubusercontent.com/49360196/56077394-50395b00-5e0e-11e9-9770-b9e61854277d.png)

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/56077406-76f79180-5e0e-11e9-94c9-709d98d04e79.png)

**Comment by Zero-Fanker** [comment]
H1031已修正，请验证。

**Comment by shuiping233** [comment]
![Snipaste_2020-11-07_19-10-09](https://user-images.githubusercontent.com/49360196/98439449-e5a4ea00-212c-11eb-97a7-0f61954400a4.png)
![Snipaste_2020-11-07_19-10-06](https://user-images.githubusercontent.com/49360196/98439467-fc4b4100-212c-11eb-97bc-b3c29d703c2a.png)
H1031B测试结果：工业工厂不再降低载具列表核炮的价格，t4则全部核炮都削减10%的价格
