### ISSUE TITLE
#Bug#苏系阵营的先锋政委的加速buff会对中立单位生效

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#108]
【现象】：先锋政委的加上buff会对中立单位产生效果

【反馈人】：SHUIPING

【影响范围】：没有

【产生原因】：未知

**Comment by shuiping233** [comment]
我记得有图的，算了，得补了

**Comment by shuiping233** [comment]
![QQ截图20190502093051](https://user-images.githubusercontent.com/49360196/57052963-6f186800-6cbd-11e9-866a-25886b4a1f2d.png)

G0428E经过测试，该问题已经解决
