### ISSUE TITLE
#Bug#喷屎色盘不对

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#11]
IEafeoN created an issue 2018-08-30
![image](https://user-images.githubusercontent.com/49360196/56454192-a282fa80-637f-11e9-94d2-0fabdbdc7d3b.png)
 屎糊了！！！！！

**Comment by Zero-Fanker** [comment]
@yuanbanlao  @shuiping233  @Renko-ji  G1207P已修复，请验证。

**Comment by yuanbanlao** [comment]
G1207P已验证，shit不是糊的了。

**Comment by yuanbanlao** [comment]
G1207P已验证，shit不是糊的了。

**Comment by shuiping233** [comment]
![Uploading GIF34.gif…]()

**Comment by shuiping233** [comment]
![GIF34](https://user-images.githubusercontent.com/49360196/70374099-45e24900-192a-11ea-823b-8631931bdc9a.gif)

**Comment by shuiping233** [comment]
打爆厕所之后中心那坨喷射物还是彩色的，不知道算不算

**Comment by Zero-Fanker** [comment]
检查你的版本号------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2019年12月7日(星期六) 晚上7:50
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Assign"<assign@noreply.github.com>;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#喷屎色盘不对 (#11)



打爆厕所之后中心那坨喷射物还是彩色的，不知道算不算
 
&mdash;

**Comment by shuiping233** [comment]
> 检查你的版本号------------------ 原始邮件 ------------------ 发件人: "shuiping"<notifications@github.com> 发送时间: 2019年12月7日(星期六) 晚上7:50 收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>; 抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Assign"<assign@noreply.github.com>; 主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#喷屎色盘不对 (#11) 打爆厕所之后中心那坨喷射物还是彩色的，不知道算不算 &mdash; You are receiving this because you were assigned. Reply to this email directly, view it on GitHub, or unsubscribe.

果真我脑子抽风进水了

**Comment by shuiping233** [comment]
![GIF35](https://user-images.githubusercontent.com/49360196/70382517-73fe7200-1998-11ea-9795-29f1f1149ad1.gif)
