### ISSUE TITLE
＃Bug ##公测0.99.F1028A＃emp格林导弹在停电状态下仍然可以正常攻击

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#116]
【现象】：emp格林导弹在停电状态下仍然可以正常攻击
【反馈】人：shuiping
【影响范围】：含有法国的对战
【产生原因】：未知
![QQ截图20190501105714](https://user-images.githubusercontent.com/49360196/57004600-cc031800-6c02-11e9-8fe5-97e44aee1510.png)

**Comment by Zero-Fanker** [comment]
已经修复，需要测试

**Comment by shuiping233** [comment]
> 已经修复，需要测试

G0505B版本经过测试，该问题已经解决，测试通过

![QQ截图20190511090101](https://user-images.githubusercontent.com/49360196/57563038-982aae00-73cb-11e9-97ae-97b3b054fbd0.png)
