### ISSUE TITLE
#Bug#盟军投弹兵捡取了攻击箱子之后手雷的爆炸动画不一样了

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#119]
【现象】：盟军投弹兵捡取了攻击箱子之后手雷的爆炸动画不一样了
【反馈人】：shuiping
【发现版本号】：F1028
【影响范围】：盟军阵营
【产生原因】：ww的隐藏逻辑
![QQ截图20190501124100](https://user-images.githubusercontent.com/49360196/57007969-2d38e480-6c1f-11e9-8075-b88c9ce7eab9.png)

**Comment by Zero-Fanker** [comment]
正常现象，不考虑修改。
