### ISSUE TITLE
#Bug#战列舰会对任何信标做出反应（包括敌方）

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#12]
IEafeoN created an issue 2018-08-30
E907无此bug，光明星无此bug 
![image](https://user-images.githubusercontent.com/49360196/56454183-88e1b300-637f-11e9-982b-6be5700999a8.png)

**Comment by shuiping233** [comment]
Zero Fanker
changed status to resolved
由于内测之前某版为战列舰允许了每个炮塔独立寻敌而引起了这个bug，现在已经修复。经过测试发现光明星也有类似的问题，现在也已经一并修复。
