### ISSUE TITLE
#Bug#尤里的空降炸弹可以被神经毒气混乱

### ISSUE THREAD

**Issue by ThomasSneddon** [Zero-Fanker/RN_All_Issues#123]
【现象】：尤里的空降炸弹可以被神经毒气混乱
【反馈人】：永恒_叶
【发现版本号】：H.G0428E
【影响范围】：
【产生原因】：

**Comment by Zero-Fanker** [comment]
G0715已修改，请测试

**Comment by shuiping233** [comment]
> G0715已修改，请测试

![QQ截图20190716201515](https://user-images.githubusercontent.com/49360196/61293549-8966da00-a806-11e9-8b23-f7edae6af90a.png)
G0715版本经过测试，该问题已经解决，测试通过
