### ISSUE TITLE
#优化#【功能开发】瞬间上下车逻辑

### ISSUE THREAD

**Issue by ThomasSneddon** [Zero-Fanker/RN_All_Issues#124]
【现象】：如果要进行分兵下车（工程师挨个出来占油井）的操作，在瞬间上下车模式下会很困难
【反馈人】：永恒_叶
【发现版本号】：H.G0428E
【影响范围】：
【产生原因】：

**Comment by Zero-Fanker** [comment]
H0229已引入，但缺少对载具下车的区别判定。
@klighting444  小碗归档到功能开发的部分吧
