### ISSUE TITLE
#建议#削弱战术核炮的伤害

### ISSUE THREAD

**Issue by Fantasycho** [Zero-Fanker/RN_All_Issues#125]
【描述】**增加电力消耗并提升科技等级到T3以上**
【原因】战术核炮可以收起并重新展开，机动性十分出众，可以三炮秒掉乌克兰的T4堡垒却仅仅是个T2，在科技与伤害上都过于强势，一炮能秒掉成片T1，T4单位都少有能活过三个一轮齐射的。
【期望解决时间】日牛下版本内测

**Comment by Zero-Fanker** [comment]
@yuanbanlao @shuiping233 确认下这个单子还需不需要弄

**Comment by Zero-Fanker** [comment]
由于平衡数据已经交给平衡组，故不再纠结拖了这么久的单子
