### ISSUE TITLE
#Bug#多人联机使用对战平台时-win指令无法进入游戏

### ISSUE THREAD

**Issue by Fantasycho** [Zero-Fanker/RN_All_Issues#127]
【现象】：使用ra2md.exe作为游戏时（多人联机），-win命令会导致黑屏后秒闪框，游戏无法打开。
【反馈人】：
【发现版本号】：G0505
【影响范围】：影响多人联机体验
【产生原因】：未知

**Comment by Zero-Fanker** [comment]
根据目前的现有逻辑，可以借助大写的-WIN在Win10下通过手动设置16色的方式来绕过qres启动窗口化。暂时没有想出更好的解决办法。

**Comment by Zero-Fanker** [comment]
DTA开发过程中用系统判定的方法进行区分对待，启动器方式不再考虑兼容。
