### ISSUE TITLE
#Bug#盟军侦查卫星可以通过间谍偷车场升级

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#13]
IEafeoN created an issue 2018-09-01
其他支援类飞机可能也存在问题

**Comment by shuiping233** [comment]
Zero Fanker
飞行器类单位不会有的，卫星是载具类，所以会受到影响。

2018-09-01
 Zero Fanker
changed status to resolved
已经证实了卫星缺少“禁止升级”的语句，现已修复。
