### ISSUE TITLE
#Bug#德国王牌车组传送的灰熊进入坦克碉堡后不会因为时间截止而消失

### ISSUE THREAD

**Issue by Fantasycho** [Zero-Fanker/RN_All_Issues#130]
【现象】：德国王牌车组传送的灰熊进入坦克碉堡后不会因为时间截止而消失。
【反馈人】：永恒_叶
【发现版本号】：G0507
【影响范围】：使用德国进行游戏
【产生原因】：AE自爆对坦克碉堡内单位无效？

**Comment by Zero-Fanker** [comment]
已修正，请测试反馈

**Comment by shuiping233** [comment]
> 已修正，请测试反馈

G0512B版本经过测试，该问题已经解决，测试通过

![QQ截图20190519134312](https://user-images.githubusercontent.com/49360196/57978261-2e9a4780-7a3c-11e9-8689-e99a8d430fea.png)
![QQ截图20190519134332](https://user-images.githubusercontent.com/49360196/57978262-2e9a4780-7a3c-11e9-9247-1ffe2c3566d3.png)
