### ISSUE TITLE
#Bug#AircraftType单位在地图无法使用连续的脚本命令

### ISSUE THREAD

**Issue by Fantasycho** [Zero-Fanker/RN_All_Issues#139]
【现象】：AircraftType单位无法正确执行连续移动到路径点X,Y的脚本
【反馈人】：
【发现版本号】：G0512
【影响范围】：AircraftType的脚本执行
【产生原因】：未知

**Comment by Zero-Fanker** [comment]
jumpjet早就扩展过，没有问题，有问题的是AircraftType

**Comment by Zero-Fanker** [comment]
0.99.916b2 已包含调整 @shuiping233 
可关注番外RA2系列任务的苏4

**Comment by shuiping233** [comment]
> 0.99.916b2 已包含调整 @shuiping233 可关注番外RA2系列任务的苏4

我打了一遍苏4，没发现哪有关Aircraft连续执行脚本的地方（

**Comment by shuiping233** [comment]
0.99.916b2测试通过
![GIF134](https://github.com/user-attachments/assets/cbada37f-824f-4252-91ea-43f8fd867044)
