### ISSUE TITLE
#Bug#地图中任意作战小队使用镜头跟随小队脚本则会直接报错

### ISSUE THREAD

**Issue by Fantasycho** [Zero-Fanker/RN_All_Issues#141]
【现象】：地图中任意作战小队使用镜头跟随小队脚本，游戏会直接报错，EIP是006E9AD7
【反馈人】：
【发现版本号】：G0512
【影响范围】：地图制作
【产生原因】：未知（已修正）

**Comment by Zero-Fanker** [comment]
crash提供crashdump谢谢------------------ 原始邮件 ------------------
发件人: "Fantasycho"<notifications@github.com>
发送时间: 2019年5月16日(星期四) 中午1:49
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Zero-Fanker/RN_All_Issues] #Bug#地图外刷的小队如果执行脚本第一行是0,x，则会直接报错 (#141)



【现象】：地图外刷的脚本第一行使用0,X的话，游戏会直接报错，EIP是006E9AD7
 【反馈人】：
 【发现版本号】：G0512
 【影响范围】：地图制作
 【产生原因】：可能是原版YR就有的bug（推测），或者是用该方式写脚本是不合法的。
 
&mdash;

**Comment by Zero-Fanker** [comment]
无效提交
