### ISSUE TITLE
#Bug#犀牛坦克狂风坦克灰熊坦克遥控坦克攻击电厂及油井会弹框

### ISSUE THREAD

**Issue by Allexacl** [Zero-Fanker/RN_All_Issues#144]
【现象】：犀牛坦克 狂风坦克 灰熊坦克 遥控坦克攻击电厂及油井会弹框
【反馈人】：炫彩大土豆子
【发现版本号】：0.99.H.G0524B
【影响范围】：所有对局
【产生原因】：未知

**Comment by Zero-Fanker** [comment]
已更新，G0525请验证。

**Comment by shuiping233** [comment]
> 已更新，G0525请验证。

G0525版本经过测试，该问题已经解决，测试通过

![QQ截图20190526145608](https://user-images.githubusercontent.com/49360196/58378439-771aad80-7fc6-11e9-948a-be38beb7c1eb.png)
![QQ截图20190526145620](https://user-images.githubusercontent.com/49360196/58378440-771aad80-7fc6-11e9-92b3-95c2466e2aca.png)
![QQ截图20190526145630](https://user-images.githubusercontent.com/49360196/58378441-771aad80-7fc6-11e9-94b8-b9f40e308c3a.png)
