### ISSUE TITLE
#Bug#AI在全体冲锋状态时，归属该AI的条顿坦克残骸会响应指令

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#146]
【现象】：德国ai在全体冲锋的时候会导致条顿残骸”飘移”
【反馈人】：Ten Fanker
【发现版本号】：
【影响范围】：令玩家怀疑日牛是不是闹鬼
【产生原因】：ai卖家全体冲锋导致残骸收到指令，残骸会偏转一下，导致“飘移”

![47e9b08ac352e356](https://user-images.githubusercontent.com/49360196/58375611-64ce4e80-7f89-11e9-861e-bf6dc36bf949.gif)

**Comment by Zero-Fanker** [comment]
除了残骸单位，所有的变形部署单位可能都有这个问题。

**Comment by shuiping233** [comment]
> 除了残骸单位，所有的变形部署单位可能都有这个问题。

叶总之前让我提这个单的时候说过，他测试过其他残骸，没有这个问题。

我尝试测试吧

**Comment by shuiping233** [comment]
> 除了残骸单位，所有的变形部署单位可能都有这个问题。

![GIF2](https://user-images.githubusercontent.com/49360196/59548443-376e3280-8f82-11e9-9c57-4ee192033e1d.gif)

**Comment by shuiping233** [comment]
> > 除了残骸单位，所有的变形部署单位可能都有这个问题。
> 
> ![GIF2](https://user-images.githubusercontent.com/49360196/59548443-376e3280-8f82-11e9-9c57-4ee192033e1d.gif)

这说明了菲林斯残骸是不受影响的，看来条顿是很“独特”的

**Comment by shuiping233** [comment]
> 除了残骸单位，所有的变形部署单位可能都有这个问题。

G0609经过测试，其他残骸单位以及所有的变形部署单位都无此问题

**Comment by Zero-Fanker** [comment]
G1013已修正，请测试。

**Comment by shuiping233** [comment]
G1028P2经过测试，该问题已经解决
![Uploading QQ截图20191103095725.png…]()

**Comment by shuiping233** [comment]
![QQ截图20191103095725](https://user-images.githubusercontent.com/49360196/68079214-4e260080-fe21-11e9-99d1-e25b56a8f137.png)
