### ISSUE TITLE
#建议反馈#苏军米格战机对装甲单位的伤害过于变态

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#147]
【描述】苏军米格战机对装甲单位的伤害过于变态，甚至能一发秒掉天启，这不符合t2战机的定位
【原因】破坏平衡性，弹头修正比异常？
【期望解决时间】下一版本公测

 
![QQ截图20190526150500](https://user-images.githubusercontent.com/49360196/58378543-2ad06d00-7fc8-11e9-9f05-f77dc872471c.png)
![QQ截图20190526150514](https://user-images.githubusercontent.com/49360196/58378544-2b690380-7fc8-11e9-8864-85361e22334b.png)
![QQ截图20190526150559](https://user-images.githubusercontent.com/49360196/58378545-2b690380-7fc8-11e9-8771-e4e35bd60205.png)
![QQ截图20190526150616](https://user-images.githubusercontent.com/49360196/58378546-2b690380-7fc8-11e9-897d-161de614f55c.png)

**Comment by Zero-Fanker** [comment]
@yuanbanlao @Super-StarX  目前计划对矿车比例调至一次只能杀伤50% 对其它数据有什么修改建议吗

**Comment by yuanbanlao** [comment]
在下调t4防空能力之后，终于可以对着t2飞行器开刀了。
个人认为，本身基础伤害大就是米格的问题，单纯对矿车伤害削弱不能完全解决他在小图中异常好使的情况。
个人认为：延长装弹时间，对于小图的建造很有拖延作用。减慢米格的建造速度是一个使得米格在1大图小图作用都有削弱的措施。至于本身攻击力，建议某些战略性单位也增加额外的米格导弹抗性（比如mcv等）

**Comment by shuiping233** [comment]
米格对mcv展开后的形态和mcv移动形态伤害差距太大了吧，展开后至少要10架一起炸才能炸掉，移动形态只需要两架

**Comment by Zero-Fanker** [comment]
> 在下调t4防空能力之后，终于可以对着t2飞行器开刀了。
> 个人认为，本身基础伤害大就是米格的问题，单纯对矿车伤害削弱不能完全解决他在小图中异常好使的情况。
> 个人认为：延长装弹时间，对于小图的建造很有拖延作用。减慢米格的建造速度是一个使得米格在1大图小图作用都有削弱的措施。至于本身攻击力，建议某些战略性单位也增加额外的米格导弹抗性（比如mcv等）

那么我的理解就是下调对特殊补给和建设类单位的输出比例，例如矿车和基地车，同时下调移动速度至和入侵者等同，装弹时间延长至1.5倍，还需要下调对哪些单位的输出吗？

**Comment by yuanbanlao** [comment]
同意，没有，请做数据调整。

**Comment by Zero-Fanker** [comment]
> > 在下调t4防空能力之后，终于可以对着t2飞行器开刀了。
> > 个人认为，本身基础伤害大就是米格的问题，单纯对矿车伤害削弱不能完全解决他在小图中异常好使的情况。
> > 个人认为：延长装弹时间，对于小图的建造很有拖延作用。减慢米格的建造速度是一个使得米格在1大图小图作用都有削弱的措施。至于本身攻击力，建议某些战略性单位也增加额外的米格导弹抗性（比如mcv等）
> 
> 那么我的理解就是下调对特殊补给和建设类单位的输出比例，例如矿车和基地车，同时下调移动速度至和入侵者等同，装弹时间延长至1.5倍，还需要下调对哪些单位的输出吗？

@Crossfield-ClassDestroyer  按照这个来做调整。

**Comment by Zero-Fanker** [comment]
G1013已修改，请验证 @yuanbanlao  @Super-StarX

**Comment by yuanbanlao** [comment]
G1013 已测试，米格战机对矿车，mcv的伤害下降显著。

**Comment by Zero-Fanker** [comment]
数据是否仍然需要调整?------------------ 原始邮件 ------------------
发件人: "yuanbanlao"<notifications@github.com>
发送时间: 2019年10月14日(星期一) 上午10:47
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Assign"<assign@noreply.github.com>;
主题: Re: [Zero-Fanker/RN_All_Issues] #建议反馈#苏军米格战机对装甲单位的伤害过于变态 (#147)



G1013 已测试，米格战机对矿车，mcv的伤害下降显著。
 
&mdash;

**Comment by yuanbanlao** [comment]
当前对mcv和矿车的数值可以接受。

**Comment by Zero-Fanker** [comment]
你归档了吗？------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2019年11月9日(星期六) 下午2:52
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Assign"<assign@noreply.github.com>;
主题: Re: [Zero-Fanker/RN_All_Issues] #建议反馈#苏军米格战机对装甲单位的伤害过于变态 (#147)



Closed #147.
 
&mdash;

**Comment by shuiping233** [comment]
> 你归档了吗？------------------ 原始邮件 ------------------ 发件人: "shuiping"<notifications@github.com> 发送时间: 2019年11月9日(星期六) 下午2:52 收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>; 抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Assign"<assign@noreply.github.com>; 主题: Re: [Zero-Fanker/RN_All_Issues] #建议反馈#苏军米格战机对装甲单位的伤害过于变态 (#147) Closed #147. &mdash; You are receiving this because you were assigned. Reply to this email directly, view it on GitHub, or unsubscribe.

我按错了，我去补补
