### ISSUE TITLE
#Bug#巨炮对磁能要塞的伤害异常

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#148]
【现象】：巨炮攻击磁能要塞的伤害很低，影响平衡性
【反馈人】：日小皮
【发现版本号】：G0525
【影响范围】：影响游戏平衡性
【产生原因】：弹头修正比异常或者装甲类型问题

以下为巨炮攻击天启和磁能要塞的情况（均为一炮）
![QQ截图20190526151217](https://user-images.githubusercontent.com/49360196/58378607-3f613500-7fc9-11e9-984f-ce92a50b4217.png)

**Comment by Crossfield-ClassDestroyer** [comment]
[修改关联.zip](https://github.com/Zero-Fanker/RN_All_Issues/files/4310039/default.zip)

**Comment by Zero-Fanker** [comment]
@yuanbanlao  @RN-Hydra  @Renko-ji  H0315已包含修改，请评估验证。

**Comment by shuiping233** [comment]
现在我可以测试一下，要不去我测？



---原始邮件---
发件人: "Zero Fanker"<notifications@github.com&gt;
发送时间: 2020年3月18日(星期三) 下午3:17
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"shuiping"<1944680304@qq.com&gt;;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#巨炮对磁能要塞的伤害异常 (#148)




 
@yuanbanlao  @RN-Hydra  @Renko-ji  H0315已包含修改，请评估验证。

**Comment by shuiping233** [comment]
H0315测试结果：巨炮单发对磁能要塞的伤害为130，对天启的单发伤害也是130

**Comment by Zero-Fanker** [comment]
> H0315测试结果：磁能要塞血量为2000，巨炮单发对磁能要塞的伤害为130，对天启的单发伤害也是130

对照修改记录验证一下，评估一下当前数值的合理性，主要得让kk验证平衡性

**Comment by yuanbanlao** [comment]
个人建议搁置，等待实战反馈。另外，磁能要塞本身就是高hp低护甲的存在，即使是坦克对他造成的伤害也有限。巨炮定位是aoe中等杀伤，本身就不适合打磁能要塞。如果将来实战中法国面对磁能要塞实在无解，会考虑添加应对方案。

**Comment by Zero-Fanker** [comment]
> 个人建议搁置，等待实战反馈。另外，磁能要塞本身就是高hp低护甲的存在，即使是坦克对他造成的伤害也有限。巨炮定位是aoe中等杀伤，本身就不适合打磁能要塞。如果将来实战中法国面对磁能要塞实在无解，会考虑添加应对方案。

那就关闭了 以后再说。
@klighting444  小碗归档一下吧
