### ISSUE TITLE
#Bug#覆盖在法国兵营的盟军力场护盾动画效果异常

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#149]
【现象】：法国兵营前哨站在被立场护盾覆盖时的动画效果异常
【反馈人】：Ten Fanker
【发现版本号】：G0525
【影响范围】：视觉体验
【产生原因】：yr垃圾引擎 ![2bfbcf34db33b59](https://user-images.githubusercontent.com/49360196/58379224-966c0780-7fd3-11e9-9f0d-d2bb1b00b609.jpg)

![-2c8f6cc3e36d80bf](https://user-images.githubusercontent.com/49360196/58379230-a4218d00-7fd3-11e9-90e9-3ae7093e5a70.jpg)

**Comment by Zero-Fanker** [comment]
![image](https://user-images.githubusercontent.com/14891010/59107018-53fae100-896a-11e9-8745-31d0f7e06243.png)
开发者正在修复，下次更新将包含

**Comment by Zero-Fanker** [comment]
请测试反馈 ; @Leaf-eon

**Comment by shuiping233** [comment]
![QQ截图20190615144648](https://user-images.githubusercontent.com/49360196/59548107-6aadc300-8f7c-11e9-92c6-b55fb3695013.png)
G0609版本经过测试，该问题已经解决，测试通过
