### ISSUE TITLE
超时空单位在读档后超时空CD会重置（原版bug）

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#15]
【现象】：如标题描述。
此bug可用作原版任务核爆辐射尘的速通，偷窃得到超时空突击队之后通过路径点存档读档的方式炸核弹
【反馈人】：Leaf-eon
【发现版本号】：0.99.F1028A
【影响范围】：影响遭遇战和单人任务
【产生原因】：原版逻辑缺陷

**Comment by Zero-Fanker** [comment]
@Leaf-eon @shuiping233 @yuanbanlao @RN-Hydra H0130已修正，请验证。

**Comment by RN-Hydra** [comment]
H0130已验证，在读档后超时空CD并没有重置。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Zero Fanker"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月30日(星期四) 晚上7:23
收件人:&nbsp;"Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;"Estrus"<1575629191@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] 超时空单位在读档后超时空CD会重置（原版bug） (#15)




@Leaf-eon @shuiping233 @yuanbanlao @RN-Hydra H0130已修正，请验证。

**Comment by Zero-Fanker** [comment]
这bug让叶子仔细验证下。

**Comment by Zero-Fanker** [comment]
> 这bug让叶子仔细验证下。

叶子说没问题了，小碗归档一下吧 @klighting444
