### ISSUE TITLE
#Bug#辐射工兵会攻击其无法造成伤害（免疫辐射）的单位

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#152]
【现象】：辐射工兵会攻击辐射武器无法造成伤害的单位，例如恐怖机器人和矿车之类的单位，会导致输出浪费。
【反馈人】：shuiping
【发现版本号】：F1028
【影响范围】：单位操作手感
【产生原因】：wwsb

**Comment by Crossfield-ClassDestroyer** [comment]
针对medium不主动攻击会影响以下单位
各阵营矿车
任务中的三个使用medium护甲
STBOMBER FIGT XJZJ2
呃从结果来看，继承方面基本可以忽略

**Comment by Zero-Fanker** [comment]
@shuiping233 @yuanbanlao @RN-Hydra @Leaf-eon  H0130已修改，请验证。
现在改为不会主动攻击这些目标了，但是强制攻击和还击还是会有的。

**Comment by RN-Hydra** [comment]
H0130验证，但依然出现主动攻击的情况，我用古巴，出的ACS特种运输车，在辐射工兵射程范围内工兵就会自动攻击，主动攻击敌人理解，但自己人也打23333




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zero Fanker"<notifications@github.com&gt;; 
发送时间: 2020年1月30日(星期四) 晚上7:21
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;; 
抄送: "Estrus"<1575629191@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#辐射工兵会攻击其无法造成伤害（免疫辐射）的单位 (#152)




@shuiping233 @yuanbanlao @RN-Hydra @Leaf-eon  H0130已修改，请验证。
 现在改为不会主动攻击这些目标了，但是强制攻击和还击还是会有的。

**Comment by Zero-Fanker** [comment]
> H0130验证，但依然出现主动攻击的情况，我用古巴，出的ACS特种运输车，在辐射工兵射程范围内工兵就会自动攻击，主动攻击敌人理解，但自己人也打23333
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Zero Fanker"<notifications@github.com&gt;; 发送时间: 2020年1月30日(星期四) 晚上7:21 收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;; 抄送: "Estrus"<1575629191@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#辐射工兵会攻击其无法造成伤害（免疫辐射）的单位 (#152) @shuiping233 @yuanbanlao @RN-Hydra @Leaf-eon H0130已修改，请验证。 现在改为不会主动攻击这些目标了，但是强制攻击和还击还是会有的。 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

ACS特性自行了解一下，请修正结论。
