### ISSUE TITLE
#Bug#科技重型防御炮的影子不能正常显示

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#153]
【现象】：科技重型防御炮的影子不正常，如下图
【反馈人】：shuiping
【发现版本号】：G0525
【影响范围】：视觉体验
【产生原因】：未知

![QQ截图20190601091825](https://user-images.githubusercontent.com/49360196/58741704-d22d2400-844e-11e9-9b13-05854765d0c3.png)

**Comment by Zero-Fanker** [comment]
H1031已修正，请验证。

**Comment by shuiping233** [comment]
![Snipaste_2020-11-01_21-12-03](https://user-images.githubusercontent.com/49360196/97803932-8572fb80-1c87-11eb-8877-adcc1e8156f8.png)
![GIF24](https://user-images.githubusercontent.com/49360196/97803936-8c017300-1c87-11eb-8dd2-7bbe9e6d3450.gif)
H1031B测试通过

这两张图或许能看出什么，但是我不太在意细节，谁有空的话可以当列文虎克（笑）
