### ISSUE TITLE
#Bug#苏联战车工厂建造速度太快导致履带等单位会流产

### ISSUE THREAD

**Issue by yuanbanlao** [Zero-Fanker/RN_All_Issues#160]
【现象】：单个重工情况下有可能导致低价载具流产
【发现版本号】：G0615P
【影响范围】：只要出重工就会这样
【产生原因】：建造速度太快

**Comment by shuiping233** [comment]
虽然钱会退回来，但是这影响产能

**Comment by Zero-Fanker** [comment]
@Crossfield-ClassDestroyer  建议使用地图测试修改。
请检查下盟军IFV 苏军履带车和zz 尤里加特林坦克 ，如果单重工连续生产上述单位会导致流产，把这些单位的建造速度调慢到恰好两个可以先后出来即可。

**Comment by Crossfield-ClassDestroyer** [comment]
【测试范围】:造价在1000$以下所有建造速度快的轻甲单位
【测试版本号】：G0824P
【结果】：问题只出现在苏军煤球车和zz上，而且相对严重

**Comment by Zero-Fanker** [comment]
G1013已调整。请验证 @yuanbanlao  @shuiping233

**Comment by shuiping233** [comment]
![GIF24](https://user-images.githubusercontent.com/49360196/68080628-5474a680-fe3a-11e9-858e-166361d2c672.gif)

**Comment by shuiping233** [comment]
G1028P2经过测试，该问题已经解决
