### ISSUE TITLE
#Bug#乌克兰游戏内观战不会获得全屏视野

### ISSUE THREAD

**Issue by yuanbanlao** [Zero-Fanker/RN_All_Issues#162]
【现象】：乌克兰阵营在T3（或以后）的时间段内选择认输观战，所有单位都会爆炸消失但是不会被判定为失败，也就没有全屏视野甚至可以胜利
【反馈人】：（如果是自己的帐户可以不填，代他人提交必填）
【发现版本号】：0615P
【影响范围】：遭遇战，多人联机
【产生原因】：天知道

**Comment by shuiping233** [comment]
会不会是没开快速游戏，然后菲林斯残骸在那？

**Comment by Zero-Fanker** [comment]
@shuiping233 群测最新版本试一下

**Comment by shuiping233** [comment]
G0615P1版本经过测试，该问题已经解决，测试通过

![QQ截图20190708115504](https://user-images.githubusercontent.com/49360196/60782757-7acf5180-a17a-11e9-82aa-34d1404e5a48.png)
![QQ截图20190708115453](https://user-images.githubusercontent.com/49360196/60782758-7acf5180-a17a-11e9-8719-d804221819b1.png)
