### ISSUE TITLE
#Bug#多人联机丢包问题太过于严重

### ISSUE THREAD

**Issue by yuanbanlao** [Zero-Fanker/RN_All_Issues#163]
【现象】：经常出现RE。当游戏速度为6时出现尤其频繁。
【反馈人】：（如果是自己的帐户可以不填，代他人提交必填）
【发现版本号】：0615P
【影响范围】：多人联机
【产生原因】：天知道

**Comment by Zero-Fanker** [comment]
网络问题无法解决。后期考虑cncnet5的UDP协议优化。需进一步评估
