### ISSUE TITLE
#Bug#G0615#新苏联01紫色所属方会训练毒蝎坦克与赤炎坦克

### ISSUE THREAD

**Issue by WZ-113** [Zero-Fanker/RN_All_Issues#165]
【现象】：新苏联01紫色所属方会训练毒蝎坦克与赤炎坦克
【反馈人】：shuiping
【发现版本号】：G0615
【影响范围】：新苏联01游戏体验/剧情体验
【产生原因】：AI条目未改 马王神的新AI

**Comment by shuiping233** [comment]
![4e75f5037a3ba94](https://user-images.githubusercontent.com/49360196/59967038-61fa5580-9557-11e9-80f8-4fdebc903cab.jpg)
![3686302cfb00e732](https://user-images.githubusercontent.com/49360196/59967039-66bf0980-9557-11e9-9c46-3b448c6d6e20.jpg)

**Comment by shuiping233** [comment]
图二说明经历过心灵震荡三年的指挥官指挥能力还不如一位新手指挥官（滑稽）

**Comment by Zero-Fanker** [comment]
AI 在之前已经调整过，可在G0824进行验证。
@WZ-113  @shuiping233  @yuanbanlao

**Comment by yuanbanlao** [comment]
经过验证，ai在8min（实际时长）的游戏中只建造了犀牛等部队，没有毒蝎坦克与赤炎坦克。
