### ISSUE TITLE
#Bug#在遭遇战苏系阵营就算所有建筑被摧毁也无法失败

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#167]
【现象】：在遭遇战苏系阵营就算所有建筑被摧毁无法失败，使得遭遇战无法正常胜利
【反馈人】：shuiping
【发现版本号】：G0615
【影响范围】：游玩体验
【产生原因】：核电废墟逻辑导致内存溢出

**Comment by shuiping233** [comment]
包括ai和玩家

**Comment by shuiping233** [comment]
#162

**Comment by Zero-Fanker** [comment]
经证实，是核电站使用的废墟逻辑导致的内存泄漏问题。

**Comment by shuiping233** [comment]
> 经证实，是核电站使用的废墟逻辑导致的内存泄漏问题。

![GIF](https://user-images.githubusercontent.com/49360196/60154992-8ede8f00-981b-11e9-8464-1aeeb0e8a24d.gif)
