### ISSUE TITLE
#Bug#AI派遣步兵进入敌方战斗碉堡后，碉堡可能因为AI战败而强制变卖

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#168]
【现象】：在遭遇战中中，友方或敌方AI会派遣步兵进入玩家碉堡然后马上售卖，同样的情况玩家却不能
【反馈人】：shuiping
【发现版本号】：F1028A
【影响范围】：游玩体验
【产生原因】：未知

**Comment by Zero-Fanker** [comment]
G1013已修正，请验证。

**Comment by yuanbanlao** [comment]
G1013已验证，敌军在进入玩家的战斗碉堡后不会变卖战斗碉堡。

**Comment by shuiping233** [comment]
再次验证，G1028P2版本，该问题已解决
