### ISSUE TITLE
#建议反馈#削弱宣传飞艇

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#169]
【描述】建议增加宣传飞艇的buff加成，例如buff可以给部队提供5%的攻击力和生命加成。建议削弱飞艇的机炮对载具和建筑的伤害，类似于武直
【原因】宣传飞艇只缓慢回血显得buff作用并不大，飞艇移动速度慢跟不上部队那么buff显得更加没用。很多（并没有）玩家生产一吨飞艇来攻城，恰好飞艇的机炮对载具建筑伤害还不错，吧飞艇用成攻城单位。但很明显的宣传飞艇只是一个辅助的buff单位
【期望解决时间】尽快

**Comment by shuiping233** [comment]
今早与kk pvp，竟然被宣传飞艇轮死了，一堆飞艇的机炮伤害会很高，无论建筑还是单位

**Comment by Renko-ji** [comment]
nb，视野也需要削一下

**Comment by shuiping233** [comment]
> nb，视野也需要削一下

视野不用，基佬夫视野也是这样大

**Comment by shuiping233** [comment]
> nb，视野也需要削一下

工头说是视野是设定，飞艇走得慢其实就没很大关系

**Comment by Renko-ji** [comment]
> > Nb，视野也需要削一下
> 
> 工头说是视野是设定，飞艇走得慢其实就没很大关系

主要是视野有点太大了，那个视野范围比间谍卫星都大

**Comment by shuiping233** [comment]
> > > Nb，视野也需要削一下
> > 
> > 
> > 工头说是视野是设定，飞艇走得慢其实就没很大关系
> 
> 主要是视野有点太大了，那个视野范围比间谍卫星都大

基佬夫和宣传飞艇视野大我觉得没什么，探视野也不是飞艇的主要工作，所以他两视野大没问题

**Comment by shuiping233** [comment]
> > > Nb，视野也需要削一下
> > 
> > 
> > 工头说是视野是设定，飞艇走得慢其实就没很大关系
> 
> 主要是视野有点太大了，那个视野范围比间谍卫星都大

何况飞艇都在后期了，pvp后期缺视野吗？

**Comment by Renko-ji** [comment]
> > > > Nb，视野也需要削一下
> > > 
> > > 
> > > 工头说是视野是设定，飞艇走得慢其实就没很大关系
> > 
> > 
> > 主要是视野有点太大了，那个视野范围比间谍卫星都大
> 
> 何况飞艇都在后期了，pvp后期缺视野吗？

小图是不缺的，大图呢。还要考虑一下多人pvp

**Comment by shuiping233** [comment]
> > > > > Nb，视野也需要削一下
> > > > 
> > > > 
> > > > 工头说是视野是设定，飞艇走得慢其实就没很大关系
> > > 
> > > 
> > > 主要是视野有点太大了，那个视野范围比间谍卫星都大
> > 
> > 
> > 何况飞艇都在后期了，pvp后期缺视野吗？
> 
> 小图是不缺的，大图呢。还要考虑一下多人pvp

小图开局会探路的啊，你后期才开视野？

**Comment by Renko-ji** [comment]
> > > > > > Nb，视野也需要削一下
> > > > > 
> > > > > 
> > > > > 工头说是视野是设定，飞艇走得慢其实就没很大关系
> > > > 
> > > > 
> > > > 主要是视野有点太大了，那个视野范围比间谍卫星都大
> > > 
> > > 
> > > 何况飞艇都在后期了，pvp后期缺视野吗？
> > 
> > 
> > 小图是不缺的，大图呢。还要考虑一下多人pvp
> 
> 小图开局会探路的啊，你后期才开视野？

我的意思是小图不缺视野。。

**Comment by shuiping233** [comment]
> > > > > Nb，视野也需要削一下
> > > > 
> > > > 
> > > > 工头说是视野是设定，飞艇走得慢其实就没很大关系
> > > 
> > > 
> > > 主要是视野有点太大了，那个视野范围比间谍卫星都大
> > 
> > 
> > 何况飞艇都在后期了，pvp后期缺视野吗？
> 
> 小图是不缺的，大图呢。还要考虑一下多人pvp

你不能说你开局啥都不搞，单位不出，不探视野，然后直接t3出基佬夫开视野？

**Comment by shuiping233** [comment]
> > > > > > > Nb，视野也需要削一下
> > > > > > 
> > > > > > 
> > > > > > 工头说是视野是设定，飞艇走得慢其实就没很大关系
> > > > > 
> > > > > 
> > > > > 主要是视野有点太大了，那个视野范围比间谍卫星都大
> > > > 
> > > > 
> > > > 何况飞艇都在后期了，pvp后期缺视野吗？
> > > 
> > > 
> > > 小图是不缺的，大图呢。还要考虑一下多人pvp
> > 
> > 
> > 小图开局会探路的啊，你后期才开视野？
> 
> 我的意思是小图不缺视野。。

那大图缺视野？

**Comment by Renko-ji** [comment]
> > > > > > > > Nb，视野也需要削一下
> > > > > > > 
> > > > > > > 
> > > > > > > 工头说是视野是设定，飞艇走得慢其实就没很大关系
> > > > > > 
> > > > > > 
> > > > > > 主要是视野有点太大了，那个视野范围比间谍卫星都大
> > > > > 
> > > > > 
> > > > > 何况飞艇都在后期了，pvp后期缺视野吗？
> > > > 
> > > > 
> > > > 小图是不缺的，大图呢。还要考虑一下多人pvp
> > > 
> > > 
> > > 小图开局会探路的啊，你后期才开视野？
> > 
> > 
> > 我的意思是小图不缺视野。。
> 
> 那大图缺视野？

也是，那就这样8

**Comment by Zero-Fanker** [comment]
@yuanbanlao  kk看一下这个情况

**Comment by yuanbanlao** [comment]
没看懂。建议重新辩论 @shuiping233 @Renko-ji

**Comment by shuiping233** [comment]
简单讲，就是宣传飞艇降低伤害提高辅助功能，只是以前我觉得宣传飞艇的buff至少可以强一些，毕竟宣传飞艇作为一个古巴特殊单位不是一次性的还这么nb



---原始邮件---
发件人: "yuanbanlao"<notifications@github.com&gt;
发送时间: 2020年10月31日(星期六) 凌晨0:11
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"shuiping"<1944680304@qq.com&gt;;
主题: Re: [Zero-Fanker/RN_All_Issues] #建议反馈#关于宣传飞艇的一些建议 (#169)




 
没看懂。建议重新辩论 @shuiping233 @Renko-ji

**Comment by yuanbanlao** [comment]
确实，古巴的宣传飞艇不是一次性的，而且生存能力很强。所以他的buff是否需要加强有待商榷。

**Comment by Zero-Fanker** [comment]
那咱们现在是维持现状，搁置争议，还是在现阶段先求同存异然后大家一起想一个调整方案?------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;yuanbanlao&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月2日(星期一) 下午2:26
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;Zero Fanker&quot;<zcyfksn@vip.qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #建议反馈#关于宣传飞艇的一些建议 (#169)

**Comment by yuanbanlao** [comment]
目前维持在204单子上的改动吧

**Comment by Zero-Fanker** [comment]
OK，那就以204中调整方案来。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;yuanbanlao&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月2日(星期一) 下午2:33
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;Zero Fanker&quot;<zcyfksn@vip.qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #建议反馈#关于宣传飞艇的一些建议 (#169)

**Comment by Zero-Fanker** [comment]
H1127已经调整，@yuanbanlao kk给出调整细节

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/101283210-fe7bea80-3813-11eb-93fb-a9ed7ccecfc9.png)
我将依照该描述进行测试

**Comment by shuiping233** [comment]
H1127B测试通过，现在宣传飞艇的不享受多重工加成，射程比爱国者少一格
