### ISSUE TITLE
#Bug#充电磁暴线圈会对其射程外的单位或建筑蓄能，但是无法攻击

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#170]
【现象】：充电线圈会对其射程外的单位或建筑蓄能，但是无法攻击，无限蓄能鬼畜
【反馈人】：shuiping
【发现版本号】：G0615
【影响范围】：游玩体验，操作手感
【产生原因】：未知

![QQ图片20190623170354](https://user-images.githubusercontent.com/49360196/59973987-2902c500-95d9-11e9-80ae-851c1b04db90.gif)

**Comment by Zero-Fanker** [comment]
AI相关，不是必现问题，优先级降低

**Comment by shuiping233** [comment]
这是必现啊，不过确实不怎么重要



---原始邮件---
发件人: "Zero ***@***.***&gt;
发送时间: 2021年5月10日(周一) 晚上7:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#充电线圈会对其射程外的单位或建筑蓄能，但是无法攻击 (#170)




 
AI相关，不是必现问题，优先级降低

**Comment by shuiping233** [comment]
此issue以被 #894 替代，故废弃此issue
