### ISSUE TITLE
#Bug#生化起源第一关通关后点击结算的继续按钮后游戏会崩溃

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#171]
【现象】：生化起源第一关通关后点击结算的继续按钮后游戏会崩溃，无法续关
【反馈人】：shuiping
【发现版本号】：G0615
【影响范围】：游玩手感
【产生原因】：未知

**Comment by Zero-Fanker** [comment]
G1207P2已修复，请验证。
