### ISSUE TITLE
#Bug#遭遇战所有模式下所有ai都将优先攻击玩家

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#173]
【现象】：遭遇战所有模式下所有ai都将优先攻击玩家，包括普通模式的混战小队
【反馈人】：公测玩家们
【发现版本号】：G0615P
【影响范围】：遭遇战，游玩手感
【产生原因】：未知

**Comment by Zero-Fanker** [comment]
原方案证实不可行，待议

**Comment by shuiping233** [comment]
目前的测试表明，无论哪个模式，哪个国家的ai，即使玩家有盟友（无论玩家还是ai），所有ai都会优先派遣所有部队集火一个玩家（可能会分兵攻打玩家盟友）

**Comment by Zero-Fanker** [comment]
已证实，并且修正。是WW代码缺陷所致。

**Comment by Zero-Fanker** [comment]
0.99.909 已修复
