### ISSUE TITLE
#Bug#AI使用天启的时候有很大概率会“刷弹”

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#176]
【现象】：AI使用天启的时候有很大概率会“刷弹”，快速射出大量导弹和炮弹，导致天启输出爆炸。
同#177
【反馈人】：shuiping
【发现版本号】：G0615B
【影响范围】：带有天启的ai
【产生原因】：未知

![QQ截图20190626123222](https://user-images.githubusercontent.com/49360196/60151287-bf6bfc00-980e-11e9-87d6-bd2b204b580c.png)

**Comment by Zero-Fanker** [comment]
@shuiping233 @yuanbanlao @RN-Hydra H0130已修正，请验证。

**Comment by shuiping233** [comment]
![Snipaste_2021-07-14_22-17-34](https://user-images.githubusercontent.com/49360196/125638476-3fdd4b80-7875-4deb-afae-7d4070afe96d.png)
图里是ai的天启，他还是能刷弹 （I0618）

**Comment by shuiping233** [comment]
0.99.914a3测试通过
