### ISSUE TITLE
#Bug#导弹类单位以及某些连续射击的单位可以通过快速连点 s 键来进行 “刷弹”

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#177]
【现象】：导弹类单位以及某些连续射击的单位可以通过快速连点 s 键来进行 “刷弹”。使得取消攻击间隔快速射出弹头。典型单位例如：雷鸣潜艇，捕食者，天启，ifv，三星防空履带车，尤里导弹艇，海蝎，等等等等，涉及到的单位可以有很多。
【反馈人】：
【发现版本号】：原版问题
【影响范围】：整个游戏
【产生原因】：wwsb

**Comment by yuanbanlao** [comment]
原版就存在。如果在pvp过度使用会被视为不道德的行为。

**Comment by Zero-Fanker** [comment]
@shuiping233 @yuanbanlao @RN-Hydra H0130已修正，请验证。

**Comment by RN-Hydra** [comment]
H0130已验证



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zero Fanker"<notifications@github.com&gt;; 
发送时间: 2020年1月30日(星期四) 晚上7:18
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;; 
抄送: "Estrus"<1575629191@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#导弹类单位以及某些连续射击的单位可以通过快速连点 s 键来进行 “刷弹” (#177)




@shuiping233 @yuanbanlao @RN-Hydra H0130已修正，请验证。

**Comment by shuiping233** [comment]
不啊，我测试了一遍，天启还是能刷弹啊，三星还特别好刷

**Comment by Zero-Fanker** [comment]
仿照Ares官方的改法我又改了一版

**Comment by Zero-Fanker** [comment]
0.99.911a2 已包含调整
