### ISSUE TITLE
#Bug#乌克兰核潜艇的导弹会被自己的辐射影响

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#179]
【现象】：乌克兰核潜艇的导弹会被自己的辐射影响，当自己发射的核导弹在身旁爆炸，会留下辐射，这会导致下一发导弹被辐射影响爆炸，如果核潜艇不停止发射导弹，那么这个情况会直到他死亡。
【反馈人】：shuiping
【发现版本号】：G0615B
【影响范围】：ai操作单位，单位操作手感
【产生原因】：未知

**Comment by shuiping233** [comment]
还有一点是，核导弹一起发射出去的时候，第一个导弹爆炸的辐射会影响其余导弹，让他们在空中爆炸，会略微影响伤害

**Comment by shuiping233** [comment]
那生化导弹车的导弹也有该问题，要另起一单吗？

**Comment by Zero-Fanker** [comment]
113提过了------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2019年12月29日(星期天) 上午8:58
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Assign"<assign@noreply.github.com>;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#乌克兰核潜艇的导弹会被自己的辐射影响 (#179)



那生化导弹车的导弹也有该问题，要另起一单吗？
 
&mdash;

**Comment by shuiping233** [comment]
刚刚测完那个了，关掉了

**Comment by shuiping233** [comment]
但是呢，这个核导弹炸的时候啊，也会和生化导弹车那个导弹一样，一群炸起来就会在空中爆炸

**Comment by Zero-Fanker** [comment]
这个指派验证了吗 我还没说版本号吧------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2019年12月29日(星期天) 上午10:25
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Assign"<assign@noreply.github.com>;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#乌克兰核潜艇的导弹会被自己的辐射影响 (#179)



但是呢，这个核导弹炸的时候啊，也会和生化导弹车那个导弹一样，一群炸起来就会在空中爆炸
 
&mdash;

**Comment by Zero-Fanker** [comment]
H0103已修正，请验证。

**Comment by shuiping233** [comment]
H0103经过测试，该问题已经解决
