### ISSUE TITLE
#建议反馈#建议加强古巴自爆战机

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#180]
【描述】加强对建筑的自爆伤害，加强其对装甲的伤害，缩短建造时间。

【原因】![QQ截图20190626221841](https://user-images.githubusercontent.com/49360196/60187782-c3286e80-9860-11e9-8cca-540b56d525cb.png)![QQ图片20190626221847](https://user-images.githubusercontent.com/49360196/60187787-c4599b80-9860-11e9-95de-5a7c49803f59.png)

【期望解决时间】下次公测

[注]:不按照格式填写会被视作无效。

**Comment by Zero-Fanker** [comment]
@yuanbanlao  kk评估一下

**Comment by shuiping233** [comment]
I0206已经加强地狱自爆机，故归档
