### ISSUE TITLE
#Bug#德国条顿坦克残骸会被辐射影响

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#182]
【现象】：德国条顿坦克残骸会被辐射影响
【发现版本号】：G0615B
【反馈人】：shuiping
【影响范围】：单位使用手感
【产生原因】：缺陷，未考虑该场景

**Comment by Zero-Fanker** [comment]
为什么不能被影响呢？ 难道残骸应该可摧毁吗------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2019年6月28日(星期五) 中午11:51
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Zero-Fanker/RN_All_Issues] #Bug#德国条顿坦克残骸会被辐射影响 (#182)



【现象】：德国条顿坦克残骸会被辐射影响
 【发现版本号】：G0615B
 【反馈人】：shuiping
 【影响范围】：单位使用手感
 【产生原因】：缺陷，未考虑该场景
 
&mdash;

**Comment by shuiping233** [comment]
> 为什么不能被影响呢？ 难道残骸应该可摧毁吗------------------ 原始邮件 ------------------ 发件人: "shuiping"<notifications@github.com> 发送时间: 2019年6月28日(星期五) 中午11:51 收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: [Zero-Fanker/RN_All_Issues] #Bug#德国条顿坦克残骸会被辐射影响 (#182) 【现象】：德国条顿坦克残骸会被辐射影响 【发现版本号】：G0615B 【反馈人】：shuiping 【影响范围】：单位使用手感 【产生原因】：缺陷，未考虑该场景 &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

？？？？？？？？？

**Comment by shuiping233** [comment]
> 为什么不能被影响呢？ 难道残骸应该可摧毁吗------------------ 原始邮件 ------------------ 发件人: "shuiping"<notifications@github.com> 发送时间: 2019年6月28日(星期五) 中午11:51 收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: [Zero-Fanker/RN_All_Issues] #Bug#德国条顿坦克残骸会被辐射影响 (#182) 【现象】：德国条顿坦克残骸会被辐射影响 【发现版本号】：G0615B 【反馈人】：shuiping 【影响范围】：单位使用手感 【产生原因】：缺陷，未考虑该场景 &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

残骸本身可以摧毁啊，我的意思是辐射会摧毁残骸这合适吧

**Comment by Zero-Fanker** [comment]
> > 为什么不能被影响呢？ 难道残骸应该可摧毁吗------------------ 原始邮件 ------------------ 发件人: "shuiping"[notifications@github.com](mailto:notifications@github.com) 发送时间: 2019年6月28日(星期五) 中午11:51 收件人: "Zero-Fanker/RN_All_Issues"[RN_All_Issues@noreply.github.com](mailto:RN_All_Issues@noreply.github.com); 抄送: "Subscribed"[subscribed@noreply.github.com](mailto:subscribed@noreply.github.com); 主题: [Zero-Fanker/RN_All_Issues] #Bug#德国条顿坦克残骸会被辐射影响 (#182) 【现象】：德国条顿坦克残骸会被辐射影响 【发现版本号】：G0615B 【反馈人】：shuiping 【影响范围】：单位使用手感 【产生原因】：缺陷，未考虑该场景 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 残骸本身可以摧毁啊，我的意思是辐射会摧毁残骸这不合适吧

为啥不合适?

**Comment by shuiping233** [comment]
> > > 为什么不能被影响呢？ 难道残骸应该可摧毁吗------------------ 原始邮件 ------------------ 发件人: "shuiping"[notifications@github.com](mailto:notifications@github.com) 发送时间: 2019年6月28日(星期五) 中午11:51 收件人: "Zero-Fanker/RN_All_Issues"[RN_All_Issues@noreply.github.com](mailto:RN_All_Issues@noreply.github.com); 抄送: "Subscribed"[subscribed@noreply.github.com](mailto:subscribed@noreply.github.com); 主题: [Zero-Fanker/RN_All_Issues] #Bug#德国条顿坦克残骸会被辐射影响 (#182) 【现象】：德国条顿坦克残骸会被辐射影响 【发现版本号】：G0615B 【反馈人】：shuiping 【影响范围】：单位使用手感 【产生原因】：缺陷，未考虑该场景 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.
> > 
> > 
> > 残骸本身可以摧毁啊，我的意思是辐射会摧毁残骸这不合适吧
> 
> 为啥不合适?

因为里边没有人

**Comment by Zero-Fanker** [comment]
为啥辐射只杀人呢------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2019年6月28日(星期五) 中午12:11
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#德国条顿坦克残骸会被辐射影响 (#182)


   
为什么不能被影响呢？ 难道残骸应该可摧毁吗------------------ 原始邮&#x4EF6; ------------------ 发&#x4EF6;人: "shuiping"notifications@github.com 发送时间: 2019年6月28日(星期五) 中午11:51 收&#x4EF6;人: "Zero-Fanker/RN_All_Issues"RN_All_Issues@noreply.github.com; 抄送: "Subscribed"subscribed@noreply.github.com; 主题: [Zero-Fanker/RN_All_Issues] #Bug#德国条顿坦克残骸会被辐射影响 (#182) 【现象】：德国条顿坦克残骸会被辐射影响 【发现版本号】：G0615B 【反馈人】：shuiping 【影响范围】：单位使用手感 【产生原因】：缺陷，未考虑该场景 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.
  
残骸本身可以摧毁啊，我的意思是辐射会摧毁残骸这不合适吧
  
为啥不合适?
  
因为里边没有人
 
&mdash;

**Comment by shuiping233** [comment]
> 为啥辐射只杀人呢------------------ 原始邮件 ------------------ 发件人: "shuiping"<notifications@github.com> 发送时间: 2019年6月28日(星期五) 中午12:11 收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>; 抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#德国条顿坦克残骸会被辐射影响 (#182) 为什么不能被影响呢？ 难道残骸应该可摧毁吗------------------ 原始邮&#x4EF6; ------------------ 发&#x4EF6;人: "shuiping"notifications@github.com 发送时间: 2019年6月28日(星期五) 中午11:51 收&#x4EF6;人: "Zero-Fanker/RN_All_Issues"RN_All_Issues@noreply.github.com; 抄送: "Subscribed"subscribed@noreply.github.com; 主题: [Zero-Fanker/RN_All_Issues] #Bug#德国条顿坦克残骸会被辐射影响 (#182) 【现象】：德国条顿坦克残骸会被辐射影响 【发现版本号】：G0615B 【反馈人】：shuiping 【影响范围】：单位使用手感 【产生原因】：缺陷，未考虑该场景 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread. 残骸本身可以摧毁啊，我的意思是辐射会摧毁残骸这不合适吧 为啥不合适? 因为里边没有人 &mdash; You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

那好吧 ，我没话反驳了
