### ISSUE TITLE
#Bug#ai部署武直会导致bug， 无法被攻击，并且免疫心控

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#184]
【现象】：ai部署武直会导致bug，无法被攻击，并且免疫心控，在空中使用火炮攻击。AI在部署时移动也会导致问题发生
【反馈人】：纸灯桑
【发现版本号】：G0615P1
【影响范围】：有尤里和苏军的对战
【产生原因】：wwsb

![QQ图片20190704173553](https://user-images.githubusercontent.com/49360196/60656654-6b05f380-9e82-11e9-89e6-a6ce6ea73a29.jpg)

**Comment by Zero-Fanker** [comment]
描述不正确，应该是部署时能被吸取导致问题。另一个就是AI在部署时移动也会导致------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2019年7月4日(星期四) 下午5:38
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Zero-Fanker/RN_All_Issues] #Bug#使用磁电吸取ai武直会导致ai武直在空中变形， 无法被攻击，并且免疫心控 (#184)



【现象】：使用磁电吸取ai武直会导致ai武直在空中变形， 无法被攻击，并且免疫心控，在空中使用火炮攻击。
 【反馈人】：纸灯桑
 【发现版本号】：G0615P1
 【影响范围】：有尤里和苏军的对战
 【产生原因】：wwsb
 

 
&mdash;

**Comment by shuiping233** [comment]
> 描述不正确，应该是部署时能被吸取导致问题。另一个就是AI在部署时移动也会导致------------------ 原始邮件 ------------------ 发件人: "shuiping"<notifications@github.com> 发送时间: 2019年7月4日(星期四) 下午5:38 收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: [Zero-Fanker/RN_All_Issues] #Bug#使用磁电吸取ai武直会导致ai武直在空中变形， 无法被攻击，并且免疫心控 (#184) 【现象】：使用磁电吸取ai武直会导致ai武直在空中变形， 无法被攻击，并且免疫心控，在空中使用火炮攻击。 【反馈人】：纸灯桑 【发现版本号】：G0615P1 【影响范围】：有尤里和苏军的对战 【产生原因】：wwsb &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

改了一下，这样行吗？

**Comment by shuiping233** [comment]
现发现ai武直不需要磁电就能在空中部署，待进一步测试取证

**Comment by shuiping233** [comment]
部分ai武直在部署降落地面后保持空中形态，并且使用火炮攻击

![70bbaea7c257a897](https://user-images.githubusercontent.com/49360196/64904828-28725a00-d702-11e9-8aff-8dc06bbb61c9.gif)
![338de18a097a69e5](https://user-images.githubusercontent.com/49360196/64904829-2c05e100-d702-11e9-9c4a-29693914af25.jpg)

**Comment by shuiping233** [comment]
武直的部署过程我录下来了：
![GIF17](https://user-images.githubusercontent.com/49360196/66013091-71951d00-e4fc-11e9-99ff-6577ec3aa39e.gif)

**Comment by Zero-Fanker** [comment]
原因是脚本过早将状态设置为guard，现在去掉了脚本最后一条的guard，并在scatter和deploy之间增加了延时脚本。

**Comment by Zero-Fanker** [comment]
G1013已修正，请验证 @shuiping233 @yuanbanlao

**Comment by shuiping233** [comment]
G1028P2经过测试，该问题并没有再出现
