### ISSUE TITLE
#Bug#三星条顿残骸会回血

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#186]
【现象】：三星条顿残骸会回血
【反馈人】：shuipnig
【发现版本号】：G0615P1
【影响范围】：无
【产生原因】：缺陷，未考虑该场景

**Comment by Zero-Fanker** [comment]
驱逐把条顿残骸单位的ability全去掉 Trainable也去掉 insignia全部写none

**Comment by Zero-Fanker** [comment]
H0103已修正，请验证。
@shuiping233  @yuanbanlao

**Comment by shuiping233** [comment]
H0103测试结果：条顿残骸已经不能（通过捡箱子）升级。
该问题已经解决
