### ISSUE TITLE
#Bug#联机时古巴的自爆飞机被击落会造成崩溃和断线

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#188]
【现象】：如题，先崩溃，然后导致RE
![image](https://user-images.githubusercontent.com/14891010/60899584-4c966280-a29d-11e9-8227-b4c498be42c0.png)

【反馈人】：shuiping
【发现版本号】：G0615P1
【影响范围】：影响古巴联机
【产生原因】：根据crashdump分析，WW对弹头voxel碎片藏雷

**Comment by Zero-Fanker** [comment]
G0715已修改，请测试

**Comment by shuiping233** [comment]
> G0715已修改，请测试

问一下，怎么测试？

**Comment by Zero-Fanker** [comment]
首先确定正常联机出这个单位 它被击落会不会出现问题 如果没有问题再带着这个单位正常联机玩 ------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2019年7月16日(星期二) 下午3:28
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#联机时古巴的自爆飞机被击落会造成崩溃和断线 (#188)


 
G0715已修改，请测试
  
问一下，怎么测试？
 
&mdash;

**Comment by shuiping233** [comment]
> 首先确定正常联机出这个单位 它被击落会不会出现问题 如果没有问题再带着这个单位正常联机玩 ------------------ 原始邮件 ------------------ 发件人: "shuiping"<notifications@github.com> 发送时间: 2019年7月16日(星期二) 下午3:28 收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>; 抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#联机时古巴的自爆飞机被击落会造成崩溃和断线 (#188) G0715已修改，请测试 问一下，怎么测试？ &mdash; You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

好
