### ISSUE TITLE
#Bug#古巴荣耀战士在先锋政委的buff下部署，会导致通过部署获得的速度加成消失

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#189]
【现象】：古巴荣耀战士在先锋政委的buff下部署，会导致通过部署获得的速度加成消失，以部署前的速度行走
【反馈人】：shuiping
【发现版本号】：G0615P1
【影响范围】：单位使用手感
【产生原因】：未知

**Comment by Zero-Fanker** [comment]
在进入部署状态后将丢弃政委加速并进入不受政委加成的状态 ，另晚点需关注#278单子现象，一起测试。

**Comment by Zero-Fanker** [comment]
H1024已调整，请验证

**Comment by shuiping233** [comment]
![GIF21](https://user-images.githubusercontent.com/49360196/97099596-cbe3bb80-16c5-11eb-8ff1-8b6508012703.gif)
H1024测试结果：现在荣耀战士部署后不在受加政委的加速buff
