### ISSUE TITLE
#功能性提议#英国圣骑士战甲部分形态可以更加实用

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#19]
IEafeoN created an issue 2018-09-08
【提起人】kk 【描述】 英国海豹圣骑和维修圣骑不实用，修改建议为前者类似于原版海报ifv的武器效果并略微加强对载具伤害，后者类似于维修ifv型维修厂并增加维修效率。 【结论】 海豹和工程师形态需要调整设定

**Comment by shuiping233** [comment]
Zero Fanker
changed title to #功能性提议#英国圣骑士战甲部分形态可以更加实用
edited description
标题很重要，标题的描述足够清晰是不需要打开看内容的。

2018-09-09
 Zero Fanker
changed status to closed
这种内部提议不算bug，注意这里是bug反馈，到日常开发事务的issue里去提。
