### ISSUE TITLE
#Bug#遭遇战模式的下方简介显示不全

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#190]
【现象】：遭遇战模式的下方简介显示不全，这个问题只有在 小队联盟【高防御】模式的简介出现
【反馈人】：shuiping
【发现版本号】：G0615P1
【影响范围】：视觉体验
【产生原因】：未知

![QQ截图20190710103057](https://user-images.githubusercontent.com/49360196/60936112-95323800-a2fe-11e9-8a37-09bd1c2ec9ce.png)

**Comment by Zero-Fanker** [comment]
不修复，以后换DTA------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2019年7月10日(星期三) 上午10:36
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Zero-Fanker/RN_All_Issues] #Bug#遭遇战模式的下方简介显示不全 (#190)



【现象】：遭遇战模式的下方简介显示不全，这个问题只有在 小队联盟【高防御】模式的简介出现
 【反馈人】：shuiping
 【发现版本号】：G0615P1
 【影响范围】：视觉体验
 【产生原因】：未知
 

 
&mdash;

**Comment by shuiping233** [comment]
> 不修复，以后换DTA------------------ 原始邮件 ------------------ 发件人: "shuiping"<notifications@github.com> 发送时间: 2019年7月10日(星期三) 上午10:36 收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: [Zero-Fanker/RN_All_Issues] #Bug#遭遇战模式的下方简介显示不全 (#190) 【现象】：遭遇战模式的下方简介显示不全，这个问题只有在 小队联盟【高防御】模式的简介出现 【反馈人】：shuiping 【发现版本号】：G0615P1 【影响范围】：视觉体验 【产生原因】：未知 &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

好，了解
