### ISSUE TITLE
#Bug#超时空兵攻击油井类建筑后，建筑恢复后再也无法提供资金

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#191]
【现象】：超时空兵攻击油井类建筑后，建筑恢复后再也无法提供资金
【反馈人】：VicViperT301
【发现版本号】：G0615P1
【影响范围】：遭遇战
【产生原因】：未知，原版bug

![QQ截图20190711144309](https://user-images.githubusercontent.com/49360196/61028443-4a421e80-a3eb-11e9-8e6c-cb4c7fe9a8f9.png)
![QQ截图20190711144426](https://user-images.githubusercontent.com/49360196/61028446-4adab500-a3eb-11e9-86b3-215f9ec46b92.png)
![QQ截图20190711144334](https://user-images.githubusercontent.com/49360196/61028445-4a421e80-a3eb-11e9-8e9a-7c0b14894c1c.png)

**Comment by Zero-Fanker** [comment]
是说恢复后也无法提供吗？------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2019年7月11日(星期四) 下午2:50
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Zero-Fanker/RN_All_Issues] #Bug#超时空兵攻击油井类建筑后，建筑再也无法提供资金 (#191)



【现象】：超时空兵攻击油井类建&#x7B51;后，建&#x7B51;再也无法提供资金
 【反馈人】：VicViperT301
 【发现版本号】：G0615P1
 【影响范围】：遭遇战
 【产生原因】：未知，原版bug
 
&mdash;

**Comment by shuiping233** [comment]
> 是说恢复后也无法提供吗？------------------ 原始邮件 ------------------ 发件人: "shuiping"<notifications@github.com> 发送时间: 2019年7月11日(星期四) 下午2:50 收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: [Zero-Fanker/RN_All_Issues] #Bug#超时空兵攻击油井类建筑后，建筑再也无法提供资金 (#191) 【现象】：超时空兵攻击油井类建&#x7B51;后，建&#x7B51;再也无法提供资金 【反馈人】：VicViperT301 【发现版本号】：G0615P1 【影响范围】：遭遇战 【产生原因】：未知，原版bug &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

是的，遭遇战会受这个bug影响的建筑还有 3大阵营的t4

**Comment by Zero-Fanker** [comment]
H1015已修正，请验证。

**Comment by shuiping233** [comment]
H1015B经过测试：该问题已修复
