### ISSUE TITLE
#建议反馈#建议给古巴增加一个地道部署超武

### ISSUE THREAD

**Issue by jiamankaer** [Zero-Fanker/RN_All_Issues#193]
【描述】可以给古巴有T2和地道时增加一个支援技能，可以直接在一个可见区域部署一个地道。价钱可以设置比地道贵一些，可以设置成1500一个地道，时间大概可以4分钟。不能在黑幕中部署。
【原因】地道虽然能快速运输部队，但是有时并不好用，开着MCV到处造地道在11小图基本不会出现，这限制了地道的发挥，加入这个支援技能可以让地道更加的厉害一些，使用率会变高。会成为古巴变强的一种方式，自爆可以几乎随时出现。
【期望解决时间】下个版本

**Comment by Zero-Fanker** [comment]
@shuiping233  @yuanbanlao  @RN-Hydra   H0326已经引入，还缺少专属图标。请验证。

**Comment by yuanbanlao** [comment]
H0331已验证，当前古巴拥有T2超武地道部署，没有名字和专属图标。技能释放范围为己方建筑为中心的中距离可建造点。 @klighting444 请归档

**Comment by shuiping233** [comment]
> H0331已验证，当前古巴拥有T2超武地道部署，没有名字和专属图标。技能释放范围为己方建筑为中心的中距离可建造点。 @klighting444 请归档

我在H0331中测试实验中发现地道超武不仅在已方建筑内可以部署，在已方部队隔壁也可以部署，
