### ISSUE TITLE
#Bug#G0615P G0615P1 G0615P2 可以跨版本联机，会导致核电被炸毁的时候游戏程序崩溃

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#194]
【现象】：G0615P G0615P1 G0615P2 可以跨版本联机，会导致核电被炸毁的时候游戏程序崩溃
【反馈人】：放飞梦想 shuiping
【发现版本号】：G0615P G0615P1 G0615P2
【影响范围】：多人联机
【产生原因】：玩家没有及时更新游戏程序

**Comment by Zero-Fanker** [comment]
这是很显然的,P1修正了内存泄漏问题，行为本身就不一样了。群测版本的小更新之间没有版本同步性校验检查，联机时务必确保版本一致。近期会有大更新，和旧版不会兼容。------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2019年7月13日(星期六) 下午5:33
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Zero-Fanker/RN_All_Issues] #Bug#G0615P G0615P1 G0615P2 可以跨版本联机，会导致核电被炸毁的时候游戏程序崩溃 (#194)



【现象】：G0615P G0615P1 G0615P2 可以跨版本联机，会导致核电被炸毁的时候游戏程序崩溃
 【反馈人】：放飞梦想 shuiping
 【发现版本号】：G0615P G0615P1 G0615P2
 【影响范围】：多人联机
 【产生原因】：玩家没更新版本
 
&mdash;

**Comment by Zero-Fanker** [comment]
从G1028P2版本开始，小更新导致的版本互通问题已经解决。
