### ISSUE TITLE
#Bug#德国灰熊uc对防御类建筑伤害异常

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#196]
【现象】：德国灰熊uc对防御类建筑伤害异常，一发只有7血，10uc都不能打得动自修的碉堡
【反馈人】：炫彩嘤嘤怪
【发现版本号】：G0615P3
【影响范围】：多人pvp，游戏平衡
【产生原因】：弹头修正比异常

![GIF2](https://user-images.githubusercontent.com/49360196/61264939-dc1da300-a7c0-11e9-9f5d-a9da2155cad4.gif)

![GIF](https://user-images.githubusercontent.com/49360196/61264938-dc1da300-a7c0-11e9-9ce9-c48a778b2d7f.gif)

**Comment by Zero-Fanker** [comment]
你试过普通灰熊了？ 数据难道不一样?------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2019年7月16日(星期二) 中午11:33
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Zero-Fanker/RN_All_Issues] #Bug#德国灰熊uc对防御类建筑伤害异常 (#196)



【现象】：德国灰熊uc对防御类建&#x7B51;伤害异常，一发只有7血，10uc都不能打得动自修的碉堡
 【反馈人】：炫彩嘤嘤怪
 【发现版本号】：G0615P3
 【影响范围】：多人pvp，游戏平衡
 【产生原因】：弹头修正比异常
 
&mdash;

**Comment by shuiping233** [comment]
> 你试过普通灰熊了？ 数据难道不一样?------------------ 原始邮件 ------------------ 发件人: "shuiping"<notifications@github.com> 发送时间: 2019年7月16日(星期二) 中午11:33 收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: [Zero-Fanker/RN_All_Issues] #Bug#德国灰熊uc对防御类建筑伤害异常 (#196) 【现象】：德国灰熊uc对防御类建&#x7B51;伤害异常，一发只有7血，10uc都不能打得动自修的碉堡 【反馈人】：炫彩嘤嘤怪 【发现版本号】：G0615P3 【影响范围】：多人pvp，游戏平衡 【产生原因】：弹头修正比异常 &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

我在做GIF了，等会上传

**Comment by Zero-Fanker** [comment]
我是说和普通版灰熊相比------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2019年7月16日(星期二) 中午11:45
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#德国灰熊uc对防御类建筑伤害异常 (#196)


 
你试过普通灰熊了？ 数据难道不一样?------------------ 原始邮&#x4EF6; ------------------ 发&#x4EF6;人: "shuiping"notifications@github.com 发送时间: 2019年7月16日(星期&#x4E8C;) 中午11:33 收&#x4EF6;人: "Zero-Fanker/RN_All_Issues"RN_All_Issues@noreply.github.com; 抄送: "Subscribed"subscribed@noreply.github.com; 主题: [Zero-Fanker/RN_All_Issues] #Bug#德国灰熊uc对防御类建&#x7B51;伤害异常 (#196) 【现象】：德国灰熊uc对防御类建&#x7B51;伤害异常，一发只有7血，10uc都不能打得动自修的碉堡 【反馈人】：炫彩嘤嘤怪 【发现版本号】：G0615P3 【影响范围】：多人pvp，游戏平衡 【产生原因】：弹头修正比异常 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.
  
我在做GIF了，等会上传
 
&mdash;

**Comment by shuiping233** [comment]
> 我是说和普通版灰熊相比------------------ 原始邮件 ------------------ 发件人: "shuiping"<notifications@github.com> 发送时间: 2019年7月16日(星期二) 中午11:45 收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>; 抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#德国灰熊uc对防御类建筑伤害异常 (#196) 你试过普通灰熊了？ 数据难道不一样?------------------ 原始邮&#x4EF6; ------------------ 发&#x4EF6;人: "shuiping"notifications@github.com 发送时间: 2019年7月16日(星期&#x4E8C;) 中午11:33 收&#x4EF6;人: "Zero-Fanker/RN_All_Issues"RN_All_Issues@noreply.github.com; 抄送: "Subscribed"subscribed@noreply.github.com; 主题: [Zero-Fanker/RN_All_Issues] #Bug#德国灰熊uc对防御类建&#x7B51;伤害异常 (#196) 【现象】：德国灰熊uc对防御类建&#x7B51;伤害异常，一发只有7血，10uc都不能打得动自修的碉堡 【反馈人】：炫彩嘤嘤怪 【发现版本号】：G0615P3 【影响范围】：多人pvp，游戏平衡 【产生原因】：弹头修正比异常 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread. 我在做GIF了，等会上传 &mdash; You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

![GIF](https://user-images.githubusercontent.com/49360196/61264931-d627c200-a7c0-11e9-8152-86d7f5965624.gif)
![GIF2](https://user-images.githubusercontent.com/49360196/61264932-d627c200-a7c0-11e9-954e-4aa76ce3366a.gif)

**Comment by shuiping233** [comment]
> > 我是说和普通版灰熊相比------------------ 原始邮件 ------------------ 发件人: "shuiping"[notifications@github.com](mailto:notifications@github.com) 发送时间: 2019年7月16日(星期二) 中午11:45 收件人: "Zero-Fanker/RN_All_Issues"[RN_All_Issues@noreply.github.com](mailto:RN_All_Issues@noreply.github.com); 抄送: "Zero Fanker"[zcyfksn@vip.qq.com](mailto:zcyfksn@vip.qq.com);"Comment"[comment@noreply.github.com](mailto:comment@noreply.github.com); 主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#德国灰熊uc对防御类建筑伤害异常 (#196) 你试过普通灰熊了？ 数据难道不一样?------------------ 原始邮件 ------------------ 发件人: "shuiping"[notifications@github.com](mailto:notifications@github.com) 发送时间: 2019年7月16日(星期二) 中午11:33 收件人: "Zero-Fanker/RN_All_Issues"[RN_All_Issues@noreply.github.com](mailto:RN_All_Issues@noreply.github.com); 抄送: "Subscribed"[subscribed@noreply.github.com](mailto:subscribed@noreply.github.com); 主题: [Zero-Fanker/RN_All_Issues] #Bug#德国灰熊uc对防御类建筑伤害异常 (#196) 【现象】：德国灰熊uc对防御类建筑伤害异常，一发只有7血，10uc都不能打得动自修的碉堡 【反馈人】：炫彩嘤嘤怪 【发现版本号】：G0615P3 【影响范围】：多人pvp，游戏平衡 【产生原因】：弹头修正比异常 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread. 我在做GIF了，等会上传 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
> 
> ![GIF](https://user-images.githubusercontent.com/49360196/61264931-d627c200-a7c0-11e9-8152-86d7f5965624.gif)
> ![GIF2](https://user-images.githubusercontent.com/49360196/61264932-d627c200-a7c0-11e9-954e-4aa76ce3366a.gif)

3灰熊可以打掉一个自修的碉堡，但是6uc却打不掉自修碉堡

**Comment by Zero-Fanker** [comment]
G0824已修改，请验证 @shuiping233  @yuanbanlao

**Comment by yuanbanlao** [comment]
验证完毕，现在的3uc灰熊可以打掉自修友军地堡了。
