### ISSUE TITLE
萌君通用ai触发（初稿）

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#20]
kk7k7k558 created an issue 2018-09-11
因为是初稿加重写再加单位迥异，大概没多少，特色计划体现在各国ai触发里。可能有很多必要性触发忘记了，补上就好。

**Comment by shuiping233** [comment]
Zero Fanker
内部事务请不要再发在BUG反馈页面

2018-09-11
 Zero Fanker
删除了不应该公开的文件

2018-09-11
 Zero Fanker
changed status to closed
迁移到内部事务
