### ISSUE TITLE
#Bug#基洛夫飞艇能提供很大的视野

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#200]
【现象】：基洛夫能提供很大的视野，在1280x800的分辨率下能提供整个屏幕的视野
【反馈人】：shuiping
【发现版本号】：G0715
【影响范围】：？
【产生原因】：未知
![QQ截图20190722152358](https://user-images.githubusercontent.com/49360196/61613922-1a213800-ac95-11e9-8370-5871b8188a76.png)

**Comment by Zero-Fanker** [comment]
和分辨率无关，基洛夫的视野设置是25，是设定，可以看往期更新日志------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2019年7月22日(星期一) 下午3:33
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Zero-Fanker/RN_All_Issues] #Bug#基洛夫飞艇的视野很大 (#200)



【现象】：基洛夫能提供很大的视野，在1280x800的分辨率下能提供整个屏幕的视野
 【反馈人】：shuiping
 【发现版本号】：G0715
 【影响范围】：？
 【产生原因】：未知
 
 
&mdash;

**Comment by shuiping233** [comment]
> 和分辨率无关，基洛夫的视野设置是25，是设定，可以看往期更新日志------------------ 原始邮件 ------------------ 发件人: "shuiping"<notifications@github.com> 发送时间: 2019年7月22日(星期一) 下午3:33 收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: [Zero-Fanker/RN_All_Issues] #Bug#基洛夫飞艇的视野很大 (#200) 【现象】：基洛夫能提供很大的视野，在1280x800的分辨率下能提供整个屏幕的视野 【反馈人】：shuiping 【发现版本号】：G0715 【影响范围】：？ 【产生原因】：未知 &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

好
