### ISSUE TITLE
#Bug#窗口化游戏时，滑条控件漂移

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#203]
【现象】：窗口化模式下，如果游戏窗口不在左上角，滑块控件(例如难度和音量控制)会随着窗口拖动而异常漂移
【反馈人】：
【发现版本号】：G0615
【影响范围】：影响窗口化时的一些滑块控件操作
【产生原因】：MoveWindow调用时传入了错误的参数，同时用户开启了微软系统显示缩放

**Comment by Zero-Fanker** [comment]
commit-ID  c9ae5f3a8d43d246565a69d294fa5c5702c8220d

**Comment by Zero-Fanker** [comment]
@shuiping233 @yuanbanlao  G0824已经修复，请验证

**Comment by yuanbanlao** [comment]
当用较小分辨率拖动窗口游戏的时候，整个游戏拖动背景是全屏化的背景之内的一小块（类似于在台球桌上拖动三角台球架）。而窗口化的菜单选项依然无法跟随屏幕移动，只能固定显示上一次的屏幕所在方位的图标。如果想要操纵菜单，只能依靠记忆力判定按键方位。

**Comment by yuanbanlao** [comment]
但是在点击到正确按键的时候，屏幕会恢复到正常情况。再次拖动依然会出现之前所说的错误情况。

**Comment by Zero-Fanker** [comment]
> 但是在点击到正确按键的时候，屏幕会恢复到正常情况。再次拖动依然会出现之前所说的错误情况。

你的问题先排除自己问题，更换过ddraw仍然有问题另外提单子。
