### ISSUE TITLE
#Bug#圣骑士机甲在有护盾情况下被蜘蛛寄生，维修车不能维修护盾情况下的圣骑士

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#204]
【现象】：圣骑士机甲在有护盾情况下被蜘蛛寄生，维修车不能维修护盾情况下的圣骑士
【发现版本号】：G0726P
【影响范围】：单位使用手感
【产生原因】：未知

**Comment by Zero-Fanker** [comment]
@yuanbanlao @Super-StarX 
评估一下是否需要穿透护盾进行维修的设定？或者说，带盾时是否要免疫zz？

**Comment by yuanbanlao** [comment]
圣骑有盾情况下防止寄生。

**Comment by Zero-Fanker** [comment]
> 圣骑有盾情况下防止寄生。

G0824已修改。请验证。
@yuanbanlao  @shuiping233

**Comment by yuanbanlao** [comment]
验证完毕，有护盾的圣骑士机甲已经是免疫蜘蛛的寄生攻击了。
