### ISSUE TITLE
#优化#英国圣骑士战甲在心控状态可以释放乘客，且圣骑士保持被控制状态，而乘客不是。

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#205]
【描述】如标题描述，需要进行优化。当前优化策略是禁止被心控状态的圣骑士战甲更换乘客。
【原因】不符合设定逻辑
【期望解决时间】

**Comment by Zero-Fanker** [comment]
H1024已调整，现在圣骑士被心控后释放乘客，载具将恢复原来的所属，而乘客被心控;

**Comment by shuiping233** [comment]
![GIF19](https://user-images.githubusercontent.com/49360196/97099170-e1a2b200-16c0-11eb-8a78-2d9faceb89dd.gif)
![GIF18](https://user-images.githubusercontent.com/49360196/97099172-e6676600-16c0-11eb-82a8-e95b58a1aac0.gif)
H1024测试结果：与修改描述一致，常规可被心控单位释放后依旧被心控，载具恢复所属，特殊情况（载英雄单位的圣骑士）下，被心控的英雄圣骑士释放乘客后乘客不被心控，载具恢复原来所属
