### ISSUE TITLE
#Bug#在重工生产了攻城机甲后，会导致集结点地块不允许建造并且通过

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#206]
【现象】：在重工生产了攻城机甲后，会导致集结点地块不允许建造并且通过
【反馈人】：焚风狂鲨先锋3
【发现版本号】：G0726P
【影响范围】：游戏体验
【产生原因】：未知
![QQ截图20190805100320](https://user-images.githubusercontent.com/49360196/62433974-4e9ef480-b769-11e9-8b96-720270c2b7d6.png)
![QQ截图20190805100348](https://user-images.githubusercontent.com/49360196/62433973-4e9ef480-b769-11e9-8d28-48a6b419601c.png)

![QQ截图20190805100439](https://user-images.githubusercontent.com/49360196/62434003-742bfe00-b769-11e9-9f08-033230b28c41.png)

**Comment by Zero-Fanker** [comment]
G0824引入，请测试。
@Leaf-eon  @shuiping233  @yuanbanlao

**Comment by yuanbanlao** [comment]
验证完毕，集结地块不允许建造且通过的情况不再发生。
