### ISSUE TITLE
#建议反馈#关于灰熊的增强可能性方案

### ISSUE THREAD

**Issue by Ruamia** [Zero-Fanker/RN_All_Issues#208]
【描述】
~~1. 群聚效应：考虑到灰熊单体偏弱，因此通常都会选择一次出大量灰熊，可以考虑令灰熊能够增强彼此伤害或防御，使较大数量的灰熊能够形成较高的威胁，鼓励玩家群聚攻击。~~
~~2. 维护模式：灰熊构造简单，因此可以即时在战场上进行维护，部署后切换为维护模式，降低速度或完全不能移动，同时较快恢复生命值，由于灰熊本身血量较低，应该不会太影响平衡，但是能够使灰熊更难缠。~~
3. 固守模式：类似GH，部署并在车体周围竖起挡板，大幅提升防御力同时增加最大射程， <strike>但是也开始存在最小射程，降低ROT和射速，在受到较多攻击时挡板会被摧毁恢复到正常防御力，需要一定时间修复，</strike> 部署和反部署有较长CD。
部署后+1射程，hp变为当前的130%，无法移动，部署冷却10游戏秒。部署动画以犀牛坦克新兵时两炮间隔为参考数据
【原因】灰熊弱弱弱
【期望解决时间】

**Comment by Zero-Fanker** [comment]
@yuanbanlao

**Comment by yuanbanlao** [comment]
别at我，我没辙。

**Comment by Zero-Fanker** [comment]
你这什么鬼 卡逗提了三个方向的修改方式 你评估一下不不就行了吗------------------ 原始邮件 ------------------
发件人: "yuanbanlao"<notifications@github.com>
发送时间: 2019年8月8日(星期四) 中午12:05
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Zero-Fanker/RN_All_Issues] #建议反馈#关于灰熊的增强可能性方案 (#208)



别at我，我没辙。
 
&mdash;

**Comment by Zero-Fanker** [comment]
1的原型是将军里CN的战神坦克。2有可能和德国创意有交叠(可维护式残骸)。3倒是也可以考虑。昨天根据3我想到了RA3帝国的坦克，部署后不可开火，防御力提升。

不过综合来说，主要还是要选择侧重生存能力还是防御能力，又或者二者兼有。

**Comment by yuanbanlao** [comment]
第一项其实和直接加强灰熊属性区别不大。因为rn的灰熊建造速度比较快而且灰熊的buff只存在于灰熊自己之间。如果是无限度的buff会导致imba，有限度的buff几乎就是加强灰熊属性。
第二项感觉类似于德国和越南的混合体。但是从操作简易程度上又会被捕食者甩一截（能力上升的代价是容错下降）。
第三项有些像我以前给坦杀提供的“钉子”方案。如果选这个作为修改方案可以做一下参考。
另外一提，灰熊和捕食者都是t1单位，灰熊更是t1主战坦克，在t1主战就出现比较高的操作要求（来加强必要的属性）会不会被认为难以上手？

**Comment by Zero-Fanker** [comment]
那就以第三项作为修改方向，同时降低操作难度的思路进行设计。例如说可考虑半血时受到伤害减25%，红血减50%(原先计划给钻地车的设定)，或者血量少于50%时可自动回血。 ------------------ 原始邮件 ------------------
发件人: "yuanbanlao"<notifications@github.com>
发送时间: 2019年8月9日(星期五) 凌晨1:29
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Zero-Fanker/RN_All_Issues] #建议反馈#关于灰熊的增强可能性方案 (#208)



第一项其实和直接加强灰熊属性区别不大。因为rn的灰熊建造速度比较快而且灰熊的buff只存在于灰熊自己之间。如果是无限度的buff会导致imba，有限度的buff几乎就是加强灰熊属性。
 第&#x4E8C;项感觉类似于德国和越南的混合体。但是从操作简易程度上又会被捕食者甩一截（能力上升的代价是容错下降）。
 第三项有些像我以前给坦杀提供的“钉子”方案。如果选这个作为修改方案可以做一下参考。
 另外一提，灰熊和捕食者都是t1单位，灰熊更是t1主战坦克，在t1主战就出现比较高的操作要求（来加强必要的属性）会不会被认为难以上手？
 
&mdash;

**Comment by yuanbanlao** [comment]
那么当前灰熊暂且对建筑提升伤害，还是以第三项方案为修改方向，修改后对建筑伤害调回正常值。

**Comment by yuanbanlao** [comment]
计划有变，由于进度有点快，所以决定跳过过渡阶段，直接进入最终版。
预期数据：部署后+1射程，hp变为当前的130%，无法移动，部署冷却10游戏秒。部署动画以犀牛坦克新兵时两炮间隔为参考数据。

**Comment by Zero-Fanker** [comment]
> 计划有变，由于进度有点快，所以决定跳过过渡阶段，直接进入最终版。
> 预期数据：部署后+1射程，hp变为当前的130%，无法移动，部署冷却10游戏秒。部署动画以犀牛坦克新兵时两炮间隔为参考数据。

现在没有部署动画是否能接受，因为素材湿没做，然后10s实际上只有150帧，在6速下体验也就实际时间的2.5s

**Comment by Zero-Fanker** [comment]
@yuanbanlao  @shuiping233 0.99.903a已引入

**Comment by shuiping233** [comment]
![GIF87](https://user-images.githubusercontent.com/49360196/115961952-8bb5a680-a54b-11eb-9525-cf4b2a32a620.gif)
![GIF86](https://user-images.githubusercontent.com/49360196/115961957-9112f100-a54b-11eb-93b6-bd38b34d1c98.gif)
0.99.903a3测试结果:部署后的灰熊并没有射程加成，其余均符合验收标准

**Comment by shuiping233** [comment]
至于cd长不长，还是由kk判定吧

**Comment by shuiping233** [comment]
@yuanbanlao

**Comment by shuiping233** [comment]
@Zero-Fanker 904a有修复射程的问题么？

**Comment by shuiping233** [comment]
0.99.905a4是否修复灰熊部署后的射程问题？

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/128636207-8655fd12-5164-4437-9906-0cb6a2ee41b1.png)
kk评定过后取消灰熊部署后射程+1，现归档
