### ISSUE TITLE
#Bug#新盟三任务中，平定装置完成建造后会播放两次建造动画

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#211]
【现象】：新盟三任务中，平定装置完成建造后会播放两次建造动画
【反馈人】：shuiping
【发现版本号】：G0726P
【影响范围】：视觉体验
【产生原因】：未知

![3acd48ec00c68dfc](https://user-images.githubusercontent.com/49360196/62773085-d2dbd980-bad3-11e9-8be4-c869cdf74a1b.gif)

**Comment by Zero-Fanker** [comment]
G0824已经使用新机制完善了建造过程，请验证。
@shuiping233  @yuanbanlao

**Comment by shuiping233** [comment]
> G0824已经使用新机制完善了建造过程，请验证。
> @shuiping233 @yuanbanlao

![gif13](https://user-images.githubusercontent.com/49360196/64071376-a7e83e00-ccab-11e9-85d8-b0d2a061c593.gif)

**Comment by shuiping233** [comment]
> > G0824已经使用新机制完善了建造过程，请验证。
> > @shuiping233 @yuanbanlao
> 
> ![gif13](https://user-images.githubusercontent.com/49360196/64071376-a7e83e00-ccab-11e9-85d8-b0d2a061c593.gif)


问题依然存在

**Comment by Zero-Fanker** [comment]
已证实，和AI有关，之前只测了玩家的建筑。

**Comment by shuiping233** [comment]
> 已证实，和AI有关，之前只测了玩家的建筑。

好

**Comment by Zero-Fanker** [comment]
G1013版本再次修正，请验证。

**Comment by shuiping233** [comment]
![60ee792c3a7759ed](https://user-images.githubusercontent.com/49360196/67158023-ac54dd00-f365-11e9-9c26-4b251f46f2c3.gif)
G1013b版本经过测试，该问题已经解决。（虽然有时候会出现停电图标，但是无伤大雅。）
