### ISSUE TITLE
#建议反馈#建议瓦尔哈拉维修平台禁止传送不能被自身装载的载具

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#215]
【描述】：瓦尔哈拉维修平台禁止传送不能被自身装载的载具，例如攻城机甲
【原因】：用维修平台传送例如攻城机甲等大型载具不会有任何效果，会浪费一次传送机会
【期望解决时间】下版本公测

**Comment by Crossfield-ClassDestroyer** [comment]
[已确定需要处理单位.zip](https://github.com/Zero-Fanker/RN_All_Issues/files/4310031/default.zip)

**Comment by Zero-Fanker** [comment]
> [已确定需要处理单位.zip](https://github.com/Zero-Fanker/RN_All_Issues/files/4310031/default.zip)

OK 由于数量众多，考虑通过修改代码实现屏蔽

**Comment by Crossfield-ClassDestroyer** [comment]
[已确定单位[Size统计完成].zip](https://github.com/Zero-Fanker/RN_All_Issues/files/4380220/Size.zip)

**Comment by Zero-Fanker** [comment]
[单位调整意见.zip](https://github.com/Zero-Fanker/RN_All_Issues/files/4381042/default.zip)
需要调整的单位已经打钩，加入Allowed列表。打x的不需要管。

**Comment by Zero-Fanker** [comment]
@shuiping233  @yuanbanlao  @RN-Hydra  H0326已引入，在当前版本测试一下

**Comment by shuiping233** [comment]
请问有受影响的单位列表吗？哪些单位改动过了？



---原始邮件---
发件人: "Zero Fanker"<notifications@github.com&gt;
发送时间: 2020年4月7日(星期二) 中午1:47
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"shuiping"<1944680304@qq.com&gt;;
主题: Re: [Zero-Fanker/RN_All_Issues] #建议反馈#建议瓦尔哈拉维修平台禁止传送不能被自身装载的载具 (#215)




 
@shuiping233  @yuanbanlao  @RN-Hydra  H0326已引入，在当前版本测试一下

**Comment by yuanbanlao** [comment]
上方文件中有。

**Comment by shuiping233** [comment]
有密码啦，打不开的



---原始邮件---
发件人: "yuanbanlao"<notifications@github.com&gt;
发送时间: 2020年4月7日(星期二) 下午3:53
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"shuiping"<1944680304@qq.com&gt;;
主题: Re: [Zero-Fanker/RN_All_Issues] #建议反馈#建议瓦尔哈拉维修平台禁止传送不能被自身装载的载具 (#215)




 
上方文件中有。

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/79631472-5b933500-818c-11ea-9791-45d36919968c.png)
![image](https://user-images.githubusercontent.com/49360196/79631496-5df58f00-818c-11ea-8985-5c8ae777ff39.png)
![image](https://user-images.githubusercontent.com/49360196/79631474-5c2bcb80-818c-11ea-830e-2003e08971db.png)
![image](https://user-images.githubusercontent.com/49360196/79631493-5df58f00-818c-11ea-8064-b45b48b59070.png)
![image](https://user-images.githubusercontent.com/49360196/79631497-5df58f00-818c-11ea-9337-5d604cb5286c.png)
![image](https://user-images.githubusercontent.com/49360196/79631500-5e8e2580-818c-11ea-949a-4239926e738b.png)
![image](https://user-images.githubusercontent.com/49360196/79631476-5cc46200-818c-11ea-9d2c-52c30bf490f8.png)
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![image](https://user-images.githubusercontent.com/49360196/79631472-5b933500-818c-11ea-9791-45d36919968c.png)
![image](https://user-images.githubusercontent.com/49360196/79631496-5df58f00-818c-11ea-8985-5c8ae777ff39.png)
![image](https://user-images.githubusercontent.com/49360196/79631474-5c2bcb80-818c-11ea-830e-2003e08971db.png)
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![image](https://user-images.githubusercontent.com/49360196/79631476-5cc46200-818c-11ea-9d2c-52c30bf490f8.png)
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by Zero-Fanker** [comment]
别直接发里面的截图啊，自己列个表，只有中文名和结果------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2020年4月18日(星期六) 下午3:51
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Zero-Fanker/RN_All_Issues] #建议反馈#建议瓦尔哈拉维修平台禁止传送不能被自身装载的载具 (#215)




 

 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
&mdash;

**Comment by shuiping233** [comment]
这是我自己统计的TXT啊，



---原始邮件---
发件人: "Zero Fanker"<notifications@github.com&gt;
发送时间: 2020年4月18日(星期六) 下午4:02
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"shuiping"<1944680304@qq.com&gt;;
主题: Re: [Zero-Fanker/RN_All_Issues] #建议反馈#建议瓦尔哈拉维修平台禁止传送不能被自身装载的载具 (#215)




 别直接发里面的截图啊，自己列个表，只有中文名和结果------------------ 原始邮件 ------------------ 
 发件人: "shuiping"<notifications@github.com&gt; 
 发送时间: 2020年4月18日(星期六) 下午3:51 
 收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;; 
 抄送: "Zero Fanker"<zcyfksn@vip.qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 
 主题: Re: [Zero-Fanker/RN_All_Issues] #建议反馈#建议瓦尔哈拉维修平台禁止传送不能被自身装载的载具 (#215) 
 
 
 
 
   
 
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
 &amp;mdash;

**Comment by shuiping233** [comment]
那行吧，我重新写一遍



---原始邮件---
发件人: "Zero Fanker"<notifications@github.com&gt;
发送时间: 2020年4月18日(星期六) 下午4:02
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"shuiping"<1944680304@qq.com&gt;;
主题: Re: [Zero-Fanker/RN_All_Issues] #建议反馈#建议瓦尔哈拉维修平台禁止传送不能被自身装载的载具 (#215)




 别直接发里面的截图啊，自己列个表，只有中文名和结果------------------ 原始邮件 ------------------ 
 发件人: "shuiping"<notifications@github.com&gt; 
 发送时间: 2020年4月18日(星期六) 下午3:51 
 收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;; 
 抄送: "Zero Fanker"<zcyfksn@vip.qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 
 主题: Re: [Zero-Fanker/RN_All_Issues] #建议反馈#建议瓦尔哈拉维修平台禁止传送不能被自身装载的载具 (#215) 
 
 
 
 
   
 
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
 &amp;mdash;
