### ISSUE TITLE
#Bug#磁能坦克和磁暴步兵充能问题

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#217]
【现象】：磁能坦克和磁暴步兵给磁暴线圈和艾菲尔充能的逻辑不像原版那样灵活，经常导致单位主动给建筑充能而忽视攻击目标，尤其AI问题严重，且容易造成堵车，忽视脚本命令。
【反馈人】：
【发现版本号】：G0824
【影响范围】：影响同时存在磁能坦克磁暴步兵和磁暴线圈等的场景
【产生原因】：内部逻辑存在缺陷，相关功能修改不可靠

**Comment by Zero-Fanker** [comment]
G1013已修改，请验证 @shuiping233  @yuanbanlao

**Comment by shuiping233** [comment]
G1028P2测试结果：磁能和磁暴均不能主动给线圈充电，ai执行磁暴和磁能的攻击脚本时也不再主动给线圈充电

![e4c1169f7c5297897b7f9d797f543d567a92bf1d jpg@518w_1e_1c](https://user-images.githubusercontent.com/49360196/68080920-37db6d00-fe40-11e9-82ea-1affd50f96aa.jpg)
![QQ截图20191103134333](https://user-images.githubusercontent.com/49360196/68080921-38740380-fe40-11e9-9e51-a025a8a7180b.png)
![QQ截图20191103134349](https://user-images.githubusercontent.com/49360196/68080922-390c9a00-fe40-11e9-9cef-0b0e57c152a4.png)

**Comment by Zero-Fanker** [comment]
玩家的还是可以的，AI小队不执行任务的时候也是可以的，确认过了吗？------------------ Original ------------------

**Comment by shuiping233** [comment]
线圈不能主动充电指：在选中磁暴和磁能的时候，光标移动到线圈上没有攻击图标，但是靠近还是可以自动充电的

**Comment by shuiping233** [comment]
现已确认，ai磁暴小队会给线圈充电

**Comment by shuiping233** [comment]
![QQ截图20191109153107](https://user-images.githubusercontent.com/49360196/68524832-5345ec80-0306-11ea-9aaf-3ea1afa4933f.png)
