### ISSUE TITLE
#Bug#新苏联第一关选择城市线如果读取存档则ai不建造给玩家的建筑

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#219]
【现象】：新苏联第一关选择城市线如果读取存档则ai不建造给玩家的建筑
【反馈人】：shuiping
【发现版本号】：G0824
【影响范围】：任务体验
【产生原因】：未知

![QQ截图20190901115742](https://user-images.githubusercontent.com/49360196/64071599-129b7880-ccb0-11e9-8123-38ceaccbcfbb.png)

[SAVE3FB9.zip](https://github.com/Zero-Fanker/RN_All_Issues/files/3586062/SAVE3FB9.zip)

**Comment by Zero-Fanker** [comment]
概率多大?如何触发?为什么我没遇到过?------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2019年9月1日(星期天) 中午12:00
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Zero-Fanker/RN_All_Issues] #Bug#新苏联第一关选择城市线ai有概率不建造给玩家的建筑 (#219)



【现象】：新苏联第一关选择城市线ai有概率不建造给玩家的建&#x7B51;
 【反馈人】：shuiping
 【发现版本号】：G0824
 【影响范围】：任务体验
 【产生原因】：未知
 

 
&mdash;

**Comment by shuiping233** [comment]
> 概率多大?如何触发?为什么我没遇到过?------------------ 原始邮件 ------------------ 发件人: "shuiping"<notifications@github.com> 发送时间: 2019年9月1日(星期天) 中午12:00 收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: [Zero-Fanker/RN_All_Issues] #Bug#新苏联第一关选择城市线ai有概率不建造给玩家的建筑 (#219) 【现象】：新苏联第一关选择城市线ai有概率不建造给玩家的建&#x7B51; 【反馈人】：shuiping 【发现版本号】：G0824 【影响范围】：任务体验 【产生原因】：未知 &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

正在测试，我看看能不能复现

**Comment by shuiping233** [comment]
> 概率多大?如何触发?为什么我没遇到过?------------------ 原始邮件 ------------------ 发件人: "shuiping"<notifications@github.com> 发送时间: 2019年9月1日(星期天) 中午12:00 收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: [Zero-Fanker/RN_All_Issues] #Bug#新苏联第一关选择城市线ai有概率不建造给玩家的建筑 (#219) 【现象】：新苏联第一关选择城市线ai有概率不建造给玩家的建&#x7B51; 【反馈人】：shuiping 【发现版本号】：G0824 【影响范围】：任务体验 【产生原因】：未知 &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

原因可能是玩家选择城市线的同时登上了平原线的悬崖，有待验证

**Comment by shuiping233** [comment]
已经证实开局无操作情况下，选择城市线 ai可以正常建筑给予玩家的建筑
![QQ截图20190901125953](https://user-images.githubusercontent.com/49360196/64071977-e9cbb100-ccb8-11e9-839b-4b2abf9b297f.png)

**Comment by shuiping233** [comment]
能复现问题的方法貌似只有挡住建造位置，可能是ai的部队刚好挡住了建造位置导致无法建造？

**Comment by shuiping233** [comment]
> 概率多大?如何触发?为什么我没遇到过?------------------ 原始邮件 ------------------ 发件人: "shuiping"<notifications@github.com> 发送时间: 2019年9月1日(星期天) 中午12:00 收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: [Zero-Fanker/RN_All_Issues] #Bug#新苏联第一关选择城市线ai有概率不建造给玩家的建筑 (#219) 【现象】：新苏联第一关选择城市线ai有概率不建造给玩家的建&#x7B51; 【反馈人】：shuiping 【发现版本号】：G0824 【影响范围】：任务体验 【产生原因】：未知 &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

已经证实，是存档问题，一旦读取存档则会出现该问题

**Comment by shuiping233** [comment]
> > 概率多大?如何触发?为什么我没遇到过?------------------ 原始邮件 ------------------ 发件人: "shuiping"[notifications@github.com](mailto:notifications@github.com) 发送时间: 2019年9月1日(星期天) 中午12:00 收件人: "Zero-Fanker/RN_All_Issues"[RN_All_Issues@noreply.github.com](mailto:RN_All_Issues@noreply.github.com); 抄送: "Subscribed"[subscribed@noreply.github.com](mailto:subscribed@noreply.github.com); 主题: [Zero-Fanker/RN_All_Issues] #Bug#新苏联第一关选择城市线ai有概率不建造给玩家的建筑 (#219) 【现象】：新苏联第一关选择城市线ai有概率不建造给玩家的建筑 【反馈人】：shuiping 【发现版本号】：G0824 【影响范围】：任务体验 【产生原因】：未知 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 已经证实，是存档问题，一旦读取存档则会出现该问题 ，修改描述

**Comment by shuiping233** [comment]
> > > 概率多大?如何触发?为什么我没遇到过?------------------ 原始邮件 ------------------ 发件人: "shuiping"[notifications@github.com](mailto:notifications@github.com) 发送时间: 2019年9月1日(星期天) 中午12:00 收件人: "Zero-Fanker/RN_All_Issues"[RN_All_Issues@noreply.github.com](mailto:RN_All_Issues@noreply.github.com); 抄送: "Subscribed"[subscribed@noreply.github.com](mailto:subscribed@noreply.github.com); 主题: [Zero-Fanker/RN_All_Issues] #Bug#新苏联第一关选择城市线ai有概率不建造给玩家的建筑 (#219) 【现象】：新苏联第一关选择城市线ai有概率不建造给玩家的建筑 【反馈人】：shuiping 【发现版本号】：G0824 【影响范围】：任务体验 【产生原因】：未知 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.


 已经证实，是存档问题，一旦读取存档则会出现该问题 ，已修改描述

**Comment by Zero-Fanker** [comment]
问题存档上传一下

**Comment by shuiping233** [comment]
[SAVE3FB9.zip](https://github.com/Zero-Fanker/RN_All_Issues/files/3586061/SAVE3FB9.zip)

**Comment by shuiping233** [comment]
已经证实，在城市线ai建造给予玩家的建筑钱存档，并且读取存档会导致该问题

**Comment by shuiping233** [comment]
0.99.911a2 咸老师：测试了所有阵营，玩家2号位，AI阵营全随机，并未出现崩溃现象
测试通过

**Comment by shuiping233** [comment]
咸老师：0.99.911a3测试通过
![image](https://user-images.githubusercontent.com/49360196/142745912-f1c0825a-ee08-4217-bbdc-cd13c7e623fb.png)
