### ISSUE TITLE
#Bug#生化导弹车子机导弹爆炸会影响附近的子机导弹

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#22]
WZ-113 created an issue 2018-09-22
【现象】生化导弹车的子机导弹互相之间存在干扰
一堆导弹车攻击同一个目标时，容易重叠，或者靠的过近。 其中一发导弹被拦截，附近的子机导弹会被摧毁造成浪费。 击中地面时，对空中子机导弹也有同样的影响 
![image](https://user-images.githubusercontent.com/49360196/56454055-f12f9500-637d-11e9-8b9e-51abef5ee0f1.png)

【影响范围】
【产生原因】

**Comment by shuiping233** [comment]
Comments (3)
 Zero Fanker
changed title to 生化导弹车子机导弹爆炸会影响附近的子机导弹
assigned issue to   Zero Fanker
edited description
2018-10-02
 Zero Fanker
changed title to #Bug#生化导弹车子机导弹爆炸会影响附近的子机导弹
edited description
2018-10-06
 Zero Fanker
edited description
2018-10-06
Log in to comment

**Comment by Zero-Fanker** [comment]
应该也是弹头对空范围的问题，驱逐看一下。

**Comment by Zero-Fanker** [comment]
@yuanbanlao @Super-StarX  @Renko-ji  G1208B已修正，请验证

**Comment by shuiping233** [comment]
![GIF41](https://user-images.githubusercontent.com/49360196/71551316-c07d2080-2a1f-11ea-82fe-cce2e2036c1b.gif)
G1208B经过测试，该问题已经解决
