### ISSUE TITLE
#Bug#新苏一任务中，清理完城堡周围部队后，莱赫将军可能被中立方吸引无法登上飞机

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#220]
【现象】：新苏一任务中，清理完城堡周围部队后，莱赫将军出现，但是并没有上飞机，将军去攻击中立单位，飞机停在原地不动。导致无法触发后续剧情
【反馈人】：shuiping
【发现版本号】：G0824
【影响范围】：影响通关
【产生原因】：存档导致触发异常

![QQ截图20190901124102](https://user-images.githubusercontent.com/49360196/64071927-f6033e80-ccb7-11e9-811d-80e44781fdc7.png)
![QQ截图20190901124226](https://user-images.githubusercontent.com/49360196/64071928-f6033e80-ccb7-11e9-9ddd-f7d8dd2dc7db.png)
![QQ截图20190901124517](https://user-images.githubusercontent.com/49360196/64071929-f69bd500-ccb7-11e9-9bc9-fc7a87ec1e3a.png)
![QQ截图20190901124702](https://user-images.githubusercontent.com/49360196/64071930-f69bd500-ccb7-11e9-9c88-85e6a0d0c085.png)
![QQ截图20190901124801](https://user-images.githubusercontent.com/49360196/64071931-f7346b80-ccb7-11e9-94a5-9f0a80f9a556.png)
![QQ截图20190901124917](https://user-images.githubusercontent.com/49360196/64071932-f7346b80-ccb7-11e9-8a48-dec8a4a5452a.png)

**Comment by Zero-Fanker** [comment]
也是存档后导致的?

**Comment by shuiping233** [comment]
> 也是存档后导致的?

并不是存档才导致的

**Comment by Zero-Fanker** [comment]
提供下存档附件。

**Comment by Zero-Fanker** [comment]
@shuiping233 这个问题在H0103B重新试下。

**Comment by shuiping233** [comment]
#61

**Comment by shuiping233** [comment]
H0118版本中，正常通关不存档读档情况下，接莱赫将军的飞机释放动员兵之后去攻击其他部队，导致任务无法进行

**Comment by Zero-Fanker** [comment]
OK等更新

**Comment by Zero-Fanker** [comment]
@yuanbanlao @RN-Hydra  @Renko-ji  H0130已修正，验证下。

**Comment by RN-Hydra** [comment]
H0130已验证，可正常通关，但由于苏2没做出来会弹无法读取剧情框，但是点确定后无法回到主界面中。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Zero Fanker"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月30日(星期四) 晚上7:03
收件人:&nbsp;"Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;"Estrus"<1575629191@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug#新苏一任务中，清理完城堡周围部队后，莱赫将军可能被中立方吸引无法登上飞机 (#220)




@yuanbanlao @RN-Hydra  @Renko-ji  H0130已修正，验证下。
