### ISSUE TITLE
#Bug#越南辐射工兵在站立静止时无法部署？

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#221]
【现象】：越南辐射工兵在站立静止时无法部署，但是在移动时候部署就没问题
【反馈人】：shuiping
【发现版本号】：G0824
【影响范围】：单位操作手感
【产生原因】：未知

**Comment by Zero-Fanker** [comment]
两次部署有CD间隔------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2019年9月7日(星期六) 上午8:24
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Zero-Fanker/RN_All_Issues] #Bug#越南辐射工兵在站立静止时无法部署？ (#221)



【现象】：越南辐射工兵在站立静止时无法部署，但是在移动时候部署就没问题
 【反馈人】：shuiping
 【发现版本号】：G0824
 【影响范围】：单位操作手感
 【产生原因】：未知
 
&mdash;

**Comment by shuiping233** [comment]
> 两次部署有CD间隔------------------ 原始邮件 ------------------ 发件人: "shuiping"<notifications@github.com> 发送时间: 2019年9月7日(星期六) 上午8:24 收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: [Zero-Fanker/RN_All_Issues] #Bug#越南辐射工兵在站立静止时无法部署？ (#221) 【现象】：越南辐射工兵在站立静止时无法部署，但是在移动时候部署就没问题 【反馈人】：shuiping 【发现版本号】：G0824 【影响范围】：单位操作手感 【产生原因】：未知 &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

那这个”cd“最好通过某些形式表现出来，不然会以为辐射部署不出来，例如像基洛夫部署那样部署后有不能部署的光标

**Comment by Zero-Fanker** [comment]
不合适，步兵很小而且数量会很多，又是血条又要有AE再加上状态显示根本来不及看，这是个很鸡肋的效果------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月22日(星期四) 上午10:38
***@***.***&gt;;
抄送:&nbsp;&quot;Zero ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug#越南辐射工兵在站立静止时无法部署？ (#221)

**Comment by shuiping233** [comment]
也对，不过这么一搞这个cd会让人觉得部署的手感非常喂shit

**Comment by Zero-Fanker** [comment]
手感这种东西优先级并不重要，没有Bug是第一位的------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月22日(星期四) 上午10:41
***@***.***&gt;;
抄送:&nbsp;&quot;Zero ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug#越南辐射工兵在站立静止时无法部署？ (#221)

**Comment by shuiping233** [comment]
好
