### ISSUE TITLE
#Bug#新AI尤里钻地车鬼畜问题

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#222]
【现象】：图后面补上。尤里钻地车有大概率会在原地鬼畜无法正常执行脚本
【反馈人】：
【发现版本号】：G0615P
【影响范围】：影响AI使用钻地车
【产生原因】：脚本填写错误或者脚本AI存在不兼容的问题。

[注释]:例子：
[注释]:【现象】：韩国火炮、洲际导弹的信标可以被超时空传送、铁幕装置影响
[注释]:【反馈人】：永恒_叶
[注释]:【发现版本号】：0.99.F1028A
[注释]:【影响范围】：影响带有AI的对局
[注释]:【产生原因】：AI新机制引入

**Comment by MadmanM** [comment]
所有涉及脚本：
[ENG1021C-G]
Name=运输工程师抢油井
0=47,131143;油井
1=8,2
2=49,0
3=46,131143;油井
4=49,0
5=46,131385;实验
6=46,131128;商店
7=46,131141;医院
8=46,131142;机场
9=49,0
10=0,11
11=0,2

[ENG1022C-G]
Name=运输工程师抢商店
0=47,131128;商店
1=8,2
2=49,0
3=46,131128;商店
4=49,0
5=46,131141;医院
6=46,131385;实验
7=46,131142;机场
8=46,131143;油井
9=49,0
10=0,11
11=0,2

[ENG1023C-G]
Name=运输工程师抢医院
0=47,131141;医院
1=8,2
2=49,0
3=46,131141;医院
4=49,0
5=46,131128;商店
6=46,131385;实验
7=46,131142;机场
8=46,131143;油井
9=49,0
10=0,11
11=0,2

[ENG1024C-G]
Name=运输工程师抢机场
0=47,131142;机场
1=8,2
2=49,0
3=46,131142;机场
4=49,0
5=46,131385;实验
6=46,131143;油井
7=46,131128;商店
8=46,131141;医院
9=49,0
10=0,11
11=0,2

[ENG1025C-G]
Name=运输工程师抢实验
0=47,131385;实验
1=8,2
2=49,0
3=46,131385;实验
4=49,0
5=46,131143;油井
6=46,131128;商店
7=46,131141;医院
8=46,131142;机场
9=49,0
10=0,11
11=0,2

[ENG1026C-G]
Name=运输工程师抢前哨
0=47,131140;前哨
1=8,2
2=49,0
3=46,131140;前哨
4=49,0
5=46,131385;实验
6=46,131128;商店
7=46,131141;医院
8=46,131143;油井
9=46,131142;机场
10=49,0
11=0,11
12=0,2

[ENG1027C-G]
Name=运输工程师抢电厂
0=47,131441;电厂
1=8,2
2=49,0
3=46,131441;电厂
4=49,0
5=46,131385;实验
6=46,131143;油井
7=46,131128;商店
8=46,131141;医院
9=46,131142;机场
10=49,0
11=0,11
12=0,2

[ENG1104C-G]
Name=运输工程师偷萌家
0=47,2;基地
1=49,0
2=8,0
3=49,0
4=46,131074;基地
5=46,131079;工厂
6=46,131177;GAAIRC
7=46,131207;AMRADR
8=46,131652;GAAIRB
9=46,131076;T4
10=46,131078;T3
11=46,131073;矿场
12=46,131075;兵营
13=46,131132;FA国兵营
14=46,131072;电厂
15=49,0
16=0,2
17=0,1

[ENG1105C-G]
Name=运输工程师偷萌矿
0=47,1;矿场
1=49,0
2=8,0
3=49,0
4=46,131073;矿场
5=46,131074;基地
6=46,131079;工厂
7=46,131177;GAAIRC
8=46,131207;AMRADR
9=46,131652;GAAIRB
10=46,131076;T4
11=46,131078;T3
12=46,131075;兵营
13=46,131132;FA国兵营
14=46,131072;电厂
15=49,0
16=0,2
17=0,1

[ENG1106C-G]
Name=运输工程师偷萌工
0=47,7;工厂
1=49,0
2=8,0
3=49,0
4=46,131079;工厂
5=46,131074;基地
6=46,131177;GAAIRC
7=46,131207;AMRADR
8=46,131652;GAAIRB
9=46,131076;T4
10=46,131078;T3
11=46,131073;矿场
12=46,131075;兵营
13=46,131132;FA国兵营
14=46,131072;电厂
15=49,0
16=0,2
17=0,1

[ENG1107C-G]
Name=运输工程师偷萌鸡1
0=47,105;GAAIRC
1=49,0
2=8,0
3=49,0
4=46,131177;GAAIRC
5=46,131652;GAAIRB
6=46,131074;基地
7=46,131079;工厂
8=46,131076;T4
9=46,131078;T3
10=46,131073;矿场
11=46,131075;兵营
12=46,131132;FA国兵营
13=46,131072;电厂
14=49,0
15=0,2
16=0,1

[ENG1108C-G]
Name=运输工程师偷萌鸡2
0=47,135;AMRADR
1=49,0
2=8,0
3=49,0
4=46,131207;AMRADR
5=46,131652;GAAIRB
6=46,131074;基地
7=46,131079;工厂
8=46,131076;T4
9=46,131078;T3
10=46,131073;矿场
11=46,131075;兵营
12=46,131132;FA国兵营
13=46,131072;电厂
14=49,0
15=0,2
16=0,1

[ENG1109C-G]
Name=运输工程师偷萌鸡3
0=47,580;GAAIRB
1=49,0
2=8,0
3=49,0
4=46,131652;GAAIRB
5=46,131177;GAAIRC
6=46,131207;AMRADR
7=46,131074;基地
8=46,131079;工厂
9=46,131076;T4
10=46,131078;T3
11=46,131073;矿场
12=46,131075;兵营
13=46,131132;FA国兵营
14=46,131072;电厂
15=49,0
16=0,2
17=0,1

[ENG1204C-G]
Name=运输工程师偷酥家
0=47,25;基地
1=49,0
2=8,0
3=49,0
4=46,131097;基地
5=46,131086;工厂
6=46,131091;NAKZB
7=46,131484;T4
8=46,131089;T4
9=46,131137;核电
10=46,131082;T3
11=46,131087;矿场
12=46,131083;兵营
13=46,131485;古巴兵营
14=49,0
15=0,2
16=0,1

[ENG1205C-G]
Name=运输工程师偷酥矿
0=47,15;矿场
1=49,0
2=8,0
3=49,0
4=46,131087;矿场
5=46,131097;基地
6=46,131086;工厂
7=46,131091;NAKZB
8=46,131484;T4
9=46,131089;T4
10=46,131137;核电
11=46,131082;T3
12=46,131083;兵营
13=46,131485;古巴兵营
14=49,0
15=0,2
16=0,1

[ENG1206C-G]
Name=运输工程师偷酥工
0=47,14;工厂
1=49,0
2=8,0
3=49,0
4=46,131086;工厂
5=46,131097;基地
6=46,131091;NAKZB
7=46,131484;T4
8=46,131089;T4
9=46,131137;核电
10=46,131082;T3
11=46,131087;矿场
12=46,131083;兵营
13=46,131485;古巴兵营
14=49,0
15=0,2
16=0,1

[ENG1207C-G]
Name=运输工程师偷酥工
0=47,14;工厂
1=49,0
2=8,0
3=49,0
4=46,131086;工厂
5=46,131097;基地
6=46,131091;NAKZB
7=46,131484;T4
8=46,131089;T4
9=46,131137;核电
10=46,131082;T3
11=46,131087;矿场
12=46,131083;兵营
13=46,131485;古巴兵营
14=49,0
15=0,2
16=0,1

[ENG1208C-G]
Name=运输工程师偷酥鸡
0=47,19;NAKZB
1=49,0
2=8,0
3=49,0
4=46,131091;NAKZB
5=46,131097;基地
6=46,131086;工厂
7=46,131484;T4
8=46,131089;T4
9=46,131137;核电
10=46,131082;T3
11=46,131087;矿场
12=46,131083;兵营
13=46,131485;古巴兵营
14=49,0
15=0,2
16=0,1

[ENG1303C-G]
Name=运输工程师偷油家
0=47,300;基地
1=49,0
2=8,0
3=49,0
4=46,131372;基地
5=46,131375;工厂
6=46,131368;T4
7=46,131481;机场
8=46,131378;T3
9=46,131090;T2
10=46,131374;兵营
11=46,131373;电厂
12=49,0
13=0,2
14=0,1

[ENG1304C-G]
Name=运输工程师偷油工
0=47,303;工厂
1=49,0
2=8,0
3=49,0
4=46,131375;工厂
5=46,131372;基地
6=46,131368;T4
7=46,131481;机场
8=46,131378;T3
9=46,131090;T2
10=46,131374;兵营
11=46,131373;电厂
12=49,0
13=0,2
14=0,1

[ENG1305C-G]
Name=运输工程师偷油鸡
0=47,409;机场
1=49,0
2=8,0
3=49,0
4=46,131481;机场
5=46,131372;基地
6=46,131375;工厂
7=46,131368;T4
8=46,131378;T3
9=46,131090;T2
10=46,131374;兵营
11=46,131373;电厂
12=49,0
13=0,2
14=0,1

[ATK1010C-G]
Name=打车打塔
0=53,0
1=0,5
2=49,0
3=0,7
4=0,6
5=0,2
6=0,1

[ATK1037C-G]
Name=神经车
0=65,65537
1=65,65566
2=65,65567
3=65,65568
4=49,0
5=0,5
6=0,1

**Comment by Zero-Fanker** [comment]
原因目前认为是后面的一些脚本，让AI的钻地车去攻击没法攻击的建筑。

**Comment by Zero-Fanker** [comment]
G1013已修正，请验证。

**Comment by shuiping233** [comment]
G1028P2经过测试，该问题已经解决
