### ISSUE TITLE
#Bug#部分ai武直在部署时不能成功部署

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#223]
【现象】：部分ai武直在部署时不能成功部署，保持空中模式降落，使用火炮攻击
【反馈人】：
【发现版本号】：G0726
【影响范围】：带有苏系ai的对战
【产生原因】：未知

![338de18a097a69e5](https://user-images.githubusercontent.com/49360196/64904461-16da8380-d6fd-11e9-86ce-22f49b26f2ee.jpg)

**Comment by Zero-Fanker** [comment]
去看一下以前有没有提过? 我记得这是一个已知问题啊，AI和玩家有一定概率部署时候会浮空导致无敌，AI概率更高?------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2019年9月14日(星期六) 下午2:36
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Zero-Fanker/RN_All_Issues] #Bug#部分ai武直在部署时不能成功部署 (#223)



【现象】：部分ai武直在部署时不能成功部署，保持空中模式降落，使用机枪攻击
 【反馈人】：
 【发现版本号】：G0726
 【影响范围】：带有苏系ai的对战
 【产生原因】：未知
 

 
&mdash;

**Comment by shuiping233** [comment]
> 去看一下以前有没有提过? 我记得这是一个已知问题啊，AI和玩家有一定概率部署时候会浮空导致无敌，AI概率更高?------------------ 原始邮件 ------------------ 发件人: "shuiping"<notifications@github.com> 发送时间: 2019年9月14日(星期六) 下午2:36 收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: [Zero-Fanker/RN_All_Issues] #Bug#部分ai武直在部署时不能成功部署 (#223) 【现象】：部分ai武直在部署时不能成功部署，保持空中模式降落，使用机枪攻击 【反馈人】： 【发现版本号】：G0726 【影响范围】：带有苏系ai的对战 【产生原因】：未知 &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

这不是浮空啊，并不会无敌啊，只是用机枪攻击而已

**Comment by shuiping233** [comment]
重点在降落后没有变换武器

**Comment by Zero-Fanker** [comment]
可以归在原先那个问题里面 是同一个问题的不同部分表现------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2019年9月14日(星期六) 下午2:44
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#部分ai武直在部署时不能成功部署 (#223)



重点在降落后没有变换武器
 
&mdash;

**Comment by shuiping233** [comment]
好

**Comment by shuiping233** [comment]
![70bbaea7c257a897](https://user-images.githubusercontent.com/49360196/64904864-aafb1980-d702-11e9-828f-d412be2c4474.gif)

**Comment by Zero-Fanker** [comment]
> ![74a94e824d4bff6a](https://user-images.githubusercontent.com/49360196/64905040-1645eb00-d705-11e9-9408-02507fd4af83.gif)

出现问题的存档传一份

**Comment by Zero-Fanker** [comment]
G1013已修正，请验证 @shuiping233  @yuanbanlao

**Comment by shuiping233** [comment]
G1028P2经过测试，该问题并没有再出现
