### ISSUE TITLE
#建议反馈#建议削弱三星熔岩炮

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#224]
【描述】 建议削弱三星熔岩炮的射速，现熔岩炮三星后射速大幅提升，加上减速效果，成为超越所有t2塔的存在，建议削弱三星熔岩炮射速至三星线圈水准
【原因】射速过快，输出太高
【期望解决时间】下一版本公测

**Comment by Zero-Fanker** [comment]
at一下kk和星星 让他们评估一下------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2019年9月14日(星期六) 下午2:56
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Zero-Fanker/RN_All_Issues] #建议反馈#建议削弱三星熔岩炮 (#224)



【描述】 建议削弱三星熔岩炮的射速，现熔岩炮三星后射速大幅提升，加上减速效果，成为超越所有t2&#x5854;的存在，建议削弱三星熔岩炮射速至三星线圈水准
 【原因】射速过快，输出太高
 【期望解决时间】下一版本公测
 
&mdash;

**Comment by shuiping233** [comment]
@Super-StarX @yuanbanlao

**Comment by yuanbanlao** [comment]
我打不出来三星熔岩塔。如果真的很强，那就削弱把。

**Comment by Zero-Fanker** [comment]
用地编摆一个，经验值那里写200------------------ 原始邮件 ------------------
发件人: "yuanbanlao"<notifications@github.com>
发送时间: 2019年11月26日(星期二) 下午5:17
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Zero-Fanker/RN_All_Issues] #建议反馈#建议削弱三星熔岩炮 (#224)



我打不出来三星熔岩&#x5854;。如果真的很强，那就削弱把。
 
&mdash;

**Comment by shuiping233** [comment]
@yuanbanlao 要不顺便讨论一下无星的熔岩炮

**Comment by shuiping233** [comment]
三星熔岩炮高射速，还能一发干红动员兵，打坦克建筑又不赖，我觉得最低要求是把三星熔岩炮和无星的同步反步兵不那么强就行了

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/127245118-9f9e9138-433e-493c-8b6b-7bf96ccfcd72.png)

**Comment by Zero-Fanker** [comment]
![image](https://user-images.githubusercontent.com/14891010/129765671-c8be2b9a-bb05-406d-85c7-1ab3029b3a2a.png)
这个单子特别早，在0.99.902就已经包含了

**Comment by shuiping233** [comment]
![gif154](https://user-images.githubusercontent.com/49360196/130321179-74f01a57-3ad6-4357-95cb-8a45c8d11597.gif)
![gif153](https://user-images.githubusercontent.com/49360196/130321180-01320c29-769b-401f-bfb6-e7c01f4bbc72.gif)

**Comment by shuiping233** [comment]
@yuanbanlao 这个你来测吧，或者叫74

**Comment by Zero-Fanker** [comment]
@yuanbanlao

**Comment by yuanbanlao** [comment]
符合预期。

**Comment by Zero-Fanker** [comment]
@klighting444  按0.99.902版本号归档
