### ISSUE TITLE
关于遭遇战南极洲地图的bug反馈

### ISSUE THREAD

**Issue by mariodad3** [Zero-Fanker/RN_All_Issues#230]
【现象】：7号位的AI在快速游戏的情况下卖家后依旧存活
【反馈人】：（如果是自己的帐户可以不填，代他人提交必填）
【发现版本号】：0.99 H.F 1028A
【影响范围】：遭遇战无法顺利结束游戏
【产生原因】：7号位发展时间过长就容易出现这种情况，快速游戏下AI自动卖家，但是电脑依旧存活 个人猜测是7号位距离下边界过近，当ai发展到一定程度后，就有可能将建筑建造到地图之外，而变卖建筑时外围建筑不会变卖，而玩家也无法看到和攻击到，导致游戏无法结束。

[SAVE38A8.zip](https://github.com/Zero-Fanker/RN_All_Issues/files/3720712/SAVE38A8.zip)

附上出问题的存档文件

**Comment by shuiping233** [comment]
如果可以的话，请用群测G0726再次测试是否还会发生

**Comment by Zero-Fanker** [comment]
已知并修复了的问题。见#167
