### ISSUE TITLE
#建议反馈#隐形单位开火显形后，因装填间隔较长导致无法及时再次隐形

### ISSUE THREAD

**Issue by yuanbanlao** [Zero-Fanker/RN_All_Issues#231]
【描述】狙击手站立状态移动现形，攻击不现形；部署状态攻击现形。其它单位不等待装填间隔，遵循独立的再次隐形间隔。
【原因】工头让另提一单
【期望解决时间】越快越好

**Comment by Zero-Fanker** [comment]
老哈有时间看一下，是不是再次隐形之前检查了武器ROFTimer

**Comment by Zero-Fanker** [comment]
去掉了对武器装填间隔的判定，并对CloakDelay引入微观控制。

**Comment by Zero-Fanker** [comment]
> 【描述】如标题所述
> 【原因】工头让另提一单
> 【期望解决时间】越快越好

有没有一些标志性的单位，用于作验证参照

**Comment by shuiping233** [comment]
b2（幽灵核炸鸡）



---原始邮件---
发件人: "Zero Fanker"<notifications@github.com&gt;
发送时间: 2020年5月3日(星期日) 上午10:55
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [Zero-Fanker/RN_All_Issues] #建议反馈#隐形单位开火显形后，因装填间隔较长导致无法及时再次隐形 (#231)




  
【描述】如标题所述
 【原因】工头让另提一单
 【期望解决时间】越快越好
  
有没有一些标志性的单位，用于作验证参照

**Comment by Zero-Fanker** [comment]
> b2（幽灵核炸鸡）
> […](#)
> ---原始邮件--- 发件人: "Zero Fanker"<notifications@github.com&gt; 发送时间: 2020年5月3日(星期日) 上午10:55 收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: Re: [Zero-Fanker/RN_All_Issues] #建议反馈#隐形单位开火显形后，因装填间隔较长导致无法及时再次隐形 (#231) 【描述】如标题所述 【原因】工头让另提一单 【期望解决时间】越快越好 有没有一些标志性的单位，用于作验证参照 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

B2是不一样的，而且B2设置一段时间的非隐形状态是为了平衡性，是故意设置的，既便这次调整我依然设置了200帧的显形时间。

**Comment by shuiping233** [comment]
那我想到了狙击手，镭射坦克我没试过，但是狙击手有时候隐形还能被蜘蛛吃，有时候隐形了又不能被蜘蛛吃



---原始邮件---
发件人: "Zero Fanker"<notifications@github.com&gt;
发送时间: 2020年5月3日(星期日) 中午11:49
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"shuiping"<1944680304@qq.com&gt;;
主题: Re: [Zero-Fanker/RN_All_Issues] #建议反馈#隐形单位开火显形后，因装填间隔较长导致无法及时再次隐形 (#231)




  
b2（幽灵核炸鸡）
 …
 ---原始邮件--- 发件人: "Zero Fanker"<notifications@github.com&gt; 发送时间: 2020年5月3日(星期日) 上午10:55 收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: Re: [Zero-Fanker/RN_All_Issues] #建议反馈#隐形单位开火显形后，因装填间隔较长导致无法及时再次隐形 (#231) 【描述】如标题所述 【原因】工头让另提一单 【期望解决时间】越快越好 有没有一些标志性的单位，用于作验证参照 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
B2是不一样的，而且B2设置一段时间的非隐形状态是为了平衡性，是故意设置的，既便这次调整我依然设置了200帧的显形时间。

**Comment by yuanbanlao** [comment]
具有长时间装填的隐形，攻击现形单位当前来看只有狙击手。

**Comment by Zero-Fanker** [comment]
> 具有长时间装填的隐形，攻击现形单位当前来看只有狙击手。

狙击手希望停止开火后立即隐形还是等待一段时间？如果等待的话是持续多久？

**Comment by yuanbanlao** [comment]
隐形中开枪。
像潜艇一样。

**Comment by Zero-Fanker** [comment]
潜艇也是遵循开火间隔的，新机制只是不等装填间隔了------------------ 原始邮件 ------------------
发件人: "yuanbanlao"<notifications@github.com>
发送时间: 2020年5月4日(星期一) 下午2:16
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Assign"<assign@noreply.github.com>;
主题: Re: [Zero-Fanker/RN_All_Issues] #建议反馈#隐形单位开火显形后，因装填间隔较长导致无法及时再次隐形 (#231)




 
&#x9690;形中开枪。
 像潜艇一样。
 
&mdash;

**Comment by Zero-Fanker** [comment]
H0504已调整，请验证 @yuanbanlao  @Super-StarX  @shuiping233

**Comment by shuiping233** [comment]
就只有狙击手吗，还有狙击手之前不是隐形中开火的？

**Comment by Zero-Fanker** [comment]
所有隐形单位都是受到本次调整影响的，例如尤里的镭射炮坦克，尤里基地车(但是基地车无武器，理论上没差别)，所有的潜水单位(重点关注下雷鸣潜艇)------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2020年5月6日(星期三) 下午2:06
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Assign"<assign@noreply.github.com>;
主题: Re: [Zero-Fanker/RN_All_Issues] #建议反馈#隐形单位开火显形后，因装填间隔较长导致无法及时再次隐形 (#231)




 
就只有狙击手吗，还有狙击手之前不是&#x9690;形中开火的？
 
&mdash;

**Comment by shuiping233** [comment]
镭射坦克，雷鸣潜艇，台风潜艇，狙击手，还有其他的么？我暂时没想到其他的

**Comment by shuiping233** [comment]
还有具体的恢复隐形时间我不知道呀，这个可能要kk亲自来才能知道符不符合他的要求吧？

**Comment by shuiping233** [comment]
H0506测试结果：雷鸣潜艇即使是手动s停止攻击亦或者导弹炸掉目标后雷鸣都可以瞬间隐形，狙击手和镭射坦克与其相比则完全不合格，狙击手和镭射在攻击完成后均无法立刻隐形，都需要一定时间，4速下狙击手开火到停止攻击并隐形大约要4s，镭射坦克也是差不多和狙击手一个样子，至于狙击手和镭射的隐形时间长是否合理我还不清楚，达到预期要求了吗 ？

**Comment by Zero-Fanker** [comment]
让kk试下 你去催下他 ------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2020年5月6日(星期三) 晚上10:32
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Assign"<assign@noreply.github.com>;
主题: Re: [Zero-Fanker/RN_All_Issues] #建议反馈#隐形单位开火显形后，因装填间隔较长导致无法及时再次隐形 (#231)




 
H0506测试结果：雷鸣潜艇即使是手动s停止攻击亦或者导弹炸掉目标后雷鸣都可以瞬间&#x9690;形，狙击手和镭射坦克与其相比则完全不合格，狙击手和镭射在攻击完成后均无法立刻&#x9690;形，都需要一定时间，4速下狙击手开火到停止攻击并&#x9690;形大约要4s，镭射坦克也是差不多和狙击手一个样子，至于狙击手和镭射的&#x9690;形时间长是否合理我还不清&#x695A;，达到预期要求了吗 ？
 
&mdash;

**Comment by shuiping233** [comment]
@yuanbanlao 来测你的单子

**Comment by yuanbanlao** [comment]
测完了，别催了。完全达不到预期效果。

**Comment by yuanbanlao** [comment]
预期目标：狙击手站立状态移动现形，攻击不现形；部署状态攻击现形。
镭射炮坦克因为本身就有一个前摇，所以我很难判断出这个单位的情况。
雷鸣和台风和原版保持一致。
尤里mcv因为没有武器不做测试。

**Comment by Zero-Fanker** [comment]
H1015已最终调整，请验证。

**Comment by yuanbanlao** [comment]
H1015B已验证，一切按照预期进行。 @klighting444 请归档。
