### ISSUE TITLE
#Bug#科技机械车间即使没有被占领也能维修已方装甲部队

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#232]
【现象】：科技机械车间即使没有被占领也能维修已方装甲部队
【反馈人】：shuiping
【发现版本号】：G1013B
【影响范围】：有科技机械车间出现的任务和遭遇战
【产生原因】：未知

![GIF21](https://user-images.githubusercontent.com/49360196/67155770-b2d45c00-f347-11e9-9a5d-fcfd199aed56.gif)

**Comment by shuiping233** [comment]
发现萌1也有

**Comment by Zero-Fanker** [comment]
驱逐看一下是不是这个AE没有设置对敌方无效。但我觉得应该只是结盟问题。

**Comment by Crossfield-ClassDestroyer** [comment]
已确定 应该是地图所属方盟友关系不正确导致的问题

**Comment by Zero-Fanker** [comment]
> 发现萌1也有

盟1本来就友方关系，所以没有问题，不过由于它是满血我现在改成非满血，否则不能维修获得。

**Comment by Zero-Fanker** [comment]
I0206已调整

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/107211995-44864200-6a41-11eb-858a-9fd50d36c99c.png)
I0206测试通过，该问题已解决
