### ISSUE TITLE
#Bug#[原版遗留]玩家的建筑生产就绪后，唯一建造厂更改所属，再次获得建造厂按Q热键崩溃问题

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#233]
【现象】：玩家如果唯一的建造厂被占领/心控/触发更改归属时，若此时存在就绪待摆放的建筑，失去建造厂再获得时按下Q键（侧边图标栏切换建筑选单默认热键），会导致程序崩溃
【反馈人】：竹蜻蜓
【发现版本号】：G1028
【影响范围】：影响玩家建造厂可能会变更所属的场景。
【产生原因】：原版平台未对该情况及时清理全局指针，野指针问题。

**Comment by Zero-Fanker** [comment]
G1028P2已修正，请验证。 @shuiping233  @yuanbanlao

**Comment by shuiping233** [comment]
G1028P2经过测试，该问题已经解决
测试环境：联机
