### ISSUE TITLE
#Bug#韩国光明星火炮在攻击信标时没有抬起炮管，导致开火位置错位

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#235]
【现象】：韩国光明星火炮在攻击信标时没有抬起炮管，导致开火位置错位
【反馈人】：T-72B TANK
【发现版本号】：G1028P2
【影响范围】：视觉体验
【产生原因】：未知

**Comment by shuiping233** [comment]
![GIF23](https://user-images.githubusercontent.com/49360196/68080571-876a6a80-fe39-11e9-8817-926ab01bab83.gif)
![Uploading GIF23.gif…]()

**Comment by Zero-Fanker** [comment]
G1028P3已修复，请验证。

**Comment by shuiping233** [comment]
G1028P3版本经过测试，该问题已经解决

**Comment by shuiping233** [comment]
![GIF30](https://user-images.githubusercontent.com/49360196/68537018-01e63d80-0398-11ea-8456-2ba4ba749a61.gif)
