### ISSUE TITLE
#Bug#静止盟军的矿车可以让所有子弹武器失效

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#236]
【现象】：静止盟军的矿车可以让所有子弹武器失效；盟军矿车一旦移动，子弹武器又恢复正常，可以对其造成伤害
【反馈人】：T-72B TANK
【发现版本号】：G1028P2
【影响范围】：带有盟军矿车的对战
【产生原因】：未知

**Comment by shuiping233** [comment]
![GIF25](https://user-images.githubusercontent.com/49360196/68081415-93a9f400-fe48-11e9-8017-2401087d4a87.gif)

**Comment by Zero-Fanker** [comment]
啥叫失效?

**Comment by shuiping233** [comment]
什么伤害都没有

**Comment by shuiping233** [comment]
断电遥控坦克仅免疫古巴宣传飞艇和自行高炮的武器

**Comment by Zero-Fanker** [comment]
@Crossfield-ClassDestroyer  看一下上述提到的武器和其他机枪类武器弹头的差异

**Comment by Zero-Fanker** [comment]
H0209已修复，请验证。
@yuanbanlao  @RN-Hydra @WZ-113 @shuiping233

**Comment by yuanbanlao** [comment]
H0209已验证。矿车不再具有此上功能。请归档 @klighting444
