### ISSUE TITLE
#Bug#英国狙击手反载具模式对部署的尤里矿车伤害与矿车移动模式不一致

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#237]
【现象】：英国狙击手反载具模式对部署的尤里矿车伤害与矿车移动模式不一致
【反馈人】：shuiping
【发现版本号】：G1028P2
【影响范围】：带有英国和尤里的对战
【产生原因】：未知

**Comment by Zero-Fanker** [comment]
护甲和占地不一样，kk怎么看 @yuanbanlao

**Comment by shuiping233** [comment]
本来录了GIF的但是不知道为何发不上来，我明天看看能不能发上来

**Comment by Zero-Fanker** [comment]
图片问题不大。我觉得有差异本身也是正常的，看kk怎么看，差异容差范围。------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2019年11月9日(星期六) 晚上7:16
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#英国狙击手反载具模式对部署的尤里矿车伤害与矿车移动模式不一致 (#237)



本来录了GIF的但是不知道为何发不上来，我明天看看能不能发上来
 
&mdash;

**Comment by shuiping233** [comment]
![GIF27](https://user-images.githubusercontent.com/49360196/68536917-c8143780-0395-11ea-9cb5-021e8d23c1ce.gif)
![GIF28](https://user-images.githubusercontent.com/49360196/68536918-c8143780-0395-11ea-9d5b-901da762e11c.gif)
![GIF29](https://user-images.githubusercontent.com/49360196/68536919-c8143780-0395-11ea-8c42-938f5a9f4f0e.gif)

**Comment by shuiping233** [comment]
H0501实测结果：部署状态的狙击手一枪打载具模式的尤矿为54点伤害，攻击部署状态的尤矿为156点伤害

**Comment by shuiping233** [comment]
当狙击手吃观察员加成时，部署的尤矿可被狙击手两发炸掉

**Comment by yuanbanlao** [comment]
如果对于部署奴矿伤害过大，建议砍一下。不过奴矿2000的血量，156的攻击可以选择忽视差异，作为英国玩家使用狙击手的一个可选选择。

**Comment by shuiping233** [comment]
没观察员的情况下只是对尤矿不同模式有不同伤害，我认为统一一下就可以，有观察员加成的情况确实要削弱对尤矿伤害了



---原始邮件---
发件人: "yuanbanlao"<notifications@github.com&gt;
发送时间: 2020年5月7日(星期四) 晚上11:29
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"shuiping"<1944680304@qq.com&gt;;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#英国狙击手反载具模式对部署的尤里矿车伤害与矿车移动模式不一致 (#237)




 
如果对于部署奴矿伤害过大，建议砍一下。不过奴矿2000的血量，156的攻击可以选择忽视差异，作为英国玩家使用狙击手的一个可选选择。

**Comment by yuanbanlao** [comment]
没有必要更改。有观察员的情况下已经可以用很多方式对奴矿造成可观伤害了，而且双雄是英国核心英雄单位，用来单奔打牛，即使伤害高也不是一个好选择。

**Comment by Zero-Fanker** [comment]
close #237 ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;yuanbanlao&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月26日(星期六) 下午4:46
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;Zero Fanker&quot;<zcyfksn@vip.qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug#英国狙击手反载具模式对部署的尤里矿车伤害与矿车移动模式不一致 (#237)

**Comment by shuiping233** [comment]
我测的好像是友军伤害，干脆重新测一下好了

**Comment by shuiping233** [comment]
修正结论，英狙反坦克模式下打展开的奴矿只需10枪

**Comment by shuiping233** [comment]
平均一枪200
