### ISSUE TITLE
#Bug#间谍渗透重工后，尤里重力支配塔射出的弹头会显示升级图标

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#239]
【现象】：间谍渗透重工后，尤里重力支配塔射出的弹头会显示升级图标
【反馈人】：shuiping
【发现版本号】：G1028P3
【影响范围】：视觉体验
【产生原因】：未知

**Comment by shuiping233** [comment]
![GIF31](https://user-images.githubusercontent.com/49360196/68537283-c51c4580-039b-11ea-956b-1a00c87c9488.gif)

**Comment by Zero-Fanker** [comment]
@shuiping233 @yuanbanlao  G1207P 已修正，请验证。

**Comment by yuanbanlao** [comment]
G1207P已验证，渗透重工之后不再产生1星重力塔图标。

**Comment by yuanbanlao** [comment]
G1207P已验证，渗透重工之后不再产生1星重力塔图标。

**Comment by yuanbanlao** [comment]
G1207P已验证，渗透重工之后不再产生1星重力塔图标。
