### ISSUE TITLE
#Bug##群测#德国自动化车间未完成但可造

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#24]
Zero Fanker created an issue 2018-10-03
屏蔽德国自动化车间的建造授权。

**Comment by shuiping233** [comment]
Zero Fanker REPORTER
assigned issue to   Thomas Sneddon
在程序中直接屏蔽，具体细节私聊说。

2018-10-03
 Zero Fanker REPORTER
assigned issue to   Zero Fanker
取消程序内修复，转为ini直接干预。

2018-10-05
 Zero Fanker REPORTER
changed status to resolved
已经在ini中屏蔽
