### ISSUE TITLE
#Bug#观战模式下的国家国旗未做更改

### ISSUE THREAD

**Issue by yuanbanlao** [Zero-Fanker/RN_All_Issues#240]
【现象】：观察者模式下的侧边栏显示原版国家的国旗而非复仇时刻国家国旗。
【反馈人】：
【发现版本号】：G1208B
【影响范围】：联机观战
【产生原因】：不知道

**Comment by Zero-Fanker** [comment]
版本号填完整，归档要参考的------------------ 原始邮件 ------------------
发件人: "yuanbanlao"<notifications@github.com>
发送时间: 2019年11月13日(星期三) 上午9:32
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Zero-Fanker/RN_All_Issues] #Bug#观战模式下的国家国旗未做更改 (#240)



【现象】：观察者模式下的侧边栏显示原版国家的国旗而非复仇时刻国家国旗。
 【反馈人】：
 【发现版本号】：p2
 【影响范围】：联机观战
 【产生原因】：不知道
 
&mdash;

**Comment by Zero-Fanker** [comment]
@xuetianyi

**Comment by Zero-Fanker** [comment]
H0602已修复，请验证 @yuanbanlao @shuiping233  @Super-StarX

**Comment by shuiping233** [comment]
我内存不够，我下星期找人测

**Comment by shuiping233** [comment]
@yuanbanlao

**Comment by shuiping233** [comment]
@yuanbanlao 从去年nov到今年jul，kk你啥时候测呀

**Comment by yuanbanlao** [comment]
咕咕咕

**Comment by yuanbanlao** [comment]
G0830已验证，国旗在观战模式下显示正常。

**Comment by Zero-Fanker** [comment]
@klighting444  小碗按 H0602归档
