### ISSUE TITLE
#建议反馈#希望能给超时空载具传送平台增加集结点功能

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#242]
【描述】：希望能给超时空载具传送平台增加集结点功能，类似于重工那样可以设置单位初始集结点
【原因】：传送的单位总在平台附近集结，需要花费时间操作那些单位，希望能简化这个过程
【期望解决时间】：下次公测

**Comment by Zero-Fanker** [comment]
已修改代码支持。

**Comment by Zero-Fanker** [comment]
@shuiping233 @yuanbanlao @RN-Hydra @WZ-113  H0130已修正，请验证。

**Comment by RN-Hydra** [comment]
H0130已验证，集结点功能一切正常。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Zero Fanker"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月30日(星期四) 晚上7:20
收件人:&nbsp;"Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;"Estrus"<1575629191@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #建议反馈#希望能给超时空载具传送平台增加集结点功能 (#242)




@shuiping233 @yuanbanlao @RN-Hydra @WZ-113  H0130已修正，请验证。
