### ISSUE TITLE
#Bug#磁暴步兵给ACS运载车充电会导致运载车护盾消失

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#244]
【现象】：磁暴步兵给ACS运载车充电会导致运载车护盾消失，如图所示
【反馈人】：shuiping
【发现版本号】：G1123P
【影响范围】：单位手感
【产生原因】：未知

**Comment by shuiping233** [comment]
![Uploading GIF32.gif…]()
![Uploading GIF32.gif…]()
![Uploading GIF32.gif…]()

**Comment by shuiping233** [comment]
![GIF32](https://user-images.githubusercontent.com/49360196/69475161-c66e5900-0e04-11ea-8237-8ac33ebc7e7a.gif)

**Comment by Zero-Fanker** [comment]
G1203P 已修复，请验证。
@yuanbanlao @Renko-ji

**Comment by yuanbanlao** [comment]
G1203已验证，磁暴步兵可以正常给acs车充电了。
