### ISSUE TITLE
#Bug#对苏俄磁能要塞使用基因突变会导致要塞爆炸

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#245]
【现象】：对苏俄磁能要塞使用基因突变会导致要塞爆炸
【反馈人】：T-72B TANK
【发现版本号】：G1123P1
【影响范围】：影响遭遇战
【产生原因】：未知

**Comment by shuiping233** [comment]
![GIF33](https://user-images.githubusercontent.com/49360196/69907888-6c2f5280-1419-11ea-948d-00287e536f78.gif)

**Comment by yuanbanlao** [comment]
G1203已验证，现在基因突变不会对磁能要塞造成伤害。
