### ISSUE TITLE
#Bug#黑鹰战机造成的火焰在空中时始终影响地面

### ISSUE THREAD

**Issue by yuanbanlao** [Zero-Fanker/RN_All_Issues#246]
【现象】：黑鹰战机投弹后产生的火焰特效在空中会同时对该格的陆地单位造成伤害。
【反馈人】：（如果是自己的帐户可以不填，代他人提交必填）
【发现版本号】：G1208
【影响范围】：有黑鹰的地方

**Comment by Zero-Fanker** [comment]
对空的早就修改过了。

**Comment by Zero-Fanker** [comment]
需要规范弹头对地面影响判定机制，计划本周末完成。

**Comment by Zero-Fanker** [comment]
H0602已修正，请验证。
@yuanbanlao  @shuiping233

**Comment by shuiping233** [comment]
H0602测试结果：该问题已解决；黑鹰攻击空中单位那么火焰只会影响空中，黑鹰攻击地面时火焰只会影响地面
