### ISSUE TITLE
#Bug#玩家可以建造新增摆件

### ISSUE THREAD

**Issue by Crossfield-ClassDestroyer** [Zero-Fanker/RN_All_Issues#247]
【现象】：玩家可以在防御栏建造新增摆件
【发现版本号】：G1203P
【影响范围】：遭遇战
【产生原因】：未屏蔽该建筑

**Comment by yuanbanlao** [comment]
G1203P1已验证，玩家不再可以建造该摆件。

**Comment by yuanbanlao** [comment]
G1203P1已验证，玩家不再可以建造该摆件。
