### ISSUE TITLE
#Bug#武直部署形态炮弹对空军有伤害

### ISSUE THREAD

**Issue by yuanbanlao** [Zero-Fanker/RN_All_Issues#249]
【现象】：武直部署形态的炮弹落在的格子上的空军也会受到伤害。
【反馈人】：Dr.k.k.k
【发现版本号】：G1203P
【影响范围】：单机联机
【产生原因】：不知道

[注释]:例子：
[注释]:【现象】：韩国火炮、洲际导弹的信标可以被超时空传送、铁幕装置影响
[注释]:【反馈人】：永恒_叶
[注释]:【发现版本号】：0.99.F1028A
[注释]:【影响范围】：影响带有AI的对局
[注释]:【产生原因】：AI新机制引入

**Comment by shuiping233** [comment]
![GIF38](https://user-images.githubusercontent.com/49360196/71551066-d1766380-2a18-11ea-9840-bb9b52ac384c.gif)
G1208B经过测试，暂未发现该问题
