### ISSUE TITLE
#Bug#盖特在高架桥上的一系列迷惑行为

### ISSUE THREAD

**Issue by yuanbanlao** [Zero-Fanker/RN_All_Issues#250]
【现象】：盖特坦克在高架桥上有以下迷惑行为：
1. a桥面地板会a不准，大多情况下单位走在任何格子上都不会受到伤害。
2. 对于同在桥上或者在水面上/不同高度陆地上的空军无法攻击，但是可以攻击相同地面高度的空军。

【反馈人】：星星
【发现版本号】：G1028P3
【影响范围】：单机联机
【产生原因】：弹道算法存在漏洞

**Comment by Zero-Fanker** [comment]
G1208P? 版本号确定?------------------ 原始邮件 ------------------
发件人: "yuanbanlao"<notifications@github.com>
发送时间: 2019年12月9日(星期一) 下午2:43
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Zero-Fanker/RN_All_Issues] #Bug#盖特在高架桥上的一系列迷惑行为 (#250)



【现象】：盖特坦克在高架桥上有以下迷惑行为：1.a桥面地板会a不准，大多情况下单位走在任何格子上都不会受到伤害。2.对于同在桥上或者在水面上/不同高度陆地上的空军无法攻击，但是可以攻击相同地面高度的空军。
 【反馈人】：星星
 【发现版本号】：G1028P
 【影响范围】：单机联机
 【产生原因】：不知道
 
&mdash;

**Comment by Zero-Fanker** [comment]
G1028P ?------------------ 原始邮件 ------------------
发件人: "yuanbanlao"<notifications@github.com>
发送时间: 2019年12月9日(星期一) 下午2:43
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Zero-Fanker/RN_All_Issues] #Bug#盖特在高架桥上的一系列迷惑行为 (#250)



【现象】：盖特坦克在高架桥上有以下迷惑行为：1.a桥面地板会a不准，大多情况下单位走在任何格子上都不会受到伤害。2.对于同在桥上或者在水面上/不同高度陆地上的空军无法攻击，但是可以攻击相同地面高度的空军。
 【反馈人】：星星
 【发现版本号】：G1028P
 【影响范围】：单机联机
 【产生原因】：不知道
 
&mdash;

**Comment by shuiping233** [comment]
不仅仅是盖特，地面单位在桥上都没法操作去执行攻击指令

**Comment by Zero-Fanker** [comment]
> 不仅仅是盖特，地面单位在桥上都没法操作去执行攻击指令

没法执行？

**Comment by Zero-Fanker** [comment]
H0209已修复，请验证。
@yuanbanlao @RN-Hydra @WZ-113 @shuiping233

**Comment by yuanbanlao** [comment]
H0209已验证。盖特坦克之前出现在高架桥上的问题也没有了。

**Comment by yuanbanlao** [comment]
@klighting444 请归档。
