### ISSUE TITLE
#Bug#生化危机起源任务敌人ai会部署天降红潮技能

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#254]
【现象】：生化危机起源任务敌人ai会部署天降红潮技能，任务无法进行下去
【反馈人】：忘了
【发现版本号】：G1208
【影响范围】：任务通关
【产生原因】：未知

**Comment by Zero-Fanker** [comment]
驱逐把生化图里的这个技能禁掉吧！

**Comment by Zero-Fanker** [comment]
H0103已修正，请验证。

**Comment by shuiping233** [comment]
H0103测试结果：在游玩了10分钟还未发现ai部署天降红潮技能。该问题已经解决
