### ISSUE TITLE
#Bug#辐射浓度可以无限叠加

### ISSUE THREAD

**Issue by yuanbanlao** [Zero-Fanker/RN_All_Issues#256]
【现象】：包括但不限于化学工兵，毒蝎坦克，火箭弹的辐射，经过测验可以叠加到一个离谱的高度，直觉上感觉可以无限叠加
【反馈人】：
【发现版本号】：G1208B
【影响范围】：单机联机
【产生原因]：辐射逻辑问题

**Comment by Zero-Fanker** [comment]
H0118已重构辐射逻辑，请验证。
@shuiping233  @yuanbanlao

**Comment by Zero-Fanker** [comment]
另，辐射的完整测试用例：

【步骤】
1. 单个辐射工兵部署，观察对陆地单位和建筑的杀伤
2. 两个辐射工兵相邻部署，观察对陆地单位和建筑的杀伤
3. 使用核弹/打爆核电厂引发核爆，观察辐射对陆地单位和建筑的杀伤
4. 使用核弹/打爆核电厂引发核爆，并在核辐射范围内使用辐射工兵，观察辐射对陆地单位和建筑的杀伤
5. 在核辐射的影响位置中心使用辐射工兵，观察辐射对陆地单位和建筑的杀伤

【期望现象】
1. 步骤1中，每16帧(需要调低游戏速度)，陆地单位会受到一次杀伤，且同一个类型的单位受到杀伤的数值从中心到边缘随距离成反比例衰减，
RN中辐射工兵不影响建筑，此外辐射工兵的辐射在建立和消逝的全过程中，辐射浓度随时间线性衰减（同一距离的单位受伤逐渐减少），辐射消逝之后，原辐射影响范围内的单位不再掉血（其它伤害来源除外）
2. 步骤2中，两个相同类型辐射源重叠区域的最大值不会超过500（实际测试时可观察一个特定单位的掉血速度）
3. 步骤3中，辐射影响范围内的建筑会受到辐射影响而掉血，目前是每16帧掉一次，且与建筑在辐射范围内的格子数量有关系，与距离有关系，具体的影响比例需要测试后予以评论（目前针对建造厂做了基准调节）
4. 步骤4中，两个不同类型的辐射源重叠区域独立计算（杀伤间隔、杀伤值），注意如果两个辐射是同时产生的，单位是否会重复播放死亡动画
5. 步骤5中，两个辐射都能独立运作，同步骤4，不会出现辐射工兵无法释放辐射的问题

**Comment by shuiping233** [comment]
![GIF55](https://user-images.githubusercontent.com/49360196/72675862-82769800-3ac5-11ea-9322-709fb31b19f5.gif)

**Comment by shuiping233** [comment]
H0118测试中，发现两辐射不同时部署而是分开部署的时候后部署的辐射极其容易不释放辐射，问题在多辐射分批部署时更明显

**Comment by shuiping233** [comment]
从我测试的结果来看，辐射目前对建筑没有伤害，但是会建筑遇到辐射会播放建筑被攻击的语音。
并没有出现多个辐射区域重叠会出现多次播放死亡动画的问题

**Comment by Zero-Fanker** [comment]
工兵不部署是因为浓度要低于1/3 你这测的同类型还是不同类型?------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2020年1月19日(星期天) 下午2:14
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Assign"<assign@noreply.github.com>;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#辐射浓度可以无限叠加 (#256)



H0118测试中，发现两辐射不同时部署而是分开部署的时候后部署的辐射极其容易不释放辐射，问题在多辐射分批部署时更明显
 
&mdash;

**Comment by shuiping233** [comment]
> 工兵不部署是因为浓度要低于1/3 你这测的同类型还是不同类型?------------------ 原始邮件 ------------------ 发件人: "shuiping"<notifications@github.com> 发送时间: 2020年1月19日(星期天) 下午2:14 收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>; 抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Assign"<assign@noreply.github.com>; 主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#辐射浓度可以无限叠加 (#256) H0118测试中，发现两辐射不同时部署而是分开部署的时候后部署的辐射极其容易不释放辐射，问题在多辐射分批部署时更明显 &mdash; You are receiving this because you were assigned. Reply to this email directly, view it on GitHub, or unsubscribe.

那行，那就没问题了

**Comment by Zero-Fanker** [comment]
只有核辐射影响建筑，另外你应该把维修关掉观察------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2020年1月19日(星期天) 下午2:17
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Assign"<assign@noreply.github.com>;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#辐射浓度可以无限叠加 (#256)



从我测试的结果来看，辐射目前对建&#x7B51;没有伤害，但是会建&#x7B51;遇到辐射会播放建&#x7B51;被攻击的语音。
 并没有出现多个辐射区域重&#x53E0;会出现多次播放死亡动画的问题
 
&mdash;

**Comment by shuiping233** [comment]
> 只有核辐射影响建筑，另外你应该把维修关掉观察------------------ 原始邮件 ------------------ 发件人: "shuiping"<notifications@github.com> 发送时间: 2020年1月19日(星期天) 下午2:17 收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>; 抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Assign"<assign@noreply.github.com>; 主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#辐射浓度可以无限叠加 (#256) 从我测试的结果来看，辐射目前对建&#x7B51;没有伤害，但是会建&#x7B51;遇到辐射会播放建&#x7B51;被攻击的语音。 并没有出现多个辐射区域重&#x53E0;会出现多次播放死亡动画的问题 &mdash; You are receiving this because you were assigned. Reply to this email directly, view it on GitHub, or unsubscribe.

自动维修要怎么关掉？把钱消耗完么，还是炸的时候先用扳手先点建筑？

**Comment by Zero-Fanker** [comment]
看到在修的时候用扳手点一下建筑啊，目前杀伤值我自测过，典型例子是建造厂，2000血下正中可打到还剩200血，边修边受到辐射的情况会直接爆掉。你需要测一下所有建筑，辐射范围内范围外的所有建筑，主要看看是不是严格遵守区域，是否存在有区域内不掉血的，有在区域外却掉血的

**Comment by shuiping233** [comment]
> 看到在修的时候用扳手点一下建筑啊，目前杀伤值我自测过，典型例子是建造厂，2000血下正中可打到还剩200血，边修边受到辐射的情况会直接爆掉。你需要测一下所有建筑，辐射范围内范围外的所有建筑，主要看看是不是严格遵守区域，是否存在有区域内不掉血的，有在区域外却掉血的

好，刚刚看见核堡垒的核辐射对建筑没有伤害

**Comment by Zero-Fanker** [comment]
这有几个原因，
1. 这个辐射浓度本来就不高，持续时间短，杀伤小，被你忽略了，不存在无伤还会告警受到攻击的
2. 护甲比率乘以辐射伤害之后杀伤值实际为0
3. 被测建筑占地是1x1，受影响面积小，类同1

**Comment by shuiping233** [comment]
> 这有几个原因， 1. 这个辐射浓度本来就不高，持续时间短，杀伤小，被你忽略了，不存在无伤还会告警受到攻击的 2. 护甲比率乘以辐射伤害之后杀伤值实际为0 3. 被测建筑占地是1x1，受影响面积小，类同1

辐射工兵那个辐射对建筑没伤害也有警告语音呢，有点乱

**Comment by shuiping233** [comment]
> 这有几个原因， 1. 这个辐射浓度本来就不高，持续时间短，杀伤小，被你忽略了，不存在无伤还会告警受到攻击的 2. 护甲比率乘以辐射伤害之后杀伤值实际为0 3. 被测建筑占地是1x1，受影响面积小，类同1

我刚刚去拿核堡垒炸基地去了也没看见辐射伤害，我调慢点看

**Comment by Zero-Fanker** [comment]
你为啥不先测核弹和核电厂呢？你觉得哪个更容易观察出现象

**Comment by shuiping233** [comment]
![GIF56](https://user-images.githubusercontent.com/49360196/72676435-25caab80-3acc-11ea-8f47-7ce3a4031123.gif)

**Comment by shuiping233** [comment]
> 你为啥不先测核弹和核电厂呢？你觉得哪个更容易观察出现象

我测完了，核辐射和绿辐射应该没有问题了

**Comment by Zero-Fanker** [comment]
在实战中多试试，看一下稳定性，以及是否有辐射量残留bug，不同范围同种类型的辐射是否有问题
