### ISSUE TITLE
#Bug#敌对的辐射也可以对自己的acs充能

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#259]
【现象】：敌对的辐射也可以对自己的acs充能
【反馈人】：MadmanM
【发现版本号】：G1208B
【影响范围】：遭遇战
【产生原因】：未知

![QQ截图20191229084938](https://user-images.githubusercontent.com/49360196/71551930-79e1f300-2a2c-11ea-8612-1ba0f42aae36.png)

**Comment by Zero-Fanker** [comment]
这个问题现在还有?

**Comment by shuiping233** [comment]
不清楚，应该还在吧

**Comment by shuiping233** [comment]
H0506测试：现在这问题还在呢

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/82141111-4f22fa80-9866-11ea-9711-567ad90b77fb.png)
![image](https://user-images.githubusercontent.com/49360196/82141111-4f22fa80-9866-11ea-9711-567ad90b77fb.png)
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by Zero-Fanker** [comment]
原来是当初只改了磁暴，辐射兵漏改了，就一句标签的事情。

**Comment by Zero-Fanker** [comment]
H1024已调整，请验证。

**Comment by shuiping233** [comment]
![GIF20](https://user-images.githubusercontent.com/49360196/97099421-b1a8de00-16c3-11eb-842a-05d78edf8bb3.gif)
H1024测试结果：现在敌对辐射不能对acs充能了，与修改描述一致，辐射对acs没有伤害

**Comment by shuiping233** [comment]
在kk回复之前这个单子要归档吗

**Comment by shuiping233** [comment]
那我去归档了， @yuanbanlao 对结果没意见吗？

**Comment by yuanbanlao** [comment]
没有意见。
