### ISSUE TITLE
#Bug##群测#星际战舰不显示图像

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#26]

**Comment by shuiping233** [comment]
Zero Fanker
changed title to #Bug##群测#星际战舰不显示图像
assigned issue to   Zero Fanker
marked as major
edited description
修改叙述，调整严重程度。

2018-10-06
 Zero Fanker
changed status to resolved
已证实并找到原因，由于内部机制变动，打包时遗漏了素材文件，现在已经修正。

**Comment by Zero-Fanker** [comment]
已发布公测已修正。
