### ISSUE TITLE
#Bug#盟军ai并不会生产攻城机甲

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#261]
【现象】：盟军ai并不会生产攻城机甲
【反馈人】：那年风花雪月（公测群玩家）
【发现版本号】：G1208B
【影响范围】：遭遇战
【产生原因】：未知

**Comment by shuiping233** [comment]
G1208B的试验结果：即使在后期很久也不会出攻城机甲

**Comment by Zero-Fanker** [comment]
@shuiping233  H0118试一下。

**Comment by shuiping233** [comment]
> @shuiping233 H0118试一下。

H0118和H0315都已经测试过了，盟军ai已经会出攻城机甲

**Comment by shuiping233** [comment]
单子可以关掉么？

**Comment by Zero-Fanker** [comment]
> > @shuiping233 H0118试一下。
> 
> H0118和H0315都已经测试过了，盟军ai已经会出攻城机甲

@klighting444  小碗归档一下吧，按H0118归档
