### ISSUE TITLE
#建议反馈#法国气象塔的友方伤害

### ISSUE THREAD

**Issue by jukebox-www** [Zero-Fanker/RN_All_Issues#264]
【描述】法国气象塔对法国巨炮的友方伤害太大，而且又慢，RN的单位又脆，往往雷霆未落，敌方单位就被消灭，随后雷霆攻击地面，造成友方伤害
建议如果敌方单位被消灭就停止动作，或者降低友方伤害，对建筑护甲伤害
【原因】一履带车接近巨炮A，被附近的飞行兵消灭。随后，法国巨炮B的炮弹溅射到A,，造成伤害。最后，法国气象塔给了巨炮A致命雷霆一击（雷霆暴击还未开），直接毁灭了巨炮A
【期望解决时间】

**Comment by Zero-Fanker** [comment]
@yuanbanlao  kk看一下这个需不需要改进

**Comment by Zero-Fanker** [comment]
对友方影响减至20%

**Comment by yuanbanlao** [comment]
好

**Comment by shuiping233** [comment]
气象塔能玩出友伤我觉得是操作问题，是可以避免的，降友军伤害也行不降也能用

**Comment by Zero-Fanker** [comment]
H1226已调整，请验证。

**Comment by shuiping233** [comment]
H1226测试通过，目前气象塔**正中**友军巨炮伤害为150左右，**正中**友军光棱坦克伤害为50，**正中**友军间谍伤害为50
