### ISSUE TITLE
#Bug#尤里疾风轰炸机和幽灵轰炸机的炸弹对正在行驶并且与炸弹移动方向一致的单位无伤害

### ISSUE THREAD

**Issue by jukebox-www** [Zero-Fanker/RN_All_Issues#265]
【现象】：尤里疾风轰炸机和幽灵轰炸机的炸弹对正在行驶并且与炸弹移动方向一致的单位无伤害 ，只要是让炸弹出现了跟踪单位的情况，炸弹都必定无伤害
【发现版本号】：G1208B
【影响范围】：遭遇战、多人联机
【产生原因】：高度判断问题？动画时间

**Comment by Zero-Fanker** [comment]
@shuiping233 证实一下

**Comment by jukebox-www** [comment]
爬坡的韩国炮也是这样

**Comment by shuiping233** [comment]
> @shuiping233 证实一下

好

**Comment by shuiping233** [comment]
H0103测试结果：凡是移动的坦克，只要顺着炸弹移动，让炸弹出现跟踪，就会导致炸弹无伤害。疾风和幽灵(B2)均出现该问题

**Comment by shuiping233** [comment]
附图：
![GIF43](https://user-images.githubusercontent.com/49360196/71774463-174ba280-2faa-11ea-9e10-3d0323155c37.gif)
![GIF44](https://user-images.githubusercontent.com/49360196/71774464-174ba280-2faa-11ea-9e80-6509336b14f0.gif)

**Comment by Zero-Fanker** [comment]
@Crossfield-ClassDestroyer  驱逐加大弹头PercentAtMax看看情况有无变化

**Comment by Zero-Fanker** [comment]
由于近期调整过轰炸机数据，需要重新验证

**Comment by NightSkyTS** [comment]
0.99.913a7此BUG依旧存在
![蜘蛛](https://user-images.githubusercontent.com/78950858/163578539-bd8dda76-097b-4663-8d38-88118f363354.gif)

**Comment by Zero-Fanker** [comment]
> H0103测试结果：移动中的坦克，只要顺着炸弹移动，让炸弹出现跟踪，就会导致炸弹无伤害。疾风和幽灵(B2)均出现该问题。但是有特例：先军要塞等移动速度较为缓慢的单位不会出现该问题，炸弹能正常造成伤害

我定位到原因了，目前是和会产生降落伞的炸弹有关系，我针对这种情况做了修复。其它的情况，需要有确凿证据再继续研究。

**Comment by Zero-Fanker** [comment]
@shuiping233 @NightSkyTS @Crossfield-ClassDestroyer 0.99.916a3 已解决

**Comment by shuiping233** [comment]
> @shuiping233 @NightSkyTS @Crossfield-ClassDestroyer 0.99.916a3 已解决

0.99.916a3测试通过
![GIF119](https://github.com/user-attachments/assets/a300c43b-39c5-4d55-8597-e57976cc4cd4)
![GIF118](https://github.com/user-attachments/assets/0778081c-eb30-4218-8c9c-d46a9485ea92)
