### ISSUE TITLE
#Bug#导弹类武器会受辐射影响在刚发射时爆炸

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#266]
【现象】：导弹类武器会受辐射影响在刚发射时爆炸
【反馈人】：忘了
【发现版本号】：G1208B
【影响范围】：任务，遭遇战
【产生原因】：辐射对导弹有伤害

**Comment by Zero-Fanker** [comment]
驱逐先证实一下

**Comment by Crossfield-ClassDestroyer** [comment]
![$VY6FTXFJLAMZ3E_FC)GY3](https://user-images.githubusercontent.com/54458394/78734583-311ace00-797b-11ea-81d2-de97cd4ff129.jpg)
![FMEFF{8D0J`MMF9T8DL0DJP](https://user-images.githubusercontent.com/54458394/78734588-337d2800-797b-11ea-906a-f264b6167811.gif)

**Comment by Zero-Fanker** [comment]
@shuiping233  H0409已修复，请验证

**Comment by shuiping233** [comment]
H0409测试结果：目前除了雷鸣潜艇的导弹仍然受到辐射的影响，其余导弹均可免疫辐射

**Comment by shuiping233** [comment]
@Crossfield-ClassDestroyer

**Comment by shuiping233** [comment]
H0505测试结果：雷鸣潜艇导弹已经不受辐射影响
