### ISSUE TITLE
#建议反馈#装甲掷弹兵与战斗要塞搭配

### ISSUE THREAD

**Issue by jukebox-www** [Zero-Fanker/RN_All_Issues#268]
【描述】所有盟军阵营都有装甲掷弹兵，但部分盟军阵营没有战斗要塞，希望对应
【原因】个人使用装甲掷弹兵很废：可能打不中，可能自伤，受地形限制太严重，只有配合战斗要塞才能有一定的作用（否则拥有原版和尤里复仇的磁能坦克的地位，不会出）。另外，邪恶联盟下苏、尤能建造战斗要塞，盟军部分阵营反而不能出。
...虽然装甲掷弹兵进战斗要塞后仍然需要大量操作，易被轰炸，但是具有一定价值

战斗要塞在原版对战具有重要的地位。曾经没有人会用它，直到玩家学会了在敌人坦克进攻时向后......现在盟军高端对局常用，类似幻影坦克的频率。
【期望解决时间】小建议

**Comment by jukebox-www** [comment]
补充，德国的瓦维修平台替换了战斗要塞，所以德国没有战斗要塞

**Comment by shuiping233** [comment]
> ![a](https://user-images.githubusercontent.com/59478375/71785746-3d228700-303e-11ea-9f6b-a84713da1a3c.PNG)
> ![屏幕截图(53)](https://user-images.githubusercontent.com/59478375/71785771-92f72f00-303e-11ea-8a7f-1b382a34c025.png)
> 
> 补充，德国的瓦尔哈拉维修平台替换了战斗要塞，所以德国没有战斗要塞

只是德国而已，并且维修平台替换要塞带来了作用远比手雷兵要塞强多了，在德国t3的前提下手雷要塞的使用价值并不大。从ai角度来讲，ai能额外生产手雷要塞并不合理

**Comment by shuiping233** [comment]
手雷兵并不是一定要依靠要塞才能用

**Comment by Zero-Fanker** [comment]
?------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2020年4月9日(星期四) 上午8:34
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [Zero-Fanker/RN_All_Issues] #建议反馈#装甲掷弹兵与战斗要塞搭配 (#268)




 
Closed #268.
 
&mdash;

**Comment by shuiping233** [comment]
没必要给德国恢复战斗要塞吧
