### ISSUE TITLE
#Bug##群测#非盟军AI的兵营会出盟军步兵（GI和GGI）

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#27]
Zero Fanker created an issue 2018-10-03
【描述】
苏军兵营会出盟军小队(目前看到的是GGI，调查一下是否是AI条目有故障。
【影响范围】
所有模式下的AI

**Comment by shuiping233** [comment]
Zero Fanker REPORTER
changed title to #Bug##群测#非盟军AI的兵营会出盟军步兵（GI和GGI）
assigned issue to   Zero Fanker
marked as major
edited description
2018-10-08
 Zero Fanker REPORTER
changed status to open
已经在着手研究AI条目，目前发现可疑的特遣小队，需要进一步排查和测试。

2018-10-08
 Zero Fanker REPORTER
changed status to resolved
已经锁定问题条目，进行了针对性修复。需要深入测试。

2018-10-14
Log in to comment
