### ISSUE TITLE
#Bug#基佬夫的炸弹和手雷兵的手雷可以对空军造成影响

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#270]
【现象】：基佬夫的炸弹和手雷兵的手雷可以对空军造成影响，除了战机和轰炸机。如图所示：![GIF47（2）](https://user-images.githubusercontent.com/49360196/72199763-5337a980-347b-11ea-96b8-8faf5348c456.gif)
![GIF48](https://user-images.githubusercontent.com/49360196/72199764-5337a980-347b-11ea-9dfc-f67d5cfd87d7.gif)
![GIF49](https://user-images.githubusercontent.com/49360196/72199765-5337a980-347b-11ea-932f-e5210589d2a4.gif)
![GIF50](https://user-images.githubusercontent.com/49360196/72199760-3b602580-347b-11ea-8b15-e5e1c6b7d36c.gif)

【反馈人】：一群很闲的公测玩家
【发现版本号】：G1208B
【影响范围】：单位平衡性

【产生原因】：如图
![H060O2BIDOI(Q{G9H71UI~4](https://user-images.githubusercontent.com/49360196/72199717-b6750c00-347a-11ea-8004-6e3ba3ed7829.png)

**Comment by shuiping233** [comment]
![GIF47（2）](https://user-images.githubusercontent.com/49360196/72199763-5337a980-347b-11ea-96b8-8faf5348c456.gif)
![GIF48](https://user-images.githubusercontent.com/49360196/72199764-5337a980-347b-11ea-9dfc-f67d5cfd87d7.gif)
![GIF49](https://user-images.githubusercontent.com/49360196/72199765-5337a980-347b-11ea-932f-e5210589d2a4.gif)
![GIF50](https://user-images.githubusercontent.com/49360196/72199760-3b602580-347b-11ea-8b15-e5e1c6b7d36c.gif)

**Comment by Zero-Fanker** [comment]
驱逐修复一下。基佬夫的对空范围适当大一些。

**Comment by shuiping233** [comment]
@yuanbanlao

**Comment by yuanbanlao** [comment]
草，太草了

**Comment by Zero-Fanker** [comment]
> 草，太草了

你好，我确实把全局数值改到能影响空中了，来打我啊~

**Comment by shuiping233** [comment]
这个基佬夫堆一起已经可以“先进反自己”了，真的不打算取消吗？

**Comment by Zero-Fanker** [comment]
@shuiping233 @yuanbanlao @RN-Hydra H0130已修正，请验证。

**Comment by RN-Hydra** [comment]
H0130已验证




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zero Fanker"<notifications@github.com&gt;; 
发送时间: 2020年1月30日(星期四) 晚上7:19
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;; 
抄送: "Estrus"<1575629191@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#基佬夫的炸弹和手雷兵的手雷可以对空军造成影响 (#270)




@shuiping233 @yuanbanlao @RN-Hydra H0130已修正，请验证。
