### ISSUE TITLE
＃建议反馈＃希望修改一下辐射工兵部署机制

### ISSUE THREAD

**Issue by 1791878927** [Zero-Fanker/RN_All_Issues#272]
【描述】把辐射工兵改成一按部署指令就可以立即部署，但辐射浓度不能每次部署后都刷新
【原因】辐射工兵在很多时候总是狂按部署却长时间蹲不下，使用体验非常差
【期望解决时间】下一版本公测

**Comment by Zero-Fanker** [comment]
@yuanbanlao kk评价一下

**Comment by yuanbanlao** [comment]
搁置，留待讨论？

**Comment by shuiping233** [comment]
辐射有cd没问题，我认为部署之后加一个类似基佬夫铁幕那种倒计时图示会好很多，不过蹲完之后不能立马蹲下确实会感觉挺难受的

**Comment by 1791878927** [comment]
站起来后不能马上再蹲下问题不大，主要是如果辐射工兵用主炮攻击后就会出现怎么按部署都蹲不下的情况，这一点非常难受

**Comment by Zero-Fanker** [comment]
> 站起来后不能马上再蹲下问题不大，主要是如果辐射工兵用主炮攻击后就会出现怎么按部署都蹲不下的情况，这一点非常难受

@yuanbanlao  @Crossfield-ClassDestroyer  验证一下

**Comment by shuiping233** [comment]
确实存在攻击后站立状态无法部署的情况，必须移动辐射工兵才能部署。
（另发现部署后鼠标指针放在建筑上显示可攻击指针图标，不过辐射工兵并不会去攻击建筑，影响微乎其微 ）

**Comment by Zero-Fanker** [comment]
> 确实存在攻击后站立状态无法部署的情况，必须移动辐射工兵才能部署。
> （另发现部署后鼠标指针放在建筑上显示可攻击指针图标，不过辐射工兵并不会去攻击建筑，影响微乎其微 ）

鼠标动画问题是原版残留，暂时不管，推测修改会对原机制造成较大影响

**Comment by Zero-Fanker** [comment]
0.99.912a 已调整 @Renko-ji @shuiping233 @Super-StarX

**Comment by shuiping233** [comment]
> 0.99.912a 已调整 @Renko-ji @shuiping233 @Super-StarX

需要调整的详细内容

**Comment by shuiping233** [comment]
0.99.912a测试通过，测试员：suli
现在辐射部署恢复原版手感
