### ISSUE TITLE
#Bug#核弹超武对建造厂伤害异常高

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#274]
【现象】：高防御下核弹非中心命中建造厂仍然可以秒杀建筑
【反馈人】：
【发现版本号】：G1208B 
【影响范围】：所有可使用核弹的场景
【产生原因】：护甲数据错误

**Comment by Zero-Fanker** [comment]
对建造厂的护甲做了比例特调。

**Comment by Zero-Fanker** [comment]
@shuiping233  H0118已修改，请验证。

**Comment by shuiping233** [comment]
![GIF57](https://user-images.githubusercontent.com/49360196/72706412-f0d85a80-3b98-11ea-9445-ef21d3be5d8b.gif)
H0118经过测试，该问题已经解决
