### ISSUE TITLE
#Bug#遭遇战韩国打电脑古巴用灰熊打厕所直接崩溃

### ISSUE THREAD

**Issue by 163lxyz** [Zero-Fanker/RN_All_Issues#277]
【现象】：日常打遭遇战我用韩国打电脑古巴，然后开局我让一个灰熊坦克四处瞎逛，最后找到了一个
厕所，然后我手残把厕所打爆了，然后突然就崩了，对了地图是万福玛利亚，模式为淘金热
【影响范围】：遭遇战发现的
【产生原因】：不明
【反馈人】：【QQ群名称】日牛的废物
【发现版本号】：H.G0615p2

**Comment by 163lxyz** [comment]
话说我用的好像不是最新版本

**Comment by Zero-Fanker** [comment]
那你说个毛线?

**Comment by Zero-Fanker** [comment]
用最新公测版重试
