### ISSUE TITLE
#Bug#黄金荣耀战士冲锋形态没有素材

### ISSUE THREAD

**Issue by WZ-113** [Zero-Fanker/RN_All_Issues#279]
【现象】：如题
【反馈人】：WZ-113
【发现版本号】：0.99.H0118B
【影响范围】：黄金荣耀战士
【产生原因】：怕不是ZF忘了

**Comment by Zero-Fanker** [comment]
@Crossfield-ClassDestroyer  驱逐测试证实一下是否有问题

**Comment by Zero-Fanker** [comment]
113在G0209复测一下

**Comment by Zero-Fanker** [comment]
@WZ-113  @RN-Hydra  @yuanbanlao H0331已经修复，请验证。

**Comment by yuanbanlao** [comment]
H0331已验证，黄金荣耀战士现在拥有专属冲锋状态。 @klighting444  请归档
