### ISSUE TITLE
#Bug#苏系防空步兵进入圣骑士机甲和ifv后，对应武器无法对空

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#281]
【现象】：苏系防空步兵进入圣骑士机甲和ifv后，对应武器无法对空
【反馈人】：公测玩家（qq：1499762839）
【发现版本号】：G1208B
【影响范围】：单位缺陷，影响操作手感
【产生原因】：未知

**Comment by shuiping233** [comment]
另外，煤球ifv和煤球圣骑士的武器，攻击地面是可以的，强制攻击地面并且上方有飞行器存在（除基洛夫和降落于机场的飞行器外），攻击在地上的弹头依然能对上方的空军造成伤害

**Comment by Zero-Fanker** [comment]
@yuanbanlao @Super-StarX  原版YR IFV+煤球对空情况是怎样的？

**Comment by shuiping233** [comment]
听某玩家说原版和yr的ifv进煤球兵是用机枪，不能对空，当然我可以开原版试试

**Comment by Zero-Fanker** [comment]
@yuanbanlao  kk觉得这个需要改吗？

**Comment by yuanbanlao** [comment]
yr是加强煤球，原版是突突枪。我觉得既然打地板能对空军造成伤害，不如直接允许对空。

**Comment by Zero-Fanker** [comment]
但是原版就不能对空的，那我就允许对空了，但弹道看起来大概会怪一点。       ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;yuanbanlao&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月31日(星期六) 凌晨0:07
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;Zero Fanker&quot;<zcyfksn@vip.qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug#苏系防空步兵进入圣骑士机甲和ifv后，对应武器无法对空 (#281)

**Comment by Zero-Fanker** [comment]
H1031已修正，请验证。

**Comment by shuiping233** [comment]
![GIF31](https://user-images.githubusercontent.com/49360196/98437215-6ce96200-211b-11eb-9036-378ee3044532.gif)

**Comment by shuiping233** [comment]
H1031B测试结果：煤球ifv和煤球圣骑士都有两个问题，无法命中快速单位，例如疾风轰炸机，雷电轰炸机；车载煤球武器有大量的活力浪费，加上本来伤害对重甲就不高，导致其攻击重型飞行器效率很低，5煤球ifv和5煤球兵同时攻击一个基佬夫，煤球兵打下来基佬夫的时候车载煤球武器还打不到基佬夫4分之一血量
![Snipaste_2020-11-07_18-06-29](https://user-images.githubusercontent.com/49360196/98438332-71fedf00-2124-11eb-930b-a6f416678dd5.png)

**Comment by Zero-Fanker** [comment]
> H1031B测试结果：煤球ifv和煤球圣骑士都有两个问题，无法命中快速单位，例如疾风轰炸机，雷电轰炸机；车载煤球武器有大量的活力浪费，加上本来伤害对重甲就不高，导致其攻击重型飞行器效率很低，5煤球ifv和5煤球兵同时攻击一个基佬夫，煤球兵打下来基佬夫的时候车载煤球武器还打不到基佬夫4分之一血量
> ![Snipaste_2020-11-07_18-06-29](https://user-images.githubusercontent.com/49360196/98438332-71fedf00-2124-11eb-930b-a6f416678dd5.png)

kk觉得这个数据需要加强吗

**Comment by yuanbanlao** [comment]
正常人不会把这种东西扔到要塞和圣骑里。
原版就不存在的操作就别整那么多花活了。

**Comment by Zero-Fanker** [comment]
> 正常人不会把这种东西扔到要塞和圣骑里。
> 原版就不存在的操作就别整那么多花活了。

@shuiping233  收工归档

**Comment by shuiping233** [comment]
收到
