### ISSUE TITLE
#Bug#盟军第三关地图中部分摆件（集装箱堆，码头吊头）无敌

### ISSUE THREAD

**Issue by WZ-113** [Zero-Fanker/RN_All_Issues#282]
【现象】：盟军第三关地图中有几个摆件既不能被选中攻击也不会受伤
【反馈人】：WZ-113
【发现版本号】：H.H0209
【影响范围】：导致游戏过于出戏
【产生原因】：八成zf的锅

**Comment by shuiping233** [comment]
这些集装箱等装饰物无敌应该属于设定，不挡路就没问题，攻城拔寨的浮岛要塞地图也有大量无敌装饰物

**Comment by Zero-Fanker** [comment]
驱逐准备解决一下。 @Crossfield-ClassDestroyer

**Comment by yuanbanlao** [comment]
得，挂给我了。
请求了解详细数据。

**Comment by Zero-Fanker** [comment]
@WZ-113  @shuiping233  H.H1015已调整，请验证。

**Comment by shuiping233** [comment]
@yuanbanlao 能指明哪些箱子或者码头吗，还是全部都要？

**Comment by yuanbanlao** [comment]
已经更改完毕。

**Comment by shuiping233** [comment]
那我归档了

**Comment by Zero-Fanker** [comment]
> 那我归档了

你测下盟3左侧的那些集装箱什么的，盟1也有出场。

**Comment by shuiping233** [comment]
我测了一下，我没问题了
