### ISSUE TITLE
#Bug#毒蝎坦克无法进入维修平台进行维修

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#283]
【现象】：毒蝎无法进入维修平台进行维修，会卡在维修厂外边不进去
【反馈人】：贾曼卡尔
【发现版本号】：G1028B
【影响范围】：单位操作手感
【产生原因】：未知

**Comment by Zero-Fanker** [comment]
这个是为啥设置成无效的

**Comment by shuiping233** [comment]
咦 我什么时候干的？
