### ISSUE TITLE
#Bug#狙击手在恐怖机器人攻击时突然隐形会导致机器人消失

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#284]
【现象】：狙击手在恐怖机器人攻击时突然隐形会导致机器人消失，狙击手并不会被杀死，狗也会产生此bug
【反馈人】：公测玩家
【发现版本号】：G1208B
【影响范围】：单位操作手感
【产生原因】：未知

![b86f7d1ad3e2ad](https://user-images.githubusercontent.com/49360196/74534181-255bee00-4f6e-11ea-93fb-16515e5f2051.gif)

**Comment by shuiping233** [comment]
H0501的测试结果：多次测试后，仍然无法复现，确认问题已经修复；即使狙击手和其他步兵混在一起也并无产生奇怪的视觉或者其他问题

**Comment by Zero-Fanker** [comment]
标注一下是开发版，后面推送到内测没问题才算解决。------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2020年5月2日(星期六) 晚上6:54
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Assign"<assign@noreply.github.com>;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#狙击手在恐怖机器人攻击时突然隐形会导致机器人消失 (#284)




 
H0501的测试结果：多次测试后，仍然无法复现，确认问题已经修复；即使狙击手和其他步兵混在一起也并无产生奇怪的视觉或者其他问题
 
&mdash;

**Comment by shuiping233** [comment]
好的


ly, view it on GitHub, or unsubscribe.

**Comment by Zero-Fanker** [comment]
H0504已修正，请验证 @shuiping233  @yuanbanlao

**Comment by shuiping233** [comment]
H0505测试结果：多次反复测试后不能复现该问题，该问题已经解决

**Comment by shuiping233** [comment]
H0505测试发现：zz在起跳后若摧毁目标会导致蜘蛛瞬间回到原来的起跳位置

**Comment by shuiping233** [comment]
![GIF82](https://user-images.githubusercontent.com/49360196/81145730-709ffe80-8fa9-11ea-9cb5-03a63a2abc05.gif)
