### ISSUE TITLE
#Bug#尤里的复制中心无法设置集结点

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#286]
【现象】：尤里的复制中心无法设置集结点
【反馈人】：公测群玩家
【发现版本号】：H0118P
【影响范围】：操作体验
【产生原因】：未知

**Comment by Zero-Fanker** [comment]
H0409已修正，请验证 @shuiping233

**Comment by shuiping233** [comment]
H0409测试结果：复制中心现在可以设置路径点了
