### ISSUE TITLE
#Bug#ai的战机丢下炸弹后会在附近转圈

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#287]
【现象】：ai的战机丢下炸弹后会在附近转圈，由于ai判定机场有空的机位，会生产出新的战机，导致在空中的飞机一直盘旋而不返回机场
【反馈人】：shuiping
【发现版本号】：H0118P
【影响范围】：ai
【产生原因】：ai在战机起飞后认为机场已空，所以建造了新的战机，导致已出发战机无法返航

**Comment by UraniumW** [comment]
个人观察得知，出现该问题原因是ai在战机起飞后认为机场已空，所以建造了新的战机，导致已出发战机无法返航

**Comment by Zero-Fanker** [comment]
按照提交格式修正一下叙述------------------ 原始邮件 ------------------
发件人: "UraniumW"<notifications@github.com>
发送时间: 2020年3月4日(星期三) 下午5:41
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#ai的战机丢下炸弹后会在附近转圈 (#287)



个人观察得知，出现该问题原因是ai在战机起飞后认为机场已空，所以建造了新的战机，导致已出发战机无法返航
 
&mdash;

**Comment by Zero-Fanker** [comment]
shuiping重新确认一下

**Comment by shuiping233** [comment]
H0506测试结果：目前版本已经不会出现该问题

**Comment by Zero-Fanker** [comment]
由于未再收到新的报告，则以最后一条记录为准。
