### ISSUE TITLE
#建议反馈#增加雷电轰炸机的装填时间

### ISSUE THREAD

**Issue by K2Cr2O7-AK74** [Zero-Fanker/RN_All_Issues#288]
【描述】雷电轰炸机因为本身速度以及威力还有出勤率导致1500一个的战机单位效率过高，对战中因为到场早以及速度快火力猛还附带减速的特性导致雷电难以拦截也难以对付，加上雷电的出勤率过高导致地面部队几乎在雷电的面前毫无招架之力。
作为限制战机类单位最合理的方法就是减少他的出勤率，即使雷电难以拦截也无法在全期起到压制性打击的效果
【原因】以之前我和yblao的对战视频为例
https://www.bilibili.com/video/av80983996?p=2
这一期视频中，盟军几乎不出动任何地面部队，仅是两个雷电轰炸机一直保持出勤率，就已经让苏没有一个良好的环境和盟军交火了，最终装甲血量严重不足的苏军无法抵挡血量健康的盟军，从而打出gg
https://www.bilibili.com/video/av80983996?p=4
也是开局在坦克大幅度劣势的情况下仅靠一个雷电便能打出翻盘
https://www.bilibili.com/video/av80983996?p=7
同样是2个雷电在保持出勤率的情况下苏军无法保持优秀血量的装甲进行对战
同时两个雷电能秒大多数建筑的情况下他也能同时压制你的部队和你的科技建筑

所以希望可以减少雷电轰炸机的出勤率，可以既让雷电轰炸机继续发挥他的作用也可以让对付雷电的选手有喘息机会，个人建议至少减少一半的雷电轰炸机出勤效率
【期望解决时间】尽快
版本号：G1208B

**Comment by K2Cr2O7-AK74** [comment]
> 【描述】雷电轰炸机因为本身速度以及威力还有出勤率导致1500一个的战机单位效率过高，对战中因为到场早以及速度快火力猛还附带减速的特性导致雷电难以拦截也难以对付，加上雷电的出勤率过高导致地面部队几乎在雷电的面前毫无招架之力。
> 作为限制战机类单位最合理的方法就是减少他的出勤率，即使雷电难以拦截也无法在全期起到压制性打击的效果
> 【原因】以之前我和yblao的对战视频为例
> https://www.bilibili.com/video/av80983996?p=2
> 这一期视频中，盟军几乎不出动任何地面部队，仅是两个雷电轰炸机一直保持出勤率，就已经让苏没有一个良好的环境和盟军交火了，最终装甲血量严重不足的苏军无法抵挡血量健康的盟军，从而打出gg
> https://www.bilibili.com/video/av80983996?p=4
> 也是开局在坦克大幅度劣势的情况下仅靠一个雷电便能打出翻盘
> https://www.bilibili.com/video/av80983996?p=7
> 同样是2个雷电在保持出勤率的情况下苏军无法保持优秀血量的装甲进行对战
> 同时两个雷电能秒大多数建筑的情况下他也能同时压制你的部队和你的科技建筑
> 
> 所以希望可以减少雷电轰炸机的出勤率，可以既让雷电轰炸机继续发挥他的作用也可以让对付雷电的选手有喘息机会，个人建议至少减少一半的雷电轰炸机出勤效率

**Comment by K2Cr2O7-AK74** [comment]
> > 【描述】雷电轰炸机因为本身速度以及威力还有出勤率导致1500一个的战机单位效率过高，对战中因为到场早以及速度快火力猛还附带减速的特性导致雷电难以拦截也难以对付，加上雷电的出勤率过高导致地面部队几乎在雷电的面前毫无招架之力。
> > 作为限制战机类单位最合理的方法就是减少他的出勤率，即使雷电难以拦截也无法在全期起到压制性打击的效果
> > 【原因】以之前我和yblao的对战视频为例
> > https://www.bilibili.com/video/av80983996?p=2
> > 这一期视频中，盟军几乎不出动任何地面部队，仅是两个雷电轰炸机一直保持出勤率，就已经让苏没有一个良好的环境和盟军交火了，最终装甲血量严重不足的苏军无法抵挡血量健康的盟军，从而打出gg
> > https://www.bilibili.com/video/av80983996?p=4
> > 也是开局在坦克大幅度劣势的情况下仅靠一个雷电便能打出翻盘
> > https://www.bilibili.com/video/av80983996?p=7
> > 同样是2个雷电在保持出勤率的情况下苏军无法保持优秀血量的装甲进行对战
> > 同时两个雷电能秒大多数建筑的情况下他也能同时压制你的部队和你的科技建筑
> > 所以希望可以减少雷电轰炸机的出勤率，可以既让雷电轰炸机继续发挥他的作用也可以让对付雷电的选手有喘息机会，个人建议至少减少一半的雷电轰炸机出勤效率
【期望解决时间】尽快
版本号：G1208B

**Comment by K2Cr2O7-AK74** [comment]
> 【描述】雷电轰炸机因为本身速度以及威力还有出勤率导致1500一个的战机单位效率过高，对战中因为到场早以及速度快火力猛还附带减速的特性导致雷电难以拦截也难以对付，加上雷电的出勤率过高导致地面部队几乎在雷电的面前毫无招架之力。
> 作为限制战机类单位最合理的方法就是减少他的出勤率，即使雷电难以拦截也无法在全期起到压制性打击的效果
> 【原因】以之前我和yblao的对战视频为例
> https://www.bilibili.com/video/av80983996?p=2
> 这一期视频中，盟军几乎不出动任何地面部队，仅是两个雷电轰炸机一直保持出勤率，就已经让苏没有一个良好的环境和盟军交火了，最终装甲血量严重不足的苏军无法抵挡血量健康的盟军，从而打出gg
> https://www.bilibili.com/video/av80983996?p=4
> 也是开局在坦克大幅度劣势的情况下仅靠一个雷电便能打出翻盘
> https://www.bilibili.com/video/av80983996?p=7
> 同样是2个雷电在保持出勤率的情况下苏军无法保持优秀血量的装甲进行对战
> 同时两个雷电能秒大多数建筑的情况下他也能同时压制你的部队和你的科技建筑
> 
> 所以希望可以减少雷电轰炸机的出勤率，可以既让雷电轰炸机继续发挥他的作用也可以让对付雷电的选手有喘息机会，个人建议至少减少一半的雷电轰炸机出勤效率
【期望解决时间】尽快
版本号：G1208B

**Comment by Zero-Fanker** [comment]
H0229已修改，请验证。@yuanbanlao

**Comment by yuanbanlao** [comment]
H0310已验证，数值已经过修改。请归档。 @klighting444
