### ISSUE TITLE
#建议反馈#地狱自爆机的调整

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#290]
【描述】
![QQ截图20200224164123](https://user-images.githubusercontent.com/49360196/75138282-c98b2500-5724-11ea-87f4-3c789c013b6d.png)
![QQ截图20200224164137](https://user-images.githubusercontent.com/49360196/75138287-cdb74280-5724-11ea-94d0-f15d721df05c.png)

【原因】太弱，实力与科技水平不符

【期望解决时间】尽快

**Comment by Zero-Fanker** [comment]
H1127已调整，请验证

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/100497970-cf250800-3199-11eb-9bb8-5263603f6bbb.png)
根据此描述进行测试

**Comment by shuiping233** [comment]
H1127测试通过，地狱自爆机现在可以秒杀t3主战了
