### ISSUE TITLE
#Bug#古巴自爆卡车可以对空

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#292]
【现象】：古巴自爆卡车可以对空
【发现版本号】：H0118P
【影响范围】：单位手感
【产生原因】：kk认为太sb

![Screenshot_20200305-143117](https://user-images.githubusercontent.com/49360196/75962793-5d1bdd00-5eff-11ea-993a-8d4cf29460b8.jpg)

**Comment by shuiping233** [comment]
![Uploading Screenshot_20200305-143117.jpg…]()

**Comment by shuiping233** [comment]
![Uploading Screenshot_20200305-143117.jpg…]()
![Uploading Screenshot_20200305-143117.jpg…]()
![Uploading Screenshot_20200305-122248.jpg…]()

**Comment by shuiping233** [comment]
![Uploading Screenshot_20200305-1431

![Uploading Screenshot_20200305-143117.jpg…]()

17.jpg…]()
![Uploading Screenshot_20200305-122248.jpg…]()

**Comment by shuiping233** [comment]
![Screenshot_20200305-143117](https://user-images.githubusercontent.com/49360196/75962793-5d1bdd00-5eff-11ea-993a-8d4cf29460b8.jpg)

**Comment by Zero-Fanker** [comment]
@yuanbanlao 请给出理由

**Comment by shuiping233** [comment]
@yuanbanlao

**Comment by yuanbanlao** [comment]
这个修改还需要特别的理由吗，硬要说那就是嫌麻烦，可能会有人问为什么可以对空。

**Comment by Zero-Fanker** [comment]
> 这个修改还需要特别的理由吗，硬要说那就是嫌麻烦，可能会有人问为什么可以对空。

能影响空中是一种设定啊，原版在桥上炸也会影响空中

**Comment by yuanbanlao** [comment]
原版不在桥上炸不会影响空中啊，我更倾向于这是一个bug而不是一个设定。

**Comment by Zero-Fanker** [comment]
> 原版不在桥上炸不会影响空中啊，我更倾向于这是一个bug而不是一个设定。

AOE有限可影响空中，我认为没啥问题啊，适当缩小下范围就是了，核武系列和重轰都是这样处理的

**Comment by shuiping233** [comment]
能关闭单子么，kk好久没提这个了

**Comment by Zero-Fanker** [comment]
不急，现在没有清理旧单子的计划，我感觉大家积极性也没那么高，挂着就是了------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月14日(星期三) 晚上8:46
***@***.***&gt;;
抄送:&nbsp;&quot;Zero ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug#古巴自爆卡车可以对空 (#292)

**Comment by shuiping233** [comment]
那我说一下这个自爆卡车和核爆卡车对空的手感，基本上对重甲飞行器影响很小，就算在基洛夫，算计者这类重甲单位底下爆炸也没多少伤害，堆他200个自爆卡车都未必炸的下一个基佬夫；对轻甲和步兵飞行单位倒是有奇效

**Comment by Zero-Fanker** [comment]
> 那我说一下这个自爆卡车和核爆卡车对空的手感，基本上对重甲飞行器影响很小，就算在基洛夫，算计者这类重甲单位底下爆炸也没多少伤害，堆他200个自爆卡车都未必炸的下一个基佬夫；对轻甲和步兵飞行单位倒是有奇效

那如果是这样的话不就很合理了吗，最多就是适当下调对部分轻甲飞行单位的影响

**Comment by shuiping233** [comment]
这个问问kk，反正PVP苏军不差反蚊子的武器，这个最多算性价比超高的蚊香



---原始邮件---
发件人: "Zero ***@***.***&gt;
发送时间: 2021年12月18日(周六) 下午3:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#古巴自爆卡车可以对空 (#292)




  
那我说一下这个自爆卡车和核爆卡车对空的手感，基本上对重甲飞行器影响很小，就算在基洛夫，算计者这类重甲单位底下爆炸也没多少伤害，堆他200个自爆卡车都未必炸的下一个基佬夫；对轻甲和步兵飞行单位倒是有奇效
  
那如果是这样的话不就很合理了吗，最多就是适当下调对部分轻甲飞行单位的影响
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shuiping233** [comment]
我现在的意见是没问题，砍不砍对轻甲伤害看74和kk怎么说



---原始邮件---
发件人: "Zero ***@***.***&gt;
发送时间: 2021年12月18日(周六) 下午3:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#古巴自爆卡车可以对空 (#292)




  
那我说一下这个自爆卡车和核爆卡车对空的手感，基本上对重甲飞行器影响很小，就算在基洛夫，算计者这类重甲单位底下爆炸也没多少伤害，堆他200个自爆卡车都未必炸的下一个基佬夫；对轻甲和步兵飞行单位倒是有奇效
  
那如果是这样的话不就很合理了吗，最多就是适当下调对部分轻甲飞行单位的影响
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Zero-Fanker** [comment]
搁置这么久，而且平衡调整也没有再提起，故关闭
