### ISSUE TITLE
#Bug#旧尤里第一关飞碟控制核电站崩溃

### ISSUE THREAD

**Issue by wang23379** [Zero-Fanker/RN_All_Issues#293]
【现象】：旧尤里战役第一关飞碟控制核电站崩溃
【发现版本号】：H0118P
【影响范围】：战役任务
【产生原因】：未知

[新建文件夹.zip](https://github.com/Zero-Fanker/RN_All_Issues/files/4341677/default.zip)

**Comment by Zero-Fanker** [comment]
请提供完整的crashdump并发至开发者邮箱

**Comment by shuiping233** [comment]
![2020年03月27日22点29分50秒](https://user-images.githubusercontent.com/49360196/77811458-6438a400-70d5-11ea-8b35-9dbb34b2b067.png)
