### ISSUE TITLE
#Bug#巨炮不会产生威胁被单位主动攻击

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#298]
【现象】：巨炮不会想其他防御塔那样会被单位主动攻击
【反馈人】：shuiping
【发现版本号】：原版问题
【影响范围】：任务，遭遇战，多人联机
【产生原因】：缺少威胁值，wwsb

**Comment by shuiping233** [comment]
从输出方面来看，巨炮比光棱塔强，巨炮威胁值需要比光棱塔大，但是不超过t4防御塔的威胁值

**Comment by Zero-Fanker** [comment]
@yuanbanlao @SuperStar-X 找他们俩评判一下------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2020年3月28日(星期六) 凌晨0:17
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#巨炮不会被单位主动攻击 (#298)




 
从输出方面来看，巨炮比光棱&#x5854;强，巨炮&#x5A01;胁值需要比光棱&#x5854;大，但是不超过t4防御&#x5854;的&#x5A01;胁值
 
&mdash;

**Comment by Zero-Fanker** [comment]
这为什么算问题?原版不是这样的?------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2020年3月28日(星期六) 凌晨0:12
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Zero-Fanker/RN_All_Issues] #Bug#巨炮不会被单位主动攻击 (#298)




 
【现象】：巨炮不会想其他防御&#x5854;那样会被单位主动攻击
 【反馈人】：shuiping
 【发现版本号】：原版问题
 【影响范围】：任务，遭遇战，多人联机
 【产生原因】：缺少&#x5A01;胁值，wwsb
 
&mdash;

**Comment by shuiping233** [comment]
原版就是这样，所以才提出



---原始邮件---
发件人: "Zero Fanker"<notifications@github.com&gt;
发送时间: 2020年3月28日(星期六) 凌晨0:25
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"shuiping"<1944680304@qq.com&gt;;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#巨炮不会被单位主动攻击 (#298)




 这为什么算问题?原版不是这样的?------------------ 原始邮件 ------------------ 
 发件人: "shuiping"<notifications@github.com&gt; 
 发送时间: 2020年3月28日(星期六) 凌晨0:12 
 收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;; 
 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
 主题: [Zero-Fanker/RN_All_Issues] #Bug#巨炮不会被单位主动攻击 (#298) 
 
 
 
 
   
 【现象】：巨炮不会想其他防御&amp;#x5854;那样会被单位主动攻击 
  【反馈人】：shuiping 
  【发现版本号】：原版问题 
  【影响范围】：任务，遭遇战，多人联机 
  【产生原因】：缺少&amp;#x5A01;胁值，wwsb 
   
 &amp;mdash;

**Comment by yuanbanlao** [comment]
与防空炮持平。如果认为我防空炮应该0威胁，巨炮也0威胁。如果认为防空炮应该有威胁，巨炮也应该有威胁。

**Comment by Zero-Fanker** [comment]
> 与防空炮持平。如果认为防空炮应该0威胁，巨炮也0威胁。如果认为防空炮应该有威胁，巨炮也应该有威胁。

辣鸡kk，那么就加上威胁。

**Comment by Zero-Fanker** [comment]
威胁值添加到15。

**Comment by Zero-Fanker** [comment]
> 威胁值添加到15。

H0409已调整，请验证 @shuiping233  @yuanbanlao

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/78963874-77af2a80-7b2b-11ea-8406-6ff39a36a46e.png)

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/78964186-1176d780-7b2c-11ea-9184-1c3892772ab8.png)
