### ISSUE TITLE
#Bug##群测#盟军重制版第一关通关后无法正确接续第二关任务

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#30]
Zero Fanker created an issue 2018-10-06
【现象】：如题，第一关评分页面点继续后无法进入新的第二关
【影响范围】：第一关接关
【产生原因】：无

**Comment by shuiping233** [comment]
Zero Fanker REPORTER
changed status to resolved
问题已经查实并且进行了研究解决。 目前发现mapsel的ini需要从1开始注册，并且接关时的数字和注册名必须对应。 例如盟军下：1=ALL01 、2=ALL02 ，则[ALL01]末尾必须是2=ALL02

**Comment by shuiping233** [comment]
H1015B测试中并未发现该问题，现归档
