### ISSUE TITLE
#建议反馈#

### ISSUE THREAD

**Issue by cikenoshashou** [Zero-Fanker/RN_All_Issues#301]
【描述】遭遇战特殊模式中玩家建造种类受限，npc不受限。例如步兵大战描述是只能建造步兵和少量载具，玩家是真的这样，npc连基诺夫空艇都能造出来
【原因】特殊模式游戏体验极差
【期望解决时间】据说是因为特殊ai没写导致的O.O 希望能尽快出

**Comment by shuiping233** [comment]
？？？？

**Comment by shuiping233** [comment]
标题有误就@shuiping233修改

**Comment by shuiping233** [comment]
特殊模式的bug以及ai的修改目前制作组暂时不会处理，并且是以主线为主
