### ISSUE TITLE
#Bug#德国条顿坦克不能破坏树木

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#303]
【现象】：德国条顿坦克不能破坏树木
【反馈人】：shuiping
【发现版本号】：H0401
【影响范围】：单位手感
【产生原因】：未知

**Comment by Zero-Fanker** [comment]
@Crossfield-ClassDestroyer  驱逐验证一下

**Comment by Zero-Fanker** [comment]
H0602已修复，请验证 @shuiping233

**Comment by shuiping233** [comment]
![GIF90](https://user-images.githubusercontent.com/49360196/85221841-cc9fd480-b3e9-11ea-8d5f-e2e98f1ecadd.gif)
![Uploading GIF90.gif…]()

**Comment by shuiping233** [comment]
H0602测试结果：该问题已解决，条顿现在可以破坏树木了
