### ISSUE TITLE
#Bug#在 ”苏联任务1-红色沙文”中占领了苏联作战实验室后可获得天降红潮支援技能

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#306]
【现象】：在苏一中占领了苏联作战实验室后可获得天降红潮支援技能
【反馈人】：shuiping
【发现版本号】：H0401
【影响范围】：苏联战役第一关
【产生原因】： 未考虑该场景

![QQ截图20200403130812](https://user-images.githubusercontent.com/49360196/78330620-f994d600-75b6-11ea-82de-13a8c6154863.png)

**Comment by shuiping233** [comment]
![Uploading QQ截图20200403130812.png…]()

**Comment by shuiping233** [comment]
![QQ截图20200403131613](https://user-images.githubusercontent.com/49360196/78330525-bf2b3900-75b6-11ea-9cfa-3dbdaf6427e3.png)
![Uploading QQ截图20200403130812.png…]()

**Comment by shuiping233** [comment]
![QQ截图20200403130812](https://user-images.githubusercontent.com/49360196/78330620-f994d600-75b6-11ea-82de-13a8c6154863.png)

**Comment by Zero-Fanker** [comment]
驱逐在地图里禁用一下这个技能

**Comment by Zero-Fanker** [comment]
H0504已调整，请验证。 @shuiping233

**Comment by shuiping233** [comment]
![QQ截图20200506134743](https://user-images.githubusercontent.com/49360196/81141835-61688300-8fa0-11ea-8931-561d72d1c8e5.png)

**Comment by shuiping233** [comment]
H0505测试结果：图中实验室不是占领的，但是仍然可以提供天降红潮

**Comment by Zero-Fanker** [comment]
打包错误，等晚上更新。 ------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2020年5月6日(星期三) 中午1:52
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#在 ”苏联任务1-红色沙文”中占领了苏联作战实验室后可获得天降红潮支援技能 (#306)




 

 
&mdash;

**Comment by shuiping233** [comment]
H0506测试结果：占领/建造苏联作战实验室已经不能提供天降红潮技能

**Comment by shuiping233** [comment]
![QQ截图20200507121101](https://user-images.githubusercontent.com/49360196/81253812-0f853300-905c-11ea-824c-9a4b0020a863.png)
