### ISSUE TITLE
#Bug#苏联任务-红色沙文通关后显示无法读取场景地图，并且点击确定按钮无反应

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#307]
【现象】：苏一通关后显示无法读取场景地图，并且点击确定按钮无反应
【反馈人】：shuiping
【发现版本号】：H0401
【影响范围】：特定任务
【产生原因】：未知

**Comment by shuiping233** [comment]
并且这会导致无法返回主界面，只能通过任务管理区关闭游戏进程

**Comment by Zero-Fanker** [comment]
暂时让这关打完就进字幕，待第二关放出后恢复。

**Comment by Zero-Fanker** [comment]
H1031已修正，请验证。

**Comment by shuiping233** [comment]
H1031B测试结果：符合预期要求，测试通过
![Snipaste_2020-11-08_10-52-37](https://user-images.githubusercontent.com/49360196/98455816-a324f100-21b0-11eb-8970-a79e791adea4.png)
![Snipaste_2020-11-08_10-52-34](https://user-images.githubusercontent.com/49360196/98455821-b1730d00-21b0-11eb-9872-05e66a79dedd.png)
