### ISSUE TITLE
#Bug#给古巴的地道编队会导致游戏崩溃

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#308]
【现象】：给古巴的地道编队会导致游戏崩溃
【反馈人】：shuiping
【发现版本号】：H0401
【影响范围】：玩家选择古巴了的对战
【产生原因】：未知

![image](https://user-images.githubusercontent.com/49360196/78501421-4a125c00-778e-11ea-88a2-7b2ce8de2688.png)

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/78501419-4a125c00-778e-11ea-9f0d-caac2d0f593e.png)
![image](https://user-images.githubusercontent.com/49360196/78501421-4a125c00-778e-11ea-88a2-7b2ce8de2688.png)

**Comment by Zero-Fanker** [comment]
H0409已修复，请验证。 @shuiping233

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/78962324-965ef280-7b26-11ea-8aed-011d4818bb1c.png)
