### ISSUE TITLE
#Bug#关卡盟3中，部署平定天线后棕色敌军坦克卡兵，以及触发的小问题

### ISSUE THREAD

**Issue by Loritas** [Zero-Fanker/RN_All_Issues#309]
【现象】：部署平定天线后棕色敌军坦克在基地出口处大量卡住，且当所有平定天线部署完毕后，展开全图时，下方玩家并未去触发的有关海豹部队的触发自动触发，悬崖上的掷弹兵和灰熊坦克会在完成渗透任务时因为援军的到来开辟的视野被发现获得。
【反馈人】：Loritas
【发现版本号】：G1208B
【影响范围】：该关卡流程体验
【产生原因】：电脑的进攻小队过多（建造过快，频率过高，不过好像是触发刷的兵？），基地的出入口较狭窄，未在展开全图时禁止掉“被玩家发现”行为的触发

![GAMERN 2020-04-06 11-54-38-96](https://user-images.githubusercontent.com/62099415/78522905-86cb6b00-7801-11ea-8e36-95eae8cb4fae.png)

**Comment by Zero-Fanker** [comment]
@Fantasycho 小皮看下

**Comment by Fantasycho** [comment]
2020/04/10，尝试修复了相关问题，已上传，待测。

**Comment by Zero-Fanker** [comment]
H0409已合入修改，请验证

**Comment by shuiping233** [comment]
图片稍后补
H0409测试结果：堵车不会堵了，但是棕色ai基本没有进攻，原因是因为在自己家部署了辐射，然后一直以来很多的驻军建筑现在都没有驻军了

**Comment by shuiping233** [comment]
补充：任务完成后获得全图视野产生的bug已经修复，已经不会再因为任务完成后的全图视野而导致触发援军以及csf

**Comment by Zero-Fanker** [comment]
> 图片稍后补
> H0409测试结果：堵车不会堵了，但是棕色ai基本没有进攻，原因是因为在自己家部署了辐射，然后一直以来很多的驻军建筑现在都没有驻军了

@MadmanM 马王神看一下AI

**Comment by shuiping233** [comment]
H1108测试结果：ai辐射蹲自己家里想堵车都没法堵车，按照问题描述看，问题已经全部修复
