### ISSUE TITLE
#Bug#瓦尔哈拉选择目标为非移动单位时可能导致程序崩溃

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#310]
【现象】：瓦尔哈拉攻击非移动的物体时会崩溃
【反馈人】：
【发现版本号】：H0401
【影响范围】：瓦尔哈拉出场的场合
【产生原因】：根据crashdump，abductor的目标吸取重构存在问题，未正确判定空指针。

**Comment by shuiping233** [comment]
# 304

**Comment by Zero-Fanker** [comment]
H0409已修复，请验证 @shuiping233

**Comment by shuiping233** [comment]
这个单子就测不移动的单位被瓦尔哈拉修复就可以了？

**Comment by Zero-Fanker** [comment]
按理说应该测试强攻地面 围墙 步兵 树木------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2020年4月10日(星期五) 中午1:22
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Assign"<assign@noreply.github.com>;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#瓦尔哈拉选择目标为非移动单位时可能导致程序崩溃 (#310)




 
这个单子就测不移动的单位被瓦尔&#x54C8;拉修复就可以了？
 
&mdash;

**Comment by shuiping233** [comment]
好的

**Comment by shuiping233** [comment]
H0409测试结果：瓦尔哈拉不能强制攻击 树木 围墙 步兵 地板，对静止的单位进行传送修复也未崩溃
