### ISSUE TITLE
#Bug#生化前兆任务第一关可以通过捡箱子获得各种载具

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#311]
【现象】：H0401的生化前兆任务第一关可以通过捡箱子获得各种载具
【发现版本号】：H0401
【影响范围】：特定任务通关体验
【产生原因】：载具箱子未关闭

**Comment by Zero-Fanker** [comment]
@Takori

**Comment by Zero-Fanker** [comment]
目前应该是删除了地图上能产生箱子的小卡车了 确认一下H0602

**Comment by Zero-Fanker** [comment]
在地图中嵌入相关ini彻底屏蔽箱子开出载具的设置。

**Comment by Zero-Fanker** [comment]
H1031已修正，请验证。

**Comment by shuiping233** [comment]
![GIF43](https://user-images.githubusercontent.com/49360196/99869330-0c6f2000-2c05-11eb-93bd-606e01ad077e.gif)
有个空箱子，是特意的？

**Comment by Zero-Fanker** [comment]
怎么可能有空的------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;shuiping&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月21日(星期六) 下午2:23
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;Zero Fanker&quot;<zcyfksn@vip.qq.com&gt;;&quot;Assign&quot;<assign@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug#生化前兆任务第一关可以通过捡箱子获得各种载具 (#311)

**Comment by shuiping233** [comment]
> 怎么可能有空的------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;shuiping&quot;<notifications@github.com&gt; 发送时间:&nbsp;2020年11月21日(星期六) 下午2:23 收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;; 抄送:&nbsp;&quot;Zero Fanker&quot;<zcyfksn@vip.qq.com&gt;;&quot;Assign&quot;<assign@noreply.github.com&gt;; 主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug#生化前兆任务第一关可以通过捡箱子获得各种载具 (#311)

貌似这关里箱子的那个拾取动画没有了，语音倒是有听到

**Comment by shuiping233** [comment]
全体恢复箱子的动画倒是还有

**Comment by shuiping233** [comment]
不管箱子的其他问题的话，（H1108）现在该问题已经不再发生
