### ISSUE TITLE
#Bug#间谍渗透重工后洲际导弹信标和韩国集火信标会出现老兵升级图标

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#313]
【现象】：间谍渗透重工后洲际导弹信标和韩国集火信标会出现老兵升级图标
【反馈人】：忘了
【发现版本号】：H0118
【影响范围】：视觉效果
【产生原因】：未考虑到该场景

以下为驱逐的截图：
![5Y4S@N@{Q5T5E$VV%CA~QIN](https://user-images.githubusercontent.com/49360196/78982561-fbc9d800-7b54-11ea-9b58-f6414cc83597.jpg)
![0K1ZGHA E$BG$1C`$DCFW`P](https://user-images.githubusercontent.com/49360196/78984407-b60f0e80-7b58-11ea-8bfc-997b39371cd9.jpg)

**Comment by Zero-Fanker** [comment]
这没修过?------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2020年4月10日(星期五) 下午5:58
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Zero-Fanker/RN_All_Issues] #Bug#间谍渗透重工后洲际导弹的信标会出现老兵升级图标 (#313)




 
【现象】：间谍渗透重工后洲际导弹的信标会出现老兵升级图标
 【反馈人】：忘了
 【发现版本号】：H0118
 【影响范围】：视觉效果
 【产生原因】：未考虑到该场景
 
&mdash;

**Comment by shuiping233** [comment]
但是他确实存在，修没修过我忘了



---原始邮件---
发件人: "Zero Fanker"<notifications@github.com&gt;
发送时间: 2020年4月10日(星期五) 晚上6:04
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"shuiping"<1944680304@qq.com&gt;;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#间谍渗透重工后洲际导弹的信标会出现老兵升级图标 (#313)




 这没修过?------------------ 原始邮件 ------------------ 
 发件人: "shuiping"<notifications@github.com&gt; 
 发送时间: 2020年4月10日(星期五) 下午5:58 
 收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;; 
 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
 主题: [Zero-Fanker/RN_All_Issues] #Bug#间谍渗透重工后洲际导弹的信标会出现老兵升级图标 (#313) 
 
 
 
 
   
 【现象】：间谍渗透重工后洲际导弹的信标会出现老兵升级图标 
  【反馈人】：忘了 
  【发现版本号】：H0118 
  【影响范围】：视觉效果 
  【产生原因】：未考虑到该场景 
   
 &amp;mdash;

**Comment by Zero-Fanker** [comment]
> 但是他确实存在，修没修过我忘了
> […](#)
> ---原始邮件--- 发件人: "Zero Fanker"<notifications@github.com&gt; 发送时间: 2020年4月10日(星期五) 晚上6:04 收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;; 抄送: "Author"<author@noreply.github.com&gt;;"shuiping"<1944680304@qq.com&gt;; 主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#间谍渗透重工后洲际导弹的信标会出现老兵升级图标 (#313) 这没修过?------------------ 原始邮件 ------------------ 发件人: "shuiping"<notifications@github.com&gt; 发送时间: 2020年4月10日(星期五) 下午5:58 收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [Zero-Fanker/RN_All_Issues] #Bug#间谍渗透重工后洲际导弹的信标会出现老兵升级图标 (#313) 【现象】：间谍渗透重工后洲际导弹的信标会出现老兵升级图标 【反馈人】：忘了 【发现版本号】：H0118 【影响范围】：视觉效果 【产生原因】：未考虑到该场景 &amp;mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

那你在内测验证过再提交

**Comment by Crossfield-ClassDestroyer** [comment]
这个截图是我截的，问题确实存在 而且估计战列舰的也存在

**Comment by Zero-Fanker** [comment]
我记得我以前就修过了，那驱逐看一下ini核对一下吧------------------ 原始邮件 ------------------
发件人: "U.S.S. Destroyer"<notifications@github.com>
发送时间: 2020年4月10日(星期五) 晚上6:14
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#间谍渗透重工后洲际导弹的信标会出现老兵升级图标 (#313)




 
这个截图是我截的，问题确实存在 而且估计战列舰的也存在
 
&mdash;

**Comment by Crossfield-ClassDestroyer** [comment]
> 我记得我以前就修过了，那驱逐看一下ini核对一下吧------------------ 原始邮件 ------------------ 发件人: "U.S.S. Destroyer"<notifications@github.com> 发送时间: 2020年4月10日(星期五) 晚上6:14 收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>; 抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#间谍渗透重工后洲际导弹的信标会出现老兵升级图标 (#313) 这个截图是我截的，问题确实存在 而且估计战列舰的也存在 &mdash; You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
我测过了，老兵 集火信标，老兵 攻击信号

**Comment by Zero-Fanker** [comment]
H0504已修正，请验证 @shuiping233

**Comment by shuiping233** [comment]
H0505测试结果：问题已修复

**Comment by shuiping233** [comment]
![QQ截图20200506115321](https://user-images.githubusercontent.com/49360196/81137166-63c2e100-8f90-11ea-92bf-946e03c8be44.png)
![QQ截图20200506115012](https://user-images.githubusercontent.com/49360196/81137186-776e4780-8f90-11ea-9a24-908914ebabe0.png)
