### ISSUE TITLE
#建议反馈#用DTA启动RN联机游戏中的鼠标DPI问题

### ISSUE THREAD

**Issue by Fantasycho** [Zero-Fanker/RN_All_Issues#315]
【描述】鼠标的dpi（灵敏度）在启动游戏后突然改变了，原本习惯的鼠标挪动手感有明显变化。
【原因】日牛联机PVP会将分辨率强制改编为1366*768，但物理分辨率却并未变化，我使用的是1080P分辨率，也就是相当于我用1080P分辨率在玩一个1366分辨率拉成1080P分辨率后的游戏，由于分辨率被强制拉大，从而导致鼠标的DPI手感改变，鼠标灵敏度变得比原来更高了，让我无法适应。我希望能在保持原来鼠标灵敏度的情况下拉大分辨率。
【期望解决时间】DTA群测或公测以前

**Comment by Zero-Fanker** [comment]
自行解决，不处理------------------ 原始邮件 ------------------
发件人: "Fantasycho"<notifications@github.com>
发送时间: 2020年4月14日(星期二) 下午5:44
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Zero-Fanker/RN_All_Issues] #建议反馈#用DTA启动日牛联机游戏中的鼠标DPI问题 (#315)




 
【描述】鼠标的dpi（灵敏度）在启动游戏后突然改变了，原本习惯的鼠标挪动手感有明显变化。
 【原因】日牛联机PVP会将分辨率强制改编为1366*768，但物理分辨率却并未变化，我使用的是1080P分辨率，也就是相当于我用1080P分辨率在玩一个1366分辨率拉成1080P分辨率后的游戏，由于分辨率被强制拉大，从而导致鼠标的DPI手感改变，鼠标灵敏度变得比原来更高了，让我无法适应。我希望能在保持原来鼠标灵敏度的情况下拉大分辨率。
 【期望解决时间】DTA群测或公测以前
 
&mdash;
