### ISSUE TITLE
#Bug#冷战地图有无法建筑区域

### ISSUE THREAD

**Issue by skywolf404** [Zero-Fanker/RN_All_Issues#316]
【现象】：冷战地图一号位旁有一格无法放置建筑
【反馈人】：自己
【发现版本号】：H.H0118P
【影响范围】：遭遇战及联机
![bug2](https://user-images.githubusercontent.com/63897668/79631172-e32b7480-8189-11ea-9f01-0e68a95f2932.gif)
![bug3](https://user-images.githubusercontent.com/63897668/79631174-e4f53800-8189-11ea-8f93-cb7c42f99a77.gif)
![bug12](https://user-images.githubusercontent.com/63897668/79631175-e7579200-8189-11ea-8861-43e9ee4f0c06.gif)
![bug13](https://user-images.githubusercontent.com/63897668/79631177-e9215580-8189-11ea-8cf9-7c10bcaffb60.gif)

**Comment by shuiping233** [comment]
我去测试一下新开一局原本这个位置是不是又空气障碍物吧

**Comment by Zero-Fanker** [comment]
> 我去测试一下新开一局原本这个位置是不是又空气障碍物吧

结论是什么

**Comment by shuiping233** [comment]
> > 我去测试一下新开一局原本这个位置是不是又空气障碍物吧
> 
> 结论是什么

新开的地图中并无此事发生，可能是战斗中发生的，不过这个和一般的空气墙地块不一样，这个能通过单位，就很奇怪

**Comment by Renko-ji** [comment]
0.99.911a3测试结果，开局没有空气墙，肯定是战斗造成的空气墙
