### ISSUE TITLE
#Bug#谭雅在攻击被鱿鱼缠绕的船时，鱿鱼和船会直接消失。没有爆炸和下沉的效果。

### ISSUE THREAD

**Issue by 1783428868** [Zero-Fanker/RN_All_Issues#317]
【现象】：谭雅在攻击被鱿鱼缠绕的船时，鱿鱼和船会直接消失。没有爆炸和下沉的效果。
【反馈人】：
【发现版本号】：H.H0118P
【影响范围】：遭遇战
【产生原因】：

**Comment by 1783428868** [comment]
更正：下沉的效果时有时无，没有下沉效果时船和鱿鱼会直接消失

**Comment by 1783428868** [comment]
更正：下沉效果时有时无，没有时鱿鱼和船会直接消失

**Comment by shuiping233** [comment]
海蝎和海豚和潜艇类自然是没有下沉动画的，而其他舰艇的下沉动画即使在被鱿鱼缠绕时击毁船只人仍然能正常播放

**Comment by shuiping233** [comment]
综上所述，这个单子设为无效

**Comment by shuiping233** [comment]
![GIF75](https://user-images.githubusercontent.com/49360196/79676850-ee7bb000-821c-11ea-8e37-63cdc24945db.gif)
