### ISSUE TITLE
#Bug#尤里的巨型乌贼没有死亡动画

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#318]
【现象】：尤里的巨型乌贼没有死亡动画，会让人觉得死的很突兀，想蒸发一样，所以可以增加死亡动画，类似于海豚死亡那种爆炸即可
【反馈人】：shuiping
【发现版本号】：H0409
【影响范围】：视觉体验
【产生原因】：未知

**Comment by shuiping233** [comment]
![GIF77](https://user-images.githubusercontent.com/49360196/79676974-5da5d400-821e-11ea-8c19-d5f0bb31f3cb.gif)

**Comment by shuiping233** [comment]
![D{SA470$VZ 4DUM9 BP9N](https://user-images.githubusercontent.com/49360196/79677036-33084b00-821f-11ea-8b5d-16def7de54e4.png)

**Comment by shuiping233** [comment]
![GIF76](https://user-images.githubusercontent.com/49360196/79677055-65b24380-821f-11ea-8fb8-14dda50e431d.gif)

**Comment by Zero-Fanker** [comment]
@xuetianyi  @Super-StarX  你们怎么看

**Comment by xuetianyi** [comment]
原版也是这样吗？如果鱿鱼的shp序列中有死亡动作，可以截取出来，然后用载具死亡动画来表现吧？


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Zero Fanker <notifications@github.com&gt;
发送时间: 2020年10月26日 23:28
收件人: Zero-Fanker/RN_All_Issues <RN_All_Issues@noreply.github.com&gt;
抄送: xuetianyi <84371865@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[Zero-Fanker/RN_All_Issues] #Bug#尤里的巨型乌贼没有死亡动画 (#318)





 
@xuetianyi  @Super-StarX  你们怎么看

**Comment by Zero-Fanker** [comment]
> 原版也是这样吗？如果鱿鱼的shp序列中有死亡动作，可以截取出来，然后用载具死亡动画来表现吧？ 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Zero Fanker <notifications@github.com&gt; 发送时间: 2020年10月26日 23:28 收件人: Zero-Fanker/RN_All_Issues <RN_All_Issues@noreply.github.com&gt; 抄送: xuetianyi <84371865@qq.com&gt;, Mention <mention@noreply.github.com&gt; 主题: 回复：[Zero-Fanker/RN_All_Issues] #Bug#尤里的巨型乌贼没有死亡动画 (#318) @xuetianyi @Super-StarX 你们怎么看 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

我暂时用原版通用爆炸动画比较小的尺寸用着了。晚点再做专属死亡动画。

**Comment by Zero-Fanker** [comment]
H1031已修正，请验证。

**Comment by shuiping233** [comment]
![GIF38](https://user-images.githubusercontent.com/49360196/98455892-745b4a80-21b1-11eb-842c-6280bfdcfd09.gif)
H1031B测试结果：符合预期描述，测试通过
