### ISSUE TITLE
#Bug##群测##联机RE#有玩家反馈合作任务会导致中途RE

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#32]
Zero Fanker created an issue 2018-10-08
【现象】：
合作任务进行中产生RE

【影响范围】：
所有合作任务模式的地图

【产生原因】：
未知

**Comment by shuiping233** [comment]
Zero Fanker REPORTER
changed status to open
正在着手研究相关的函数，目前在看5C30C0

2018-10-08
 Zero Fanker REPORTER
changed title to #Bug##群测##联机RE#有玩家反馈合作任务会导致中途RE
2018-10-08
 Zero Fanker REPORTER
针对建筑的BeingProduced变量已经做了修正。 desync.jpg 仍然有动画和抛射体的问题

2018-10-14
 Zero Fanker REPORTER
changed status to duplicate
Duplicate of #54.

确认就是古巴自行高炮的问题。

2018-10-27
Log in to comment

**Comment by Zero-Fanker** [comment]
旧bug迁移已修正问题
