### ISSUE TITLE
#建议反馈#让观察者可以识别玩家的单位名称

### ISSUE THREAD

**Issue by yuanbanlao** [Zero-Fanker/RN_All_Issues#320]
【描述】建议观察者可以识别玩家的单位名称，而不是显示敌方单位。
【原因】影响观战观感
【期望解决时间】如果工程量过大，优化单子可以先拖着，期望是先做完所有内容。

**Comment by Zero-Fanker** [comment]
H1024已调整，请验证。

**Comment by shuiping233** [comment]
H1024测试结果：观察者可以看到敌方单位和建筑的名字，暂未进行联机测试

**Comment by shuiping233** [comment]
H1024测试结果：联机测试发现，中途退出的玩家查看敌方单位仍然无法显示敌方单位和建造的具体名称，观察者位则无问题
