### ISSUE TITLE
#建议反馈#让观察者可以看到玩家的隐形单位

### ISSUE THREAD

**Issue by yuanbanlao** [Zero-Fanker/RN_All_Issues#321]
【描述】建议观察者可以看到玩家的隐形单位
【原因】影响观感
【期望解决时间】如果工程量过大，优化单子可以拖后，优先完成开发内容

**Comment by shuiping233** [comment]
不如一起把查看生产线，查看电力等等的功能也加上去？



---原始邮件---
发件人: "yuanbanlao"<notifications@github.com&gt;
发送时间: 2020年4月20日(星期一) 下午4:29
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Zero-Fanker/RN_All_Issues] #建议反馈#观察者可以看到玩家的隐形单位 (#321)




 
【描述】建议观察者可以看到玩家的隐形单位
 【原因】影响观感
 【期望解决时间】如果工程量过大，优化单子可以拖后，优先完成开发内容

**Comment by Zero-Fanker** [comment]
DTA客户端的多个观察者情况没有测试，目前是用单观察者的，符合预期。

**Comment by Zero-Fanker** [comment]
H1024已调整，请验证。@yuanbanlao @shuiping233

**Comment by shuiping233** [comment]
![Snipaste_2020-10-25_12-04-49](https://user-images.githubusercontent.com/49360196/97098695-10b62500-16bb-11eb-839b-ee73e5c107d6.png)
![Snipaste_2020-10-25_12-03-54](https://user-images.githubusercontent.com/49360196/97098701-1b70ba00-16bb-11eb-9b41-44e982620853.png)
H1024测试结果：结果符合预期，除了能看隐形单位外也能消除裂缝产生器的影响

**Comment by Zero-Fanker** [comment]
你这个是测的单人观察者还是多人的，还需要测一下多个观察者的情况，是否每个观察者都正常 ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;shuiping&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月25日(星期天) 中午12:12
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;Zero Fanker&quot;<zcyfksn@vip.qq.com&gt;;&quot;Assign&quot;<assign@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #建议反馈#让观察者可以看到玩家的隐形单位 (#321)

**Comment by shuiping233** [comment]
@yuanbanlao 出来测单子

**Comment by shuiping233** [comment]
H1024测试结果：联机测试发现，中途退出的玩家无法看见隐形单位，观察者位则无问题
