### ISSUE TITLE
#Bug#电力不足时关闭的建筑无法开启

### ISSUE THREAD

**Issue by Legend-Huang** [Zero-Fanker/RN_All_Issues#322]
【现象】：1、停电后的恢复供电功能在电力不足情况下无法使用 2、停掉生产建筑后生产建筑依然享受速度加成
【反馈人】：Legend-Huang
【发现版本号】：H0118P
【影响范围】：遭遇战、多人联机
【产生原因】：停电的逻辑问题

1、在电力不足情况下，玩家会停用部分建筑使电力恢复，如图停掉了一个建筑后仍然停电，那么再对其启用的功能失效。

这个Bug可能会在玩家建立了许多防御塔时并且电力不足时产生影响，玩家对多防御塔进行不停的停电和启用操作时，比较容易触发此Bug，希望能修复。

可以算作特性，但是与命令与征服3的停电逻辑不符。
![QQ截图20200427164818](https://user-images.githubusercontent.com/11090991/80352876-1c10cb00-88a7-11ea-9e06-7111609ebf65.png)

2、战车工厂等生产建筑，停电之后依然能给生产加速，可以利用于联机或遭遇战作弊。

[注释]:例子：
[注释]:【现象】：韩国火炮、洲际导弹的信标可以被超时空传送、铁幕装置影响
[注释]:【反馈人】：永恒_叶
[注释]:【发现版本号】：0.99.F1028A
[注释]:【影响范围】：影响带有AI的对局
[注释]:【产生原因】：AI新机制引入

**Comment by shuiping233** [comment]
没有这个版本号，然后标题不需要前面那句话

**Comment by Zero-Fanker** [comment]
第一个问题可以算作特性对待，不做调整。YR的动画停电/非停电状态切换很迷，允许启用会引入更严重的问题。

加速问题会关注。

**Comment by shuiping233** [comment]
我正在准备测试验证

**Comment by shuiping233** [comment]
H0409测试结果：与问题描述一致，即使给生产建筑断电，多生产建筑生产加速的效果依然存在

**Comment by Zero-Fanker** [comment]
多工厂加成没考虑关闭建筑的问题已经另外开单子 #401，本问题维持现状，目前不解决。
