### ISSUE TITLE
#建议反馈#建议要塞和攻城机甲的碾压等级相同，互相无法被碾压

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#323]
【描述】建议要塞和攻城机甲互相不能被碾压，现版本中要塞可以碾压机甲
【原因】视觉上要塞碾机甲不太合理，机甲的模型体积比要塞大

![QQ截图20200427175324](https://user-images.githubusercontent.com/49360196/80364896-44a1c080-88b9-11ea-836e-1f8614485039.png)

小星星的方案则是互相无法被碾
![QQ截图20200427175304](https://user-images.githubusercontent.com/49360196/80364900-47041a80-88b9-11ea-8273-ed725b9ca054.png)

kk的看法则是：无所谓
![image](https://user-images.githubusercontent.com/49360196/80364930-56836380-88b9-11ea-9a92-9c43d8f0131b.png)

【期望解决时间】尽快

**Comment by shuiping233** [comment]
![QQ截图20200427175324](https://user-images.githubusercontent.com/49360196/80364896-44a1c080-88b9-11ea-836e-1f8614485039.png)
![QQ截图20200427175304](https://user-images.githubusercontent.com/49360196/80364900-47041a80-88b9-11ea-8273-ed725b9ca054.png)

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/80364930-56836380-88b9-11ea-9a92-9c43d8f0131b.png)

**Comment by Zero-Fanker** [comment]
暂不做考虑。让kk给出正面评论。
@yuanbanlao

**Comment by yuanbanlao** [comment]
我同意星星的方案。

**Comment by Zero-Fanker** [comment]
> 我同意星星的方案。

??????

**Comment by yuanbanlao** [comment]
？？？？？？？

**Comment by shuiping233** [comment]
？？？？？

**Comment by yuanbanlao** [comment]
那么做出的修改为：机甲碾压等级3，抗压等级4；要塞碾压等级4.

**Comment by Zero-Fanker** [comment]
那这个是0.99.905就已经包含了？

**Comment by shuiping233** [comment]
0.99.909测试通过
