### ISSUE TITLE
#Bug#核弹发射后的警报声不会随着距离核爆中心的远近而有所衰减

### ISSUE THREAD

**Issue by yuanbanlao** [Zero-Fanker/RN_All_Issues#324]
【现象】：核弹发射之后不再像np平台一样能够“听声辩位”
【反馈人】：星星
【发现版本号】：H0409
【影响范围】：单机联机
【产生原因】：ares修坏了

**Comment by Super-StarX** [comment]
是sound.ini中的Type=local功能不好使了

**Comment by Zero-Fanker** [comment]
H1031已修正，请验证。

**Comment by shuiping233** [comment]
@yuanbanlao 我觉得这个单子给你测更好

**Comment by yuanbanlao** [comment]
给出适当的理由

**Comment by Super-StarX** [comment]
已修复------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;yuanbanlao&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月26日(星期四) 晚上10:34
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;Super-StarX&quot;<88648845@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug#核弹发射后的警报声不会随着距离核爆中心的远近而有所衰减 (#324)

**Comment by shuiping233** [comment]
好的，我找时间归档



---原始邮件---
发件人: "Super-StarX"<notifications@github.com&gt;
发送时间: 2020年11月26日(星期四) 晚上10:56
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"shuiping"<1944680304@qq.com&gt;;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#核弹发射后的警报声不会随着距离核爆中心的远近而有所衰减 (#324)




 已修复------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;&amp;quot;yuanbanlao&amp;quot;<notifications@github.com&amp;gt; 
 发送时间:&amp;nbsp;2020年11月26日(星期四) 晚上10:34 
 收件人:&amp;nbsp;&amp;quot;Zero-Fanker/RN_All_Issues&amp;quot;<RN_All_Issues@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;&amp;quot;Super-StarX&amp;quot;<88648845@qq.com&amp;gt;;&amp;quot;Comment&amp;quot;<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug#核弹发射后的警报声不会随着距离核爆中心的远近而有所衰减 (#324)
