### ISSUE TITLE
#建议反馈#"一键切换Win10兼容补丁.bat"的编码问题

### ISSUE THREAD

**Issue by LucaTrulyworth** [Zero-Fanker/RN_All_Issues#325]
【描述】“一键切换Win10兼容补丁.bat"执行出现乱码，且并未实现一键切换功能
【原因】“Win8&Win10兼容补丁”目录名存在汉字，windows下cmd默认采用GBK编码汉字，“一键切换Win10兼容补丁.bat"也采用GBK编码。但是有时候本机处于某些原因（比如开发需要），cmd改成了UTF-8编码，导致脚本文件路径识别错误，无法实现功能，且会出现乱码提示。
建议把“Win8&Win10兼容补丁”目录中的中文字符去掉，让bat文件可以纯ascii字符，减少兼容性问题。

**Comment by Zero-Fanker** [comment]
了解，不过后续已经使用统一版的ddraw补丁，不再继续支持切换补丁功能。因此该项建议不会被采纳，并且兼容性补丁的文件夹会被废除。
感谢反馈！
