### ISSUE TITLE
#Bug#苏系收割者可以被狗吃掉

### ISSUE THREAD

**Issue by 1938611698** [Zero-Fanker/RN_All_Issues#329]
【现象】：苏系收割者可以被狗吃掉
【发现版本号】 : H0118P
【影响范围] :单位手感
【产生原因】 : 有点说不通

**Comment by shuiping233** [comment]
这就很离谱，你格式呢？

**Comment by shuiping233** [comment]
@yuanbanlao

**Comment by 1938611698** [comment]
[现象] : 收割者可以被狗咬死
[发现版本号] : H0118P
[影响范围] :单位手感
[产生原因] : 有点说不通

**Comment by shuiping233** [comment]
这个问题需要验证，我等会会测试

**Comment by Zero-Fanker** [comment]
> @yuanbanlao

kk觉得收割者是否需要免疫警犬？

**Comment by yuanbanlao** [comment]
这个单看游戏性就行了。觉得合理就保留，不合理就取消

**Comment by Zero-Fanker** [comment]
要统筹考虑的话还需要关注一下赛博格和暴风摩托，尤里的T4兽人应该不涉及，因为数据是基于普通兽人的。从合理性角度半机械人应该是能防警犬的吧。 ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;yuanbanlao&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月4日(星期五) 下午3:04
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;Zero Fanker&quot;<zcyfksn@vip.qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug#苏系收割者可以被狗吃掉 (#329)

**Comment by yuanbanlao** [comment]
那就按照合理性角度解决吧，所有半机械生物防警犬

**Comment by shuiping233** [comment]
@yuanbanlao 既然已经讨论完了，这个数据改好了么

**Comment by shuiping233** [comment]
所以改了吗？

**Comment by Zero-Fanker** [comment]
问kk 状态没改的就认为没啊------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月22日(星期四) 中午12:02
***@***.***&gt;;
抄送:&nbsp;&quot;Zero ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug#苏系收割者可以被狗吃掉 (#329)

**Comment by yuanbanlao** [comment]
改了改了。

**Comment by shuiping233** [comment]
0.99.905a5是否实装？

**Comment by shuiping233** [comment]
![GIF148](https://user-images.githubusercontent.com/49360196/127740872-a788ce80-1002-4cff-80b5-cecc9dc502f1.gif)
0.99.905a5测试通过

**Comment by shuiping233** [comment]
现归档
