### ISSUE TITLE
#Bug#狙击手反坦克模式武器对步兵的单发伤害比狙击模式武器的单发伤害高

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#330]
【现象】：狙击手反坦克模式武器对步兵的单发伤害比狙击模式武器的单发伤害高
【反馈人】：shuiping
【发现版本号】：H0409
【影响范围】：单位平衡
【产生原因】：希腊奶

![2020年05月01日16点27分51秒](https://user-images.githubusercontent.com/49360196/80793499-dcf5b900-8bc9-11ea-8529-c9cbc391cd1d.png)
左大兵吃狙击枪，右大兵吃反坦克炮

**Comment by shuiping233** [comment]
![2020年05月01日16点27分51秒](https://user-images.githubusercontent.com/49360196/80793499-dcf5b900-8bc9-11ea-8529-c9cbc391cd1d.png)

**Comment by shuiping233** [comment]
@yuanbanlao

**Comment by shuiping233** [comment]
虽然很科学，但是狙击手要变成射大炮的啦，然后还能打一坨伤害，狙击枪的作用就变小了

**Comment by Zero-Fanker** [comment]
然而有弹道偏移------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2020年5月1日(星期五) 下午4:32
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Assign"<assign@noreply.github.com>;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#狙击手反坦克模式武器对步兵的单发伤害比狙击模式武器的单发伤害高 (#330)




 
Assigned #330 to @Zero-Fanker.
 
&mdash;

**Comment by shuiping233** [comment]
虽然有偏吧，也有打不着的时候，但是不影响反坦克炮可以反制步兵海

**Comment by Zero-Fanker** [comment]
本来就是设定反集群啊------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2020年5月1日(星期五) 下午5:40
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#狙击手反坦克模式武器对步兵的单发伤害比狙击模式武器的单发伤害高 (#330)




 
虽然有偏吧，也有打不着的时候，但是不影响反坦克炮可以反制步兵海
 
&mdash;

**Comment by shuiping233** [comment]
好的

**Comment by shuiping233** [comment]
@yuanbanlao 如果没意见我就关掉单子了

**Comment by yuanbanlao** [comment]
步兵经常集群使用。如果弹道偏移不过分的话一定是部署好用，参见履带车

**Comment by shuiping233** [comment]
> 步兵经常集群使用。如果弹道偏移不过分的话一定是部署好用，参见履带车

事实证明他弹道不怎么飘，只比煤球兵差一点而已

**Comment by shuiping233** [comment]
有观察者的情况下，可以做到一炮干死一堆兵

**Comment by yuanbanlao** [comment]
那就看是要游戏性还是要真实性了。或者说，大幅度降低部署后攻击速度也是可行的。

**Comment by Zero-Fanker** [comment]
二者肯定是要兼顾的，那么目前的数据认为OP了吗？ ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;yuanbanlao&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月8日(星期六) 凌晨0:32
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;Zero Fanker&quot;<zcyfksn@vip.qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug#狙击手反坦克模式武器对步兵的单发伤害比狙击模式武器的单发伤害高 (#330)

**Comment by yuanbanlao** [comment]
游戏性，伤害大一点也无妨，降低射速即可。

**Comment by Zero-Fanker** [comment]
> 游戏性，伤害大一点也无妨，降低射速即可。

那你屠一下龙，降低射速？

**Comment by yuanbanlao** [comment]
这个单子被一个总单子包含，而总单子已经完成。
