### ISSUE TITLE
#建议反馈#

### ISSUE THREAD

**Issue by cpwdmac** [Zero-Fanker/RN_All_Issues#335]
【描述】（填写你要反馈或者建议的内容，越详细越好，条理清晰可分条列举）
【原因】（填写你要提出建议的原因，不写原因基本不会被重视）
【期望解决时间】（如果你期望及时得到解决，可以填写期望的日期，选填）

[注]:不按照格式填写会被视作无效。

**Comment by cpwdmac** [comment]
【描述】 为古巴的恐怖分子新增一个劫持载具的能力，劫持的载具不会被心控，被摧毁时会爆炸，也可以部署爆炸，爆炸的伤害取决于载具的生命值，被劫持载具无法回复生命值
【原因】 古巴的恐怖分子始终在游戏里没有得到好的登场环境，希望可以为其增加一些更具有古巴特色的手段出现在战场上，参考将军里的劫持犯。
【期望解决时间】 希望能在版本更新时添加

**Comment by shuiping233** [comment]
与 #336 重复 这个issue关闭
