### ISSUE TITLE
#Bug#超时空武器导致的建造动画异常

### ISSUE THREAD

**Issue by xuetianyi** [Zero-Fanker/RN_All_Issues#338]
【现象】：当一个建筑在buildup动画播放期间，被超时空武器击中，然后解冻，该建筑就会反复播放buildup动画。
【发现版本号】：H0506
【影响范围】：游戏体验
【产生原因】：未知

**Comment by Zero-Fanker** [comment]
H1031已修正，请验证。

**Comment by shuiping233** [comment]
H1031B测试结果：已经无法复现该问题
