### ISSUE TITLE
#Bug#生化1重制版的箱子问题

### ISSUE THREAD

**Issue by VoidSea** [Zero-Fanker/RN_All_Issues#339]
【描述】生化系列任务1中一个箱子我死活吃不到，建议向右移动一格
![tt](https://user-images.githubusercontent.com/14891010/97326703-3c99fc00-18af-11eb-8698-ee25382df5e9.jpg)

【验收标准】让玩家能正常吃到所有的箱子

**Comment by Zero-Fanker** [comment]
@Takori

**Comment by Zero-Fanker** [comment]
#311 和这个问题一并解决一下。

**Comment by Zero-Fanker** [comment]
@shuiping233  看下现在还有没有这个问题。

**Comment by shuiping233** [comment]
![Snipaste_2020-11-21_14-17-08](https://user-images.githubusercontent.com/49360196/99869251-881c9d00-2c04-11eb-8002-7c5af9e64c9d.png)
是不是直接把这箱子干掉了？

**Comment by Zero-Fanker** [comment]
我没改，可能之前被地图师抹掉了。      ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;shuiping&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月21日(星期六) 下午2:19
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;Zero Fanker&quot;<zcyfksn@vip.qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug#生化1重制版的箱子问题 (#339)

**Comment by shuiping233** [comment]
那我去看看还有没有其他错位的箱子，没有的话这单子我归档去

**Comment by shuiping233** [comment]
并未发现错位无法拾取的箱子，该问题已经不存在
