### ISSUE TITLE
#Bug#H0409P特殊战役二的战机无法装填弹药，停放时角度出错且无法手动矫正

### ISSUE THREAD

**Issue by ZeroXrorn** [Zero-Fanker/RN_All_Issues#342]
【现象】：H0409P特殊战役二的战机无法装填弹药，停放时角度出错且无法手动矫正
【反馈人】：	ZeroXrorn
【发现版本号】：H0409P
【影响范围】：任务体验
【产生原因】：未知
![QQ图片20200510192724](https://user-images.githubusercontent.com/65109756/81498141-c2bc8900-92f5-11ea-86f2-2ac4622e57b6.jpg)
![QQ图片20200510192728](https://user-images.githubusercontent.com/65109756/81498138-bafce480-92f5-11ea-99df-4aa52b49bbe1.jpg)
![QQ图片20200510192731](https://user-images.githubusercontent.com/65109756/81498146-cd771e00-92f5-11ea-9ecb-2f7de646008c.jpg)

**Comment by Zero-Fanker** [comment]
没复现出来。shuiping呢 @shuiping233

**Comment by shuiping233** [comment]
过会我测测看



---原始邮件---
发件人: "Zero Fanker"<notifications@github.com&gt;
发送时间: 2020年5月16日(星期六) 下午3:10
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"shuiping"<1944680304@qq.com&gt;;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#H0409P特殊战役二的战机无法装填弹药，停放时角度出错且无法手动矫正 (#342)




 
没复现出来。shuiping呢 @shuiping233

**Comment by shuiping233** [comment]
H0409P1无法复现，这issues关掉好了，应该是H0409P1顺便修好了

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/82116670-10c20880-979e-11ea-87bd-fa2893a3142a.png)

**Comment by shuiping233** [comment]
> 【现象】：H0409P特殊战役二的战机无法装填弹药，停放时角度出错且无法手动矫正
> 【反馈人】：	ZeroXrorn
> 【发现版本号】：H0409P
> 【影响范围】：任务体验
> 【产生原因】：未知
> ![QQ图片20200510192724](https://user-images.githubusercontent.com/65109756/81498141-c2bc8900-92f5-11ea-86f2-2ac4622e57b6.jpg)
> ![QQ图片20200510192728](https://user-images.githubusercontent.com/65109756/81498138-bafce480-92f5-11ea-99df-4aa52b49bbe1.jpg)
> ![QQ图片20200510192731](https://user-images.githubusercontent.com/65109756/81498146-cd771e00-92f5-11ea-9ecb-2f7de646008c.jpg)

如果你也能在H0409P1还能复现这个bug那就请在这里留言

**Comment by shuiping233** [comment]
无进一步信息，并且我无法复现，现关闭此issues
