### ISSUE TITLE
#Bug#H0409P苏系AI不造密闭实验室，但可以造秘密实验室

### ISSUE THREAD

**Issue by ZeroXrorn** [Zero-Fanker/RN_All_Issues#343]
【现象】：（描述修正）在多次测试后发现，在大部分情况下的苏系AI即使满足建造T4条件都不会制造T4实验室
【反馈人】：ZeroXrorn 
【发现版本号】：H0409P
【影响范围】：遭遇战
【产生原因】：未知

[注释]: 例子：
[注释]:【现象】：韩国火炮、洲际导弹的信标可以被超时空传送、铁幕装置影响
[注释]:【反馈人】：永恒_叶
[注释]:【发现版本号】：0.99.F1028A
[注释]:【影响范围】：影响带有AI的对局
[注释]:【产生原因】：AI新机制引入

**Comment by shuiping233** [comment]
描述有点模糊，请描述清楚，具体到阵营，包括地图和模式

**Comment by shuiping233** [comment]
@ZeroXrorn   请补充描述，如果没反馈我将关闭该单子

**Comment by Zero-Fanker** [comment]
@yuanbanlao kk关注下

**Comment by shuiping233** [comment]
我觉得没这个事情，我去测测看

**Comment by shuiping233** [comment]
![Snipaste_2020-10-08_14-43-37](https://user-images.githubusercontent.com/49360196/95424259-f5d27980-0974-11eb-8719-2547a66ee888.png)

**Comment by shuiping233** [comment]
虽然说苏系ai建造t4较晚，但是不会建造密闭实验室的情况是很少的，我猜是没有空间放置t4而已

**Comment by yuanbanlao** [comment]
那没事啊，反正ai跨科技等级出单位十分普遍。既然能出T4就没必要再管那么多了。

**Comment by Zero-Fanker** [comment]
> 虽然说苏系ai建造t4较晚，但是不会建造密闭实验室的情况是很少的，我猜是没有空间放置t4而已

那么就不存在题述问题。
