### ISSUE TITLE
#Bug#H0409P新的CNCDDRAW渲染补丁鼠标可以移动到游戏外面，对双屏幕或窗口化用户不友好

### ISSUE THREAD

**Issue by Legend-Huang** [Zero-Fanker/RN_All_Issues#344]
【现象】：新的CNCDDRAW渲染补丁鼠标可以移动到游戏外面，对多屏幕或窗口化用户不友好
【反馈人】：
【发现版本号】：H0409P
【影响范围】：因为使用了双屏幕、多屏幕、窗口化进行游戏，主要影响的场景为：使用了双屏幕或多屏幕直播时玩复仇时刻，一个屏幕看弹幕，另一个屏幕是游戏，如果鼠标能移到外面就很不方便会导致不经意的切屏，希望能更改方式或增加相关选项
【产生原因】：使用了双屏幕、多屏幕、窗口化进行游戏

[注释]:例子：
[注释]:【现象】：韩国火炮、洲际导弹的信标可以被超时空传送、铁幕装置影响
[注释]:【反馈人】：永恒_叶
[注释]:【发现版本号】：0.99.F1028A
[注释]:【影响范围】：影响带有AI的对局
[注释]:【产生原因】：AI新机制引入

**Comment by Zero-Fanker** [comment]
![image](https://user-images.githubusercontent.com/14891010/81571469-93c91480-93d4-11ea-87e1-7aebb17d2bbd.png)

**Comment by Zero-Fanker** [comment]
@yuanbanlao @RN-Hydra  @Super-StarX  H0602 DTA更新已支持，请验证。
群测玩家请等待后续DTA发布。

**Comment by shuiping233** [comment]
说一下限制鼠标移出窗口外功能的体验：开启后，鼠标不能穿越游戏窗口，如果游戏窗口正好覆盖到桌面菜单栏，那么鼠标移动到屏幕低端会唤出菜单栏。但是如果使用win+d键最小化游戏窗口，会导致鼠标定死在屏幕左上角不能移动

**Comment by Zero-Fanker** [comment]
cncddraw本来就是这样的，正常使用没啥问题，你要退出就点退出菜单。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;shuiping&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月18日(星期天) 下午5:27
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;Zero Fanker&quot;<zcyfksn@vip.qq.com&gt;;&quot;Assign&quot;<assign@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug#H0409P新的CNCDDRAW渲染补丁鼠标可以移动到游戏外面，对双屏幕或窗口化用户不友好 (#344)

**Comment by shuiping233** [comment]
那现在已经符合问题需求了，我现在归档

**Comment by Zero-Fanker** [comment]
> 那现在已经符合问题需求了，我现在归档

记得归档
