### ISSUE TITLE
#bug#尤里第一关货车线会导致多两个间谍

### ISSUE THREAD

**Issue by yu121971** [Zero-Fanker/RN_All_Issues#346]
【现象】：ifv线正常，两个间谍渗透后，车上间谍下车进入卫星，然后出来一个。
货车线，一个间谍渗透后，另外两个间谍并没有进入卫星。导致后续行动可以有多的间谍用。
【反馈人】：	yu121971
【发现版本号】：H0409P1
【影响范围】：关卡难度
【产生原因】：未知

**Comment by shuiping233** [comment]
下次请按格式

**Comment by Zero-Fanker** [comment]
@Fantasycho 小皮后面跟进一下。

**Comment by yu121971** [comment]
具体来讲就是渗透卫星时。
ifv线，两个间谍进去卫星，一个间谍从车上下来进入卫星，然后出来一个间谍。最后可使用的间谍只有一个。
货车线，一个间谍进去卫星，两个站在外面不动，然后进卫星的间谍出来到可操纵的时候拉一下两个开始移动的间谍，就可以使用三个间谍了。

**Comment by shuiping233** [comment]
I206测试中已无法复现该问题，现归档
