### ISSUE TITLE
#Bug#H0409P1尤里第一关不能上火车

### ISSUE THREAD

**Issue by 283795021** [Zero-Fanker/RN_All_Issues#347]
【现象】：尤里第一关间谍不能上火车，剩余时间一分钟火车到达后没有反应
【反馈人】：本人
【发现版本号】：H0409P1
【影响范围】：影响通关，卡关
【产生原因】：不知道
![VID_20200516_144202 00_00_13--00_00_23](https://user-images.githubusercontent.com/32633330/82112999-0fd0ad00-9785-11ea-8e5b-934fc9977f62.gif)

**Comment by 283795021** [comment]
![bug](https://user-images.githubusercontent.com/32633330/82113047-5b835680-9785-11ea-81ab-82cce4c7648a.gif)

**Comment by shuiping233** [comment]
倒计时过了之后间谍能上火车吗？

**Comment by 283795021** [comment]
> 
> 
> 倒计时过了之后间谍能上火车吗？

倒计时过了之后就任务失败了

**Comment by 283795021** [comment]
![我要上车!](https://user-images.githubusercontent.com/32633330/82113086-cc2a7300-9785-11ea-9acb-c7a3d3fc0f6d.gif)

**Comment by shuiping233** [comment]
正常任务流程应该是接近火车轨道后会取消玩家控制权然后等候火车，你多次尝试过了吗？

**Comment by 283795021** [comment]
> 正常任务流程应该是接近火车轨道后会取消玩家控制权然后等候火车，你多次尝试过了吗？

多次尝试读取存档，两次重新开始重新打过

**Comment by shuiping233** [comment]
都是这样吗？那我去看看情况

**Comment by 283795021** [comment]
> 都是这样吗？那我去看看情况

对，都是这样，上不了车，我也不知什么情况。我之前怀疑存档有bug，就重新打了，然后还是在车旁边不上车

**Comment by 283795021** [comment]
我刚刚打了第三遍，重头开始，依然上不去火车

**Comment by 283795021** [comment]
![上不去啊](https://user-images.githubusercontent.com/32633330/82113489-0c3f2500-9789-11ea-9ab8-1ae1ce97361b.gif)

**Comment by 283795021** [comment]
我知道bug在哪了= =，触发区域在图示区域
![image](https://user-images.githubusercontent.com/32633330/82114027-bf5d4d80-978c-11ea-8a78-0e5ab99ff387.png)

**Comment by 283795021** [comment]
> 都是这样吗？那我去看看情况

![image](https://user-images.githubusercontent.com/32633330/82114500-97bbb480-978f-11ea-9be3-30450bfaaa2a.png)
这是我的行走路线，走下面一路bu'hui不会触发，需要靠近两个仓库才会触发

**Comment by Zero-Fanker** [comment]
@Fantasycho 小皮这个单子一并关注一下。

**Comment by shuiping233** [comment]
H0704测试结果：间谍已经可以正常进火车，不过我没测太多次

**Comment by Zero-Fanker** [comment]
如果你要不到原始存档，此单就作废，下次要求提供存档。 ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;shuiping&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月21日(星期二) 上午10:24
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;Zero Fanker&quot;<zcyfksn@vip.qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug#H0409P1尤里第一关不能上火车 (#347)

**Comment by shuiping233** [comment]
哦好的，那我再去测测看

**Comment by shuiping233** [comment]
无法复现该问题，故关闭此单
