### ISSUE TITLE
#Bug#古巴兵营附近存在沙袋时显示次序不正确

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#349]
【现象】：盟军特别行动2古巴兵营与沙袋出现显示问题，如图所示
【反馈人】：Zero Fanker
【发现版本号】：H0409P1
【影响范围】：视觉体验
【产生原因】：古巴兵营建筑的绘制次序错误

![QQ图片20200517102259_WPS图片](https://user-images.githubusercontent.com/49360196/82138072-2bed5080-9850-11ea-8f77-3b77b9e33c28.png)

**Comment by shuiping233** [comment]
![QQ图片20200517102259_WPS图片](https://user-images.githubusercontent.com/49360196/82138072-2bed5080-9850-11ea-8f77-3b77b9e33c28.png)

**Comment by shuiping233** [comment]
![Snipaste_2020-09-26_22-13-53](https://user-images.githubusercontent.com/49360196/94342756-d3bc2b80-0045-11eb-8940-01d07eba2261.png)

**Comment by shuiping233** [comment]
H0830测试结果：沙袋还是有显示问题

**Comment by Zero-Fanker** [comment]
不管是偶先还是必现，现在通过技术手段让它稳定。另原先单位从它背后经过也会有问题，本次一并修复了。

**Comment by shuiping233** [comment]
我找机会在测几遍吧

**Comment by Zero-Fanker** [comment]
H1031已修正，请验证。

**Comment by shuiping233** [comment]
![Snipaste_2020-11-07_19-52-34](https://user-images.githubusercontent.com/49360196/98440368-4800e900-2133-11eb-8085-7ad715975fc6.png)
H1031B测试结果：虽然现在围墙不会“穿过”古巴兵营了，但是古巴兵营的显示次序仍然有问题，当光棱塔，心灵控制塔，盟军兵营，苏军机场等其他建筑存在的时候，古巴兵营仍然会出现类似于沙袋这样，有一部分元素“穿过”其他建筑或者其他建筑的元素“穿过”兵营自身
以下为图例：
![Snipaste_2020-11-07_19-44-31](https://user-images.githubusercontent.com/49360196/98440470-e0976900-2133-11eb-940a-179dee6bfc18.png)
![Snipaste_2020-11-07_19-43-44](https://user-images.githubusercontent.com/49360196/98440510-189eac00-2134-11eb-95bd-dad495310e50.png)
![Snipaste_2020-11-07_19-43-02](https://user-images.githubusercontent.com/49360196/98440513-1b999c80-2134-11eb-8f95-22ee1b866653.png)
![Snipaste_2020-11-07_19-42-38](https://user-images.githubusercontent.com/49360196/98440515-1c323300-2134-11eb-91e6-597cc542d351.png)
![Snipaste_2020-11-07_19-41-32](https://user-images.githubusercontent.com/49360196/98440517-1ccac980-2134-11eb-8ac0-1a56729fc4ed.png)
![Snipaste_2020-11-07_19-40-57](https://user-images.githubusercontent.com/49360196/98440519-1d636000-2134-11eb-8e02-113ea6f22f88.png)
![Snipaste_2020-11-07_19-40-13](https://user-images.githubusercontent.com/49360196/98440520-1d636000-2134-11eb-93fc-e86c53598abb.png)

**Comment by shuiping233** [comment]
此issues归档，问题合并到  #404
