### ISSUE TITLE
#Bug#狂兽人建筑内攻击动画可穿透黑幕

### ISSUE THREAD

**Issue by Fantasycho** [Zero-Fanker/RN_All_Issues#351]
【现象】：狂兽人进驻建筑以后，对外开火动画透过黑幕依然看得见
【反馈人】：
【发现版本号】：H0409
【影响范围】：有尤里狂兽人进建筑就会发生。
【产生原因】：

**Comment by Zero-Fanker** [comment]
H1031已修正，请验证。 @shuiping233  @Fantasycho  @yuanbanlao  @Super-StarX  @Renko-ji

**Comment by shuiping233** [comment]
H1031B测试通过
![GIF26](https://user-images.githubusercontent.com/49360196/97805437-17cbcd00-1c91-11eb-92bf-45c5804f280a.gif)
