### ISSUE TITLE
#建议反馈#调整韩国黑鹰战机坠机爆炸效果

### ISSUE THREAD

**Issue by Fantasycho** [Zero-Fanker/RN_All_Issues#352]
【描述】RT，每次黑鹰战机投弹或被击落时，地面会产生一个长时间的燃烧动画，动画虽然还挺美观，但是一直有个动画在那里烧不仅会让电脑卡顿，还会看着很让人精神污染。
【原因】联机掉帧，观感不好，感觉不好。
【期望解决时间】2020年6月

**Comment by Zero-Fanker** [comment]
> 【描述】RT，每次黑鹰战机投弹或被击落时，地面会产生一个长时间的燃烧动画，动画虽然还挺美观，但是一直有个动画在那里烧不仅会让电脑卡顿，还会看着很让人精神污染。
> 【原因】联机掉帧，观感不好，感觉不好。
> 【期望解决时间】2020年6月

效能影响倒是没多少的，现在换用的动画比较小。
那坠落效果改回原版那种好了。

**Comment by Zero-Fanker** [comment]
H1031已修正，请验证。 @shuiping233  @Renko-ji  @Fantasycho

**Comment by shuiping233** [comment]
![GIF35](https://user-images.githubusercontent.com/49360196/98439638-1fc2bb80-212e-11eb-94a3-b668bcd180dd.gif)
H1031B测试结果：现在黑鹰战机坠落爆炸效果为原版效果，测试通过
