### ISSUE TITLE
#Bug#个别地图工程师不能维修水泥高架桥

### ISSUE THREAD

**Issue by 1938611698** [Zero-Fanker/RN_All_Issues#354]
【现象】：淘金热模式地图《华盛顿之战》《双子湖》中有维修小屋的特大水泥高架桥被炸断之后工程师不能进入维修小屋维修，或者能进入小屋，但是无法复原。
【反馈人】：
【发现版本号】：H0409P1
【影响范围】：影响遭遇战、多人联机
【产生原因】：

**Comment by Zero-Fanker** [comment]
由于内测最新版本已经重制了双子湖地图，因此此次调整不包含，重制版的地图理论上不会有问题。

**Comment by Zero-Fanker** [comment]
H1226已调整，请验证。@shuiping233

**Comment by shuiping233** [comment]
I0102测试结果：华盛顿特区和双子湖的所有桥梁均已测试，先现在都能被摧毁和修复。测试通过
