### ISSUE TITLE
#Bug#海豹ifv下掉海豹之后对美国精英空降部队飞机攻击报错

### ISSUE THREAD

**Issue by hndengxin** [Zero-Fanker/RN_All_Issues#357]
【现象】：海豹ifv下掉海豹之后，ifv对美国精英空降小队的运输飞机攻击，会弹窗报错
【反馈人】：
【发现版本号】：H.H0409P1
【影响范围】：遭遇战小队联盟高防御模式
【产生原因】：
[debug.log](https://github.com/Zero-Fanker/RN_All_Issues/files/4677273/debug.log)
[Revenge.log](https://github.com/Zero-Fanker/RN_All_Issues/files/4677282/Revenge.log)

[注释]:例子：
[注释]:【现象】：韩国火炮、洲际导弹的信标可以被超时空传送、铁幕装置影响
[注释]:【反馈人】：永恒_叶
[注释]:【发现版本号】：0.99.F1028A
[注释]:【影响范围】：影响带有AI的对局
[注释]:【产生原因】：AI新机制引入

**Comment by shuiping233** [comment]
不是见过debug文件发开发者邮箱吗？怎么还放这里？下次别放这

**Comment by shuiping233** [comment]
描述有点乱，能再补充操作说明么？

**Comment by hndengxin** [comment]
emm，就是美国精英空降小队的运输飞机把那些小兵放下来之后再起飞，这时候去攻击运输机会弹框报错，无论是什么东西去攻击它都会，我试了ifv，履带车，爱国者飞弹，都会弹，小兵和飞机没试过------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;shuiping&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年5月25日(星期一) 晚上10:30
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;hndengxin&quot;<1410645546@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug#海豹ifv下掉海豹之后对美国精英空降部队飞机攻击报错 (#357)

**Comment by Zero-Fanker** [comment]
首先更新到群测版，其次保证你用的是cncddraw------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;hndengxin&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年5月26日(星期二) 上午8:20
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug#海豹ifv下掉海豹之后对美国精英空降部队飞机攻击报错 (#357)

**Comment by shuiping233** [comment]
H0602测试结果：并未发现该问题，我没法复现

**Comment by shuiping233** [comment]
@hndengxin 我怀疑与 #374 是相同原因，鱼鹰运输机是否砸在建筑上了？

**Comment by Zero-Fanker** [comment]
> @hndengxin 我怀疑此问题与 #374 是相同原因，鱼鹰运输机是否砸在建筑上了？

我也认为是同一个原因，更新最新群测版后跟进一下，如果一周内没有新结论就关闭。

**Comment by Zero-Fanker** [comment]
无进一步信息。
