### ISSUE TITLE
#Bug#尤里战役第二关，只要一用飞碟吸电就报错退出

### ISSUE THREAD

**Issue by alexrmnf** [Zero-Fanker/RN_All_Issues#359]
【现象】：（描述bug现象，越详细越好）
【反馈人】：（如果是自己的帐户可以不填，代他人提交必填）
【发现版本号】：（填写发现问题的版本号标识，你当时用的是哪个就填哪个）
【影响范围】：（填写影响范围，例如影响遭遇战、多人联机、影响通关等）
【产生原因】：（填写你认为的原因，如使用了非官方地图，或者进行了某种操作等，不知道可以不填）

[注释]:例子：
[注释]:【现象】：韩国火炮、洲际导弹的信标可以被超时空传送、铁幕装置影响
[注释]:【反馈人】：永恒_叶
[注释]:【发现版本号】：0.99.F1028A
[注释]:【影响范围】：影响带有AI的对局
[注释]:【产生原因】：AI新机制引入

**Comment by Zero-Fanker** [comment]
请修正格式，否则视为无效。另外更换ddraw，谢谢

**Comment by shuiping233** [comment]
#293 
请把按格式把描述回复到这里

**Comment by shuiping233** [comment]
问题重复，#293 #359 也是指这个问题，所以关闭#359
