### ISSUE TITLE
#Bug#Aircraft类飞行器受到古巴回血buff时，被击落后不能正常坠毁

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#363]
【现象】：Aircraft类飞行器受到古巴回血buff时，被击落后不能正常坠毁，导致飞行时翻滚，飞行中播放醉落的翻滚动画，例如米格和入侵者。同 #513
【反馈人】：UraniumW
【发现版本号】：H0602
【影响范围】：视觉体验
【产生原因】：未知

![gif204](https://user-images.githubusercontent.com/49360196/136681106-9bc99f6a-cf90-42f1-add1-bd8b5084a872.gif)
![gif203](https://user-images.githubusercontent.com/49360196/136681108-79dcaf21-eb38-40ef-b07e-1ef818dbe93c.gif)
![gif202](https://user-images.githubusercontent.com/49360196/136681110-ba8c2005-74b7-4f00-abea-aaa60ec0b6f4.gif)
![gif201](https://user-images.githubusercontent.com/49360196/136681112-25526888-5ab2-4d89-a36c-1ca62c4ea02d.gif)
![gif198压缩1](https://user-images.githubusercontent.com/49360196/136681113-341e5729-5d01-439f-86f1-1078c96d8851.gif)

**Comment by shuiping233** [comment]
![GIF11](https://user-images.githubusercontent.com/49360196/98435569-03635680-210f-11eb-9bc6-97183d40a519.gif)
![GIF10](https://user-images.githubusercontent.com/49360196/98435572-078f7400-210f-11eb-8bc6-bd989e1119f9.gif)

**Comment by shuiping233** [comment]
![gif198压缩1](https://user-images.githubusercontent.com/49360196/136677460-e301cfe8-be9a-4c9c-a32b-790ec92ea80b.gif)
添加证据

**Comment by shuiping233** [comment]
复现方法已找到，已修改描述

**Comment by Zero-Fanker** [comment]
0.99.911a 已修正

**Comment by shuiping233** [comment]
![gif207](https://user-images.githubusercontent.com/49360196/136696679-f01f685e-911b-4944-bf57-ecf673dd9a39.gif)
0.99.911a测试通过

**Comment by shuiping233** [comment]
@klighting444 帮忙归档一下
