### ISSUE TITLE
#建议反馈#【任务地图】生化危机1 前兆 中希望减少防空步兵的数量

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#364]
【描述】建议减少敌人煤球数量
【原因】起源生化一煤球太多了
【期望解决时间】（如果你期望及时得到解决，可以填写期望的日期，选填）
【反馈人】：シ博と旅行する
【版本号】：未知（反馈人没提供）

[注]:不按照格式填写会被视作无效。

**Comment by Zero-Fanker** [comment]
先去把单子验了 Bug是修不完的 ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;shuiping&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月21日(星期天) 下午5:53
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Zero-Fanker/RN_All_Issues] #建议反馈#起源生化一煤球太多了 (#364)

**Comment by shuiping233** [comment]
是那个人的建议啊（笑），我只是提单而已

**Comment by Zero-Fanker** [comment]
以后调整叙述，别用非正式的称呼做标题。
