### ISSUE TITLE
#建议反馈#建议提高雷电轰炸机的坠落伤害

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#365]
【描述】建议提高雷电轰炸机的坠落伤害
【原因】雷电轰炸机的坠落伤害太低
【期望解决时间】下版本公测

[注]:不按照格式填写会被视作无效。

**Comment by Zero-Fanker** [comment]
要多少？ 太高会影响pvp的 ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;shuiping&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月25日(星期四) 中午11:53
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Zero-Fanker/RN_All_Issues] #建议反馈#建议提高雷电轰炸机的坠落伤害 (#365)

**Comment by shuiping233** [comment]
和入侵者的坠落伤害一致吧，我觉得要问kk

**Comment by shuiping233** [comment]
@yuanbanlao

**Comment by yuanbanlao** [comment]
所有飞机的坠落伤害都不再像原版一样，是飞机的用途之一。此问题搁置或者不解决。

**Comment by shuiping233** [comment]
雷电的高伤害炸弹弥补了醉落伤害低，反正不给雷电砸东西也算是好事

**Comment by shuiping233** [comment]
那就维持现状吧
