### ISSUE TITLE
#Bug#【DTA】部分地图在局域网联机下出现非主机无法载入

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#368]
【现象】：DTA客户端内，部分地图在局域网联机下出现非主机无法载入，全息图读取不正常，但单机可以载入
【反馈人】：凌飞月
【发现版本号】：H0704 ， DTA20200627
【影响范围】：联机
【产生原因】：未知

**Comment by mariodad3** [comment]
使用DTA进行联机游戏会出现这种情况，单人遭遇战和局域网单开不会出现问题
0：目前只在选择以【RN】为开头的地图时出现
1：全息图非主机无法正常显示，一律显示为[RN][7]非洲
2：非主机无法正常加载游戏，情况为程序出现后黑屏，主机中其他玩家进度条不动

**Comment by Zero-Fanker** [comment]
那单人情况下，预览全息图都是正常的吗？ ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;mariodad3&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月11日(星期六) 上午9:35
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;Zero Fanker&quot;<zcyfksn@vip.qq.com&gt;;&quot;Assign&quot;<assign@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug#部分地图在局域网联机下出现非主机无法载入 (#368)

**Comment by Zero-Fanker** [comment]
已证实问题存在，由于客户端机制通过hash来查找地图，而RN地图非外置，故无法被找到。已调整逻辑。

**Comment by Zero-Fanker** [comment]
@klighting444  小碗帮我归档到DTA开发的里面。
