### ISSUE TITLE
#Bug#洛林导弹不能炸毁树木

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#370]
【现象】：洛林导弹能对树开火但不能炸毁树木
【反馈人】：shuiping
【发现版本号】：H0704
【影响范围】：操作手感
【产生原因】：未知

[注释]:例子：
[注释]:【现象】：韩国火炮、洲际导弹的信标可以被超时空传送、铁幕装置影响
[注释]:【反馈人】：永恒_叶
[注释]:【发现版本号】：0.99.F1028A
[注释]:【影响范围】：影响带有AI的对局
[注释]:【产生原因】：AI新机制引入

**Comment by Zero-Fanker** [comment]
H1226已调整，请验证。

**Comment by shuiping233** [comment]
![GIF65](https://user-images.githubusercontent.com/49360196/103223686-beff7480-4961-11eb-93ea-9ea219edbbe7.gif)
H1226测试通过，该问题已解决
