### ISSUE TITLE
#Bug#莫名其妙的崩溃

### ISSUE THREAD

**Issue by jtzy000** [Zero-Fanker/RN_All_Issues#372]
在先锋政委靠近伯瑞斯的那一刻发生了崩溃，debug日志已附上
[debug.20200811-090733.log](https://github.com/Zero-Fanker/RN_All_Issues/files/5054667/debug.20200811-090733.log)
[debug.log](https://github.com/Zero-Fanker/RN_All_Issues/files/5054668/debug.log)

**Comment by Zero-Fanker** [comment]
请按照对话框提示提供打包好的压缩包------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;jtzy000&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月11日(星期二) 中午12:01
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Zero-Fanker/RN_All_Issues] #Bug#莫名其妙的崩溃 (#372)

**Comment by Zero-Fanker** [comment]
@shuiping233  确认下这个问题是不是内测修复的飞行器坠毁崩溃问题。

**Comment by shuiping233** [comment]
问题已经无法追溯，鉴于内侧已经修复vxl飞行器问题。现关闭此issue
