### ISSUE TITLE
#Bug#食蚁兽在水上可以碾压潜艇等船只

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#373]
【现象】：食蚁兽在水上可以碾压潜艇等船只，也可以碾压生物（海豚，巨型乌贼）
【反馈人】：948268741
【发现版本号】：H0704
【影响范围】：单位平衡性
【产生原因】：未考虑到此场景
![GIF97](https://user-images.githubusercontent.com/49360196/90131629-06180f00-dd9f-11ea-93bf-c727c7dbf8cd.gif)

[注释]:例子：
[注释]:【现象】：韩国火炮、洲际导弹的信标可以被超时空传送、铁幕装置影响
[注释]:【反馈人】：永恒_叶
[注释]:【发现版本号】：0.99.F1028A
[注释]:【影响范围】：影响带有AI的对局
[注释]:【产生原因】：AI新机制引入

**Comment by shuiping233** [comment]
![GIF97](https://user-images.githubusercontent.com/49360196/90131629-06180f00-dd9f-11ea-93bf-c727c7dbf8cd.gif)

**Comment by shuiping233** [comment]
具体能碾压的单位我找时间统计

**Comment by shuiping233** [comment]
@yuanbanlao

**Comment by yuanbanlao** [comment]
已修复，现在的食蚁兽无法碾压任何舰船。

**Comment by Zero-Fanker** [comment]
H1015已修正，请验证。

**Comment by shuiping233** [comment]
H1015测试结果：食蚁兽不能再碾潜艇等船只了

**Comment by shuiping233** [comment]
有个问题，食蚁兽如果alt潜艇那么会让潜艇现行（敌对潜艇），算不算bug？

**Comment by Zero-Fanker** [comment]
这是另一个我还没解决的现象，且与题述不是同类问题，原版所有敌对舰艇贴身都会导致对方显形。 因此你可以补充在另外一个潜艇被攻击显形的单子里。 ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;shuiping&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月18日(星期天) 晚上9:29
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;Zero Fanker&quot;<zcyfksn@vip.qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug#食蚁兽在水上可以碾压潜艇等船只 (#373)

**Comment by shuiping233** [comment]
那么此issues将归档
