### ISSUE TITLE
#Bug#vxl飞行器在建筑上空被击毁时会导致游戏崩溃

### ISSUE THREAD

**Issue by Dumpling-9** [Zero-Fanker/RN_All_Issues#374]
【现象】：vxl飞行器在建筑上空被击毁时会导致游戏崩溃
例如：击坠移动中的鱼鹰运输机和建筑物占用地格上空的镭射幽浮，还有基佬夫空艇，蜂鸟等飞行单位
【反馈人】：Dumpling-9
【发现版本号】：G1208B，H0409P1，H0704
【影响范围】：有vxl飞行器的对战
【产生原因】：
![QQ截图20200817202553](https://user-images.githubusercontent.com/49360196/90397210-16472b80-e0ca-11ea-94c8-46dd746d881d.png)
![QQ截图20200817202543](https://user-images.githubusercontent.com/49360196/90397215-1810ef00-e0ca-11ea-959a-b6653286d68c.png)

**Comment by shuiping233** [comment]
@Dumpling-9 下次记得写标题

**Comment by shuiping233** [comment]
@Dumpling-9 你说的击毁移动的鱼鹰会崩溃是指在建筑上空击毁还是在空地上击毁？

**Comment by shuiping233** [comment]
@Dumpling-9 既然你是用G1208B,说一下你用什么补丁吧

**Comment by Dumpling-9** [comment]
击毁鱼鹰崩溃只要是移动状态就会崩溃，我用的补丁是“ddrawcompat”文件夹内的补丁

**Comment by shuiping233** [comment]
> 击毁鱼鹰崩溃只要是移动状态就会崩溃，我用的补丁是“ddrawcompat”文件夹内的补丁

好的，我将会准备测试，请使用群文件里的新补丁或者更新到H0409P1再测试一遍

**Comment by Dumpling-9** [comment]
> > 击毁鱼鹰崩溃只要是移动状态就会崩溃，我用的补丁是“ddrawcompat”文件夹内的补丁
> 
> 好的，我将会准备测试，请使用群文件里的新补丁或者更新到H0409P1再测试一遍

**Comment by shuiping233** [comment]
@Dumpling-9  为什么close issues？是有什么错误吗？

**Comment by Dumpling-9** [comment]
抱歉，想继续回答问题时点中close了...另外，G1208B版本使用交流与服务群内提供的ddraw补丁仍有击坠移动状态的鱼鹰坠毁导致游戏崩溃的问题

**Comment by shuiping233** [comment]
> 抱歉，想继续回答问题时点中close了...另外，G1208B版本使用交流与服务群内提供的ddraw补丁仍有击坠移动状态的鱼鹰坠毁导致游戏崩溃的问题

行，我知道了

**Comment by shuiping233** [comment]
H0825联机测试结果：vxl飞行单位在建筑上空击毁不会再崩溃，问题已经解决

**Comment by Zero-Fanker** [comment]
那就归档吧，按H0825------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;shuiping&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月26日(星期三) 晚上10:40
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;Zero Fanker&quot;<zcyfksn@vip.qq.com&gt;;&quot;Assign&quot;<assign@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug#vxl飞行器在建筑上空被击毁时会导致游戏崩溃 (#374)

**Comment by shuiping233** [comment]
好的



---原始邮件---
发件人: "Zero Fanker"<notifications@github.com&gt;
发送时间: 2020年8月26日(星期三) 晚上11:59
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"shuiping"<1944680304@qq.com&gt;;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#vxl飞行器在建筑上空被击毁时会导致游戏崩溃 (#374)




 那就归档吧，按H0825------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;&amp;quot;shuiping&amp;quot;<notifications@github.com&amp;gt; 
 发送时间:&amp;nbsp;2020年8月26日(星期三) 晚上10:40 
 收件人:&amp;nbsp;&amp;quot;Zero-Fanker/RN_All_Issues&amp;quot;<RN_All_Issues@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;&amp;quot;Zero Fanker&amp;quot;<zcyfksn@vip.qq.com&amp;gt;;&amp;quot;Assign&amp;quot;<assign@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug#vxl飞行器在建筑上空被击毁时会导致游戏崩溃 (#374)
