### ISSUE TITLE
#建议反馈#建议取消古巴ai的部署地道技能

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#375]
【描述】取消古巴ai的部署地道技能，或者使用其他替代方案
【原因】如图所示，古巴地道占地3x3，比英国空投碉堡还离谱，ai无限制的丢地道给玩家基地占用了大量的建筑用地并且没什么用处
![QQ图片20200817205311](https://user-images.githubusercontent.com/49360196/90398298-c5383700-e0cb-11ea-9d55-c3344a793af3.png)

【期望解决时间】下版本公测

[注]:不按照格式填写会被视作无效。

**Comment by Zero-Fanker** [comment]
那就暂时先屏蔽吧 @yuanbanlao

**Comment by yuanbanlao** [comment]
个人建议在ai系统里屏蔽这个而不是直接无法使用。

**Comment by Zero-Fanker** [comment]
@shuiping233 H1015已调整，请验证。

**Comment by shuiping233** [comment]
H1015B经过测试：该问题已经解决，ai不在向玩家扔地道了
