### ISSUE TITLE
#Bug#内测DTA客户端问题汇总

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#376]
1：~~DTA的按键设置中并没有电力管理选项，进入游戏才能设置~~（H1015B已解决）
2：~~”更多战役”字样可能不会让玩家认为是选关界面~~ --不管了
3：~~合作模式中加入了一些遭遇战地图，其中莫斯科保卫战缩略图的玩家出生位置有偏移~~ --合作模式已经没有这些图了
4：~~提醒玩家“不能使用特殊符号作为用户名”的窗口是英文~~
5：~~开始战役中点击的盟军图标并不会亮起，选择其他图标反倒是一起亮起，并且按键反馈不太明显~~ #541 
6：~~在DTA客户端中修改游戏分辨率，进入游戏会强制修改分辨率~~（H1015B已解决）
7：~~读取存档时会黑屏好一会，容易让人以为是不是未响应了~~
8：~~使用DTA联机时有较高的指令操作延迟~~（H1015B已解决）
9：~~遭遇战以及联机对战中缺少了一些游戏模式~~（0.99.905a已解决）
10：~~地图列表的排列有些正常有些不正常，原版地图按玩家数由小到大排列，RN前缀地图的排列没有规律~~  （0.99.905a已解决）
11：~~局域网联机最高帧数只有44帧，cnc大厅联机则最高有60帧~~
12：~~客户端的载入存档可以读取旧版本的存档，读取后闪退返回客户端~~ #390
13：~~一些缩略图的视觉效果问题以及文字重叠问题~~ #395 #385
14：~~DTA不太稳定，有时候会崩溃，特别是联机功能部分，疑似和输入法有关~~ --这个应该没了吧
【反馈人】：shuiping
【发现版本号】：DTA客户端H0825
【影响范围】：影响客户端使用体验
【产生原因】：客户端Bug

**Comment by Zero-Fanker** [comment]
第六条是说单人情况下分辨率超过1366x768会触及限制?

**Comment by shuiping233** [comment]
> 第六条是说单人情况下分辨率超过1366x768会触及限制?
我手上虽然有低分辩率屏幕，但是我不清楚低于1366x768会不会有这个问题，这句话的意思是无论在dta如何改分辨率进入游戏后分辨率定死在1366x768

**Comment by Zero-Fanker** [comment]
但事实就是并不存在“无论如何”，我日常测试在1024x768的传统分辨率下无任何问题，所以你去全面试一下再给一个确切的综合性的结论吧     ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;shuiping&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月27日(星期天) 凌晨5:21
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;Zero Fanker&quot;<zcyfksn@vip.qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug#内测DTA客户端问题汇总 (#376)

**Comment by Zero-Fanker** [comment]
我测了一下，1920x1080的分辨率也未遭遇“告警”

**Comment by shuiping233** [comment]
我测试了H1015B版本，强制设置分辨率的问题已经修复了

**Comment by Zero-Fanker** [comment]
OK, 应该是命令行参数传递修复顺带修好的。 ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;shuiping&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月17日(星期六) 晚上9:30
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;Zero Fanker&quot;<zcyfksn@vip.qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug#内测DTA客户端问题汇总 (#376)

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/97779309-25f9ea80-1bb8-11eb-849a-5352d2249205.png)
此图对应描述第五点

**Comment by shuiping233** [comment]
这个单子是否需要归档并且分别新开单子？
