### ISSUE TITLE
#Bug#同时框选两个及以上载具时载具不能部署

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#377]
【现象】：同时框选两个及以上载具时载具不能部署，例如：基地车，核炮
【反馈人】：shuiping
【发现版本号】：H0825
【影响范围】：操作体验
【产生原因】：未知

[注释]:例子：
[注释]:【现象】：韩国火炮、洲际导弹的信标可以被超时空传送、铁幕装置影响
[注释]:【反馈人】：永恒_叶
[注释]:【发现版本号】：0.99.F1028A
[注释]:【影响范围】：影响带有AI的对局
[注释]:【产生原因】：AI新机制引入

**Comment by shuiping233** [comment]
@Zero-Fanker

**Comment by shuiping233** [comment]
我测了一下，H1014版本还存在这个问题

**Comment by shuiping233** [comment]
该问题仅存在与能部署成建筑的载具上，目前发现该问题的单位有：核炮，3方基地车

**Comment by shuiping233** [comment]
修正描述：当可部署变成建筑的单位和其他单位一起被框选时，按下部署（D键）之后可部署变成建筑的单位不能执行指令

**Comment by Zero-Fanker** [comment]
这不原版就这样吗，基地车什么时候能支持热键反部署了？------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月8日(星期二) 中午1:28
***@***.***&gt;;
抄送:&nbsp;&quot;Zero ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug#同时框选两个及以上载具时载具不能部署 (#377)

**Comment by shuiping233** [comment]
不啊，我没说反部署，我倒是可以录个gif

**Comment by shuiping233** [comment]
说人话就是基地车和别的东西框到一起之后使劲d基地车都不部署，就是单独选中基地车才行



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月8日(周二) 中午1:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#同时框选两个及以上载具时载具不能部署 (#377)




 这不原版就这样吗，基地车什么时候能支持热键反部署了？------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 ***@***.***&amp;gt; 
 发送时间:&amp;nbsp;2021年6月8日(星期二) 中午1:28 
 ***@***.***&amp;gt;; 
 抄送:&amp;nbsp;&amp;quot;Zero ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug#同时框选两个及以上载具时载具不能部署 (#377)

**Comment by Zero-Fanker** [comment]
> 

追加验证一下，是当基地车和其它单位被框选在一起时，用部署快捷键时，基地车无法响应指令

**Comment by Zero-Fanker** [comment]
0.99.912a 已调整 @Renko-ji @shuiping233

**Comment by shuiping233** [comment]
0.99.912a测试通过，测试员：咸老师
