### ISSUE TITLE
#建议反馈#RN众载具的size问题

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#378]
【描述】布伦在运输船内占用5个格子，其余载具或许有类似的问题，我建议一次性搞定所有可能出问题的载具的size
【原因】某些载具size不合理会影响到对战
【期望解决时间】尽快

**Comment by shuiping233** [comment]
我有空会测试一遍所有载具，有问题的会提出来

**Comment by shuiping233** [comment]
@yuanbanlao

**Comment by yuanbanlao** [comment]
在改了在改了，正在学ini基础别催

**Comment by yuanbanlao** [comment]
名称/旧数据/新数据
超声波坦克/3/6
时空猎手/5/6
布伦运载车/6/3
极光支援者/5/3
利刃突击艇/6/15
利刃突击艇-部署/6/15
ACS运输车/6/15
亡命冲锋车/5/6
食蚁兽运输车/5/6
烈焰核心/5/6
烈焰核心部署阶段/5/15
烈焰核心自杀阶段/5/15
核炮/3/12
费林斯核堡垒/8/9
潜地突击车/4/15
噬魂者坦克/3/6
战神火炮/3/6

**Comment by yuanbanlao** [comment]
@shuiping233

**Comment by shuiping233** [comment]
新数据没啥问题，就是想问问磁能要塞的size



---原始邮件---
发件人: "yuanbanlao"<notifications@github.com&gt;
发送时间: 2020年9月4日(星期五) 下午2:47
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"shuiping"<1944680304@qq.com&gt;;
主题: Re: [Zero-Fanker/RN_All_Issues] #建议反馈#RN众载具的size问题 (#378)




 
名称/旧数据/新数据
 超声波坦克/3/6
 时空猎手/5/6
 布伦运载车/6/3
 极光支援者/5/3
 利刃突击艇/6/15
 利刃突击艇-部署/6/15
 ACS运输车/6/15
 亡命冲锋车/5/6
 食蚁兽运输车/5/6
 烈焰核心/5/6
 烈焰核心部署阶段/5/15
 烈焰核心自杀阶段/5/15
 核炮/3/12
 费林斯核堡垒/8/9
 潜地突击车/4/15
 噬魂者坦克/3/6
 战神火炮/3/6

**Comment by yuanbanlao** [comment]
6.如果觉得不合理可以改。

**Comment by shuiping233** [comment]
磁能要塞size要是和菲林斯核堡垒一致我就没其他意见了



---原始邮件---
发件人: "yuanbanlao"<notifications@github.com&gt;
发送时间: 2020年9月5日(星期六) 中午1:25
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"shuiping"<1944680304@qq.com&gt;;
主题: Re: [Zero-Fanker/RN_All_Issues] #建议反馈#RN众载具的size问题 (#378)




 
6.如果觉得不合理可以改。

**Comment by Zero-Fanker** [comment]
H1015已修复，请验证。

**Comment by shuiping233** [comment]
烈焰核心部署了我怎么拉进运输船（笑）

**Comment by Zero-Fanker** [comment]
测不了的场景说明一下就行了，只是数据在内部上要统一，例如可能会遭遇德国瓦尔哈拉传送维修的场景。 ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;shuiping&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月18日(星期天) 晚上9:23
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;Zero Fanker&quot;<zcyfksn@vip.qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #建议反馈#RN众载具的size问题 (#378)

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/97080439-dd798480-162d-11eb-8604-806dc5bbf91e.png)
H1015B测试结果如上图

**Comment by shuiping233** [comment]
@yuanbanlao  核炮，菲林斯，喷毒机甲这三个不符合预期，还有我额外测了个条顿，条顿是5格，我觉的既然赤炎坦克都6格那么条顿应该和赤炎一样

**Comment by yuanbanlao** [comment]
条顿，喷毒机甲现已修正，都为6.核炮，费林斯的size数据没有问题，猜测两者因为不是1，2，3，6，15中的任意一个，所以不判定为可进入运输船？

**Comment by shuiping233** [comment]
这不应该，会不会是运输船限制不能进12格的单位？

**Comment by Zero-Fanker** [comment]
> 日牛还有这种机制吗？，会不会是运输船限制不能进12格的单位？

kk注意放开一下运输船的SizeLimit

**Comment by shuiping233** [comment]
H1108测试发现条顿现在不能被瓦尔拉哈传送了，德国载具目前据测试结果看就条顿无法被传送 @yuanbanlao

**Comment by yuanbanlao** [comment]
已修正，瓦尔哈拉sizelimit设置为6.

**Comment by shuiping233** [comment]
> 已修正，瓦尔哈拉sizelimit设置为6.

H1127B瓦尔哈拉仍然不能传送条顿，测试中我发现了另一个6格的盟军载具也不能被传送：超声波坦克

**Comment by shuiping233** [comment]
> 条顿，喷毒机甲现已修正，都为6.核炮，费林斯的size数据没有问题，猜测两者因为不是1，2，3，6，15中的任意一个，所以不判定为可进入运输船？

H1127B：核炮，菲林斯，条顿，喷毒机甲现在可以正常进入三方运输船了

**Comment by shuiping233** [comment]
> 名称/旧数据/新数据
> 超声波坦克/3/6
> 时空猎手/5/6
> 布伦运载车/6/3
> 极光支援者/5/3
> 利刃突击艇/6/15
> 利刃突击艇-部署/6/15
> ACS运输车/6/15
> 亡命冲锋车/5/6
> 食蚁兽运输车/5/6
> 烈焰核心/5/6
> 烈焰核心部署阶段/5/15
> 烈焰核心自杀阶段/5/15
> 核炮/3/12
> 费林斯核堡垒/8/9
> 喷毒机甲/5/6
> 潜地突击车/4/15
> 噬魂者坦克/3/6
> 战神火炮/3/6

超声波坦克和时空猎手能不能被瓦尔哈拉传送要讨论一下吗？@yuanbanlao

**Comment by shuiping233** [comment]
> > 名称/旧数据/新数据
> > 超声波坦克/3/6
> > 时空猎手/5/6
> > 布伦运载车/6/3
> > 极光支援者/5/3
> > 利刃突击艇/6/15
> > 利刃突击艇-部署/6/15
> > ACS运输车/6/15
> > 亡命冲锋车/5/6
> > 食蚁兽运输车/5/6
> > 烈焰核心/5/6
> > 烈焰核心部署阶段/5/15
> > 烈焰核心自杀阶段/5/15
> > 核炮/3/12
> > 费林斯核堡垒/8/9
> > 喷毒机甲/5/6
> > 潜地突击车/4/15
> > 噬魂者坦克/3/6
> > 战神火炮/3/6
> 
> 超声波坦克和时空猎手能不能被瓦尔哈拉传送要讨论一下吗？@yuanbanlao

![image](https://user-images.githubusercontent.com/49360196/101367601-49afff00-38e1-11eb-9507-9756274493c7.png)
@yuanbanlao

**Comment by shuiping233** [comment]
> 已修正，瓦尔哈拉sizelimit设置为6.

![image](https://user-images.githubusercontent.com/49360196/101367660-57658480-38e1-11eb-9bb9-299d6b2bc1d5.png)
@yuanbanlao 你需要重新确认你是否改了瓦尔哈拉的尺寸限制

**Comment by Zero-Fanker** [comment]
H1226再次调整，请验证。

**Comment by shuiping233** [comment]
H1226测试通过，瓦尔哈拉相关问题已经修复
