### ISSUE TITLE
#Bug#【hares】遭遇战读档后ui雷达边框缺失

### ISSUE THREAD

**Issue by xuetianyi** [Zero-Fanker/RN_All_Issues#379]
【现象】：读档遭遇战后，侧边栏的雷达左右边框会变成黑色。如果让雷达失效，然后再生效，就能把边框又刷新回来。战役中没试过。
【发现版本号】：20.01.03.0F0325
【影响范围】：遭遇战

![XNFI{ZLBMAQ3(R% E4N @NV](https://user-images.githubusercontent.com/15405394/93023761-ca819680-f623-11ea-94ea-d29f302b9008.png)

**Comment by Zero-Fanker** [comment]
前两天更新的有问题吗

**Comment by xuetianyi** [comment]
试了，RN没有这个问题。应该不用管了。

**Comment by Zero-Fanker** [comment]
> 试了，RN没有这个问题。应该不用管了。

OK
