### ISSUE TITLE
#Bug# 尤里飞碟吸发电厂的时候把他击落会直接闪退

### ISSUE THREAD

**Issue by SGTAtroriaOkita** [Zero-Fanker/RN_All_Issues#383]
【现象】：（描述bug现象，越详细越好）
【反馈人】：（如果是自己的帐户可以不填，代他人提交必填）
【发现版本号】：（填写发现问题的版本号标识，你当时用的是哪个就填哪个）
【影响范围】：（填写影响范围，例如影响遭遇战、多人联机、影响通关等）
【产生原因】：（填写你认为的原因，如使用了非官方地图，或者进行了某种操作等，不知道可以不填）

[注释]:例子：
[注释]:【现象】：韩国火炮、洲际导弹的信标可以被超时空传送、铁幕装置影响
[注释]:【反馈人】：永恒_叶
[注释]:【发现版本号】：0.99.F1028A
[注释]:【影响范围】：影响带有AI的对局
[注释]:【产生原因】：AI新机制引入

**Comment by shuiping233** [comment]
填清楚信息，版本号要标明字母数字，而不是一个最新版匆匆了事



---原始邮件---
发件人: "SGTAtroriaOkita"<notifications@github.com&gt;
发送时间: 2020年10月1日(星期四) 中午12:43
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Zero-Fanker/RN_All_Issues] #Bug# 尤里飞碟吸发电厂的时候把他击落会直接闪退 (#383)




 
【现象】：（描述bug现象，越详细越好）
 【反馈人】：（如果是自己的帐户可以不填，代他人提交必填）
 【发现版本号】：（填写发现问题的版本号标识，你当时用的是哪个就填哪个）
 【影响范围】：（填写影响范围，例如影响遭遇战、多人联机、影响通关等）
 【产生原因】：（填写你认为的原因，如使用了非官方地图，或者进行了某种操作等，不知道可以不填）

**Comment by shuiping233** [comment]
#347 反馈的是同类问题，如果你的情况属实那么你的版本就不是最新的

**Comment by SGTAtroriaOkita** [comment]
所以说  在哪里才能找到最新版的呢 ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;shuiping&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月1日(星期四) 下午5:11
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;SGTAtroriaOkita&quot;<2500191978@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug# 尤里飞碟吸发电厂的时候把他击落会直接闪退 (#383)

**Comment by shuiping233** [comment]
目前群测最新版本号位H0704P，公测群有更新包



---原始邮件---
发件人: "SGTAtroriaOkita"<notifications@github.com&gt;
发送时间: 2020年10月1日(星期四) 晚上6:03
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"shuiping"<1944680304@qq.com&gt;;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug# 尤里飞碟吸发电厂的时候把他击落会直接闪退 (#383)




 所以说  在哪里才能找到最新版的呢 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;&amp;quot;shuiping&amp;quot;<notifications@github.com&amp;gt; 
 发送时间:&amp;nbsp;2020年10月1日(星期四) 下午5:11 
 收件人:&amp;nbsp;&amp;quot;Zero-Fanker/RN_All_Issues&amp;quot;<RN_All_Issues@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;&amp;quot;SGTAtroriaOkita&amp;quot;<2500191978@qq.com&amp;gt;;&amp;quot;Author&amp;quot;<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug# 尤里飞碟吸发电厂的时候把他击落会直接闪退 (#383)

**Comment by SGTAtroriaOkita** [comment]
那么  我来啦------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;shuiping&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月1日(星期四) 晚上6:04
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;SGTAtroriaOkita&quot;<2500191978@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug# 尤里飞碟吸发电厂的时候把他击落会直接闪退 (#383)

**Comment by SGTAtroriaOkita** [comment]
对了  公测群号是多少呀 ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;shuiping&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月1日(星期四) 晚上6:04
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;SGTAtroriaOkita&quot;<2500191978@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug# 尤里飞碟吸发电厂的时候把他击落会直接闪退 (#383)

**Comment by shuiping233** [comment]
我不提供，你自己找



---原始邮件---
发件人: "SGTAtroriaOkita"<notifications@github.com&gt;
发送时间: 2020年10月1日(星期四) 晚上6:20
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"shuiping"<1944680304@qq.com&gt;;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug# 尤里飞碟吸发电厂的时候把他击落会直接闪退 (#383)




 对了  公测群号是多少呀 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;&amp;quot;shuiping&amp;quot;<notifications@github.com&amp;gt; 
 发送时间:&amp;nbsp;2020年10月1日(星期四) 晚上6:04 
 收件人:&amp;nbsp;&amp;quot;Zero-Fanker/RN_All_Issues&amp;quot;<RN_All_Issues@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;&amp;quot;SGTAtroriaOkita&amp;quot;<2500191978@qq.com&amp;gt;;&amp;quot;Author&amp;quot;<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug# 尤里飞碟吸发电厂的时候把他击落会直接闪退 (#383)

**Comment by Zero-Fanker** [comment]
已解决的问题，且未按照要求填写
