### ISSUE TITLE
#Bug# 盟军老版战役倒数第二关  在海盗左面超时空转换器哪里登录并建造基地  传送过来超时空监狱之后无法归还操作

### ISSUE THREAD

**Issue by SGTAtroriaOkita** [Zero-Fanker/RN_All_Issues#384]
【现象】：选择三个登陆点  我选择了离超时空最近的哪里   之后跳出来两个超时空监狱之后就没法操作了 （鼠标直接丢了）
【反馈人】：（如果是自己的帐户可以不填，代他人提交必填）
【发现版本号】：G1208b
【影响范围】：影响正常通关

[注释]:例子：
[注释]:【现象】：韩国火炮、洲际导弹的信标可以被超时空传送、铁幕装置影响
[注释]:【反馈人】：永恒_叶
[注释]:【发现版本号】：0.99.F1028A
[注释]:【影响范围】：影响带有AI的对局
[注释]:【产生原因】：AI新机制引入

**Comment by shuiping233** [comment]
H0409测试结果：确实存在该问题

**Comment by SGTAtroriaOkita** [comment]
对了&nbsp; 昨天我打的那个版本号是G1208&nbsp; &nbsp;那个黑森林的那个&nbsp; 最新版我没试



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "shuiping"<notifications@github.com&gt;; 
发送时间: 2020年10月2日(星期五) 晚上8:01
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;; 
抄送: "SGT.Artoria Okita"<2500191978@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug# 盟军老版战役倒数第二关  在海盗左面超时空转换器哪里登录并建造基地  传送过来超时空监狱之后无法归还操作 (#384)





 
H0409测试结果：确实存在该问题

**Comment by Zero-Fanker** [comment]
测旧版干啥？ 最新的试过了? ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;shuiping&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月2日(星期五) 晚上8:01
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug# 盟军老版战役倒数第二关  在海盗左面超时空转换器哪里登录并建造基地  传送过来超时空监狱之后无法归还操作 (#384)

**Comment by SGTAtroriaOkita** [comment]
就是盟军g1208的老版战役黑森林那一关   飞行兵一开始就蹲右面那个苏军重生点    把那五个基洛夫  下面数第二个基洛夫打爆     之后游戏直接闪退------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Zero&amp;nbsp;Fanker&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月2日(星期五) 晚上8:13
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;SGTAtroriaOkita&quot;<2500191978@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug# 盟军老版战役倒数第二关  在海盗左面超时空转换器哪里登录并建造基地  传送过来超时空监狱之后无法归还操作 (#384)

**Comment by Zero-Fanker** [comment]
更新到G1208B就没问题了，早就解决了。 ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;SGTAtroriaOkita&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月2日(星期五) 晚上9:07
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;Zero Fanker&quot;<zcyfksn@vip.qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug# 盟军老版战役倒数第二关  在海盗左面超时空转换器哪里登录并建造基地  传送过来超时空监狱之后无法归还操作 (#384)

**Comment by SGTAtroriaOkita** [comment]
ok------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Zero&amp;nbsp;Fanker&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月2日(星期五) 晚上9:12
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;SGTAtroriaOkita&quot;<2500191978@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug# 盟军老版战役倒数第二关  在海盗左面超时空转换器哪里登录并建造基地  传送过来超时空监狱之后无法归还操作 (#384)

**Comment by shuiping233** [comment]
H0830测试完毕，该问题已不存在

**Comment by shuiping233** [comment]
这问题也是第一次提，要归档么

**Comment by Zero-Fanker** [comment]
不需要，不是通过修改解决的都不用。       ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;shuiping&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月6日(星期二) 中午1:32
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;Zero Fanker&quot;<zcyfksn@vip.qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug# 盟军老版战役倒数第二关  在海盗左面超时空转换器哪里登录并建造基地  传送过来超时空监狱之后无法归还操作 (#384)

**Comment by shuiping233** [comment]
了解

**Comment by shuiping233** [comment]
H0830刚刚测了，也是一样的



---原始邮件---
发件人: "Zero Fanker"<notifications@github.com&gt;
发送时间: 2020年10月2日(星期五) 晚上8:13
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"shuiping"<1944680304@qq.com&gt;;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug# 盟军老版战役倒数第二关  在海盗左面超时空转换器哪里登录并建造基地  传送过来超时空监狱之后无法归还操作 (#384)




 测旧版干啥？ 最新的试过了? ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;&amp;quot;shuiping&amp;quot;<notifications@github.com&amp;gt; 
 发送时间:&amp;nbsp;2020年10月2日(星期五) 晚上8:01 
 收件人:&amp;nbsp;&amp;quot;Zero-Fanker/RN_All_Issues&amp;quot;<RN_All_Issues@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;&amp;quot;Subscribed&amp;quot;<subscribed@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug# 盟军老版战役倒数第二关  在海盗左面超时空转换器哪里登录并建造基地  传送过来超时空监狱之后无法归还操作 (#384)
