### ISSUE TITLE
#建议反馈#疾风轰炸机效果改进

### ISSUE THREAD

**Issue by yuanbanlao** [Zero-Fanker/RN_All_Issues#387]
【描述】尤里的轰炸机弹头动画消失的很突兀,建议加一个半透明消失
【原因】星星提的
【期望解决时间】（如果你期望及时得到解决，可以填写期望的日期，选填）

[注]:不按照格式填写会被视作无效。

**Comment by Zero-Fanker** [comment]
半透明消失就不搞了，但是步兵的死亡动画换掉了，精英的动画也换掉了
0.99.912a 已调整 @Renko-ji @shuiping233

**Comment by shuiping233** [comment]
0.99.912a测试通过，测试员：咸老师
