### ISSUE TITLE
#建议反馈#跪请工头增加移动反隐单位

### ISSUE THREAD

**Issue by skywolf404** [Zero-Fanker/RN_All_Issues#389]
【描述】由于个人多次测试1v5，发现问题还是蛮严重的，B2突袭太过imba，但是反隐却只能靠雷达和机场，这明显太过离谱。对玩家也太不公平，海B2足够多（其实两架就够了），在对面还没来得及出足够的反隐建筑时就能偷掉对面。
【原因】原因如上（貌似又打反了？）
【期望解决时间】下个群测可以吗（想桃子）

[注]:不按照格式填写会被视作无效。

**Comment by skywolf404** [comment]
> 【描述】由于个人多次测试1v5，发现问题还是蛮严重的，B2突袭太过imba，但是反隐却只能靠雷达和机场，这明显太过离谱。对玩家也太不公平，海B2足够多（其实两架就够了），在对面还没来得及出足够的反隐建筑时就能偷掉对面。
> 【原因】原因如上（貌似又打反了？）
> 【期望解决时间】下个群测可以吗（想桃子）

个人想法是苏军可以采用一种侦查式的防御建筑（T3），盟军采用移动部署的小车，尤里似乎可以采用心灵侦测小车？ # @shuiping233

**Comment by shuiping233** [comment]
先告诉你，pve不能决定平衡



---原始邮件---
发件人: "極地灰鼠"<notifications@github.com&gt;
发送时间: 2020年10月5日(星期一) 中午12:20
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Zero-Fanker/RN_All_Issues] #建议反馈#跪请工头增加移动反隐单位 (#389)




 
【描述】由于个人多次测试1v5，发现问题还是蛮严重的，B2突袭太过imba，但是反隐却只能靠雷达和机场，这明显太过离谱。对玩家也太不公平，海B2足够多（其实两架就够了），在对面还没来得及出足够的反隐建筑时就能偷掉对面。
 【原因】原因如上（貌似又打反了？）
 【期望解决时间】下个群测可以吗（想桃子）

**Comment by shuiping233** [comment]
防御无人机和空域卫士可以移动



---原始邮件---
发件人: "極地灰鼠"<notifications@github.com&gt;
发送时间: 2020年10月5日(星期一) 中午12:20
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Zero-Fanker/RN_All_Issues] #建议反馈#跪请工头增加移动反隐单位 (#389)




 
【描述】由于个人多次测试1v5，发现问题还是蛮严重的，B2突袭太过imba，但是反隐却只能靠雷达和机场，这明显太过离谱。对玩家也太不公平，海B2足够多（其实两架就够了），在对面还没来得及出足够的反隐建筑时就能偷掉对面。
 【原因】原因如上（貌似又打反了？）
 【期望解决时间】下个群测可以吗（想桃子）

**Comment by skywolf404** [comment]
> 防御无人机和空域卫士可以移动
> […](#)
> ---原始邮件--- 发件人: "極地灰鼠"<notifications@github.com&gt; 发送时间: 2020年10月5日(星期一) 中午12:20 收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [Zero-Fanker/RN_All_Issues] #建议反馈#跪请工头增加移动反隐单位 (#389) 【描述】由于个人多次测试1v5，发现问题还是蛮严重的，B2突袭太过imba，但是反隐却只能靠雷达和机场，这明显太过离谱。对玩家也太不公平，海B2足够多（其实两架就够了），在对面还没来得及出足够的反隐建筑时就能偷掉对面。 【原因】原因如上（貌似又打反了？） 【期望解决时间】下个群测可以吗（想桃子） — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我的意思是小型的支援用车，在T4防空的空隙里填补常规防空（如果说影响平衡可以限制数量）

**Comment by shuiping233** [comment]
@yuanbanlao

**Comment by Zero-Fanker** [comment]
那还要T3、T4防空干什么? ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;極地灰鼠&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月5日(星期一) 中午12:28
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #建议反馈#跪请工头增加移动反隐单位 (#389)

**Comment by yuanbanlao** [comment]
at我干什么，T4防空单位的反隐我又没砍，还是20多的范围
20多的范围pve自带一个+自己出一个完全够用，防空火力你想用t4或者基础防空都可以
pvp的话本来b2就是换东西的

**Comment by yuanbanlao** [comment]
倒不如说，日牛的特色之一就是隐形单位不是绝对隐形而且前期情况下不好解决。

**Comment by Zero-Fanker** [comment]
综上所述，多玩，多理解，多讨论吧
