### ISSUE TITLE
#Bug#中立科技火箭炮的弹道问题

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#394]
【现象】：科技火箭炮的导弹经常会乱飞，当他攻击在斜坡或者悬崖的位置上的敌人时不是导弹转圈就是导弹穿过敌人打不中
【反馈人】：shuiping
【发现版本号】：H1015B
【影响范围】：对战
【产生原因】：未知
![GIF13](https://user-images.githubusercontent.com/49360196/97060180-234e3280-15c5-11eb-9b27-545ec036c18d.gif)
![GIF12](https://user-images.githubusercontent.com/49360196/97060187-26492300-15c5-11eb-959d-c2f3efcf530e.gif)

**Comment by shuiping233** [comment]
![GIF13](https://user-images.githubusercontent.com/49360196/97060180-234e3280-15c5-11eb-9b27-545ec036c18d.gif)
![GIF12](https://user-images.githubusercontent.com/49360196/97060187-26492300-15c5-11eb-959d-c2f3efcf530e.gif)

**Comment by shuiping233** [comment]
![GIF13](https://user-images.githubusercontent.com/49360196/97060229-4973d280-15c5-11eb-86aa-3cc62607dc69.gif)
![GIF12](https://user-images.githubusercontent.com/49360196/97060243-5395d100-15c5-11eb-82bd-effb677c5a30.gif)

**Comment by Zero-Fanker** [comment]
H1127已调整，请验证。

**Comment by shuiping233** [comment]
H1127B测试通过，该问题已经解决
