### ISSUE TITLE
#Bug#客户端中选地图的bug

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#395]
【现象】：1、地图“双峰”的缩略图出生点不正确 √
2、地图“成事在人2”没有缩略图，并且读取地图会导致崩溃√
3、地图“华盛顿之战”的缩略图亮度过低导致无法看清地图
4、地图“暴风天2”的缩略图亮度过低导致无法看清地图
5、地图“双子湖”使用的是旧版本的缩略图 √
6、~~抢地盘模式中，地图“八号死亡港口”的出生点并不在地图中心聚集~~
7、缩略图下方的文字信息太长导致部分文字会叠在一起 √
8、合作模式中加入了一些遭遇战地图，其中莫斯科保卫战缩略图的玩家出生位置有偏移 √

![Snipaste_2020-10-24_14-44-04](https://user-images.githubusercontent.com/49360196/97070240-7fd34100-1609-11eb-943e-9c7a2da1ff7b.png)
![Snipaste_2020-10-24_14-43-42](https://user-images.githubusercontent.com/49360196/97070250-95e10180-1609-11eb-817b-4efa5519c492.png)
![Snipaste_2020-10-24_14-43-20](https://user-images.githubusercontent.com/49360196/97070260-a42f1d80-1609-11eb-97cc-d0aec004df3f.png)
![Snipaste_2020-10-24_14-42-58](https://user-images.githubusercontent.com/49360196/97070261-a7c2a480-1609-11eb-8587-c27e6ee5aa36.png)
![Snipaste_2020-10-24_14-42-10](https://user-images.githubusercontent.com/49360196/97070264-ab562b80-1609-11eb-80bd-f97e335758c5.png)
![Snipaste_2020-10-24_14-39-43](https://user-images.githubusercontent.com/49360196/97070265-ab562b80-1609-11eb-9619-1e1e3d8e7ca4.png)
![Snipaste_2020-10-24_14-43-36](https://user-images.githubusercontent.com/49360196/97070259-a0030000-1609-11eb-9e30-5be7ec33e045.png)

【反馈人】：shuiping
【发现版本号】：H1015B
【影响范围】：视觉体验
【产生原因】：未知

**Comment by shuiping233** [comment]
![Snipaste_2020-10-24_14-44-04](https://user-images.githubusercontent.com/49360196/97070240-7fd34100-1609-11eb-943e-9c7a2da1ff7b.png)
![Snipaste_2020-10-24_14-43-42](https://user-images.githubusercontent.com/49360196/97070250-95e10180-1609-11eb-817b-4efa5519c492.png)
![Snipaste_2020-10-24_14-43-20](https://user-images.githubusercontent.com/49360196/97070260-a42f1d80-1609-11eb-97cc-d0aec004df3f.png)
![Snipaste_2020-10-24_14-42-58](https://user-images.githubusercontent.com/49360196/97070261-a7c2a480-1609-11eb-8587-c27e6ee5aa36.png)
![Snipaste_2020-10-24_14-42-10](https://user-images.githubusercontent.com/49360196/97070264-ab562b80-1609-11eb-80bd-f97e335758c5.png)
![Snipaste_2020-10-24_14-39-43](https://user-images.githubusercontent.com/49360196/97070265-ab562b80-1609-11eb-9619-1e1e3d8e7ca4.png)




![Snipaste_2020-10-24_14-43-36](https://user-images.githubusercontent.com/49360196/97070259-a0030000-1609-11eb-9e30-5be7ec33e045.png)

**Comment by Zero-Fanker** [comment]
第6点无问题，这地图本来就没有专用抢地盘版本。 ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;shuiping&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月24日(星期六) 下午2:59
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Zero-Fanker/RN_All_Issues] #Bug#客户端中选地图的bug (#395)

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/97077771-fb88ba00-1618-11eb-9bff-517c9f718f89.png)
第七点与图一致

**Comment by shuiping233** [comment]
![Snipaste_2020-11-01_19-38-08](https://user-images.githubusercontent.com/49360196/97804194-3b8b1500-1c89-11eb-8384-2a848582df7b.png)
![Snipaste_2020-11-01_19-37-32](https://user-images.githubusercontent.com/49360196/97804196-3f1e9c00-1c89-11eb-9280-027622b4ad4b.png)

H1031B中发现两张一样名字的地图

**Comment by Zero-Fanker** [comment]
把单子拆分一下，未完成的另开，然后这个归档

**Comment by RN-Hydra** [comment]
2、3、4条依然存在问题，暴风天2虽然能看清地图，但预览地图的亮度应该增加

**Comment by Zero-Fanker** [comment]
> 2、3、4条依然存在问题，暴风天2虽然能看清地图，但预览地图的亮度应该增加

“把单子拆分一下，未完成的另开，然后这个归档”
