### ISSUE TITLE
#Bug#裂缝产生器周围存在建筑时会导致奇怪的遮罩问题

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#404]
【现象】：裂缝产生器周围存在建筑时会导致奇怪的遮罩问题，类似于 #349  
【反馈人】：shuiping
【发现版本号】：H1031B
【影响范围】：视觉体验
【产生原因】：未知

![Snipaste_2020-11-07_19-40-13](https://user-images.githubusercontent.com/49360196/98440761-8c8d8400-2135-11eb-97d6-d59684ea3a99.png)
![Snipaste_2020-11-07_19-38-12](https://user-images.githubusercontent.com/49360196/98440763-8eefde00-2135-11eb-9e6d-cb707c9475c8.png)
![Snipaste_2020-11-07_19-37-31](https://user-images.githubusercontent.com/49360196/98440765-8f887480-2135-11eb-9895-7bdac5240610.png)

**Comment by Zero-Fanker** [comment]
H1127 已调整，请验证。

**Comment by shuiping233** [comment]
> H1127 已调整，请验证。

确定修复了吗？H1127的裂缝产生器还是那个样
![Snipaste_2020-12-13_13-06-50](https://user-images.githubusercontent.com/49360196/102003594-30c1a680-3d44-11eb-89a3-08714f5f83cc.png)

**Comment by Zero-Fanker** [comment]
H1226再次调整，请验证。

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/103222686-924a5d80-495f-11eb-9d0b-49b38a7f44ae.png)
![Uploading GIF63.gif…]()

**Comment by Zero-Fanker** [comment]
I0206已调整

**Comment by shuiping233** [comment]
![GIF75](https://user-images.githubusercontent.com/49360196/107213326-2faaae00-6a43-11eb-8b7d-6996bd487bd4.gif)
I0206测试通过，未发现有其他问题
