### ISSUE TITLE
#Bug#寄生类单位攻击后有可能出现循环播放攻击动画

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#405]
【现象】：寄生类单位攻击后有可能出现循环播放攻击动画，并且寄生类单位会消失，例如恐怖机器人和警犬；

如图所示：![GIF37](https://user-images.githubusercontent.com/49360196/98454943-82a36980-21a5-11eb-9ca3-fd1dcf88c7d9.gif)
【反馈人】：shuiping
【发现版本号】：H1031B
【影响范围】：视觉体验
【产生原因】：未知

**Comment by RN-Hydra** [comment]
0.99.905a已验证

**Comment by Zero-Fanker** [comment]
准备归档？
