### ISSUE TITLE
#Bug#磁能坦克不能强制对树木开火

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#406]
【现象】：磁能坦克不能强制对树开火也不能炸毁树木
【反馈人】：shuiping
【发现版本号】：H1031B
【影响范围】：操作手感
【产生原因】：未知

**Comment by Zero-Fanker** [comment]
@yuanbanlao kk怎么看

**Comment by yuanbanlao** [comment]
因为对建筑的弹头比是0？如果不是我干活的话我倾向于修一下

**Comment by Zero-Fanker** [comment]
主要是合理性和必要性角度，确定下有没有必要影响树木。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;yuanbanlao&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月28日(星期六) 下午2:10
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;Zero Fanker&quot;<zcyfksn@vip.qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug#磁能坦克不能强制对树木开火 (#406)

**Comment by shuiping233** [comment]
是否有必要统计所有不能干树的载具？

**Comment by yuanbanlao** [comment]
合理性，建议修，必要性，无所谓 。

**Comment by shuiping233** [comment]
0.99.916a测试通过
![GIF117](https://github.com/user-attachments/assets/96621b56-0ead-4afa-80b9-26f17868e48c)
