### ISSUE TITLE
#建议反馈#反隐音效有点刺耳

### ISSUE THREAD

**Issue by ssKRW** [Zero-Fanker/RN_All_Issues#408]
【描述】反隐音效可以稍微小一点或柔和一点。
或者潜艇的反隐音效改成其他音效
【原因】**海战中**反隐声音过于密集，刺耳
【期望解决时间】

**Comment by shuiping233** [comment]
与#285 描述一致，故关闭此issues

**Comment by ssKRW** [comment]
> 与#285 描述一致，故关闭此issues

啊，不太一样啊。我只是说海战中的问题啊。

**Comment by Zero-Fanker** [comment]
是一回事啊= = 目前反隐形又没有反潜和地面的区分     ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;ssKRW&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月8日(星期天) 下午2:34
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #建议反馈#反隐音效有点刺耳 (#408)
