### ISSUE TITLE
#Bug#潜地突击车从箱子的位置钻出却吃不到箱子

### ISSUE THREAD

**Issue by ssKRW** [Zero-Fanker/RN_All_Issues#413]
【现象】：潜地突击车从地里面钻出来吃不到箱子，平地走能吃到箱子。
【反馈人】：
【发现版本号】：H.G1208C
【影响范围】：遭遇战
【产生原因】：

**Comment by Zero-Fanker** [comment]
@shuiping233 这个问题内测是不是早就解决了？------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;ssKRW&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月14日(星期六) 晚上10:41
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Zero-Fanker/RN_All_Issues] #Bug# (#413)

**Comment by shuiping233** [comment]
> @shuiping233 这个问题内测是不是早就解决了？------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;ssKRW&quot;<notifications@github.com&gt; 发送时间:&nbsp;2020年11月14日(星期六) 晚上10:41 收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;; 抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;; 主题:&nbsp;[Zero-Fanker/RN_All_Issues] #Bug# (#413)

从以前的单子看倒是没有相似描述的，我现在去确认一下

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/99161079-31f1ba80-2729-11eb-9958-0bb9ca35379c.png)


> @shuiping233 这个问题内测是不是早就解决了？------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;ssKRW&quot;<notifications@github.com&gt; 发送时间:&nbsp;2020年11月14日(星期六) 晚上10:41 收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;; 抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;; 主题:&nbsp;[Zero-Fanker/RN_All_Issues] #Bug# (#413)

好吧，并没有修复

**Comment by Zero-Fanker** [comment]
H1226已修复，请验证。

**Comment by shuiping233** [comment]
![GIF64](https://user-images.githubusercontent.com/49360196/103223131-8c08b100-4960-11eb-87d6-a182cdb22021.gif)
H1226测试通过，该问题已解决
