### ISSUE TITLE
#Bug#尤里意念核心破损时的火焰动画位置不合理

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#419]
【现象】：如图所示，意念核心左下的那朵火就像是在烧地板
【反馈人】：shuiping
【发现版本号】：H1127B
【影响范围】：视觉体验
【产生原因】：未知
![GIF51](https://user-images.githubusercontent.com/49360196/100528270-e0135f00-3215-11eb-97df-5f6172c6945f.gif)

**Comment by Zero-Fanker** [comment]
@yuanbanlao  kk这个你搞一下吧

**Comment by yuanbanlao** [comment]
已修正。请验收。

**Comment by Zero-Fanker** [comment]
@NightSkyTS NSTS帮忙看一下 归档版本号按 0.99.912a8

**Comment by NightSkyTS** [comment]
0.99.913a6测试通过
![意念核心](https://user-images.githubusercontent.com/78950858/161471466-b2ff43d3-289f-4484-bd71-92ce80d406b7.gif)
