### ISSUE TITLE
#Bug#地图“黄金国”中有一个科技中立“废墟”

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#424]
【现象】：如图所示：
![Snipaste_2020-12-13_19-32-05](https://user-images.githubusercontent.com/49360196/102014164-9ab36d80-3d8f-11eb-8fc7-426cae4020bb.png)
这个一开始就是一个废墟，我没用工程师修过所以我不知道他是什么
【反馈人】：shuiping
【发现版本号】：H1127B
【影响范围】：遭遇战
【产生原因】：未知

[注释]:例子：
[注释]:【现象】：韩国火炮、洲际导弹的信标可以被超时空传送、铁幕装置影响
[注释]:【反馈人】：永恒_叶
[注释]:【发现版本号】：0.99.F1028A
[注释]:【影响范围】：影响带有AI的对局
[注释]:【产生原因】：AI新机制引入

**Comment by Zero-Fanker** [comment]
用debug指令把坐标标识一下吧

**Comment by shuiping233** [comment]
日，这图里的地图不是黄金国

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/126573430-9913aae9-328e-4c39-b2da-eefec96b0776.png)
地图确认为骑马天堂，不过0.99.905a已经修复此问题

**Comment by shuiping233** [comment]
并且图示防空机枪被摧毁后可以恢复正常

**Comment by shuiping233** [comment]
地图探索过了，并未发现有“废墟”

**Comment by Zero-Fanker** [comment]
> 地图探索过了，并未发现有“废墟”

所以这个到底是不是bug？

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/140615465-0303bf71-a56a-4069-87cc-7dc1b718bfca.png)
图中所示好像是这里，0.99.911a2测试未发现有废墟，故关闭此issue
