### ISSUE TITLE
#Bug#盟军矿石精炼器在基地电力不足时仍然可用，但显示为没有电力的状态

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#426]
【现象】：如图显示
![image](https://user-images.githubusercontent.com/14891010/103173824-834ca800-4898-11eb-88a7-03a7200970d8.png)

【反馈人】：
【发现版本号】：H1226
【影响范围】：影响观感，容易引起功能性误判。
【产生原因】：功能无法受电力影响

**Comment by Zero-Fanker** [comment]
H.I0102已调整，请验证。@shuiping233

**Comment by shuiping233** [comment]
目前是精炼器停电是仍能使用并保持正常状态是吗？

**Comment by Zero-Fanker** [comment]
是的 ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;shuiping&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月6日(星期三) 晚上7:14
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;Zero Fanker&quot;<zcyfksn@vip.qq.com&gt;;&quot;Assign&quot;<assign@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug#盟军矿石精炼器在基地电力不足时仍然可用，但显示为没有电力的状态 (#426)

**Comment by shuiping233** [comment]
![Snipaste_2021-01-06_19-57-19](https://user-images.githubusercontent.com/49360196/103766214-66af2d80-5059-11eb-9675-280a5cfe4c0f.png)
![Snipaste_2021-01-06_19-57-07](https://user-images.githubusercontent.com/49360196/103766232-6e6ed200-5059-11eb-8286-7a887c4b2619.png)
I0102测试通过，该问题已经解决
