### ISSUE TITLE
#建议反馈#建议给幻影添加一个辅助性部署技能

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#427]
【描述】部署cd为30s一次，部署后在身边释放一个与幻影相同血量相同移速相同模型（对敌人而言）属性和真幻影完全相同的假“幻影”，假“幻影”可以正常攻击也可以正常变树，但是攻击无伤害，任何攻击都能这个假“幻影”一次打爆，用于吸引火力，假“幻影”在已方视角有特殊标识与真幻影区分。特别的是假“幻影”免疫辐射，并且不能触发地雷。假“幻影”会在两分钟后自动消失
【原因】幻影作为t3出场率低下，打条顿是去送，天启加强了之后幻影又被吊打，更不可能刚脑车
【期望解决时间】下一版本

**Comment by shuiping233** [comment]
@yuanbanlao

**Comment by yuanbanlao** [comment]
幻影就是打脑车的。没有所谓更不可能。
如果非要加强，不如直接降价。幻影提供的是不装车的便捷和造价的相对低廉（相对于装了ggi造价就要上4000的要塞来说）还有只占一个产能线的优势。而不是花里胡哨的其他东西。

**Comment by Zero-Fanker** [comment]
好，那么kk觉得要不要加强? 还是可以维持现状?------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;yuanbanlao&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月13日(星期三) 中午11:37
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #建议反馈#建议给幻影添加一个辅助性部署技能 (#427)

**Comment by yuanbanlao** [comment]
现在又不是每个阵营都有辐射工兵的状态，其实幻影的天敌已经少了。
加强还是看实战情况吧，当前不知道为什么没有人出幻影，明明是一个还不错的选择。

**Comment by Zero-Fanker** [comment]
那就维持现状呗------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;yuanbanlao&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月13日(星期三) 中午11:49
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;Zero Fanker&quot;<zcyfksn@vip.qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #建议反馈#建议给幻影添加一个辅助性部署技能 (#427)

**Comment by Zero-Fanker** [comment]
@yuanbanlao kk是不是已经有相关的幻影坦克的调整了，那就把这个单子关掉吧

**Comment by shuiping233** [comment]
已关闭
