### ISSUE TITLE
#Bug#充能后的磁暴线圈攻击范围错误

### ISSUE THREAD

**Issue by B-Set** [Zero-Fanker/RN_All_Issues#436]
【现象】：动图演示了磁暴线圈会试图攻击位于特定位置的敌人，但是不会产生攻击的电弧（地图：新苏联第一关）
当目标处于图片中犀牛坦克的位置时BUG就会发生（地图：标准作战模式：圆心（2-8））
![bug](https://user-images.githubusercontent.com/79000292/107845379-ecbb5280-6e15-11eb-9713-897d160a7a49.gif)
![image](https://user-images.githubusercontent.com/79000292/107845512-f7c2b280-6e16-11eb-9cab-0632803d6c93.png)

【发现版本号】：099.902
【影响范围】：所有出现充能磁暴线圈的场合
【产生原因】：可能是磁暴线圈充能武器的范围

**Comment by shuiping233** [comment]
该问题与 #170 描述一致，补充之后关闭此issue
