### ISSUE TITLE
#Bug#步兵同时受到古巴兵营和政委效果影响时，古巴兵营被摧毁可能导致崩溃

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#439]
【现象】：如标题所述，由玩家提供的crashdump分析得出。
【反馈人】：（如果是自己的帐户可以不填，代他人提交必填）
【发现版本号】：0.99.902
【影响范围】：含有古巴的对局
【产生原因】：该问题主要是古巴士气加成AE引起，AE的产生方被消灭且士气加成仍然存在时。

**Comment by Zero-Fanker** [comment]
经分析，该问题是单位被摧毁时未正确更新AE的Invoker指针所致。是AE逻辑和InvalidatePointer逻辑调整时引起的缺陷。

**Comment by Zero-Fanker** [comment]
0.99.90.3a 已修复，请验证  @shuiping233

**Comment by shuiping233** [comment]
0.99.903a2无法再次复现该问题，现归档
