### ISSUE TITLE
#建议反馈#【Cncnet客户端】由于版本更新导致旧版存档无法被支持，但是客户端仍然能选择加载旧版存档

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#440]
【描述】需要标识并禁止加载不兼容的存档，允许清理删除旧版存档。
【原因】不兼容存档加载导致程序崩溃。
【期望解决时间】正常开发速度

**Comment by Zero-Fanker** [comment]
![image](https://user-images.githubusercontent.com/14891010/108724128-f5233400-755f-11eb-9fbc-41eaeeb9ba65.png)

**Comment by Zero-Fanker** [comment]
@shuiping233 0.99.904a已经正式支持

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/123544456-f078c180-d785-11eb-813c-b7bce2d31099.png)
0.99.904a2测试通过
