### ISSUE TITLE
#Bug#对空类机枪武器攻击伞兵时有概率无法正确命中伞兵

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#441]
【现象】：对空类机枪武器攻击伞兵时有概率无法正确命中伞兵，更具体的触发条件待测
【反馈人】：shuiping
【发现版本号】：0.99.902
【影响范围】：遭遇战
【产生原因】：未知

**Comment by Zero-Fanker** [comment]
这个本来就没法保证啊，既然引入实体弹道了就是这么回事。

**Comment by shuiping233** [comment]
这个是我没描述清楚，是攻击伞兵的机枪武器有时候完全打不中伞兵

**Comment by shuiping233** [comment]
具体表现是子弹全部像光线一样飞出屏幕外了

**Comment by Renko-ji** [comment]
0.99.911a3测试结果，此现象打十发才会空一发，在工头描述的正常范围内

**Comment by shuiping233** [comment]
#766

**Comment by Zero-Fanker** [comment]
> #766

@shuiping233 所以现在这个到底是怎么说？你关联的单子和这个没关系啊

**Comment by shuiping233** [comment]
由于 #766 和此issue描述的是相同的问题，且后续跟进内容全在 #766 上，所以归档 #766 而关闭此issue
