### ISSUE TITLE
#Bug#瓦尔哈拉传送移动中的单位导致单元格被永久占据

### ISSUE THREAD

**Issue by xuetianyi** [Zero-Fanker/RN_All_Issues#444]
【现象】：实际上是Abductor=yes的武器均存在此bug，不局限于瓦尔哈拉。
当用Abductor类武器攻击时，目标如果处于行进状态，目标在被吸入后，脚下的格子会形成残留，表面上看什么也没有，但是会占用建筑面积，也会阻挡其它单位的行进路线。
目标在被吸入时，就算它被加上了移动速度降低为0的AE，只要他正在企图执行移动指令，都会引发此bug，尽管他并没能移动分毫距离。
目标在完全站立状态时被吸入，则不会出现bug，开火状态时也没事。
【发现版本号】：0.99.902
【影响范围】：遭遇战、多人联机、战役
【产生原因】：未知

**Comment by Zero-Fanker** [comment]
0.99.903a已修复，请验证@shuiping233

**Comment by shuiping233** [comment]
0.99.903a2测试通过
