### ISSUE TITLE
#Bug#尤里复制中心会帮助美国复制工厂补充产能

### ISSUE THREAD

**Issue by yuanbanlao** [Zero-Fanker/RN_All_Issues#445]
【现象】：复制工厂出坦克有限制，没憋出来的会从复制中心冒出来
【反馈人】：星星
【发现版本号】：内测0.99.9，所以公测一定有）
【影响范围】：（填写影响范围，例如影响遭遇战、多人联机、影响通关等）
【产生原因】：（填写你认为的原因，如使用了非官方地图，或者进行了某种操作等，不知道可以不填）

[注释]:例子：
[注释]:【现象】：韩国火炮、洲际导弹的信标可以被超时空传送、铁幕装置影响
[注释]:【反馈人】：永恒_叶
[注释]:【发现版本号】：0.99.F1028A
[注释]:【影响范围】：影响带有AI的对局
[注释]:【产生原因】：AI新机制引入

**Comment by shuiping233** [comment]
我去测一测



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月28日(周日) 中午11:19
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Zero-Fanker/RN_All_Issues] #Bug#尤里复制中心会帮助美国复制工厂补充产能 (#445)




 
【现象】：复制工厂出坦克有限制，没憋出来的会从复制中心冒出来
 【反馈人】：星星
 【发现版本号】：内测0.99.9，所以公测一定有）
 【影响范围】：（填写影响范围，例如影响遭遇战、多人联机、影响通关等）
 【产生原因】：（填写你认为的原因，如使用了非官方地图，或者进行了某种操作等，不知道可以不填）

**Comment by Zero-Fanker** [comment]
> 我去测一测

确认了吗

**Comment by Zero-Fanker** [comment]
OK我已经证实了，做了修复，近期更新。

**Comment by Zero-Fanker** [comment]
0.99.903a 已修复，请验证 @shuiping233 @yuanbanlao

**Comment by shuiping233** [comment]
![Snipaste_2021-04-15_23-32-38](https://user-images.githubusercontent.com/49360196/114896441-eb70cb00-9e42-11eb-80e4-5030ccb85fda.png)
![Snipaste_2021-04-15_23-31-45](https://user-images.githubusercontent.com/49360196/114896454-ee6bbb80-9e42-11eb-969b-ed9ecde9ab2f.png)
0.99.903a1测试通过，问题已修复
