### ISSUE TITLE
#Bug#三星基洛夫空艇能在部署的铁幕消失前投放炸弹

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#447]
【现象】：三星基洛夫空艇能在部署的铁幕消失前投放炸弹
【反馈人】：半世风华（1410645546）
【发现版本号】：0.99.902
【影响范围】：（填写影响范围，例如影响遭遇战、多人联机、影响通关等）
【产生原因】：未知
![GIF78](https://user-images.githubusercontent.com/49360196/113168817-98f6b280-9277-11eb-8196-39585e11d82f.gif)
![GIF77](https://user-images.githubusercontent.com/49360196/113168837-9bf1a300-9277-11eb-913c-d579a75956c4.gif)

**Comment by Zero-Fanker** [comment]
***@***.*** kk你觉得呢------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年3月31日(星期三) 晚上11:20
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Zero-Fanker/RN_All_Issues] #Bug#三星基洛夫空艇能在部署的铁幕消失前投放炸弹 (#447)

**Comment by yuanbanlao** [comment]
如果是bug那就修。

**Comment by Zero-Fanker** [comment]
我觉得不是bug，精英级能提早一点投弹，我最开始设计的时候就知道，特意保留的 ------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月13日(星期二) 中午12:57
***@***.***&gt;;
抄送:&nbsp;&quot;Zero ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug#三星基洛夫空艇能在部署的铁幕消失前投放炸弹 (#447)

**Comment by shuiping233** [comment]
那就是视觉效果的问题嘛

**Comment by shuiping233** [comment]
好吧不是问题，那我close了？
