### ISSUE TITLE
#Bug#深海屠戮模式下尤里工程师下海模型会消失

### ISSUE THREAD

**Issue by NightSkyTS** [Zero-Fanker/RN_All_Issues#449]
【现象】：深海屠戮模式下尤里工程师下海模型会消失
【发现版本号】：0.99.902
【影响范围】：遭遇战 深海屠戮模式
![1](https://user-images.githubusercontent.com/78950858/113426988-d178c680-9406-11eb-9ff7-f66e24dc8933.gif)

**Comment by Zero-Fanker** [comment]
0.99.906已修复 @shuiping233

**Comment by shuiping233** [comment]
![gif152](https://user-images.githubusercontent.com/49360196/130320520-cf9a7656-308d-4a23-84cf-2ab15a06a43e.gif)
0.99.906a3测试通过
