### ISSUE TITLE
#Bug##群测##旧TR任务尤里第一关，玩家可以通过心灵控制鱼鹰运输机，快速完成目标一，二，同时任务四无法达成

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#45]
Zoa Holic created an issue 2018-10-14
【现象】1. 任务一二可以用被控制的鱼鹰直接运步兵进心灵隔离室完成
2. 任务四的心灵信标部署后美军没有被控制，无法完成后面的任务
【影响范围】尤里第一关，第一第二第四任务。
【产生原因】新加的鱼鹰运输机，心灵信标不起作用

**Comment by shuiping233** [comment]
Zoa Holic REPORTER
edited description
2018-10-14
 Zero Fanker
assigned issue to   Zero Fanker
edited description
2018-10-14
 Zero Fanker
changed status to resolved
问题原因已经找到，现在已经修复，测试通过。
