### ISSUE TITLE
#Bug#英国利刃突击艇生产的机器人在特定情况下不会自动销毁

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#450]
【现象】：英国利刃突击艇生产的机器人在特定情况下不会自动销毁，触发条件未知
【反馈人】：终结者prc（QQ：2226599527）
【发现版本号】：0.99.902
【影响范围】：对战中
【产生原因】：未知

[SAVE2748.zip](https://github.com/Zero-Fanker/RN_All_Issues/files/6290040/SAVE2748.zip)

**Comment by Zero-Fanker** [comment]
原因不明，概率低，故优先级降低

**Comment by Zero-Fanker** [comment]
目前怀疑是以前AE机制的问题，多重AE可能导致该问题，例如遇到气象塔的AE，需要重新验证

**Comment by shuiping233** [comment]
0.99.914a2无法复现此问题。已尝试让利刃机器人受到气象塔的减速AE效果，但是未能复现问题情景
故关闭此issues

**Comment by Zero-Fanker** [comment]
其实我推测可能和之前V3减速效果以及错误的AE叠加逻辑处理有关系，可以再观察一下有古巴宣传车、T4心控抑制效果、V3减速等综合作用下的反应
