### ISSUE TITLE
#Bug#部分建筑图像不能正确刷新

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#455]
【现象】：0.99.903a2中部分带平台的建筑图像会经常性的消失一部分，常见于生产建筑，部分建筑尤为明显，玩家视角离开建筑后视角再移动回建筑上则会触发此问题
以盟军维修厂，尤里坦克碉堡最为严重，建筑图像有可能完全消失
其余的部分生产建筑的图像有可能缺一个角，如下图所示
【反馈人】：shuiping233
【发现版本号】：0.99.903a2
【影响范围】：视觉体验
【产生原因】：建筑图像轮廓算法修改导致问题，建造动画和本体尺寸不一致导致
![Snipaste_2021-05-04_11-02-07](https://user-images.githubusercontent.com/49360196/116957729-2b510280-accb-11eb-90a1-e59e412d7b65.png)
![Snipaste_2021-05-04_11-01-56](https://user-images.githubusercontent.com/49360196/116957735-2e4bf300-accb-11eb-9339-ef2cd1193362.png)
![Snipaste_2021-05-04_10-58-40](https://user-images.githubusercontent.com/49360196/116957736-2ee48980-accb-11eb-9fe1-df461e4cb72e.png)
![Snipaste_2021-05-04_10-58-02](https://user-images.githubusercontent.com/49360196/116957737-2f7d2000-accb-11eb-88de-311a11326fff.png)
![Snipaste_2021-05-04_10-57-48](https://user-images.githubusercontent.com/49360196/116957739-3015b680-accb-11eb-886d-81dca82ccce0.png)

![Snipaste_2021-05-04_11-02-02](https://user-images.githubusercontent.com/49360196/116957733-2d1ac600-accb-11eb-800a-07780dbbcb43.png)
![Snipaste_2021-05-04_11-01-59](https://user-images.githubusercontent.com/49360196/116957734-2db35c80-accb-11eb-9e93-b4a85a7d6444.png)

![Snipaste_2021-04-18_20-14-55](https://user-images.githubusercontent.com/49360196/116957894-a4e8f080-accb-11eb-9b2d-6eb9d0820d24.png)
![Snipaste_2021-04-18_14-56-56](https://user-images.githubusercontent.com/49360196/116957948-b631fd00-accb-11eb-887c-d5148ac24cfd.png)

**Comment by shuiping233** [comment]
![Snipaste_2021-04-18_20-14-55](https://user-images.githubusercontent.com/49360196/116957894-a4e8f080-accb-11eb-9b2d-6eb9d0820d24.png)

**Comment by shuiping233** [comment]
![Snipaste_2021-04-18_14-56-56](https://user-images.githubusercontent.com/49360196/116957948-b631fd00-accb-11eb-887c-d5148ac24cfd.png)

**Comment by shuiping233** [comment]
![Snipaste_2021-06-20_21-38-01](https://user-images.githubusercontent.com/49360196/123281810-8f11e200-d53c-11eb-9b9a-5ac4bcc421bb.png)
![Snipaste_2021-06-20_21-37-54](https://user-images.githubusercontent.com/49360196/123281818-90dba580-d53c-11eb-996c-80f673d98a08.png)

**Comment by Zero-Fanker** [comment]
0.99.904a2 已修正

**Comment by shuiping233** [comment]
0.99.904a2测试通过，该问题已解决

**Comment by shuiping233** [comment]
![Snipaste_2021-06-27_20-34-34](https://user-images.githubusercontent.com/49360196/123544826-b9a3ab00-d787-11eb-9a54-2bf8e113050c.png)
目前测试到回收尤里围墙还有图像残留

**Comment by shuiping233** [comment]
测试通过，变卖围墙视觉问题单子另开
