### ISSUE TITLE
#Bug#古巴占领秘密实验室无法获得巨炮

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#456]
【现象】：古巴占领秘密实验室也无法获得巨炮
【反馈人】：shuiping233
【发现版本号】：0.99.902
【影响范围】：遭遇战
【产生原因】：未知

**Comment by shuiping233** [comment]
#101

**Comment by Zero-Fanker** [comment]
0.99.904a 已修复，请验证

**Comment by shuiping233** [comment]
![Snipaste_2021-06-22_22-55-23](https://user-images.githubusercontent.com/49360196/123002942-13e9e800-d3e5-11eb-893a-96153348512a.png)
0.99.904a测试通过
