### ISSUE TITLE
#Bug#DTA的遭遇战中没有淘金热模式

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#459]
【现象】：DTA的遭遇战中没有淘金热模式，如图：
![image](https://user-images.githubusercontent.com/49360196/120109062-66473880-c19a-11eb-8bcf-118c33eb6743.png)

【反馈人】：shuiping233
【发现版本号】：0.99.903a
【影响范围】：遭遇战
【产生原因】：未知

**Comment by Zero-Fanker** [comment]
@xuetianyi xty看下是不是漏了

**Comment by Zero-Fanker** [comment]
0.99.905a已修正，注意客户端单独归档

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/126859781-55af37d5-7c30-418f-aef6-4b9c5bfcac81.png)
0.99.905a4测试通过
