### ISSUE TITLE
#Bug#盟军第一关卡关

### ISSUE THREAD

**Issue by Suli1337** [Zero-Fanker/RN_All_Issues#460]
【现象】：盟军第一关在复制中心区域发生暴动后不再有新的剧情触发
【反馈人】：Suli
【发现版本号】：0.99.903a2 - I0608
【影响范围】：战役
【产生原因】：个人认为是AI问题，触发应该不可能有问题
![QQ图片20210610233831](https://user-images.githubusercontent.com/85695579/121555205-628e9e00-ca45-11eb-9f7f-312bef6f520e.png)

**Comment by Zero-Fanker** [comment]
已确认是临时补丁触发条件读取逻辑问题，已修正。

**Comment by Suli1337** [comment]
> 已确认是临时补丁触发条件读取逻辑问题，已修正。

I0611测试通过
