### ISSUE TITLE
#Bug#磁暴步兵不能攻击树木

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#462]
【现象】：磁暴步兵不能攻击树木
【反馈人】：74
【发现版本号】：0.99.903a2 - I0611
【影响范围】：单位手感
【产生原因】：未知

**Comment by Zero-Fanker** [comment]
@yuanbanlao

**Comment by shuiping233** [comment]
不用等kk了，kk之前说过这太弱智



---原始邮件---
发件人: "Zero ***@***.***&gt;
发送时间: 2021年6月24日(周四) 凌晨0:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#磁暴步兵不能攻击树木 (#462)




 
@yuanbanlao

**Comment by Zero-Fanker** [comment]
kk说这个比较难改，晚点我看了再说

**Comment by yuanbanlao** [comment]
这个我还在等看了再说。

**Comment by Zero-Fanker** [comment]
@shuiping233 @kk7k7k558 @Renko-ji @Crossfield-ClassDestroyer   0.99.916a 已包含

**Comment by yuanbanlao** [comment]
0.99.916a已测试，bug已解决，磁暴步兵可以正常攻击并摧毁树木。然后是不是可以直接关了？我忘了

**Comment by Zero-Fanker** [comment]
要归档 可以让shuiping弄 暂时还没有github action自动归档



---Original---
From: ***@***.***&gt;
Sent at: 2024年10月10日(Thu) AM8:40
To: ***@***.***&gt;;
Cc: "Zero ***@***.******@***.***&gt;;
Subject: Re: [Zero-Fanker/RN_All_Issues] #Bug#磁暴步兵不能攻击树木 (#462)




 
0.99.916a已测试，bug已解决，磁暴步兵可以正常攻击并摧毁树木。然后是不是可以直接关了？我忘了
