### ISSUE TITLE
#Bug#部署后的灰熊坦克没有图片

### ISSUE THREAD

**Issue by yuanbanlao** [Zero-Fanker/RN_All_Issues#463]
【现象】：部署后的灰熊坦克没有图片。透明的，可以开炮，一切正常。
【反馈人】：（如果是自己的帐户可以不填，代他人提交必填）
【发现版本号】：内测0.99.903a2
【影响范围】：游戏
【产生原因】：不知道

[注释]:例子：
[注释]:【现象】：韩国火炮、洲际导弹的信标可以被超时空传送、铁幕装置影响
[注释]:【反馈人】：永恒_叶
[注释]:【发现版本号】：0.99.F1028A
[注释]:【影响范围】：影响带有AI的对局
[注释]:【产生原因】：AI新机制引入

**Comment by shuiping233** [comment]
来个截图，我没发现有问题来着

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/122426112-911af480-cfc2-11eb-9134-9de99d683f0f.png)

**Comment by Zero-Fanker** [comment]
自己重新安装和更新
