### ISSUE TITLE
#Bug#玩家不能对钻矿设备进行电力管理，但是AI可以

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#464]
【现象】：玩家不能对钻矿设备进行电力管理，但是ai可以，导致ai关闭钻矿设备后，玩家占领钻矿设备后再次无法启动它
【反馈人】：shuiping233
【发现版本号】：0.99.903a2（I0618）
【影响范围】：遭遇战
【产生原因】：未知

![Snipaste_2021-06-19_20-44-52](https://user-images.githubusercontent.com/49360196/122662477-db1ff800-d1c5-11eb-9fc2-a8578c846bc6.png)

**Comment by Zero-Fanker** [comment]
这个现在还是这样吗

**Comment by shuiping233** [comment]
是，玩家依旧无法手动关闭钻矿设备



---原始邮件---
发件人: "Zero ***@***.***&gt;
发送时间: 2021年9月29日(周三) 晚上11:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#玩家不能对钻矿设备进行电力管理，但是ai可以 (#464)




 
这个现在还是这样吗
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Zero-Fanker** [comment]
已调整，现在人类玩家也可以正常关闭这个建筑。并且，视觉效果上做了微调，未工作状态的钻矿设备将不播放动画：
![image](https://github.com/user-attachments/assets/ecef6c24-d9a4-40b4-95b2-36139d700f09)

**Comment by Zero-Fanker** [comment]
@shuiping233 @kk7k7k558 @Renko-ji @Crossfield-ClassDestroyer   0.99.916a 已包含

**Comment by shuiping233** [comment]
0.99.916a测试通过，现在玩家可以通过电力管理按钮关闭钻矿设备了
![GIF116](https://github.com/user-attachments/assets/468f0d68-29e5-496e-af42-634c99c46737)
