### ISSUE TITLE
#Bug#空军无法在高架桥上攻击高架桥上的敌人

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#465]
【现象】：空中单位（如基洛夫、飞行兵、入侵者战机等）在桥梁上方时，无法对桥梁上的目标开火。
而且，如果桥下是陆地，无法对桥面开火。如果桥下是水，则可以对桥面开火。
只有高架桥会有此bug，地面桥梁正常。
【反馈人】：xty @xuetianyi 
【发现版本号】：0.99.902
【影响范围】：飞行单位在桥正上方攻击桥上目标
【产生原因】：目标判定逻辑缺陷

![tmp167](https://user-images.githubusercontent.com/15405394/122661170-11577a80-d1ba-11eb-9c86-5fda85f5da25.gif)

![tmp168](https://user-images.githubusercontent.com/15405394/122661206-42d04600-d1ba-11eb-8559-8b4f329e375b.gif)

![tmp169](https://user-images.githubusercontent.com/15405394/122661208-495ebd80-d1ba-11eb-81cf-5cee3e415e20.gif)

**Comment by Zero-Fanker** [comment]
不能打桥面单位解决了，需要看看为啥s没反应。

**Comment by xuetianyi** [comment]
进展神速


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Zero Fanker ***@***.***&gt;
发送时间: 2021年6月22日 22:13
收件人: Zero-Fanker/RN_All_Issues ***@***.***&gt;
抄送: xuetianyi ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[Zero-Fanker/RN_All_Issues] #Bug#空军无法在高架桥上攻击高架桥上的敌人 (#465)





 
不能打桥面单位解决了，需要看看为啥s没反应。

**Comment by Zero-Fanker** [comment]
0.99.904a1 已修正 @shuiping233

**Comment by shuiping233** [comment]
![GIF101](https://user-images.githubusercontent.com/49360196/123542358-d0dc9b80-d77b-11eb-84a0-fcc84c46bb5e.gif)
0.99.904a2测试结果：在路地上高架桥的基佬夫可以攻击高架桥上的单位了，但是基佬夫强制攻击高架桥地板则不能开火

**Comment by shuiping233** [comment]
![GIF103](https://user-images.githubusercontent.com/49360196/123542760-fb2f5880-d77d-11eb-9f63-f1f371caa275.gif)
海上高架桥则完全无问题，基佬夫可以攻击高架桥地板

**Comment by Zero-Fanker** [comment]
> ![GIF101](https://user-images.githubusercontent.com/49360196/123542358-d0dc9b80-d77b-11eb-84a0-fcc84c46bb5e.gif)
> 0.99.904a2测试结果：在路地上高架桥的基佬夫可以攻击高架桥上的单位了，但是基佬夫强制攻击高架桥地板则不能开火

测了下这个是原版bug
![image](https://user-images.githubusercontent.com/14891010/123983686-a5191a00-d9f6-11eb-82b9-3a79acfd90a8.png)

**Comment by shuiping233** [comment]
那先归档？

**Comment by Zero-Fanker** [comment]
归档，然后不能攻击陆地高架的bug另外写一个单子------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月4日(星期天) 晚上9:34
***@***.***&gt;;
抄送:&nbsp;&quot;Zero ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug#空军无法在高架桥上攻击高架桥上的敌人 (#465)

**Comment by shuiping233** [comment]
新单子在 #478，现归档
