### ISSUE TITLE
#Bug#【Cncnet客户端】启动游戏时不检查玩家最大人数

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#467]
【现象】：客户端启动游戏时部分地图不检查玩家最大人数限制，若有大于地图容纳位置数量的玩家或ai时启动游戏则会导致游戏进程无法正常启动读取地图
【反馈人】：shuiping233
【发现版本号】：0.99.904a
【影响范围】：游戏体验
【产生原因】：rampstring默认不检查最大人数
![Snipaste_2021-06-23_23-15-28](https://user-images.githubusercontent.com/49360196/123125254-ee0f2280-d47a-11eb-9212-cc4c52917c77.png)

**Comment by shuiping233** [comment]
@Zero-Fanker

**Comment by Zero-Fanker** [comment]
0.99.904a2 已修正

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/123541803-e603fb00-d778-11eb-9172-d3533da7c266.png)

**Comment by shuiping233** [comment]
0.99.904a测试通过，该问题已解决

**Comment by shuiping233** [comment]
![Snipaste_2021-06-27_18-52-27](https://user-images.githubusercontent.com/49360196/123541854-08961400-d779-11eb-981a-5bcf4d77f51b.png)
