### ISSUE TITLE
#Bug#【cncnet客户端】在使用CNCNET联机时，玩家创建房间不带密码会导致其他用户进入房间时显示：密码错误无法进入

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#472]
【现象】：在使用CNCNET联机时，玩家创建房间不带密码会导致其他用户进入房间时显示：密码错误无法进入
【反馈人】：shuiping233
【发现版本号】：0.99.904a2
【影响范围】：联机体验
【产生原因】：未知

**Comment by shuiping233** [comment]
@Zero-Fanker

**Comment by Zero-Fanker** [comment]
前缀统一用cncnet客户端吧

**Comment by Zero-Fanker** [comment]
0.99.904a3已修复
