### ISSUE TITLE
#Bug#【cncnet客户端】局域网联机时若有观察者则可能导致某位玩家FE

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#473]
【现象】：局域网联机时若有观察者则可能导致某位玩家FE
【反馈人】：shuiping233
【发现版本号】：0.99.904a2
【影响范围】：联机
【产生原因】：74猜可能是观察者随机到了玩家的位置上，导致正常玩家的位置被观察者顶替

**Comment by Zero-Fanker** [comment]
0.99.904a3 已调整，请验证
