### ISSUE TITLE
#Bug#核子地毯式轰炸机的投弹提前量过高

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#474]
【现象】：核子地毯式轰炸机的投弹提前量过高，导致其直接攻击建筑无法炸毁其本来应该炸毁的建造
【反馈人】：shuiping233
【发现版本号】：0.99.904a2
【影响范围】：单位手感
【产生原因】：未知

**Comment by yuanbanlao** [comment]
提前投弹是为了增加操作量。相对于其他两家的t4轰炸机，图55的轰炸效果既持续也强大。在能够近乎决定性毁灭装甲部队的前提下，炸毁建筑物理应需要一点操作。
