### ISSUE TITLE
#Bug#狙击观察员能以智能炸弹作为投放炸弹的目标

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#475]
【现象】：狙击观察员能以智能炸弹作为投放炸弹的目标 ，英国就可以借此轻松刷出一堆智能炸弹当地雷用了
【反馈人】：74
【发现版本号】：0.99.904a2
【影响范围】：PVP
【产生原因】：未考虑到该场景

[注释]:例子：
[注释]:【现象】：韩国火炮、洲际导弹的信标可以被超时空传送、铁幕装置影响
[注释]:【反馈人】：永恒_叶
[注释]:【发现版本号】：0.99.F1028A
[注释]:【影响范围】：影响带有AI的对局
[注释]:【产生原因】：AI新机制引入

**Comment by Zero-Fanker** [comment]
@yuanbanlao kk修一下

**Comment by yuanbanlao** [comment]
已修复。现在观察手对空投智能炸弹和空投单兵碉堡都只会使用威力很低的机枪。

**Comment by Zero-Fanker** [comment]
0.99.912a 已调整 @Renko-ji @shuiping233

**Comment by shuiping233** [comment]
0.99.912a测试通过，测试员：suli
