### ISSUE TITLE
#Bug#精英级古巴自行高炮使用了错误的武器对空

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#482]
【现象】：古巴三星自行高炮对空武器开火位置错误
【反馈人】：shuiping233
【发现版本号】：0.99.904a3
【影响范围】：视觉体验
【产生原因】：忘记设置？
![GIF119](https://user-images.githubusercontent.com/49360196/125634962-f2ef7ffb-f3ab-4ed6-b34a-0c0e326a9fe1.gif)

**Comment by Zero-Fanker** [comment]
看了下精英武器确实填错了。

**Comment by shuiping233** [comment]
顺便把武器修了吧，#483 能挂已完成了吗

**Comment by Zero-Fanker** [comment]
0.99.905a4 已包含修正

**Comment by Zero-Fanker** [comment]
以后平台版本号不用再描述了

**Comment by shuiping233** [comment]
0.99.905a4测试通过
![GIF131](https://user-images.githubusercontent.com/49360196/126859247-41273c24-b1fb-440b-8131-dbb0c016b222.gif)
