### ISSUE TITLE
#Bug#古巴三星自行高炮对空武器使用的是三星防空履带车的对空武器

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#483]
【现象】：古巴三星自行高炮对空武器使用的是三星防空履带车的对空武器，如图所示
【反馈人】：shuiping233
【发现版本号】：0.99.904a3-I0618
【影响范围】：单位平衡性
【产生原因】：未知
![GIF119](https://user-images.githubusercontent.com/49360196/125634962-f2ef7ffb-f3ab-4ed6-b34a-0c0e326a9fe1.gif)

**Comment by Zero-Fanker** [comment]
和#483重复
