### ISSUE TITLE
#建议反馈#鲍里斯召唤的米格战机需要增强

### ISSUE THREAD

**Issue by xuetianyi** [Zero-Fanker/RN_All_Issues#485]
【描述】目前鲍里斯呼叫的米格战机威力太低，一次无法炸毁一座载具厂，甚至无法炸毁一座机场。飞行速度也偏慢，只需要很少的防空力量就可阻挡。
【原因】RN建筑的维修速度很快，且是自动维修，即便是对手没有刻意用防空针对，鲍里斯的米格也无法给对手的建筑带来多大威胁，一次不能炸毁目标，下一轮飞机来的时候又修得差不多了。
【期望解决时间】希望下个测试版本能得到修正。

**Comment by Zero-Fanker** [comment]
@yuanbanlao 评定一下------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月15日(星期四) 中午1:22
***@***.***&gt;;
抄送:&nbsp;&quot;Zero ***@***.******@***.***&gt;;
主题:&nbsp;[Zero-Fanker/RN_All_Issues] #建议反馈#鲍里斯呼叫的米格战机太弱 (#485)

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/125871180-94515b4d-e4a5-428d-96cf-d896b4619de0.png)

**Comment by yuanbanlao** [comment]
已修正。数据可继续测试。

**Comment by shuiping233** [comment]
0.99.905a4是否实装

**Comment by Zero-Fanker** [comment]
0.99.905a5会有------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月31日(星期六) 下午3:59
***@***.***&gt;;
抄送:&nbsp;&quot;Zero ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #建议反馈#鲍里斯召唤的米格战机需要增强 (#485)

**Comment by shuiping233** [comment]
![GIF147](https://user-images.githubusercontent.com/49360196/127740822-c6de7585-d393-4395-bc3e-91de58503e88.gif)

0.99.905a5测试通过

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/128617015-452b9729-9fd8-4b3c-b07d-211629b0c275.png)
补充，米格轰炸机仍然是200血
