### ISSUE TITLE
#Bug#精英级多功能步兵车优先升级最后上车的乘员

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#488]
【现象】：多功能步兵车若除驾驶员外仍有其他乘员，那么步兵车击杀敌人之后载员将会先升级，而不是驾驶员先升级。若步兵车满载乘员，则先从最后上车的乘员开始升级
【反馈人】：suli
【发现版本号】：0.99.905a
【影响范围】：单位手感
【产生原因】：未知
![image](https://user-images.githubusercontent.com/49360196/126260352-32d12480-af19-4228-993f-8703456f7436.png)

**Comment by Zero-Fanker** [comment]
低优先级------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月20日(星期二) 中午12:06
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Zero-Fanker/RN_All_Issues] #Bug#多功能步兵车载员的升级顺序问题 (#488)

**Comment by shuiping233** [comment]
已降低优先级

**Comment by Zero-Fanker** [comment]
比预想的好处理，就先搞定了。

**Comment by Zero-Fanker** [comment]
0.99.905a4 已包含修正

**Comment by shuiping233** [comment]
> 0.99.905a4 已包含修正

下次修复bug后能不能说一下修复之后的效果，特别是这种没有提到修复后是怎么样的单子

**Comment by shuiping233** [comment]
> 0.99.905a4 已包含修正

0.99.905a4测试结果：现在多功能步兵车升级到精英后炮手会正常升级，但是其余乘员则通过此多功能步兵车进行升级。测试通过
