### ISSUE TITLE
#Bug#超时空载具传送平台在断电或者停止工作时仍能正常播放建筑动画

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#490]
【现象】：超时空载具传送平台在断电或者停止工作时仍能正常播放建筑动画
【反馈人】：shuiping233
【发现版本号】：0.99.905a
【影响范围】：视觉体验
【产生原因】：未知

**Comment by Zero-Fanker** [comment]
0.99.905a4 已包含修正

**Comment by shuiping233** [comment]
0.99.905a4测试通过
![GIF132](https://user-images.githubusercontent.com/49360196/126859451-f65c80e0-c754-4f37-a3b3-ead3495b96ba.gif)
