### ISSUE TITLE
#Bug#超时空载具传送平台断电时仍然可以产生单位

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#491]
【现象】：超时空载具传送平台断电时仍然可以复制单位
【反馈人】：shuiping233
【发现版本号】：0.99.905a
【影响范围】：遭遇战
【产生原因】：未知

**Comment by Zero-Fanker** [comment]
0.99.905a4 已包含修正

**Comment by shuiping233** [comment]
0.99.905a4测试通过
![GIF134](https://user-images.githubusercontent.com/49360196/126859739-1d933cf8-8277-4ae8-96bf-26d1586e0e14.gif)
