### ISSUE TITLE
#Bug#尤里复制中心不受EMP影响

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#492]
【现象】：尤里复制中心不受EMP影响
【反馈人】：shuiping233
【发现版本号】：0.99.905a
【影响范围】：遭遇战
【产生原因】：未考虑该场景

[注释]:例子：
[注释]:【现象】：韩国火炮、洲际导弹的信标可以被超时空传送、铁幕装置影响
[注释]:【反馈人】：永恒_叶
[注释]:【发现版本号】：0.99.F1028A
[注释]:【影响范围】：影响带有AI的对局
[注释]:【产生原因】：AI新机制引入

**Comment by Zero-Fanker** [comment]
0.99.905a4 已包含修正

**Comment by shuiping233** [comment]
0.99.905a4测试通过
![GIF133](https://user-images.githubusercontent.com/49360196/126859534-ea7b1bf1-e37a-4432-9c2f-aa853b5e5953.gif)
