### ISSUE TITLE
#Bug#苏军ACS运载车受到黑鹰战机火焰攻击后无法恢复护盾

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#493]
【现象】：使用了RSD伤害的AE攻击带盾单位导致护盾永久失效
【反馈人】：@xuetianyi
【发现版本号】：0.99.902
【影响范围】：影响苏军ACS运载车、英国圣骑士战甲的护盾使用，遭遇韩国火焰弹攻击即导致护盾永久失效
【产生原因】：逻辑缺陷

**Comment by Zero-Fanker** [comment]
0.99.905a5 已修正，请验证

**Comment by xuetianyi** [comment]
确定已经修复。


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Zero Fanker ***@***.***&gt;
发送时间: 2021年7月31日 17:21
收件人: Zero-Fanker/RN_All_Issues ***@***.***&gt;
抄送: xuetianyi ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[Zero-Fanker/RN_All_Issues] #Bug#苏军ACS运载车受到黑鹰战机火焰攻击后无法恢复护盾 (#493)






0.99.905a5 已修正，请验证

**Comment by Zero-Fanker** [comment]
> 确定已经修复。 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Zero Fanker ***@***.***&gt; 发送时间: 2021年7月31日 17:21 收件人: Zero-Fanker/RN_All_Issues ***@***.***&gt; 抄送: xuetianyi ***@***.***&gt;, Mention ***@***.***&gt; 主题: 回复：[Zero-Fanker/RN_All_Issues] #Bug#苏军ACS运载车受到黑鹰战机火焰攻击后无法恢复护盾 (#493) 0.99.905a5 已修正，请验证 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

后来老哈又发现了一些其它问题，昨天晚上又改了一版

**Comment by shuiping233** [comment]
问一句，acs的护盾之前是被火烧了之后没法充电充回去吗？

**Comment by Zero-Fanker** [comment]
是黑鹰的火焰持续效果，圣骑士也可以测------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月31日(星期六) 晚上9:17
***@***.***&gt;;
抄送:&nbsp;&quot;Zero ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #Bug#苏军ACS运载车受到黑鹰战机火焰攻击后无法恢复护盾 (#493)

**Comment by shuiping233** [comment]
好

**Comment by shuiping233** [comment]
![gif149(1)](https://user-images.githubusercontent.com/49360196/128616982-5f5055ae-d2f9-4c17-94ff-e3b8e8fda5f5.gif)
0.99.905a7测试通过
