### ISSUE TITLE
#Bug#越南支援技能“致命封锁”缺少技能指针

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#495]
【现象】：点击技能后指针消失
【反馈人】：shuiping233
【发现版本号】：0.99.902
【影响范围】：视觉体验
【产生原因】：未知

**Comment by Zero-Fanker** [comment]
0.99.905a5 已修正

**Comment by shuiping233** [comment]
![Snipaste_2021-07-31_19-03-54](https://user-images.githubusercontent.com/49360196/127737995-7d01d188-26f8-48f7-a8f0-92b68ac4ed58.png)
0.99.905a5测试通过
