### ISSUE TITLE
#Bug#法国布雷车的碾压等级不正常

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#497]
【现象】：布雷车能被履带车碾，不合适
【反馈人】：jukebox-www
【发现版本号】：0.99.905
【影响范围】：单位手感
【产生原因】：未考虑到该场景

**Comment by Zero-Fanker** [comment]
0.99.905a5已修正

**Comment by shuiping233** [comment]
0.99.905a7测试通过，现在布雷车没法被履带车碾了
