### ISSUE TITLE
#Bug#古巴，法国在钢铁洪流模式下不能造车场

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#5]
RN_Admin created an issue 2018-08-27
可能是车场的建造条件需要 苏军/盟军 的 通用兵营所致

**Comment by Zero-Fanker** [comment]
请测试反馈，群测版本应该是已经支持了。该修改在2月份已经合入。

**Comment by shuiping233** [comment]
G0615P1版本经过测试，该问题已经解决，测试通过


![QQ截图20190708102300](https://user-images.githubusercontent.com/49360196/60778851-2670a580-a16b-11e9-9eb7-d96407016e26.png)
![QQ截图20190708102537](https://user-images.githubusercontent.com/49360196/60778852-2670a580-a16b-11e9-9152-c5da54a30901.png)
