### ISSUE TITLE
#Bug#越南化学武器会产生蓝色的病毒粒子，而应该产生绿色毒雾

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#501]
【现象】：越南的毒蝎坦克、毒牙轰炸机等产生的次生伤害粒子为病毒，而不是毒雾
【反馈人】：
【发现版本号】：0.99.902
【影响范围】：越南化学武器的特效展示
【产生原因】：不合理的动画效果

**Comment by Zero-Fanker** [comment]
@shuiping233 0.99.906已调整

**Comment by shuiping233** [comment]
修正，0.99.906a3并未调整该问题

**Comment by Crossfield-ClassDestroyer** [comment]
![QQ图片20211209205600](https://user-images.githubusercontent.com/54458394/145401219-c9394b84-0607-4736-933a-c58b847690f7.png)
已修正并使用新素材

**Comment by Zero-Fanker** [comment]
0.99.912a4 已修复

**Comment by NightSkyTS** [comment]
0.99.912a测试通过
![SCRN 20220208-171834-00933](https://user-images.githubusercontent.com/78950858/152960588-aa55f4a8-21de-4982-b60e-7948a08d9caf.png)
