### ISSUE TITLE
#Bug#【cncnet客户端】cncnet联机模式下可以单人启动游戏

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#502]
【现象】：cncnet联机模式下可以单人启动游戏
【反馈人】：2561775623
【发现版本号】：0.99.905a8
【产生原因】：未知

**Comment by Zero-Fanker** [comment]
0.99.906 已修复。

**Comment by shuiping233** [comment]
![Snipaste_2021-08-18_22-36-30](https://user-images.githubusercontent.com/49360196/130097507-ef9cd05b-b2f5-4dd9-8dac-07d2353ccbf2.png)
0.99.906c测试通过
