### ISSUE TITLE
#建议反馈#尤里空投炸弹的动画不美观，需要更换

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#503]
【描述】尤里空投炸弹的色调不是很合适
【原因】动画处理的不恰当
【期望解决时间】

**Comment by Zero-Fanker** [comment]
之前虽然已经调整，但是打包存在一定的问题导致实装到版本中表现不符合预期。
现0.99.911a3已调整至预期

**Comment by shuiping233** [comment]
![gif247](https://user-images.githubusercontent.com/49360196/142887716-6fef4c29-3a1a-49b7-98c7-eae70a40ffd5.gif)
0.99.911a3测试通过
