### ISSUE TITLE
#Bug#尤里火箭型兽人在读取存档后可能引起闪退

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#508]
【现象】：地图上已存在火箭型兽人时，读取存档可能引起闪退，据分析是STL vector的异常
【反馈人】：ELARMAN
【发现版本号】：0.99.905
【影响范围】：影响存在火箭型兽人的单人游戏存档
【产生原因】：已证实
[SAVE2BFB.zip](https://github.com/Zero-Fanker/RN_All_Issues/files/7039858/SAVE2BFB.zip)

**Comment by Zero-Fanker** [comment]
0.99.907 已修复 @shuiping233

**Comment by shuiping233** [comment]
0.99.909测试通过
