### ISSUE TITLE
#Bug#古巴地道投放技能鼠标提示文字缺失

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#511]
【现象】：古巴地道投放技能提示文字缺失
【反馈人】：
【发现版本号】：0.99.905
【影响范围】：影响古巴技能鼠标浮动显示
【产生原因】：忘记写CSF

**Comment by Zero-Fanker** [comment]
0.99.908 已修复

**Comment by Zero-Fanker** [comment]
@shuiping233

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/134772565-b3f77a2e-d7f2-44f3-ab0f-84222160567b.png)
0.99.909测试通过
