### ISSUE TITLE
#Bug# 步兵受到有压制效果的武器是有概率变成无敌

### ISSUE THREAD

**Issue by Fantasycho** [Zero-Fanker/RN_All_Issues#515]
【现象】：某场遭遇战时，一个AI的动员兵攻击玩家的加特林机炮，但加特林机炮无法对该动员兵造成伤害。而后检查发现该动员兵处于无敌状态，无法被击杀。
【反馈人】：
【发现版本号】：0.99.905a8
【影响范围】：少数出现bug的遭遇战
【产生原因】：

**Comment by shuiping233** [comment]
不管ai还是玩家以及什么步兵单位均可能触发该问题，暂无复现方法

**Comment by Zero-Fanker** [comment]
[SAVE_InvincibleInf.zip](https://github.com/Zero-Fanker/RN_All_Issues/files/7316137/SAVE_InvincibleInf.zip)

内测玩家给出了0.99.910存档一份

**Comment by Zero-Fanker** [comment]
找不到复现方法，暂时搁置

**Comment by Zero-Fanker** [comment]
原因已查明，以V3为代表的对步兵产生压制效果的武器在击杀步兵时会导致此问题

**Comment by Zero-Fanker** [comment]
0.99.913a7 已修复

**Comment by NightSkyTS** [comment]
0.99.913b联机状态测试鲍里斯，警犬，蜘蛛击杀并未触发

**Comment by Zero-Fanker** [comment]
@klighting444 小碗帮忙归档
