### ISSUE TITLE
#Bug#浮岛要塞地图的中立方混凝土围墙破损图像错误

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#516]
【现象】：中立方围墙损坏时会导致地上出现黑色残影
【反馈人】：
【发现版本号】：0.99.902
【影响范围】：所有出现该种类型中立围墙的地图
【产生原因】：ini图像参数错误

**Comment by Zero-Fanker** [comment]
@shuiping233  0.99.906b 已修复

**Comment by shuiping233** [comment]
![AR6N8U03T6_9CXT@XWH EML](https://user-images.githubusercontent.com/49360196/134772581-e26e2aaa-f435-4704-a2b3-3f58620c1e11.jpg)
0.99.909测试通过
