### ISSUE TITLE
#建议反馈#最新版地图弹窗报错问题

### ISSUE THREAD

**Issue by xdovobx** [Zero-Fanker/RN_All_Issues#517]
【描述】（填写你要反馈或者建议的内容，越详细越好，条理清晰可分条列举）
【原因】（填写你要提出建议的原因，不写原因基本不会被重视）
【期望解决时间】（如果你期望及时得到解决，可以填写期望的日期，选填）

[注]:不按照格式填写会被视作无效。

-新版双子湖进入游戏仅几十秒便弹窗报错，随后游戏崩溃``
-如上
-一个月左右就好，实在没时间也不强求

**Comment by shuiping233** [comment]
请提交debug文件到复仇时刻邮箱，我908无法复现该问题

**Comment by Zero-Fanker** [comment]
首先，按照格式提交，其次crash按照要求提交错误日志。综上该条反馈作废。
