### ISSUE TITLE
#Bug#英国利刃投放的机器人欢呼动作不正常

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#519]
【现象】：欢呼时机器人不能正确显示图像
【反馈人】：
【发现版本号】：0.99.909
【影响范围】：影响英国机器人的欢呼
【产生原因】：缺少欢呼动作，且帧序列设置错误

**Comment by shuiping233** [comment]
![gif163](https://user-images.githubusercontent.com/49360196/135619405-f9bd8196-ef9e-4be1-bc28-ff0bd8b56d67.gif)
0.99.910a2测试通过
