### ISSUE TITLE
#Bug#苏联基洛夫飞艇铁幕部署的长延时效果丢失

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#521]
【现象】：原先的设计中，基洛夫飞艇部署后会显示倒计时图标并且在较长一段时间内不能继续使用铁幕。现在这个时间间隔变的很短且不显示倒计时图标
【反馈人】：
【发现版本号】：0.99.908
【影响范围】：影响基洛夫飞艇使用时的公平性
【产生原因】：内部逻辑调整时引起的原来效果失效

**Comment by shuiping233** [comment]
![gif165](https://user-images.githubusercontent.com/49360196/135625593-4ebc4fef-93ef-4edb-aa5c-e8bfcbb59257.gif)
0.99.910a2测试通过
