### ISSUE TITLE
#Bug#淘金热模式中钻矿平台图标缺失

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#522]
【现象】：钻矿平台缺少图标
【反馈人】：
【发现版本号】：0.99.902
【影响范围】：影响淘金热模式钻矿平台的图标显示
【产生原因】：缺少图标素材

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/135618736-0c63fab8-9d21-4461-bc31-b199e089b31a.png)
0.99.910a2测试通过
