### ISSUE TITLE
#Bug#军犬攻击步兵时有坦克碾压此步兵导致坦克被寄生

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#523]
【现象】：在军犬攻击敌军步兵同时我方坦克将其压死，导致我方坦克进入了一种类似于被恐怖机器人攻击的状态，但是不会损失血量
【反馈人】mfn
【发现版本号】：0.99.909
【影响范围】：游戏手感，视觉体验
【产生原因】：寄生逻辑判断问题

https://user-images.githubusercontent.com/49360196/135491087-2dd181fc-f55a-4b12-9a84-3f5ad5b90e61.mp4

[注释]:例子：
[注释]:【现象】：韩国火炮、洲际导弹的信标可以被超时空传送、铁幕装置影响
[注释]:【反馈人】：永恒_叶
[注释]:【发现版本号】：0.99.F1028A
[注释]:【影响范围】：影响带有AI的对局
[注释]:【产生原因】：AI新机制引入

**Comment by Zero-Fanker** [comment]
原来可以直接传视频啊

**Comment by shuiping233** [comment]
> 原来可以直接传视频啊

好早之前的事情了，群里讲过吧233

**Comment by Zero-Fanker** [comment]
0.99.910已修复 @shuiping233

**Comment by Zero-Fanker** [comment]
@klighting444 小碗帮我归档
