### ISSUE TITLE
#Bug#幻影坦克开火动画缺失，且周围驻留绿色像素点

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#525]
【现象】：如标题
【反馈人】：
【发现版本号】：0.99.902
【影响范围】：影响幻影坦克开火显示
【产生原因】：动画数据错误

**Comment by shuiping233** [comment]
![gif164](https://user-images.githubusercontent.com/49360196/135620296-32d55295-487e-44b7-9829-d5259950377f.gif)
0.99.910a2测试通过
