### ISSUE TITLE
#Bug#苏联机场不受EMP效果影响

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#527]
【现象】：苏联机场不受EMP效果影响
【反馈人】：shuiping233
【发现版本号】：0.99.910a2
【影响范围】：游戏平衡性
【产生原因】：未知

![gif166](https://user-images.githubusercontent.com/49360196/135630253-accd36d3-4388-4da8-8354-c87943bae70d.gif)

**Comment by Zero-Fanker** [comment]
0.99.912a 已调整 @Renko-ji @shuiping233

**Comment by shuiping233** [comment]
0.99.912a测试通过，测试员：咸老师
