### ISSUE TITLE
#Bug#科技火箭炮没有开火音效

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#529]
【现象】：科技火箭炮没有开火音效
【反馈人】：Zero-Fanker
【发现版本号】：0.99.910a3
【影响范围】：游戏体验
【产生原因】：未知

https://user-images.githubusercontent.com/49360196/135700517-26421231-ce8d-49d5-b8e7-41e543e6a648.mp4

**Comment by Zero-Fanker** [comment]
由于相关任务关卡需要使用，优先级提升

**Comment by Zero-Fanker** [comment]
0.99.914a8 已修复

**Comment by shuiping233** [comment]
https://user-images.githubusercontent.com/49360196/184471593-2cc3bf88-ab94-44c4-b768-fb48785c13d5.mp4


https://user-images.githubusercontent.com/49360196/184471597-25325d93-64ad-41dc-adbb-6ec3b0b042c6.mp4

0.99.914a9测试通过

**Comment by shuiping233** [comment]
@klighting444 4 请按0.99.914a9归档
