### ISSUE TITLE
#Bug##视觉BUG##群测#法国兵营前哨站的雷达动画存在遮挡问题

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#53]
Zero Fanker created an issue 2018-10-18
【现象】：法国兵营前哨站的雷达动画遮挡等级过高，甚至会覆盖在空中的单位
【影响范围】：法国兵营雷达图像附近视觉显示
【产生原因】：art设置不合理

**Comment by shuiping233** [comment]
Zero Fanker reporter

    可能是因为本体产生的遮挡，需要把本体有遮挡的部分拆成动画，用参数调整。
        2018-10-18
    Zero Fanker reporter
        changed status to resolved

    修改了素材，本体和动画做了适当调整。测试通过。
        2018-10-18
