### ISSUE TITLE
#Bug#【CnCNet客户端】多人对局设置多个AI在同一出生点仍可开始游戏

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#534]
【现象】：设置多个ai在同一出生点仍可开始游戏。进入游戏内会导致有ai没有基地车也没法被消灭，导致游戏无法胜利
【反馈人】：shuiping233
【发现版本号】：0.99.910
【影响范围】：联机体验
【产生原因】：未知

**Comment by Zero-Fanker** [comment]
0.99.911a已修正

**Comment by shuiping233** [comment]
![AI{_NK9G6 }JT)B3HJCO7Z3](https://user-images.githubusercontent.com/49360196/136694914-556ffee2-a89a-4f63-88b1-ac49a6e46975.png)
![3BPOGBEM2V~~1NK%}L~CB_A](https://user-images.githubusercontent.com/49360196/136694916-086e7628-941d-4296-bb7a-68fcbae4dcfd.png)
0.99.911测试通过

**Comment by shuiping233** [comment]
@klighting444 帮忙归档一下
