### ISSUE TITLE
#Bug#【CnCnet客户端】多人对局AI可选成一样的颜色而不被阻止

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#535]
【现象】：AI不可以选成一样的颜色，应该与未使用客户端时保持一致，且单人多人行为保持一致
【反馈人】：@Zero-Fanker
【发现版本号】：0.99.910
【影响范围】：影响多人游戏带AI玩家
【产生原因】：多人模式下未校验AI玩家之间的颜色

**Comment by Zero-Fanker** [comment]
0.99.911a已修正
