### ISSUE TITLE
#Bug#【CnCNet客户端】合作模式下的载入图和普通遭遇战没有差异，而非特殊载入图

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#536]
【现象】：合作模式载入图现在并不像原版那样是特殊的载入图，而是普通的遭遇战载入图
【反馈人】：
【发现版本号】：0.99.910
【影响范围】：影响合作模式的载入体验
【产生原因】：客户端载入图的参数错误

**Comment by Zero-Fanker** [comment]
0.99.911a已修正

**Comment by shuiping233** [comment]
![Uploading image.png…]()
0.99.911a测试通过

**Comment by shuiping233** [comment]
@klighting444 帮忙归档一下
