### ISSUE TITLE
#Bug#随机数生成算法有一定概率导致游戏卡死

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#537]
【现象】：某种原因会导致游戏卡死，不仅仅在攻城拔寨模式下出现
【反馈人】：zero-fanker
【发现版本号】：0.99.910
【影响范围】：影响通关
【产生原因】：根据分析大部分情况由闪电风暴产生，已获得一份memory dump
![Snipaste_2021-10-06_23-38-29](https://user-images.githubusercontent.com/49360196/136236759-e2ab2ef4-8ba8-438a-9a98-dfbbd6bdbcd8.png)
![Snipaste_2021-10-06_23-20-52](https://user-images.githubusercontent.com/49360196/136236762-61e754ae-819a-4a7f-a40c-8064779868cd.png)
[debug.log](https://github.com/Zero-Fanker/RN_All_Issues/files/7295380/debug.log)

**Comment by shuiping233** [comment]
已修正描述

**Comment by shuiping233** [comment]
https://user-images.githubusercontent.com/49360196/136677285-c2633e6b-3317-4062-b0c2-947aa46765dc.mp4
![image](https://user-images.githubusercontent.com/49360196/136677297-7c350157-dc7b-43f9-a22f-78ab884b7b19.png)

**Comment by Zero-Fanker** [comment]
已更换随机数算法，0.99.912a3已包含 @shuiping233

**Comment by shuiping233** [comment]
需要长期观察

**Comment by Zero-Fanker** [comment]
> 需要长期观察

我觉得都这么久了，可以不用观察了。另外这个真实的原因也可能不是这个算法本身的问题，发现是闪电风暴相关的代码有底层机制（编译器相关）缺陷

**Comment by Zero-Fanker** [comment]
@klighting444 小碗帮忙归档一下
