### ISSUE TITLE
#Bug#攻城拔寨-争分夺秒地图中，进攻方AI的海军会导致寻路失败而非常卡顿

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#538]
【现象】：4、5号位AI玩家会把船厂建在死路中，而导致卡顿
【反馈人】：
【发现版本号】：0.99.910
【影响范围】：影响AI参与进攻方时的游戏体验
【产生原因】：AI寻路卡顿

**Comment by shuiping233** [comment]
内陆湖（或水面被地形隔断）的ai海军有可能会导致游戏极度卡顿
![BD37$SR@5UU(5S6BIK0 7XT](https://user-images.githubusercontent.com/49360196/136677858-be11777c-1007-452c-802b-0cb6d6fe9f67.jpg)

**Comment by Zero-Fanker** [comment]
0.99.911a2 已调整，禁用了AI的船厂

**Comment by shuiping233** [comment]
0.88.911a3粗略测试，通过

**Comment by shuiping233** [comment]
测试通过
