### ISSUE TITLE
#Bug#关于战术核炮的心控问题

### ISSUE THREAD

**Issue by AEROLOP918** [Zero-Fanker/RN_All_Issues#539]
【现象】：尤里X心控部署的战术核炮后收起会出现如同尤复1.000中基地车同种情况，不再是心控状态而直接拥有归属权
【反馈人】：AEROLOP
【发现版本号】：0.99.910
【影响范围】：遭遇战或更多
【产生原因】：尤复传统
![EP66X_3EL$RPA4YYUM 3J_Y](https://user-images.githubusercontent.com/78075525/136337032-a3cb8995-96fa-4b90-8692-a4ef37245561.png)
![J~QR}@48JQ3@(JKDL7MZ19J](https://user-images.githubusercontent.com/78075525/136337062-c12280e7-f1ef-4698-ae9a-a46fd24bbe19.png)

**Comment by Zero-Fanker** [comment]
已重构建筑和载具之间的转换心控逻辑

**Comment by Zero-Fanker** [comment]
@NightSky-TS

**Comment by Zero-Fanker** [comment]
@NightSkyTS NSTS帮忙验证一下

**Comment by NightSkyTS** [comment]
![核炮](https://user-images.githubusercontent.com/78950858/162750553-bf3e24c9-98e2-4292-a6e6-cfbaa0da70cf.gif)
0.99.913a6测试通过
