### ISSUE TITLE
#Bug##群测#【联机RE】古巴自行高炮在开火时会导致联机断线

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#54]
Zero Fanker created an issue 2018-10-21
【现象】：自行高炮在开火时联机RE。
【影响范围】：任何联机的游戏模式，只要地图上存在古巴自行高炮。
【产生原因】：自行高炮多炮管轮流开火画效同步机制存在缺陷。

**Comment by shuiping233** [comment]
Zero Fanker reporter

    changed status to resolved

多炮管轮流开火画效机制缺陷已经确认，似乎由于不同的机器帧率在同步之前会有所不同，导致依赖于绘制刷新的变量会存在差异。现在将该变量调整至开火状态同步函数内。测试通过。

    2018-10-21

Zero Fanker reporter

factory.png 工厂的差异以后可能仍然需要注意

    2018-10-22

Zero Fanker reporter

Issue #32 was marked as a duplicate of this issue.

    2018-10-27
