### ISSUE TITLE
#Bug#【CnCnet客户端】新开战役中的阵营按钮亮色显示逻辑不正确

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#541]
【现象】：如图所示
【反馈人】：zerofanker
【发现版本号】：0.99.910
【影响范围】：视觉体验
【产生原因】：未知
![gif197](https://user-images.githubusercontent.com/49360196/136415793-c452f66b-54cf-4ed2-82aa-33e7bd66f6e5.gif)

**Comment by Zero-Fanker** [comment]
0.99.911a 已修正

**Comment by shuiping233** [comment]
@klighting444 帮忙归档一下
