### ISSUE TITLE
#Bug#地图【成事在人II】无法打开

### ISSUE THREAD

**Issue by superhuoguo** [Zero-Fanker/RN_All_Issues#543]
【现象】：地图【成事在人II】无法打开
【反馈人】：（如果是自己的帐户可以不填，代他人提交必填）
【发现版本号】：0.99.910
[【影响范围】：遭遇战和多人联机]
【产生原因】：（填写你认为的原因，如使用了非官方地图，或者进行了某种操作等，不知道可以不填）
我还把当天的debug文件打包好了（应该就只有这些了吧）不知道有没有用
> 
[debug.20211010-004219.zip](https://github.com/Zero-Fanker/RN_All_Issues/files/7316030/debug.20211010-004219.zip)
``

**Comment by Zero-Fanker** [comment]
同 #393

**Comment by Zero-Fanker** [comment]
![image](https://user-images.githubusercontent.com/14891010/136669644-4ba84a26-2859-4f02-82a2-69b8a19f722c.png)
![image](https://user-images.githubusercontent.com/14891010/136669648-1ec554c0-236a-4f84-82ba-31e3102f6726.png)
搞定

**Comment by Zero-Fanker** [comment]
0.99.911a已修复 @shuiping233
