### ISSUE TITLE
#Bug#【CnCnet客户端】划过按钮会重复播放两次音效

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#544]
【现象】：划过按钮会重复播放两次音效，你听
【反馈人】：星星 @Super-StarX 
【发现版本号】：0.99.910
【影响范围】：听觉体验（？？？）
【产生原因】：我不知道
![image](https://user-images.githubusercontent.com/49360196/136677584-f4a0d7e1-ed0e-48ac-8ecc-8e58a1a4c7e6.png)

https://user-images.githubusercontent.com/49360196/136677611-4f8c2b0d-bdde-4454-9e4f-357d199acbf2.mp4

**Comment by Zero-Fanker** [comment]
目前先修正按钮透明像素引起的问题

**Comment by Zero-Fanker** [comment]
0.99.911a2 已修复 @shuiping233

**Comment by shuiping233** [comment]
https://user-images.githubusercontent.com/49360196/140630148-3e9c8f47-c8aa-488e-9a8d-d5121526b73f.mp4

0.99.911a2 咸老师：CNCNET大厅 登录界面的“登录”与“返回”依旧有此问题

**Comment by Zero-Fanker** [comment]
那其他按钮呢？ 别只说问题啊

**Comment by shuiping233** [comment]
其他按钮没发现有问题，都正常

**Comment by Zero-Fanker** [comment]
>  2021-11-07.10-01-04.mp4 
> 0.99.911a2 咸老师：CNCNET大厅 登录界面的“登录”与“返回”依旧有此问题

@xuetianyi

**Comment by Zero-Fanker** [comment]
> > 2021-11-07.10-01-04.mp4
> > 0.99.911a2 咸老师：CNCNET大厅 登录界面的“登录”与“返回”依旧有此问题
> 
> @xuetianyi

0.99.911最后残留的问题修复了吗

**Comment by Renko-ji** [comment]
> > > 2021-11-07.10-01-04.mp40.99.911a2咸老师：CNET大厅登录界面的“登录”与“返回”依旧有此问题
> > 
> > 
> > @xuethanyi
> 
> 0.99.911最后残留的问题修复了吗

刚测完，没有了

**Comment by Zero-Fanker** [comment]
> > > > 2021-11-07.10-01-04.mp40.99.911a2咸老师：CNET大厅登录界面的“登录”与“返回”依旧有此问题
> > > 
> > > 
> > > @xuethanyi
> > 
> > 
> > 0.99.911最后残留的问题修复了吗
> 
> 刚测完，没有了

那小碗帮忙归档 @klighting444
