### ISSUE TITLE
#Bug#苏军维修厂存在遮罩问题

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#545]
【现象】：如图所示
【反馈人】：zerofanker
【发现版本号】：0.99.910
【影响范围】：视觉体验
【产生原因】：未知

![333333333333QQ图片20211010091150](https://user-images.githubusercontent.com/49360196/136677717-9a881225-33c6-4392-b3e0-aaab84d261fd.png)

**Comment by Zero-Fanker** [comment]
0.99.911a已修正

**Comment by shuiping233** [comment]
@klighting444 帮忙归档一下
