### ISSUE TITLE
#Bug#乌克兰核潜艇精英级鱼雷武器射程比新兵级鱼雷武器射程短

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#548]
【现象】：乌克兰核潜艇精英级鱼雷武器射程比新兵级鱼雷武器射程短，如图所示
【反馈人】：咕咕咕咕咕咕（1838664143）
【发现版本号】：0.99.910
【影响范围】：单位手感
【产生原因】：未知
![gif194](https://user-images.githubusercontent.com/49360196/136677986-4c35dbff-b11c-4f64-8cbf-f972bab8742e.gif)

![gif196](https://user-images.githubusercontent.com/49360196/136677979-d48af61f-1b4b-4a9f-9fad-2d1e5368d3ee.gif)
![gif195](https://user-images.githubusercontent.com/49360196/136677982-0cb0fc28-dad0-4bdd-95c3-27f00fb391c1.gif)

**Comment by Zero-Fanker** [comment]
@yuanbanlao 快，屠龙了

**Comment by yuanbanlao** [comment]
已修正，现在所有射程都为7.请验收

**Comment by Zero-Fanker** [comment]
你完成的话把单子的标签的“new”改成“resolved”，project挪到进行中。
验收等我发布到内测再告诉shuiping

**Comment by Zero-Fanker** [comment]
0.99.912a 已调整 @Renko-ji @shuiping233

**Comment by shuiping233** [comment]
0.99.912a测试通过，测试员：suli
