### ISSUE TITLE
#Bug#（攻城拔寨模式）浮岛要塞中有部分空降伞兵不匹配阵营

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#552]
【现象】：浮岛要塞中有部分空降伞兵不匹配玩家阵营，如图所示

【反馈人】：zerofanker
【发现版本号】：0.99.910
【影响范围】：联机体验
【产生原因】：未知
![E%ZJ~P9B@`80NUL20{5)KDP](https://user-images.githubusercontent.com/49360196/136679512-c9b4d2fa-a422-44ae-930b-b7f945d707fe.jpg)

**Comment by Zero-Fanker** [comment]
@shuiping233  0.99.911a2 观察一下

**Comment by shuiping233** [comment]
0.99.911a3测试通过，该问题已修复
