### ISSUE TITLE
#Bug#在摆放建筑预览过程中进行存档，读取后可能引起崩溃

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#553]
【现象】：在建筑建造完毕的情况下如果点击建筑并预览地形可摆放位置时，此时进行存档，再读取后可导致程序崩溃。
[SAVE_WouldCrash.zip](https://github.com/Zero-Fanker/RN_All_Issues/files/7316137/SAVE_InvincibleInf.zip)
【反馈人】：yun提供存档，@Zero-Fanker 追溯问题时遇到
【发现版本号】：0.99.910
【影响范围】：影响题述操作时的存档和读取
【产生原因】：WWSB遗留问题

**Comment by Zero-Fanker** [comment]
0.99.911a2已修复 @shuiping233

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/142745603-9c293b7b-983e-4924-9cff-9fc62503a78c.png)
0.99.911a3仍有此问题

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/142745766-a24fb6cb-9cce-4782-af2f-f8da27e3051a.png)

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/142764234-22cd636f-edb7-442e-86fe-b0f2e111b9fd.png)

**Comment by RN-Hydra** [comment]
0.99.912a3依然存在此问题，在存档后，无论在游戏内或者客户端读取存档，点击建筑即刻崩溃。

**Comment by RN-Hydra** [comment]
0.99.912a7测试无问题

**Comment by shuiping233** [comment]
0.99.912a7测试无问题
