### ISSUE TITLE
#Bug#海豚攻击时有一定概率会引起崩溃

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#554]
【现象】：玩家参与多人游戏时的crashdump分析，结论是音波武器绘制产生崩溃
【反馈人】：绫风
【发现版本号】：0.99.910
【影响范围】：影响对局中存在海豚的场合
【产生原因】：使用了不稳定的实现方式

[except.txt](https://github.com/Zero-Fanker/RN_All_Issues/files/7357738/except.txt)

**Comment by Zero-Fanker** [comment]
0.99.911a2 已修复

**Comment by shuiping233** [comment]
这个只在联机出现还是单机都有？

**Comment by Zero-Fanker** [comment]
> Reference in n

这是crash，不是RE

**Comment by Zero-Fanker** [comment]
所以测来测去 能不能给个结论了

**Comment by shuiping233** [comment]
不鸟了，应该没这回事了

**Comment by shuiping233** [comment]
以0.99.912a6归档
