### ISSUE TITLE
#Bug#鼠标浮动至单位显示或电力值单位图标栏显示文本有可能引起崩溃

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#555]
【现象】：如题

[except.txt](https://github.com/Zero-Fanker/RN_All_Issues/files/7383099/except.txt)
【反馈人】：凌飞月
【发现版本号】：0.99.910
【影响范围】：暂时未确定实际原因，因此影响全局
【产生原因】：疑似原版历史遗留问题

**Comment by Zero-Fanker** [comment]
0.99.911a2 已修复 @shuiping233

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/142745552-e3314ffc-b08c-42b7-b3cd-dd3ccfe4ac13.png)
0.99.911a3未发现问题，测试通过
