### ISSUE TITLE
#Bug#盟军AI不会正确使用攻城机甲

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#556]
【现象】：AI造出攻城机甲之后会囤积在基地中而不出击
【反馈人】：
【发现版本号】：0.99.902
【影响范围】：影响盟军AI使用和发挥攻城机甲
【产生原因】：攻城机甲特殊的生产机制导致的问题

**Comment by Zero-Fanker** [comment]
0.99.911a2 已修复 @shuiping233  典型可以观察遭遇战的AI是否会在基地囤积攻城机甲，同理TR旧版任务尤里07

**Comment by shuiping233** [comment]
0.99.911a3未发现ai囤积攻城机甲，测试通过

**Comment by shuiping233** [comment]
@Renko-ji  帮忙测测这个）

**Comment by Zero-Fanker** [comment]
这个等我再更新一版，其中一个小队的暴风摩托才修好
