### ISSUE TITLE
#Bug#（攻城拔寨模式）争分夺秒地图中心灵控制增幅器部署后游戏会崩溃

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#558]
【现象】：如标题所示，崩溃文件暂且未有，周六日应该会有了
【反馈人】：凌飞月
【发现版本号】：0.99.910
【影响范围】：游戏体验
【产生原因】：未知

**Comment by Zero-Fanker** [comment]
经过分析为WW遗留隐患，定位为当敌军工厂存在一个正在建造尚未出厂的单位时就会导致该工厂转换所属时，立刻销毁未出厂单位导致悬空指针问题。

**Comment by Zero-Fanker** [comment]
0.99.911a2 已修复 @shuiping233

**Comment by shuiping233** [comment]
0.99.911a2 咸老师：测试了所有阵营，玩家2号位，AI阵营全随机，并未出现崩溃现象
测试通过
