### ISSUE TITLE
#56: #Bug##群测1014E#古巴/越南亡者救赎技能，尸体转变动画所属色丢失

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#56]
Zero Fanker created an issue 2018-10-28
【现象】：被亡者救赎技能绑定的目标步兵在死亡后，播放的尸体转收割者动画，所属色异常。
【影响范围】：尸体转变动画的所属无法通过肉眼识别。
【产生原因】：程序内部故障或者数据编写疏忽

**Comment by shuiping233** [comment]
Zero Fanker reporter

    changed status to resolved

代码中找到了缺失判定的地方，现在已经修复。

    2018-10-28
