### ISSUE TITLE
#Bug#尤里阵营拾取到其他阵营采矿车时 采矿车无法正常采矿

### ISSUE THREAD

**Issue by mariodad3** [Zero-Fanker/RN_All_Issues#564]
【现象】：尤里阵营拾取采矿车无法采矿
【反馈人】：尤里丘尔库夫斯基
【发现版本号】：0.99.910
【影响范围】：遭遇战模式 尤里阵营拾取采矿车后无法主动采矿  无法为其他阵营队友倒矿补充经济
【产生原因】：尤里阵营缺少对应的矿场

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/140342876-6b751b5a-82ed-4ead-9ea1-c835a188f647.png)

**Comment by shuiping233** [comment]
优先级降低

**Comment by Zero-Fanker** [comment]
> ![image](https://user-images.githubusercontent.com/49360196/140342876-6b751b5a-82ed-4ead-9ea1-c835a188f647.png)
按这个说法就是压根不用调了，如果改成不能捡到，那不就没法拿去卖钱了，如果玩家又想先攒着后来有了盟苏基地再用，你又何必去干预呢
