### ISSUE TITLE
#Bug#尤里内战时无法主动反间谍

### ISSUE THREAD

**Issue by mariodad3** [Zero-Fanker/RN_All_Issues#565]
【现象】：尤里内战时无法主动发间谍，心控会对渗透者失效，即使是AI也不会控制或者攻击伪装之后的渗透者
【反馈人】：尤里丘尔库夫斯基
【发现版本号】：0.99.910
【影响范围】：遭遇战
【产生原因】：未知

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/140343662-91b23744-9720-4d66-9ff4-47af9186c1ac.png)
尤里间谍免疫心控是游戏设定，若还有问题请回复此issues
