### ISSUE TITLE
#Bug#地图“活见鬼”没有实装

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#568]
【现象】：地图“活见鬼”没有实装
【反馈人】：shuiping233
【发现版本号】：0.99.911a2
【影响范围】：遭遇战地图
【产生原因】：未知

**Comment by Zero-Fanker** [comment]
@shuiping233 @Renko-ji 0.99.911a3已修复

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/142744554-993c1840-eeb8-4c69-bdc4-421c1dd290bb.png)
0.99.911a3测试通过
