### ISSUE TITLE
#Bug#地图“极寒边境”中初始部队是精英级

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#569]
【现象】：地图“极寒边境”中初始部队是精英级的
【反馈人】：shuiping233
【发现版本号】：0.99.911a2
【影响范围】：遭遇战地图
【产生原因】：未知

**Comment by Zero-Fanker** [comment]
@Fantasycho

**Comment by Zero-Fanker** [comment]
0.99.914a8 已修复

**Comment by NightSkyTS** [comment]
艾兰：0.99.914a9测试通过
![7](https://user-images.githubusercontent.com/78950858/183950567-d658bd03-deeb-4f8b-acf1-db7ec22f456b.png)

**Comment by shuiping233** [comment]
@klighting444 请帮忙归档
