### ISSUE TITLE
 #建议##群测##天启坦克武器数据调整

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#57]
Zoa Holic created an issue 2018-10-28
【现象】：天启坦克的飞弹感觉有些喧宾夺主了，飞弹尾焰遮住主炮，给人一种只会飞弹，不会开炮的错觉
【影响范围】：影响天启坦克的打击感
【产生原因】：尾焰太长，使用飞弹频率高，像是飞弹车，而且有飞机飞过时会放弃开炮，去追飞机（这个好像没法避免）

**Comment by shuiping233** [comment]
kk7k7k558 reporter

    marked as major

    2018-11-02

kk7k7k558 reporter

    changed title to #改进#1028A#光棱的走a和反甲一个也没去

    2018-11-02

Zero Fanker

    changed title to #改进#公测1028A#光棱坦克同时具备走A和较强的反甲能力，有OP嫌疑
    edited description

辣鸡kk注意格式！

    2018-11-02

**Comment by shuiping233** [comment]
kk7k7k558

其实很大原因也是因为天启射程有些奇特。 导弹的射速和主炮有时候真的可以做到完美重叠。 建议减小导弹爆炸动画，并给天启主炮添加炮口火焰。

    2018-11-02

**Comment by Zero-Fanker** [comment]
@yuanbanlao 调整的参数说一下

@shuiping233 H1127已调整

**Comment by yuanbanlao** [comment]
详见204.
天启坦克增强主炮伤害20%，主炮射速降低15%。

**Comment by shuiping233** [comment]
我测试的时候总感觉天启导弹和主炮射程不一致，还有就是让天启攻击单位他会冲的很前，不知道是有意为之还是其他原因

**Comment by shuiping233** [comment]
关于伤害的测试我用公测G1028C与内侧H1127进行对比

**Comment by shuiping233** [comment]
> 详见204.
> 天启坦克增强主炮伤害20%，主炮射速降低15%。

天启的加伤是只加damage吗，还是弹头比例都加20%

**Comment by yuanbanlao** [comment]
只加damage

**Comment by shuiping233** [comment]
天启变成歼星舰我不介意

**Comment by shuiping233** [comment]
kk和我都测过了，H1127B测试通过

**Comment by shuiping233** [comment]
![GIF58](https://user-images.githubusercontent.com/49360196/101282837-47cb3a80-3812-11eb-8da5-1863ba3ed213.gif)
![GIF57](https://user-images.githubusercontent.com/49360196/101282857-5fa2be80-3812-11eb-99b4-e23fdd5fd24f.gif)
![GIF56](https://user-images.githubusercontent.com/49360196/101282863-67626300-3812-11eb-8599-8cff46053ec2.gif)
