### ISSUE TITLE
#Bug#地图“猛虎湾之夜”读取后游戏崩溃

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#571]
【现象】：地图“猛虎湾之夜”读取后游戏崩溃
【反馈人】：shuiping233
【发现版本号】：0.99.911a2
【影响范围】：遭遇战地图
【产生原因】：未知

snapshot-20211109-172201
![image](https://user-images.githubusercontent.com/49360196/141608499-0f7c2b9c-22e4-4b73-9851-b03fcd191d21.png)

**Comment by Zero-Fanker** [comment]
0.99.914a8 已修复

**Comment by NightSkyTS** [comment]
0.99.914a9测试通过，现在可以正常使用这张地图进行游戏

**Comment by NightSkyTS** [comment]
0.99.914a9测试通过，现在可以正常使用这张地图进行游戏

**Comment by Zero-Fanker** [comment]
@klighting444 小碗帮忙归档
