### ISSUE TITLE
#Bug#地图“苏联大镇”没有实装

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#572]
【现象】：地图“苏联大镇”没有实装
【反馈人】：shuiping233
【发现版本号】：0.99.911a2
【影响范围】：遭遇战地图
【产生原因】：未知

**Comment by Zero-Fanker** [comment]
@shuiping233 @Renko-ji 0.99.911a3已修复

**Comment by shuiping233** [comment]
0.99.911a3测试通过
