### ISSUE TITLE
#Bug#地图“末日森林”缩略图的出生点位置异常且读取后游戏崩溃

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#573]
【现象】：客户端缩略图位置显示异常，进入地图弹窗
【反馈人】：shuiping233
【发现版本号】：0.99.911a2
【影响范围】：遭遇战地图
【产生原因】：未知
![image](https://user-images.githubusercontent.com/49360196/141608667-59f50398-09db-4cac-9655-6cb067afab3f.png)

![image](https://user-images.githubusercontent.com/49360196/141608654-f5d9ae4f-81c2-4943-9072-21eb99779201.png)

**Comment by Zero-Fanker** [comment]
@Fantasycho

**Comment by Zero-Fanker** [comment]
0.99.914a8 已修复

**Comment by NightSkyTS** [comment]
0.99.914a9测试通过，可以正常进入游戏并游玩

**Comment by shuiping233** [comment]
@klighting444 请帮忙归档

**Comment by Zero-Fanker** [comment]
> @klighting444 请帮忙归档

归档归档，最近准备研究下脚本归档
