### ISSUE TITLE
#Bug# 地图“人定胜天”存在缩略图问题以及缺少部分中立建筑

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#574]
【现象】：地图“人定胜天”有缩略图问题，以及原有放置中立建筑的特殊地块没有了建筑，显得地图突兀	
【反馈人】：shuiping233
【发现版本号】：0.99.911a2
【影响范围】：遭遇战地图
【产生原因】：未知
![image](https://user-images.githubusercontent.com/49360196/141609321-0f094803-268c-4404-9fa2-d8157925c9ac.png)

**Comment by Zero-Fanker** [comment]
@@Fantasycho

**Comment by Zero-Fanker** [comment]
0.99.914a8 已修复

**Comment by NightSkyTS** [comment]
艾兰：0.99.914a9测试通过
![1](https://user-images.githubusercontent.com/78950858/183972627-744d031a-d4c9-49b7-af44-9950153b6460.png)
![2](https://user-images.githubusercontent.com/78950858/183972668-06a6d361-e0e7-477c-a886-3581b329e2cd.png)
![3](https://user-images.githubusercontent.com/78950858/183972768-3fc9ca0e-4785-4fbe-aa76-2dc46bf99208.png)

**Comment by Zero-Fanker** [comment]
@klighting444 小碗帮忙归档
