### ISSUE TITLE
#Bug#地图“ 攻击与防御豪华版”有缩略图问题且AI会在此图水面生产海军

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#575]
【现象】：地图“ 攻击与防御豪华版”有缩略图问题且ai会在此图水面生产海军
【反馈人】：shuiping233
【发现版本号】：0.99.911a2
【影响范围】：遭遇战地图
【产生原因】：未知

![image](https://user-images.githubusercontent.com/49360196/141609434-78111393-df50-4ebc-bc72-2fc8561f093f.png)

**Comment by Zero-Fanker** [comment]
@Fantasycho

**Comment by Zero-Fanker** [comment]
请描述清楚缩略图问题

**Comment by shuiping233** [comment]
全息缩略图中含有心灵终结的中立建筑

**Comment by Zero-Fanker** [comment]
0.99.914a8 已修复

**Comment by NightSkyTS** [comment]
0.99.914a9初步测试通过，预览图没有不该存在的东西，船坞在此地图无法建造

**Comment by shuiping233** [comment]
@klighting444 请按0.99.914a9归档
