### ISSUE TITLE
#Bug#地图“ 一小块地城市版”缩略图出生点位置异常且1号位上方有不可建造的地块

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#576]
【现象】：地图“ 一小块地城市版”载入时预览图出生点位置异常；1号位上方有不可建造的地块，扩大一下地图大小和边界就可以解决了
【反馈人】：shuiping233
【发现版本号】：0.99.911a2
【影响范围】：遭遇战地图
【产生原因】：未知
![image](https://user-images.githubusercontent.com/14891010/180222290-ecf3b0d5-7aa3-433a-ac84-414d35500ecd.png)
![image](https://user-images.githubusercontent.com/49360196/141609528-ece03ebc-4c18-4797-8064-641e38a69633.png)

**Comment by Zero-Fanker** [comment]
@Fantasycho

**Comment by Zero-Fanker** [comment]
0.99.914a8 已修复

**Comment by NightSkyTS** [comment]
0.99.914a9测试通过
![1](https://user-images.githubusercontent.com/78950858/183932024-ebea8d88-8509-4d5a-8f6b-f0f722d381bb.png)
![2](https://user-images.githubusercontent.com/78950858/183932095-d73ebbc8-fc63-4176-b59b-c463a7a3d491.png)

**Comment by Zero-Fanker** [comment]
@klighting444 小碗帮忙归档
