### ISSUE TITLE
#Bug#地图"特区暴动"AI不会进攻玩家以及缺少了所有的矿井

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#577]
【现象】：特区暴动AI不会打人以及没有矿井
【反馈人】：咸老师 
【发现版本号】：0.99.911a2
【影响范围】：遭遇战
![image](https://user-images.githubusercontent.com/49360196/141647128-0cb654d9-105b-4587-926f-3c549fb057bc.png)

**Comment by Zero-Fanker** [comment]
@shuiping233 @Renko-ji 0.99.911a3已修复

**Comment by shuiping233** [comment]
0.99.911a3测试通过，4个出生点位置隔壁都有一个矿井了
![Snipaste_2021-11-20_21-44-20](https://user-images.githubusercontent.com/49360196/142728671-cd786ee0-c6fb-474d-beca-b1362f2273b5.png)
![Uploading Snipaste_2021-11-20_21-44-08.png…]()
