### ISSUE TITLE
#Bug#苏联核反应堆建造动画在部分气候地形场景仍然是绿色

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#580]
【现象】：沙漠、月球、新城区（YR新增）的核反应堆建造动画中辐射效果部分仍然为原版的绿色，而非新的橙色
【反馈人】：
【发现版本号】：0.99.910
【影响范围】：影响一些气候地形场景核电厂动画的一致性
【产生原因】：未覆盖到这些气候场景

**Comment by Zero-Fanker** [comment]
@shuiping233 @Renko-ji 0.99.911a3已修复

**Comment by shuiping233** [comment]
![gif238](https://user-images.githubusercontent.com/49360196/142728461-c6377c82-d671-43a3-9c79-e1f6d779a070.gif)
![gif237](https://user-images.githubusercontent.com/49360196/142728466-a6817d8b-1fd1-4a66-98d7-c6cd55eb0909.gif)
![gif236](https://user-images.githubusercontent.com/49360196/142728473-bdf8f5a9-eaf5-4efe-8af9-59f7dbd74b62.gif)
0.99.911a3测试通过

**Comment by Zero-Fanker** [comment]
是建造动画，不是工作动画

**Comment by shuiping233** [comment]
哦，那我补个图，
![gif241](https://user-images.githubusercontent.com/49360196/142728932-585a43b8-7aaa-4ea4-b782-e60a82c18fc2.gif)
![gif240](https://user-images.githubusercontent.com/49360196/142728934-cb6dc4ae-f019-47e7-b247-e11abc2bc263.gif)
![gif239](https://user-images.githubusercontent.com/49360196/142728935-f5dabbd4-fb70-4648-aa92-eb01ba7a6792.gif)
