### ISSUE TITLE
#Bug#尤里雕像在温和地形也显示为雪地样式

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#586]
【现象】：如题
【反馈人】：
【发现版本号】：0.99.910
【影响范围】：影响非雪地气候地形的尤里雕像图像展示
【产生原因】：参数填错

**Comment by Zero-Fanker** [comment]
0.99.912a 已调整 @Renko-ji @shuiping233

**Comment by shuiping233** [comment]
0.99.912a测试通过，测试员：suli
