### ISSUE TITLE
#Bug#【CNCNet客户端】多人游戏下房主更改初始金钱选项的提示未翻译

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#587]
【现象】：显示为“Starting Credit”，需要翻译
【反馈人】：
【发现版本号】：0.99.910
【影响范围】：影响多人更改金钱数额
【产生原因】：翻译遗漏

**Comment by Zero-Fanker** [comment]
0.99.912a 已调整 @Renko-ji @shuiping233

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/146643082-cdeed404-5b46-4e2a-9f91-32eb42dcd46f.png)
0.99.912a2测试通过
