### ISSUE TITLE
#Bug#部分涉及CN的地图未正确显示版图

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#588]
【现象】：涉及CN藏南地区的地图版图错误，需要修正（客户端的局势演进和越南的载入图）
【反馈人】：
【发现版本号】：0.99.910
【影响范围】：版图显示，原则问题
【产生原因】：使用的原始地图素材版图规划错误

**Comment by Zero-Fanker** [comment]
0.99.912a 已调整 @Renko-ji @shuiping233 @a-small-c4

**Comment by shuiping233** [comment]
![Snipaste_2021-12-18_23-06-30](https://user-images.githubusercontent.com/49360196/146646366-880a1a45-188b-4ff7-a853-b9f26850402d.png)
![Snipaste_2021-12-18_23-11-10](https://user-images.githubusercontent.com/49360196/146646368-568a3a96-1288-4a3a-97eb-760e28a9d5b1.png)
![Snipaste_2021-12-18_23-11-05](https://user-images.githubusercontent.com/49360196/146646369-3f936acf-0470-4d39-9cbd-2ab405031684.png)
![Snipaste_2021-12-18_23-09-29](https://user-images.githubusercontent.com/49360196/146646370-683b90c6-61f3-488b-ba61-1cc5b6efc76c.png)
![Snipaste_2021-12-18_23-08-39](https://user-images.githubusercontent.com/49360196/146646371-5743c8ba-4502-44f8-9c7e-9a690305789e.png)
![Snipaste_2021-12-18_23-06-36](https://user-images.githubusercontent.com/49360196/146646372-c2c7fa9e-07ee-4b76-8453-7cf11751edc3.png)
我比对了一下，没发现问题，0.99.912a2测试通过
