### ISSUE TITLE
#Bug#存在一个在部分地形下没有模型的亮瞎狗眼的聚光灯

### ISSUE THREAD

**Issue by A-small-C4** [Zero-Fanker/RN_All_Issues#589]
【现象】：存在一个在部分地形下没有模型的亮瞎狗眼的聚光灯
【发现版本号】：0.99.911
【影响范围】：遭遇战、多人联机
【产生原因】：存在一个在部分地形下没有模型的亮瞎狗眼的聚光灯
![QQ图片20211129134521](https://user-images.githubusercontent.com/52919411/144045148-9433008c-d96f-4fab-a32e-48fa743a9561.png)

**Comment by Zero-Fanker** [comment]
同 #749
