### ISSUE TITLE
#Bug#尤里第一关结束后结语为盟军第一关的结语

### ISSUE THREAD

**Issue by Suli1337** [Zero-Fanker/RN_All_Issues#591]
【现象】：如图，关卡结束后本关结语不正确
【反馈人】：Suli
【发现版本号】：0.99.911
【影响范围】：通关后影响玩家了解剧情
【产生原因】：关联错误？
![A~P6AN3SR$DKTW9MJW~_$0E](https://user-images.githubusercontent.com/85695579/144369113-0691f4ab-9559-483b-85a9-5797e7825bb6.png)

**Comment by Zero-Fanker** [comment]
根本原因是尤里的军衔称呼一直没有定，而这里是会有影响的

**Comment by Zero-Fanker** [comment]
@shuiping233 @kk7k7k558  0.99.916a 已包含

**Comment by shuiping233** [comment]
> @shuiping233 @kk7k7k558 @Renko-ji @Crossfield-ClassDestroyer 0.99.916a 已包含

0.99.916a测试未通过，通关文本显示为“未超时说明”
![image](https://github.com/user-attachments/assets/489abbe5-f521-4547-958d-3086cb9d9131)
