### ISSUE TITLE
#Bug#法国布雷车部署的地雷可以被售卖获得资金

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#597]
【现象】：法国布雷车部署的地雷可以被售卖，可以刷钱
【反馈人】：政委
【发现版本号】：0.99.911
【影响范围】：遭遇战
【产生原因】：未知

![gif249](https://user-images.githubusercontent.com/49360196/144749309-bd8cb375-c703-4494-a6fb-1b1d9d72bad7.gif)

**Comment by Zero-Fanker** [comment]
已下调变卖金额。详情见 RN_Internal_Issues/issues/335

**Comment by shuiping233** [comment]
下调完成，后续改进详见 Zero-Fanker/RN_Internal_Issues/issues/335
将此issue归档
