### ISSUE TITLE
#建议反馈#希望有某种方案解决尤里ai基地车骑脸失败后玩家极难寻找的问题

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#598]
【描述】希望有某种方案解决尤里ai基地车骑脸失败后玩家极难寻找的问题，暂时没想到好方案
【原因】这个感觉挺恶心玩家了
【期望解决时间】will be done

[注]:不按照格式填写会被视作无效。

**Comment by Zero-Fanker** [comment]
该建议不予采纳。要么查明是不是基地车卡bug，要么避免AI这样做
