### ISSUE TITLE
#优化#给友方设置的手动引爆的伊文炸弹不播放计时音效

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#599]
【描述】：期望给友方设置的手动引爆的伊文炸弹不播放计时音效，声音有点扰民了

【反馈人】：zero fanker

**Comment by Zero-Fanker** [comment]
0.99.912a 已调整 @Renko-ji @shuiping233 @mariodad3

**Comment by shuiping233** [comment]
0.99.912a测试通过，测试员：咸老师
