### ISSUE TITLE
#Bug#双子湖地图客户端预览错误，出生点位置错误

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#601]
【现象】：如标题
【反馈人】：
【发现版本号】：0.99.911
【影响范围】：影响双子湖地图的使用
【产生原因】：地图师未做完

**Comment by Zero-Fanker** [comment]
@mariodad3

**Comment by Zero-Fanker** [comment]
0.99.912a 已调整 @Renko-ji @shuiping233

**Comment by shuiping233** [comment]
0.99.912a测试通过，测试员：suli
