### ISSUE TITLE
#Bug#多人模式下美国超时空载具平台可以通过改变盟友关系突破建造限制

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#604]
【现象】：多人组队时，通过暂时解除结盟占领友方超时空平台，可以绕过超时空平台建造限制，造出任意数量的超时空平台
【反馈人】：
【发现版本号】：0.99.911
【影响范围】：影响多人组队时的平衡性
【产生原因】：超时空平台可占领存在漏洞

**Comment by Zero-Fanker** [comment]
0.99.912a 已调整 @Renko-ji @shuiping233 @mariodad3

**Comment by shuiping233** [comment]
0.99.912a测试通过，测试员：suli
