### ISSUE TITLE
#Bug#核子天启坦克可以通过美国超时空传送平台得到复制

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#605]
【现象】：如题
【反馈人】：@mariodad3
【发现版本号】：0.99.911
【影响范围】：影响用有超时空传送平台后可建造核子天启坦克的平衡性
【产生原因】：未考虑到该情形

**Comment by Zero-Fanker** [comment]
0.99.912a 已调整 @Renko-ji @shuiping233 @mariodad3

**Comment by shuiping233** [comment]
0.99.912a测试通过，测试员：suli
