### ISSUE TITLE
#Bug#AI攻城机甲从载具工厂走出而非传送

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#607]
【现象】：ai攻城机甲从重工出来，还会穿模
【反馈人】：皮总
【发现版本号】：0.99.911
【影响范围】：视觉体验
【产生原因】：未知

[注释]:例子：
[注释]:【现象】：韩国火炮、洲际导弹的信标可以被超时空传送、铁幕装置影响
[注释]:【反馈人】：永恒_叶
[注释]:【发现版本号】：0.99.F1028A
[注释]:【影响范围】：影响带有AI的对局
[注释]:【产生原因】：AI新机制引入

**Comment by Zero-Fanker** [comment]
0.99.912a2 已尝试调整，请观察

**Comment by shuiping233** [comment]
咸：测试并无此问题    Suli：测试中发现拥有老兵升级的攻城机甲在出厂后向工厂预集合点移动的过程中会出现老兵图标
待归档，新问题我去提单

**Comment by Zero-Fanker** [comment]
> 咸：测试并无此问题 Suli：测试中发现拥有老兵升级的攻城机甲在出厂后向工厂预集合点移动的过程中会出现老兵图标 待归档，新问题我去提单

试过AI是否能正常带队出击吗？还是说会堵在家里

**Comment by shuiping233** [comment]
待观察



---原始邮件---
发件人: "Zero ***@***.***&gt;
发送时间: 2022年1月15日(周六) 晚上7:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#AI攻城机甲从载具工厂走出而非传送 (Issue #607)




  
咸：测试并无此问题 Suli：测试中发现拥有老兵升级的攻城机甲在出厂后向工厂预集合点移动的过程中会出现老兵图标 待归档，新问题我去提单
  
试过AI是否能正常带队出击吗？还是说会堵在家里
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shuiping233** [comment]
0.9.912a2测试通过，其余问题将另开issue
