### ISSUE TITLE
#Bug#美国大兵/海豹突击队-多功能步兵车的武器能穿透大型建筑物

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#609]
【现象】：多功能步兵车的武器能穿透大型建筑物
【反馈人】：shuiping233
【发现版本号】：0.99.912a
【影响范围】：单位手感
【产生原因】：未考虑该该场景

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/145715875-81de63e0-6d3c-4f15-8dc5-1e13ac182e02.png)
这里还有一个附带的问题，工头应该要给海豹ifv和gi ifv添加实体弹道，这会削弱他们的输出，因为子弹有飞行时间

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/145715910-9762a876-d36e-448d-a233-74884a50d776.png)
![image](https://user-images.githubusercontent.com/49360196/145715952-fc0c44d2-e9d2-4a82-9a87-98f33b4ee0a2.png)
![image](https://user-images.githubusercontent.com/49360196/145715956-47681c53-0a51-4533-8276-4dffa266cf8a.png)

**Comment by shuiping233** [comment]
![Snipaste_2021-12-12_22-18-14](https://user-images.githubusercontent.com/49360196/145716144-aae9a357-deab-4f62-b6be-b62b965c633a.png)
![Snipaste_2021-12-12_22-18-09](https://user-images.githubusercontent.com/49360196/145716145-4fa02c4d-6ea2-44e4-8d79-892dde332b6f.png)
![image](https://user-images.githubusercontent.com/49360196/145716150-81370a5c-4241-4a9f-bb63-f38aa14c4d42.png)

**Comment by Zero-Fanker** [comment]
0.99.913a6 已修复 @shuiping233 @NightSkyTS @yuanbanlao

**Comment by NightSkyTS** [comment]
![机炮](https://user-images.githubusercontent.com/78950858/162747235-82bc160b-d19d-4f80-bc9e-1f4d0a820853.gif)
0.99.913a6测试未通过

**Comment by Zero-Fanker** [comment]
> ![机炮](https://user-images.githubusercontent.com/78950858/162747235-82bc160b-d19d-4f80-bc9e-1f4d0a820853.gif) 0.99.913a6测试未通过

看来光加实体弹道没有用，底层机制就不支持，我试了一下所有机炮单位都是这样。看你们觉得有没有必要专门为IFV增加穿透控制，或者是对所有枪械类的火炮类的单位都加上

**Comment by shuiping233** [comment]
> > ![机炮](https://user-images.githubusercontent.com/78950858/162747235-82bc160b-d19d-4f80-bc9e-1f4d0a820853.gif)
> >       
> >         [
> >           
> >         ](https://user-images.githubusercontent.com/78950858/162747235-82bc160b-d19d-4f80-bc9e-1f4d0a820853.gif)
> >         
> >             ![机炮](https://user-images.githubusercontent.com/78950858/162747235-82bc160b-d19d-4f80-bc9e-1f4d0a820853.gif)
> >           
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/78950858/162747235-82bc160b-d19d-4f80-bc9e-1f4d0a820853.gif)
> >         
> >        0.99.913a6测试未通过
> 
> 看来光加实体弹道没有用，底层机制就不支持，我试了一下所有机炮单位都是这样。看你们觉得有没有必要专门为IFV增加穿透控制，或者是对所有枪械类的火炮类的单位都加上

题外话，那个海豹突击队的子弹为啥能被一些奇怪的建筑阻挡

**Comment by shuiping233** [comment]
![gif38](https://user-images.githubusercontent.com/49360196/178223590-722145a8-f522-4789-8f00-810beca7ceaf.gif)
子弹抛射体到底是什么时候才会被阻挡呢，搞不懂

**Comment by Zero-Fanker** [comment]
我暂时在底层允许穿透所有建筑了

**Comment by shuiping233** [comment]
> 我暂时在底层允许穿透所有建筑了

所以目前预期的效果是子弹能穿透除了沙袋以外的任何建筑吗?

**Comment by Zero-Fanker** [comment]
@shuiping233  0.99.916b3 已调整

**Comment by shuiping233** [comment]
0.99.916b3测试通过,现在子弹抛射体可以穿透建筑了
![GIF158](https://github.com/user-attachments/assets/4070c6b8-eb93-4001-b618-bc4a155872a2)
