### ISSUE TITLE
#Bug#AI的韩国忠武级战舰过度影响游戏帧数

### ISSUE THREAD

**Issue by Suli1337** [Zero-Fanker/RN_All_Issues#613]
【现象】：（I5 8500测试环境 [170掉30）韩国的忠武级战舰在韩国AI的情况下，出三艘帧数爆降
再游玩甚至有可能会导致崩溃，玩家韩国出大概10艘左右帧数会有明显的帧数下降（100掉40）
【反馈人】：Suli
【发现版本号】：0.99.911
【影响范围】：多人联机，遭遇战
【产生原因】：忠武级战舰的替身单位问题

**Comment by Zero-Fanker** [comment]
目前分析得出和AI脚本的Hunt行为有关。

**Comment by Zero-Fanker** [comment]
已针对Profile的结果进行了优化缓解。

**Comment by Suli1337** [comment]
在0.99.13a3的针对性测试时未发现性能问题,但私认为后续还需观察

**Comment by Zero-Fanker** [comment]
只要原来有问题的场景已经最大程度缓解了，这个单子就是解决了

**Comment by shuiping233** [comment]
0.99.913a3测试通过

**Comment by Zero-Fanker** [comment]
@klighting444 小碗帮忙归档
