### ISSUE TITLE
#Bug#华盛顿之战地图多人联机时产生崩溃

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#615]
【现象】：华盛顿之战地图多人联机时产生崩溃，但实际上是因为RE引起
[snapshot-20211213-224106.zip](https://github.com/Zero-Fanker/RN_All_Issues/files/7713553/snapshot-20211213-224106.zip)

【反馈人】：@Crossfield-ClassDestroyer
【发现版本号】：0.99.911
【影响范围】：影响华盛顿之战多人联机，以及某些触发有错误的地图联机
【产生原因】：经过分析，是由于该地图触发调用了一个无意义的触发所致

**Comment by Zero-Fanker** [comment]
现已增加防护，同时对地图无效触发进行了清理

**Comment by Zero-Fanker** [comment]
@shuiping233 0.99.912a3 已修复

**Comment by shuiping233** [comment]
0.99.912a6测试通过
和咸老师打了一局华盛顿，啥事没发生
