### ISSUE TITLE
#Bug#华盛顿之战地图盟军超时空传送仪冷却过短

### ISSUE THREAD

**Issue by Crossfield-ClassDestroyer** [Zero-Fanker/RN_All_Issues#616]
【现象】：华盛顿之战地图盟军超时空传送仪冷却过短

【发现版本号】：0.99.912a
【影响范围】：影响华盛顿之战遭遇战与多人联机平衡性
【产生原因】：可能原因为先前测试数值时忘记清理地图设置。

**Comment by Crossfield-ClassDestroyer** [comment]
已修正并删除多余内置标签

**Comment by Zero-Fanker** [comment]
@shuiping233 0.99.912a2 已调整

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/151644806-057b00ad-27fe-491f-804e-b5ee93408673.png)
0.99.912a2测试通过
