### ISSUE TITLE
#Bug#越南的化学导弹、毒牙轰炸机等产生的次生伤害粒子为病毒，而不是毒雾

### ISSUE THREAD

**Issue by Crossfield-ClassDestroyer** [Zero-Fanker/RN_All_Issues#617]
【现象】：越南的化学导弹、毒牙轰炸机等产生的次生伤害粒子为病毒，而不是毒雾
【反馈人】：
【发现版本号】：0.99.912a
【影响范围】：越南化学导弹武器的特效展示
【产生原因】：未替换其粒子动画效果

**Comment by Zero-Fanker** [comment]
0.99.912a2 已修复 @shuiping233

**Comment by shuiping233** [comment]
![gif268](https://user-images.githubusercontent.com/49360196/146680642-000231cc-6f36-480a-8c8f-a6f1ffbb19f9.gif)
0.99.912a2测试通过
