### ISSUE TITLE
#Bug#间谍偷窃载具工厂无效果

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#618]
【现象】：间谍偷窃载具工厂不再能获得己方载具初始老兵效果
【反馈人】：Suli
【发现版本号】：0.99.912a
【影响范围】：影响间谍单位的使用
【产生原因】：代码修改引入新问题

**Comment by Zero-Fanker** [comment]
0.99.912a2 已修复 @Crossfield-ClassDestroyer @shuiping233

**Comment by shuiping233** [comment]
suli已测试
0.99.912a2测试通过
