### ISSUE TITLE
#Bug#英国单兵碉堡投在部署时候会有UnitLost的播报并且其落地爆炸伤害会影响空中单位

### ISSUE THREAD

**Issue by Crossfield-ClassDestroyer** [Zero-Fanker/RN_All_Issues#622]
【现象】：英国单兵碉堡投在部署时候会有UnitLost的播报并且其落地爆炸伤害会影响空中单位
【发现版本号】：0.99.912a
【影响范围】：游戏体验和平衡性
【产生原因】：设计问题

**Comment by Zero-Fanker** [comment]
@shuiping233 0.99.912a3 已修复

**Comment by NightSkyTS** [comment]
0.99.912a4依旧有此问题，测试地图为火线冲突
![111](https://user-images.githubusercontent.com/78950858/151733094-c53941f7-3aa7-4bef-a8c5-23adc547a5c4.gif)

**Comment by Zero-Fanker** [comment]
> 0.99.912a4依旧可以对空，未发现其他问题，测试地图为火线冲突 ![111](https://user-images.githubusercontent.com/78950858/151733094-c53941f7-3aa7-4bef-a8c5-23adc547a5c4.gif)

0.99.912a5 空中影响已调整

**Comment by shuiping233** [comment]
![gif309](https://user-images.githubusercontent.com/49360196/151913320-a1a9666c-fd62-4e5b-88de-7f97f28fbfd3.gif)
0.99.912a5测试通过
