### ISSUE TITLE
#Bug#雪地下，法国要塞墙一个方向的驻扎图像有误

### ISSUE THREAD

**Issue by A-small-C4** [Zero-Fanker/RN_All_Issues#625]
【现象】：雪地下，法国要塞墙其中一个方向的驻扎图像有误，正常状态下显示为损毁状态下的沙包铁丝网。
【发现版本号】：0.99.912a
【影响范围】：遭遇战、多人联机
【产生原因】：？？？
![QQ图片20211221150428](https://user-images.githubusercontent.com/52919411/146879804-bee1bd57-1c36-4ea8-9c0a-1fca4f11ddc7.png)

**Comment by Zero-Fanker** [comment]
好吧，我去看看是不是文件帧弄错了

**Comment by Zero-Fanker** [comment]
你是不是弄错了，损毁的长这样：
![image](https://user-images.githubusercontent.com/14891010/147099683-9c82a8c0-360a-4106-9fc7-196cd103dc32.png)

**Comment by Zero-Fanker** [comment]
@shuiping233 0.99.912a3 已修复

**Comment by RN-Hydra** [comment]
经测试无问题
![QQ图片20220130104025](https://user-images.githubusercontent.com/48992878/151684631-33525695-ca9e-4519-bad6-2da90e59cf20.png)
