### ISSUE TITLE
#Bug#盟军超时空传送仪雪地场景建造动画帧错误

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#626]
【现象】：在雪地场景下，盟军超时空传送仪最后几帧有两帧有问题
【反馈人】：
【发现版本号】：原版
【影响范围】：雪地地图盟军超时空传送仪建造摆放视觉效果
【产生原因】：WW渲染模型的时候关键帧错误

**Comment by shuiping233** [comment]
0.99.912a5测试结果：我不知道“最后的两帧”是指什么问题，但是我自己发现了一些问题
![image](https://user-images.githubusercontent.com/49360196/151936592-0958bb38-8829-4b41-a117-3972d51602f4.png)
上图展示了当停电状态时部署超时空传送仪时发现的问题
![111](https://user-images.githubusercontent.com/49360196/151936753-fc21fb42-25d4-478d-aa81-f2fccb510e98.png)
![112](https://user-images.githubusercontent.com/49360196/151936759-6d6ee762-d02c-4138-9fbc-7fc68111a98b.png)
![Snipaste_2022-02-01_16-33-11](https://user-images.githubusercontent.com/49360196/151936778-d3379ff5-a26a-4ad5-996c-c146b69c6775.png)
而上述三张图则展示了另一个问题，超时空建造动画和建造完成后的模型有是有一处不匹配的地方的

**Comment by Zero-Fanker** [comment]
> 0.99.912a5测试结果：我不知道“最后的两帧”是指什么问题，但是我自己发现了一些问题 ![image](https://user-images.githubusercontent.com/49360196/151936592-0958bb38-8829-4b41-a117-3972d51602f4.png) 上图展示了当停电状态时部署超时空传送仪时发现的问题 ![111](https://user-images.githubusercontent.com/49360196/151936753-fc21fb42-25d4-478d-aa81-f2fccb510e98.png) ![112](https://user-images.githubusercontent.com/49360196/151936759-6d6ee762-d02c-4138-9fbc-7fc68111a98b.png) ![Snipaste_2022-02-01_16-33-11](https://user-images.githubusercontent.com/49360196/151936778-d3379ff5-a26a-4ad5-996c-c146b69c6775.png) ![image](https://user-images.githubusercontent.com/49360196/151937044-8dbf68f9-df8a-403e-8819-5e40668619cd.png) ![image](https://user-images.githubusercontent.com/49360196/151937090-661873d2-4c4d-48a7-b66d-70cef53d92b8.png)
> 
> 而上述⑤张图则展示了另一个问题，超时空建造动画和建造完成后的模型有是有一处不匹配的地方的

你说的这个不是雪地帧问题

**Comment by shuiping233** [comment]
那这个单子我归档了？ 
@Zero-Fanker

**Comment by Zero-Fanker** [comment]
> 那这个单子我归档了？ @Zero-Fanker

归档

**Comment by Zero-Fanker** [comment]
@klighting444 小碗帮忙归档
