### ISSUE TITLE
#优化#调整遭遇战玩家可选颜色

### ISSUE THREAD

**Issue by Suli1337** [Zero-Fanker/RN_All_Issues#627]
【描述】现在游戏内的阵营区分度兵不明显，部分情况下游戏体验不好，尤其是绿色
【原因】在有近似色阵营情况下，不好区分单位所属，影响对局
【期望解决时间】尽快即可

**Comment by Zero-Fanker** [comment]
你之前说的是绿色吗

**Comment by Suli1337** [comment]
是,但是好像不仅仅是绿色

**Comment by Suli1337** [comment]
不过好像也只是绿色

**Comment by shuiping233** [comment]
那我来整个绿的看看

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/152672526-19c202f0-1cb0-445e-8e61-01f8ff179dc8.png)

**Comment by shuiping233** [comment]
![Snipaste_2022-02-06_16-07-25](https://user-images.githubusercontent.com/49360196/152672559-65970083-37ed-41b8-b797-bdd84c243f85.png)

![Snipaste_2022-02-06_16-07-18](https://user-images.githubusercontent.com/49360196/152672563-c9af70af-a9f8-4761-b671-4fc8361f52ec.png)
说的很对，要不是ai行为比较独特，我都分不出了

**Comment by Zero-Fanker** [comment]
0.99.913a7 已调整，并且加入了更多颜色

**Comment by xuetianyi** [comment]
强烈建议取消棕色（屎黄色），在小地图上，特别是沙漠地形上，棕色相当于在小地图上隐身了。


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Zero Fanker ***@***.***&gt;
发送时间: 2022年4月15日 20:55
收件人: Zero-Fanker/RN_All_Issues ***@***.***&gt;
抄送: xuetianyi ***@***.***&gt;, Assign ***@***.***&gt;
主题: 回复：[Zero-Fanker/RN_All_Issues] #建议反馈#希望提高阵营颜色的区分度 (Issue #627)





 
0.99.913a7 已调整，并且加入了更多颜色

**Comment by Zero-Fanker** [comment]
> 强烈建议取消棕色（屎黄色），在小地图上，特别是沙漠地形上，棕色相当于在小地图上隐身了。 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Zero Fanker ***@***.***&gt; 发送时间: 2022年4月15日 20:55 收件人: Zero-Fanker/RN_All_Issues ***@***.***&gt; 抄送: xuetianyi ***@***.***&gt;, Assign ***@***.***&gt; 主题: 回复：[Zero-Fanker/RN_All_Issues] #建议反馈#希望提高阵营颜色的区分度 (Issue #627) 0.99.913a7 已调整，并且加入了更多颜色 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were assigned.Message ID: ***@***.***&gt;

没这么夸张吧，隐形了？

**Comment by NightSkyTS** [comment]
![111111](https://user-images.githubusercontent.com/78950858/163586567-bd2a348c-0afd-4043-b9df-25e5a74c82ef.png)
![SCRN 20220415-223843-00999](https://user-images.githubusercontent.com/78950858/163586643-ae8a6237-98c1-423d-b149-df01c43b776a.jpg)
![QQ图片20220415230057](https://user-images.githubusercontent.com/78950858/163586708-b66762a5-af61-4ce7-94ba-9ce6631187ae.png)
0.99.913a7测试完毕，颜色可任意选择，颜色分辨度提升，深棕色在沙漠地图上确实挺难从小地图上分辨

**Comment by Zero-Fanker** [comment]
> ![111111](https://user-images.githubusercontent.com/78950858/163586567-bd2a348c-0afd-4043-b9df-25e5a74c82ef.png) ![SCRN 20220415-223843-00999](https://user-images.githubusercontent.com/78950858/163586643-ae8a6237-98c1-423d-b149-df01c43b776a.jpg) ![QQ图片20220415230057](https://user-images.githubusercontent.com/78950858/163586708-b66762a5-af61-4ce7-94ba-9ce6631187ae.png) 0.99.913a7测试完毕，颜色可任意选择，颜色分辨度提升，深棕色在沙漠地图上确实挺难从小地图上分辨

所属色主要都按色阶排列了，如果直接去掉可能跳色怪怪的，我换个别的颜色吧

**Comment by Zero-Fanker** [comment]
![image](https://user-images.githubusercontent.com/14891010/163659221-f04d3765-4af4-4693-af7f-f08ad2c3fff6.png)
这样好些吗

**Comment by Zero-Fanker** [comment]
![image](https://user-images.githubusercontent.com/14891010/163661956-65d1ea95-8744-44ef-99dd-e752408fb140.png)
![image](https://user-images.githubusercontent.com/14891010/163661969-97e891e6-971e-4ca2-815b-8231f4a905e6.png)

另一个色值
