### ISSUE TITLE
#Bug#越南毒气系粒子动画跳帧现象

### ISSUE THREAD

**Issue by Crossfield-ClassDestroyer** [Zero-Fanker/RN_All_Issues#628]
【现象】：越南毒气系粒子动画跳帧现象
【发现版本号】：0.99.912a2
【影响范围】：视觉效果
【产生原因】：套用数值问题

**Comment by Zero-Fanker** [comment]
@shuiping233 0.99.912a3 已修复

**Comment by shuiping233** [comment]
> @shuiping233 0.99.912a3 已修复

说说这个问题是怎么回事，我没能理解

**Comment by Zero-Fanker** [comment]
动画不连贯，没放完整个循环

**Comment by shuiping233** [comment]
![gif300](https://user-images.githubusercontent.com/49360196/151798181-113373fd-a2e4-4b0b-997a-a3a86629e438.gif)
0.99.912a4测试通过
