### ISSUE TITLE
#Bug#意念核心可以直接把降落中的敌方美国空降坦克转为永久拥有

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#631]
【现象】：如题，如图所示
【反馈人】：Reimu_RC
【发现版本号】：0.99.911
【影响范围】：技能手感
【产生原因】：未知

![gif269](https://user-images.githubusercontent.com/49360196/147409520-de8aa7cd-9488-4965-90c0-f1a997c12808.gif)

**Comment by shuiping233** [comment]
![gif273](https://user-images.githubusercontent.com/49360196/147409541-30cf783c-5239-4b1f-802f-c2b98bca14ee.gif)

![gif272](https://user-images.githubusercontent.com/49360196/147409545-0ad2176a-53b4-4831-8ce9-fd202bf1561b.gif)
未发行的内部版本已修复此问题，待实装

**Comment by Zero-Fanker** [comment]
@shuiping233 0.99.912a3 已修复。你上次说会有其它问题是什么问题

**Comment by shuiping233** [comment]
> @shuiping233 0.99.912a3 已修复。你上次说会有其它问题是什么问题

我忘了，我翻翻看有没有什么奇怪问题

**Comment by shuiping233** [comment]
![gif298](https://user-images.githubusercontent.com/49360196/151777590-a6ce2852-591f-4e43-ab20-9cf6c335efb1.gif)

0.99.912a4测试通过

**Comment by shuiping233** [comment]
> @shuiping233 0.99.912a3 已修复。你上次说会有其它问题是什么问题

![image](https://user-images.githubusercontent.com/49360196/151778097-2c5954a2-7cc4-4bee-8972-8ef6e32f628f.png)
是声音问题吧，是工头你问的，刚刚仔细听了一下，没发现问题
