### ISSUE TITLE
#Bug#谭雅会使用手枪攻击逆火战略核轰炸机

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#632]
【现象】：如题，如图所示
【反馈人】：shuiping233
【发现版本号】：0.99.912a2
【影响范围】：单位手感
【产生原因】：未考虑到该场景

![gif271](https://user-images.githubusercontent.com/49360196/147409600-678552c3-2cbf-4c16-9d49-9ab12f048b99.gif)

**Comment by Zero-Fanker** [comment]
那其他飞行器呢

**Comment by shuiping233** [comment]
![gif274](https://user-images.githubusercontent.com/49360196/147485434-5ddb84aa-4ea2-449c-9b17-e9bdaa5b6444.gif)
如图所示，pvp能出的飞机都是谭妈用c4炸（

**Comment by Zero-Fanker** [comment]
@Crossfield-ClassDestroyer 驱逐把谭雅主武器弹头对逆火的的空中护甲做个调整吧

**Comment by Zero-Fanker** [comment]
0.99.912a3已修复 @shuiping233

**Comment by shuiping233** [comment]
![gif333](https://user-images.githubusercontent.com/49360196/152165603-928d9a2f-4e2c-4dc0-94ee-8de35ac95c30.gif)
0.99912a6测试通过
