### ISSUE TITLE
#Bug#【CNCNet客户端】玩家或AI都选择同一个队伍时仍然能启动游戏

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#635]
【现象】：如题
【反馈人】：@Zero-Fanker
【发现版本号】：0.99.911
【影响范围】：影响遭遇战体验
【产生原因】：CNCNet原生逻辑不合理

**Comment by Zero-Fanker** [comment]
对标原版YR，现在不再允许

**Comment by Zero-Fanker** [comment]
0.99.913a4 已调整

**Comment by NightSkyTS** [comment]
0.99.913a6测试通过
![QQ图片20220317205440](https://user-images.githubusercontent.com/78950858/158812919-589c94db-9f69-4eb2-b653-d875f70f56d9.png)

**Comment by Zero-Fanker** [comment]
> 0.99.913a6测试通过 ![QQ图片20220317205440](https://user-images.githubusercontent.com/78950858/158812919-589c94db-9f69-4eb2-b653-d875f70f56d9.png)

多人下也要试试，我自己试是没问题的，不过需要你们再次确认一下

**Comment by NightSkyTS** [comment]
![QQ图片20220501111154](https://user-images.githubusercontent.com/78950858/166130605-a41481d7-6df4-4756-84ae-30c3b0b00962.png)
0.99.913a8联机状态测试通过

**Comment by Zero-Fanker** [comment]
@klighting444 小碗帮忙归档
