### ISSUE TITLE
#建议反馈#暴风摩托不应该被基因突变器击杀

### ISSUE THREAD

**Issue by Suli1337** [Zero-Fanker/RN_All_Issues#637]
【描述】希望暴风摩托可以免疫基因突变器
【原因】不符合此单位设定
【期望解决时间】尽快

**Comment by Zero-Fanker** [comment]
你看下0.99.912a4是不是已经解决了

**Comment by shuiping233** [comment]
![gif332](https://user-images.githubusercontent.com/49360196/152124400-21d8883f-cc38-49e3-936a-7a35da33b98a.gif)
我只能说工头突变是单位消失魔法了

**Comment by Zero-Fanker** [comment]
@shuiping233 @kk7k7k558 @Renko-ji @Crossfield-ClassDestroyer   0.99.916a 已包含

**Comment by shuiping233** [comment]
0.99.916a测试通过，基因突变不再会让暴风摩托消失了
![GIF115](https://github.com/user-attachments/assets/00f3ca5d-e8fd-443b-8092-c8c7ae4228fa)
