### ISSUE TITLE
#Bug#【CNCNet客户端】客户端错别字“登陆”应该为“登录”

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#638]
【现象】：在用户登录的地方应该叫“登录”
【反馈人】：
【发现版本号】：0.99.911
【影响范围】：CNCNet登录提示
【产生原因】：文字错误

**Comment by Zero-Fanker** [comment]
@shuiping233 0.99.912a3 已修复

**Comment by RN-Hydra** [comment]
游戏设置里的CnCNet消息里的略过登陆窗口没有改

**Comment by Zero-Fanker** [comment]
> 游戏设置里的CnCNet消息里的略过登陆窗口没有改

0.99.912a4 已修复

**Comment by NightSkyTS** [comment]
0.99.912a4测试通过
![1](https://user-images.githubusercontent.com/78950858/151733767-538c0cf4-2120-40ed-b52a-3d9a9d8877fb.png)
![2](https://user-images.githubusercontent.com/78950858/151733779-775ccaed-814f-4860-8a3c-7a6f9525e94c.png)
