### ISSUE TITLE
#Bug#地图 热带泪痕 开局数分钟后未响应

### ISSUE THREAD

**Issue by A-small-C4** [Zero-Fanker/RN_All_Issues#639]
【现象】：遭遇战选择地图 热带泪痕 后开局数分钟后未响应，画面冻住，地图音效仍正常播放。已经出现多次。
【发现版本号】：0.99.912a
【影响范围】：遭遇战
【产生原因】：地图或存在问题

![QQ图片20220109132456](https://user-images.githubusercontent.com/52919411/148669625-dad4830f-df0d-40d5-ba5c-e05146e60da4.png)
![QQ图片20220109132520](https://user-images.githubusercontent.com/52919411/148669630-3bba04f7-dc18-49fa-ace1-4211a1849a4b.png)
![QQ图片20220109133032](https://user-images.githubusercontent.com/52919411/148669631-54c9a13d-b421-42a1-9e80-34170396ee5a.png)

**Comment by Zero-Fanker** [comment]
根据分析该地图触发的标签有问题。

**Comment by Zero-Fanker** [comment]
@shuiping233 0.99.912a3 已修复

**Comment by RN-Hydra** [comment]
经测试无问题，不过奇怪的就是开启快速游戏，另外7家AI全是友军的情况下，歼灭其中一方友军就判断游戏结束算正常吗

**Comment by shuiping233** [comment]
> 经测试无问题，不过奇怪的就是开启快速游戏，另外7家AI全是友军的情况下，歼灭其中一方友军就判断游戏结束算正常吗

其他图咧，要是也这样我也试试

**Comment by shuiping233** [comment]
> 经测试无问题，不过奇怪的就是开启快速游戏，另外7家AI全是友军的情况下，歼灭其中一方友军就判断游戏结束算正常吗

其他图咧，要是也这样我也试试

**Comment by Zero-Fanker** [comment]
> 经测试无问题，不过奇怪的就是开启快速游戏，另外7家AI全是友军的情况下，歼灭其中一方友军就判断游戏结束算正常吗

这是属于另一个Bug的范畴，因为允许同队开局，我等会去禁掉不就没这个问题了吗

**Comment by shuiping233** [comment]
> > 经测试无问题，不过奇怪的就是开启快速游戏，另外7家AI全是友军的情况下，歼灭其中一方友军就判断游戏结束算正常吗
> 
> 这是属于另一个Bug的范畴，因为允许同队开局，我等会去禁掉不就没这个问题了吗

#635

**Comment by shuiping233** [comment]
归档版本号为0.99.912a4
