### ISSUE TITLE
#Bug#渗透重工后老兵升级的攻城机甲在出厂后向工厂预集合点移动的过程中会出现老兵图标

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#640]
【现象】：如题
【反馈人】：suli
【发现版本号】：0.99.911
【影响范围】：未知
【产生原因】：未知

![gif260](https://user-images.githubusercontent.com/49360196/148794142-38932e0f-5313-4e1f-adfd-bdd64dbe6252.gif)

**Comment by Zero-Fanker** [comment]
0.99.912a5 已修复 @shuiping233

**Comment by shuiping233** [comment]
![gif334](https://user-images.githubusercontent.com/49360196/152264590-1d5b631f-2b49-441c-a816-3b22dd67e1f8.gif)
0.99.912a6测试通过
