### ISSUE TITLE
#Bug# 遭遇战地图“ 大白令海峡 ”中AI无法生产单位

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#642]
【现象】：ai无法生产单位
【发现版本号】：0.99.912
【影响范围】：未知
【产生原因】：未知

**Comment by Zero-Fanker** [comment]
0.99.914a8 已修复

**Comment by NightSkyTS** [comment]
艾兰：0.99.914a9测试通过
![4](https://user-images.githubusercontent.com/78950858/183961977-74322ec7-b284-4b21-b09b-2f1969124d2f.png)

**Comment by Zero-Fanker** [comment]
@shuiping233 @Crossfield-ClassDestroyer  归档
