### ISSUE TITLE
#Bug#遭遇战地图“  猛禽之城 ”中预览图有问题以及载入地图后崩溃

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#644]
【现象】：“  猛禽之城 ”中预览图有问题以及载入地图后崩溃
【发现版本号】：0.99.912
【影响范围】：未知
【产生原因】：未知

[注释]:例子：
[注释]:【现象】：韩国火炮、洲际导弹的信标可以被超时空传送、铁幕装置影响
[注释]:【反馈人】：永恒_叶
[注释]:【发现版本号】：0.99.F1028A
[注释]:【影响范围】：影响带有AI的对局
[注释]:【产生原因】：AI新机制引入

**Comment by Zero-Fanker** [comment]
0.99.914a8 已修复

**Comment by NightSkyTS** [comment]
0.99.914a9测试未通过，现在载入完毕后可以正常进入游戏，不会崩溃，但预览图依旧存在心灵终结的中立建筑
![3](https://user-images.githubusercontent.com/78950858/183940847-bc4a8beb-ef1b-4554-9754-91d3c9b12570.png)

**Comment by shuiping233** [comment]
@klighting444 请按0.99.914a9归档

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/184542815-ec9008ea-0181-4a70-80b2-40474cafda2d.png)
已经更换新的全息缩略图
