### ISSUE TITLE
#Bug#遭遇战地图“  不要踩到鳄鱼 ”载入地图后游戏崩溃

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#645]
【现象】：载入地图后游戏崩溃
【发现版本号】：0.99.912
【影响范围】：未知
【产生原因】：未知

[注释]:例子：
[注释]:【现象】：韩国火炮、洲际导弹的信标可以被超时空传送、铁幕装置影响
[注释]:【反馈人】：永恒_叶
[注释]:【发现版本号】：0.99.F1028A
[注释]:【影响范围】：影响带有AI的对局
[注释]:【产生原因】：AI新机制引入

**Comment by Zero-Fanker** [comment]
0.99.912a4 已修复

**Comment by NightSkyTS** [comment]
0.99.912a4测试通过
