### ISSUE TITLE
#Bug#【CNCNet客户端】有时通过客户端启动游戏返回后用户名会变成字节码

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#647]
【现象】：如题
【反馈人】：
【发现版本号】：0.99.910
【影响范围】：影响玩家名称显示，尤其影响联机
【产生原因】：客户端和原版使用了不同的编码形式

**Comment by Zero-Fanker** [comment]
@shuiping233 0.99.912a4 已修复

**Comment by shuiping233** [comment]
> 

这个要怎么测）

**Comment by Zero-Fanker** [comment]
> > 
> 
> 这个要怎么测）

按旧版启动器修改用户名之后在ra2md.ini里观察Handle字段

**Comment by shuiping233** [comment]
旧版启动器没法复现，新版启动器也没法复现，暂未发现问题
0.99.912a6测试通过
