### ISSUE TITLE
#Bug#【CNCNet客户端】任务列表中选中盟军的-更多内容敬请期待-后开始游戏，会跳转到TR旧版任务的第四关

### ISSUE THREAD

**Issue by IDCK** [Zero-Fanker/RN_All_Issues#649]
【现象】：同理，选中苏军的 -更多任务敬请期待- 后开始游戏，会提示任务无法载入并稳定触发游戏崩溃（出现KABOOOM弹窗），尤里任务列表中则没有 -更多任务敬请期待- 这一行字。
【发现版本号】：0.99.912a3
【影响范围】：未知
【产生原因】：未知

**Comment by shuiping233** [comment]
我补个图
![image](https://user-images.githubusercontent.com/49360196/151708814-17c87a77-5141-41f2-887c-7c8c25fba7b6.png)
![image](https://user-images.githubusercontent.com/49360196/151708823-1cc4d10b-b714-4174-971b-fc3901c1e2f2.png)

**Comment by Zero-Fanker** [comment]
![image](https://github.com/user-attachments/assets/03bbd5f4-4d6d-483c-8f49-da7007d0d6b2)
这个应该也是早就解决了的，但是没归档
