### ISSUE TITLE
#Bug#联机时使用“空投碉堡”支援技能或者呼叫"智能炸弹"会引起游戏同步联机错误

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#652]
【现象】：如题，联机时当空投碉堡和智能炸弹落地爆炸后游戏立刻RE
【反馈人】：shuiping和咸老师
【发现版本号】：0.99.912a4
【影响范围】：游戏稳定性
【产生原因】：未知

![image](https://user-images.githubusercontent.com/49360196/151795917-a76df063-cb71-45cb-9da1-70f627f06e58.png)

**Comment by Zero-Fanker** [comment]
经确认是建筑的PlaceAnywhere所致。

**Comment by shuiping233** [comment]
0.99.915a5测试结果：现在使用空投碉堡已经不会导致RE了，但是智能炸弹仍然会引发RE
智能炸弹的问题已经在未发行的内部版本修复

**Comment by shuiping233** [comment]
0.99.915a6测试通过

**Comment by Zero-Fanker** [comment]
> 0.99.912a4

引入版本号归档时没写啊，下次注意不能遗漏啊！
