### ISSUE TITLE
#Bug#科技中立反坦克炮对苏俄磁能要塞的伤害很高

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#655]
【现象】：如题，如图
【反馈人】：shuiping233
【发现版本号】：0.99.912a7
【影响范围】：未知
【产生原因】：未知
![gif402](https://user-images.githubusercontent.com/49360196/152804159-f1121e5d-e9b6-4d90-ad91-02caf04c51bd.gif)

**Comment by Crossfield-ClassDestroyer** [comment]
这玩意对磁能要塞造成700%伤害，你们决定一下是改比例还是直接删 
相关单位 ：坦克杀手 正常700% 精英800%

**Comment by shuiping233** [comment]
平衡组的讨论的意见是，磁能要塞属于重甲，坦杀的武器应该对磁能要塞造成坦杀对重甲单位一致的伤害

**Comment by Zero-Fanker** [comment]
@shuiping233 ini早就改了，cb5392a5ada386aba54e18278c45b4f43322c7b4，没归档？

**Comment by shuiping233** [comment]
相关commit提交时间是 Mon Jul 04 2022 10:42:24 GMT+0800 ，所以按照0.99.913归档
