### ISSUE TITLE
#Bug#超时空武器冻结超武时，超武不能正常半透明显示

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#656]
【现象】：如题
【反馈人】：
【发现版本号】：0.99.902
【影响范围】：影响超武在被超时空军团武器攻击时的视觉显示
【产生原因】：超武PowerdOffEffect动画没有同步超时空的状态

**Comment by Zero-Fanker** [comment]
@shuiping233 0.99.913a1 已修正

**Comment by shuiping233** [comment]
0.99.913a1测试通过
![gif421](https://user-images.githubusercontent.com/49360196/154824462-7b5bf127-937a-4e5a-8076-ed2a465d55db.gif)
![gif420](https://user-images.githubusercontent.com/49360196/154824464-121c7c8c-43b9-4c66-97f7-43ab377948e0.gif)
![gif419](https://user-images.githubusercontent.com/49360196/154824468-1c729168-7410-4060-a7f8-67eb2b916aac.gif)
