### ISSUE TITLE
#Bug#【CnCNet客户端】有时多人对局结束时保存数据会导致客户端崩溃

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#660]
【现象】：如crashreport
[ClientCrashLog_12_2_2022_22_35.zip](https://github.com/Zero-Fanker/RN_All_Issues/files/8053871/ClientCrashLog_12_2_2022_22_35.zip)

【反馈人】：
【发现版本号】：0.99.912a8
【影响范围】：影响多人对局后的结算体验，可能也会影响单人
【产生原因】：程序设计缺陷，不兼容RN数据

**Comment by shuiping233** [comment]
工头讲讲怎么测这个）

**Comment by Zero-Fanker** [comment]
> 工头讲讲怎么测这个）

这TM很难测，直接归档
