### ISSUE TITLE
#Bug#自动化车间插件以及条顿Ⅱ型无法正常显示单位名称

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#672]
【现象】：如题，如图
【反馈人】：shuiping233
【发现版本号】：0.99.913a1
【影响范围】：未知
【产生原因】：未知
![image](https://user-images.githubusercontent.com/49360196/154826406-8c3a4ff3-1c49-42c4-8980-c382ce0bef21.png)
![image](https://user-images.githubusercontent.com/49360196/154826416-14b9ae4b-20cc-40c6-bb8a-8e66138d1061.png)
![image](https://user-images.githubusercontent.com/49360196/154826419-0670a233-ead1-41e9-9aea-6a0f1aa3a2f3.png)
![image](https://user-images.githubusercontent.com/49360196/154826442-ae051fcd-bdab-4b8e-8bed-f6b68544d59b.png)

**Comment by Zero-Fanker** [comment]
这个好像也是很久以前就解决了的

**Comment by shuiping233** [comment]
emm，就当0.99.916a修复的吧，反正问题已经修复了）
