### ISSUE TITLE
#Bug#基洛夫不能正常接近被设置为攻击目标的友方造船厂

### ISSUE THREAD

**Issue by xuetianyi** [Zero-Fanker/RN_All_Issues#678]
【现象】：类似基洛夫这类单位（武器抛射体里有Vertical=yes的直升机类单位）不响应对水上建筑的攻击（如造船厂）。具体现象是不会往目标建筑建筑飞行，如果手动先飞到船厂跟前再攻击，它会原地扔炸弹，但不会往目标上空飞。对水上单位、步兵、以及任何陆地目标开火时都是正常的。这个bug至少在0.99.905a8版本就存在了，最新版也一样。
【反馈人】：本尊
【发现版本号】：0.99.905a8
【影响范围】：所有存在船厂和基洛夫的场合
【产生原因】：未知

**Comment by shuiping233** [comment]
0.99.913a3测试结果：与问题描述一致，913a3仍有此问题
![gif427](https://user-images.githubusercontent.com/49360196/156884820-48a70410-d3ec-458e-bc51-9adb33018f89.gif)

**Comment by Zero-Fanker** [comment]
@shuiping233 这问题是不是早就修了？

**Comment by Zero-Fanker** [comment]
这个问题确实挺费劲的，没办法找到根本原因。想办法做了缓解，等测试反馈吧

**Comment by Zero-Fanker** [comment]
@shuiping233 @kk7k7k558 @Renko-ji @Crossfield-ClassDestroyer   0.99.916a 已包含

**Comment by shuiping233** [comment]
0.99.916a测试通过，现在基洛夫空艇可以正常强制攻击友方造船厂了
![GIF114](https://github.com/user-attachments/assets/9326c427-43a3-467a-82ef-175cbbc8a24d)
