### ISSUE TITLE
#Bug#精英级磁能要塞开火一段时间后引起崩溃

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#679]
【现象】：如题
【反馈人】：@
【发现版本号】：0.99.913a3
【影响范围】：影响精英级磁能要塞的使用
【产生原因】：ini维护员填错数据，并且程序上未做防护
[snapshot-20220308-203138.zip](https://github.com/Zero-Fanker/RN_All_Issues/files/8207277/snapshot-20220308-203138.zip)

**Comment by Zero-Fanker** [comment]
0.99.913a4 已修复 @Crossfield-ClassDestroyer

**Comment by Crossfield-ClassDestroyer** [comment]
0.99.913a4确认无问题，实际效验版本0.99.913a6 推迟原因 管别的单子忘了这玩意了

**Comment by Zero-Fanker** [comment]
@klighting444 小碗帮忙归档
