### ISSUE TITLE
#Bug#“生死斗”模式空军科技限制不一致

### ISSUE THREAD

**Issue by NightSkyTS** [Zero-Fanker/RN_All_Issues#681]
【现象】：米格，鹰眼，黑鹰都允许建造，仅入侵者无法建造
【发现版本号】：0.99.911
![SCRN 20220313-180924-00244](https://user-images.githubusercontent.com/78950858/158055037-762972a1-fd5d-4586-8a22-a30bf25e4f35.jpg)
![SCRN 20220313-180738-00075](https://user-images.githubusercontent.com/78950858/158055061-3e56cb1d-cecb-4da0-99a9-a6a42efd6014.jpg)
![SCRN 20220313-180603-00492](https://user-images.githubusercontent.com/78950858/158055072-3ec5f721-8934-4af6-ac11-9d59911e6abc.jpg)
![SCRN 20220313-182405-00589](https://user-images.githubusercontent.com/78950858/158055440-15f8b8ac-eb65-4111-8bfa-722ae50c1db9.jpg)

**Comment by Zero-Fanker** [comment]
除此之外，还有没有别的不合理的？

**Comment by NightSkyTS** [comment]
> 除此之外，还有没有别的不合理的？

从个人来看，没有别的不合理的地方了

**Comment by Zero-Fanker** [comment]
0.99.914a6 已修复

**Comment by NightSkyTS** [comment]
0.99.914a6测试通过，因黑鹰战机是阵营特色单位，故维持现状
![入侵者](https://user-images.githubusercontent.com/78950858/177238068-86aff1c9-e86f-4d42-b65f-c54a7ee031db.png)
![韩国](https://user-images.githubusercontent.com/78950858/177238100-2d3fa5a5-a4ac-4d0c-985c-2e2b7c537998.png)
![苏军](https://user-images.githubusercontent.com/78950858/177238118-d2eca847-1b05-4d0e-b019-63ceffa27c8b.png)
![尤里](https://user-images.githubusercontent.com/78950858/177238122-116f96ac-aaad-4486-a0e8-8e6f57cc1dfd.png)

**Comment by Zero-Fanker** [comment]
@klighting444 小碗帮忙归档
