### ISSUE TITLE
#Bug#精英级机枪型兽人使用激光武器

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#684]
【现象】：如题，如图
【反馈人】：shuiping233
【发现版本号】：0.99.913a6
【影响范围】：未知
【产生原因】：未知
![QQ图片20220326222344](https://user-images.githubusercontent.com/49360196/160244014-1acc8b77-46d8-430b-adf3-55b96bd20673.gif)

**Comment by Zero-Fanker** [comment]
0.99.913a7 已修复 @NightSkyTS

**Comment by Zero-Fanker** [comment]
@klighting444 小碗帮忙归档
