### ISSUE TITLE
#Bug#遥控坦克可以被间谍抢夺

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#685]
【现象】：如题
【反馈人】：shuiping233
【发现版本号】：0.99.913a6
【影响范围】：未知
【产生原因】：未知

**Comment by Zero-Fanker** [comment]
驱逐改一下吧，禁止窃车

**Comment by shuiping233** [comment]
> 驱逐改一下吧，禁止窃车

0.99.916b2测试通过
