### ISSUE TITLE
#建议反馈#允许遭遇战单人开局

### ISSUE THREAD

**Issue by jukebox-www** [Zero-Fanker/RN_All_Issues#694]
【描述】建议允许遭遇战单人模式开局，以方便玩家熟悉单位。
【原因】宣传的老影片版本允许，更新到新的启动器版本不能以单人模式开局，不宜。

**Comment by Zero-Fanker** [comment]
不开放，需要熟悉可以自行添加地图，设置最小玩家数量为1即可
