### ISSUE TITLE
#Bug#若干遭遇战地图加载时没有预览图

### ISSUE THREAD

**Issue by A-small-C4** [Zero-Fanker/RN_All_Issues#696]
【现象】：地图“不进则退”没有预览图
此外怪兽电影、冰河世纪、冰原深处、烈性炸药、月球巡礼、加州，欧文 同理

【发现版本号】：0.99.913a7
【影响范围】：遭遇战，多人联机
【产生原因】：mmx格式地图兼容性问题
![QQ图片20220420222506](https://user-images.githubusercontent.com/52919411/164257184-7392b104-a103-4da8-a585-9cc073a6f01a.png)

**Comment by A-small-C4** [comment]
![QQ图片20220421112711](https://user-images.githubusercontent.com/52919411/164359371-77894622-0660-4908-a4fc-47882a50d1ee.png)
经测试这几张地图同样没有预览图。

**Comment by Zero-Fanker** [comment]
0.99.913b 已修复

**Comment by NightSkyTS** [comment]
0.99.913b确认描述的地图修复完毕
