### ISSUE TITLE
#Bug#磁电坦克攻击已落地部署的直升机单位时摧毁直升机会导致其无敌

### ISSUE THREAD

**Issue by koishiX233** [Zero-Fanker/RN_All_Issues#697]
【现象】：磁电坦克攻击武装直升机这样的落地部署单位后，武装直升机在被磁电举到身边的过程中被摧毁，会生成一个无法摧毁的0血中立单位，并且会自动攻击武装直升机原所属的敌人，原所属无法操控。（经测试蜂鸟，夜鹰也会这样，推测类似这样的单位都有这种bug）
【反馈人】：古明地雷
【发现版本号】：0.99.911
【影响范围】：遭遇战、多人联机、可能影响通关
【产生原因】：不知道

**Comment by Zero-Fanker** [comment]
经过分析是因为目标是“可坠毁”的，已增加判定，当被locomotor武器攻击时不能触发坠毁

**Comment by Zero-Fanker** [comment]
0.99.913b3 已修复 @NightSkyTS

**Comment by NightSkyTS** [comment]
0.99.913b3测试通过
![无敌落地飞机](https://user-images.githubusercontent.com/78950858/169644169-71a0e502-0972-45c3-9bdc-2ae97b3bb99b.gif)

**Comment by Zero-Fanker** [comment]
@klighting444 小碗帮忙归档
