### ISSUE TITLE
#bug#磁电坦克攻击武直这样的部署单位出现的异常

### ISSUE THREAD

**Issue by koishiX233** [Zero-Fanker/RN_All_Issues#698]
【现象】：磁电坦克攻击武装直升机这样的落地部署单位后，武装直升机在被磁电举到身边的过程中被摧毁，会生成一个无法摧毁的0血中立单位，并且会自动攻击武装直升机原所属的敌人，原所属无法操控。（经测试蜂鸟，夜鹰也会这样，推测类似这样的单位都有这种bug）
【反馈人】：古明地雷
【发现版本号】：0.99.911
【影响范围】：遭遇战、多人联机、可能影响通关
【产生原因】：不知道

**Comment by Zero-Fanker** [comment]
同#697
