### ISSUE TITLE
#Bug#条顿坦克，核堡垒会在空中/水中生成残骸

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#7]
RN_Admin created an issue 2018-08-27
条顿坦克，核堡垒被磁电坦克吸到空中打爆，会在空中生成残骸 在桥上时被炸桥，会在水中生成残骸

**Comment by shuiping233** [comment]
IEafeoN
changed status to resolved
2018-08-29
 Zero Fanker
assigned issue to   Zero Fanker
