### ISSUE TITLE
#Bug#生化危机前兆-不明生物剧情僵尸引起崩溃

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#702]
【现象】：![WNP{I(9300WSBAAP`BCNFQ3](https://user-images.githubusercontent.com/14891010/167453924-8464788f-15eb-4957-94c0-f6685cc4b209.png)
【反馈人】：服务群“降雪 ”
【发现版本号】：0.99.913b
【影响范围】：影响生化危机-不明生物的正常运行
【产生原因】：生化机制调整数据未同步

**Comment by Zero-Fanker** [comment]
0.99.913b2 已修复 @NightSkyTS

**Comment by NightSkyTS** [comment]
0.99.913b2测试通过，可以正常通关，无其他问题，难度为中等（正常）

**Comment by Zero-Fanker** [comment]
@klighting444 小碗帮忙归档
