### ISSUE TITLE
#Bug#尤里狂兽人和奴隶在高地可以获得射程加成

### ISSUE THREAD

**Issue by NightSkyTS** [Zero-Fanker/RN_All_Issues#703]
【现象】：原版BUG，兽人与奴隶可以在悬崖边上攻击到悬崖下的单位
【发现版本号】：0.99.913b
【产生原因】：如题，吃到了高地射程加成
![隔山打牛青春版](https://user-images.githubusercontent.com/78950858/167630393-17f34d33-3e4e-4fe6-be90-ebed7dbe3b20.gif)

**Comment by Zero-Fanker** [comment]
你只提了两个就按两个来搞了

**Comment by Zero-Fanker** [comment]
0.99.913b2 已修复 @NightSkyTS

**Comment by NightSkyTS** [comment]
0.99.913b2测试通过
![狂兽人](https://user-images.githubusercontent.com/78950858/167982698-faa5e56d-96f1-4738-a94c-c9efad2e5adb.gif)
![奴隶](https://user-images.githubusercontent.com/78950858/167982772-f5058acd-2fe0-4fdd-bc4c-e0fc56cb5003.gif)

**Comment by Zero-Fanker** [comment]
@klighting444 小碗帮忙归档
