### ISSUE TITLE
#Bug#德国AI在遭遇战开局时就会建造自动化车间

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#704]
【现象】：严重过早建造自动化车间，不合理
【反馈人】：
【发现版本号】：0.99.913a4
【影响范围】：影响德国AI在场时的游戏体验
【产生原因】：不合适的建造前提设置

**Comment by NightSkyTS** [comment]
0.99.913b2测试通过，据观察结果，现在AI会在T4后才会尝试建造自动化车间

**Comment by Zero-Fanker** [comment]
@klighting444 小碗帮忙归档
