### ISSUE TITLE
#Bug#先锋政委近战攻击会受到高地射程加成以及近战攻击附带拆墙效果

### ISSUE THREAD

**Issue by NightSkyTS** [Zero-Fanker/RN_All_Issues#705]
【现象】：如题，因为有射程加成，可以隔山打牛，近战攻击目标时可以对附近的围墙造成伤害（两者并无关联）
【发现版本号】：0.99.913b2
![先锋政委](https://user-images.githubusercontent.com/78950858/167987833-56c99acc-1e6b-4fbc-9930-2c9bebe1f9dd.gif)

**Comment by Zero-Fanker** [comment]
0.99.914a4 已修复

**Comment by NightSkyTS** [comment]
0.99.914a5测试通过
![拆墙](https://user-images.githubusercontent.com/78950858/175796938-55682f5c-c98a-40e2-9279-b4c49909d116.gif)

**Comment by Zero-Fanker** [comment]
@klighting444 小碗帮忙归档
