### ISSUE TITLE
#Bug#“深海屠戮”模式下德国与越南初始单位异常

### ISSUE THREAD

**Issue by NightSkyTS** [Zero-Fanker/RN_All_Issues#707]
【现象】：在深海屠戮模式中，开启初始单位选项后给予的初始单位会被替换为对应阵营的基础海军，但德国与越南不会，德国依旧是灰熊US，越南则是一半潜艇一半毒蝎
【发现版本号】：0.99.913b
![SCRN 20220512-170530-00949](https://user-images.githubusercontent.com/78950858/168039449-32a6f0b0-239e-4d4c-ac2f-a138a1cf9c15.jpg)
![SCRN 20220512-172151-00053](https://user-images.githubusercontent.com/78950858/168039804-7d49732b-2830-466b-8ff3-dcfc3aaf64e1.jpg)

**Comment by Zero-Fanker** [comment]
0.99.914a7 已修复

**Comment by NightSkyTS** [comment]
0.99.914a7测试通过
![德国](https://user-images.githubusercontent.com/78950858/179380143-e7b07957-f9dc-4ff1-a5e8-ce604c7e2236.png)
![越南](https://user-images.githubusercontent.com/78950858/179380151-ece55067-51bf-40ee-be58-85e0998d360a.png)
