### ISSUE TITLE
#Bug#超时空兵团可以通过其他阵营的作战实验室解锁

### ISSUE THREAD

**Issue by NightSkyTS** [Zero-Fanker/RN_All_Issues#709]
【现象】：在拥有了盟军兵营的情况下，仅需要T3建筑即可建造超时空兵团，哪怕T3建筑不是盟军T3
【发现版本号】：0.99.913b2
【影响范围】：遭遇战，可以建造高科且出现了盟军兵营的非盟军战役
![QQ图片20220513182211](https://user-images.githubusercontent.com/78950858/168264381-3738c781-ed2d-41ed-88ee-276949bd30ce.jpg)

**Comment by Zero-Fanker** [comment]
0.99.913b3 已修复 @NightSkyTS

**Comment by NightSkyTS** [comment]
0.99.913b3测试通过，现在只有在同时拥有盟军兵营与盟军高科的情况下才可以建造超时空军团兵
![超时空兵团](https://user-images.githubusercontent.com/78950858/169643216-e8626c77-5ddb-428f-bd7a-332d5f56041e.jpg)

**Comment by Zero-Fanker** [comment]
@klighting444 小碗帮忙归档
