### ISSUE TITLE
#Bug#悬浮类飞行器可以借助下方的围墙强制变卖

### ISSUE THREAD

**Issue by koishiX233** [Zero-Fanker/RN_All_Issues#711]
【现象】：如题
【反馈人】：古明地雷
【发现版本号】：0.99.913b2
【影响范围】：遭遇战、多人联机
【产生原因】：不知道
![卖基洛夫咯](https://user-images.githubusercontent.com/101552603/168280864-d22b9a26-6c70-440e-99a5-95372e883b47.gif)

**Comment by Zero-Fanker** [comment]
0.99.913b3 已修复 @NightSkyTS

**Comment by NightSkyTS** [comment]
0.99.913b3测试通过（宣传飞艇，镭射幽浮，计算者均已测试无误）
![变卖基洛夫](https://user-images.githubusercontent.com/78950858/169643960-d5779e17-4031-4dc4-bdb9-7e286a66384b.gif)

**Comment by Zero-Fanker** [comment]
@klighting444 小碗帮忙归档
