### ISSUE TITLE
#建议反馈#建议将乌贼对暴风摩托使用普通近战攻击，而不是缠绕

### ISSUE THREAD

**Issue by NightSkyTS** [Zero-Fanker/RN_All_Issues#713]
【描述】当前版本的乌贼攻击暴风摩托使用的是寄生攻击，建议改成头锤攻击（乌贼攻击雷鸣潜艇的攻击方式）
![暴风摩托](https://user-images.githubusercontent.com/78950858/169465861-35ed1159-181e-48d7-849d-2f711528ed27.gif)
【原因】违和感较强
【期望解决时间】任意时间

**Comment by Zero-Fanker** [comment]
0.99.913b3 已修复 @NightSkyTS

**Comment by NightSkyTS** [comment]
0.99.913b3测试通过
![暴风摩托2](https://user-images.githubusercontent.com/78950858/169643916-6ad87ec4-18fe-485e-b393-05ff422e61c3.gif)

**Comment by Zero-Fanker** [comment]
@klighting444 小碗帮忙归档
