### ISSUE TITLE
#Bug#TX的新城区地形斜坡存在一处视觉错误

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#714]
【现象】：![(SKE9CXJ8`N0}3 WVO E1FC](https://user-images.githubusercontent.com/14891010/169576793-ae56f3c3-bd43-4350-85a9-e65833055857.png)
【反馈人】：韩方序
【发现版本号】：0.99.911
【影响范围】：影响用到新城区TX扩展部分斜坡的地图
【产生原因】：TX地形包Bug

**Comment by Zero-Fanker** [comment]
0.99.913b3 已修复 @NightSkyTS

**Comment by shuiping233** [comment]
哪张地图？

**Comment by Zero-Fanker** [comment]
> 哪张地图？

这个恐怕需要自己用地图测试，是TX新增的草地斜坡

**Comment by shuiping233** [comment]
![Snipaste_2022-07-05_09-48-54](https://user-images.githubusercontent.com/49360196/177233793-7e0c972e-fdad-439f-a17a-57c8098ccf11.png)
![Snipaste_2022-07-05_09-48-44](https://user-images.githubusercontent.com/49360196/177233797-2e87a79b-78d1-4416-9091-76a30861cc97.png)
0.99.914a5测试通过

**Comment by Zero-Fanker** [comment]
@klighting444 小碗帮忙按0.99.913归档
