### ISSUE TITLE
#Bug#可反部署的建筑单位无法手动设定路径反部署

### ISSUE THREAD

**Issue by usyd20** [Zero-Fanker/RN_All_Issues#718]
【现象】：以奴隶矿厂为例，处于建筑状态时不能控制其移动
【反馈人】：
【发现版本号】：0.99 913b4
【影响范围】：遭遇战（目前）
【产生原因】：未知

**Comment by usyd20** [comment]
【现象】：奴隶矿厂处于建筑状态时不能控制其移动
【反馈人】：
【发现版本号】：0.99 913b4
【影响范围】：遭遇战（目前）
【产生原因】：未知

**Comment by Zero-Fanker** [comment]
确认核炮也受到影响

**Comment by Zero-Fanker** [comment]
@NightSkyTS 0.99.913b5已修复，验证时请注意复测 #711

**Comment by NightSkyTS** [comment]
0.99.913b5初步测试通过，测试对象：核炮，奴隶矿车，三方MCV
![多个奴隶矿车](https://user-images.githubusercontent.com/78950858/170741132-93d6ea93-b974-4412-a698-2026c5b59730.gif)
![复数的核炮](https://user-images.githubusercontent.com/78950858/170741252-05d6a03a-ce36-41c5-aafa-e5bead399398.gif)
