### ISSUE TITLE
#Bug#部分危险品设施残血图像损失

### ISSUE THREAD

**Issue by NightSkyTS** [Zero-Fanker/RN_All_Issues#719]
【现象】：如题，爆炸物在到达残血情况下会变成透明的.....
【发现版本号】：0.99.911
【影响范围】：视觉效果
![文件损失1](https://user-images.githubusercontent.com/78950858/170748368-9642588e-abc0-4cee-b878-2a08d9f82cac.png)
![文件损失2](https://user-images.githubusercontent.com/78950858/170748464-53882da7-7fcf-4e37-ae51-d0c903adab22.png)
![文件损失3](https://user-images.githubusercontent.com/78950858/170748678-30491589-2b2c-4ca1-b469-632633b8fc0f.png)
![文件损失4](https://user-images.githubusercontent.com/78950858/170758388-6ef9d558-e8ab-4d00-932f-50c22846569e.png)

**Comment by Zero-Fanker** [comment]
0.99.914a已修复

**Comment by Zero-Fanker** [comment]
@klighting444 小碗帮忙归档
