### ISSUE TITLE
#Bug#番外任务“为长官欢呼”有两辆履带车无法被常规方式击杀

### ISSUE THREAD

**Issue by NightSkyTS** [Zero-Fanker/RN_All_Issues#724]
【现象】：如题，无法被直接的攻击方式摧毁，但在摧毁了其所属的生产建筑后会直接自爆....
【发现版本号】：0.99.914a
![QQ图片20220602133942](https://user-images.githubusercontent.com/78950858/171560697-485896c3-ac86-48a2-b94a-bde839cb719c.png)
![无敌履带车X2](https://user-images.githubusercontent.com/78950858/171560751-7932109b-f0a2-46e2-8191-f41eee9dbe0a.gif)

**Comment by Zero-Fanker** [comment]
0.99.916b2 已包含调整 @shuiping233

**Comment by shuiping233** [comment]
0.99.916b2测试通过
![GIF130](https://github.com/user-attachments/assets/bac83646-67ae-4c4a-981c-4490e81b0d34)
![GIF129](https://github.com/user-attachments/assets/7014b2df-184f-4904-a6f8-a78e0ea6eb8b)
