### ISSUE TITLE
#建议反馈#优化重制原版若干伦敦建筑雪地形态

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#732]
【描述】
![FZ$D3T8MUH}N1 @ECNNO4 2](https://user-images.githubusercontent.com/14891010/172411189-10847738-b3d6-48fa-ae58-8c9e6d78b2a2.png)
CALOND01
![5BH70ATFI)4EPR48`BZU3Z1](https://user-images.githubusercontent.com/14891010/172411221-092a2c88-7735-4961-bee6-4d418aca6f5f.png)

CALOND03

![WFU 6QPUW7CR6MUYJ5Q A 7](https://user-images.githubusercontent.com/14891010/172411267-241a491a-d226-46d0-887b-b611ce6e7334.png)
CATRAN01

【原因】原版素材质量不达标
【期望解决时间】跟随迭代完成

**Comment by Zero-Fanker** [comment]
0.99.914a2已调整

**Comment by shuiping233** [comment]
![Snipaste_2022-06-13_14-03-44](https://user-images.githubusercontent.com/49360196/173290279-cedc58f4-3c80-4099-985c-827b4d409190.png)
![Snipaste_2022-06-13_14-03-22](https://user-images.githubusercontent.com/49360196/173290291-230129f6-9425-4ab2-af36-d07a9a70ed0d.png)
![Snipaste_2022-06-13_14-02-23](https://user-images.githubusercontent.com/49360196/173290293-c65558fc-62f3-48c4-b2fe-aa2de1c4b6e3.png)
![Snipaste_2022-06-13_14-01-46](https://user-images.githubusercontent.com/49360196/173290294-4b1e3bef-f0a1-4985-a316-e6817a1b438c.png)
0.99.914a2测试通过
