### ISSUE TITLE
#Bug#番外任务盟军第一关、苏联第五关中科技中立防御建筑被摧毁会引起游戏崩溃

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#733]
【现象】：如题
【反馈人】：shuiping233
【发现版本号】：0.99.914a
【影响范围】：番外任务（目前仅在番外任务中发现）
【产生原因】：番外任务系列地图缺少special所属方定义

[注释]:例子：
[注释]:【现象】：韩国火炮、洲际导弹的信标可以被超时空传送、铁幕装置影响
[注释]:【反馈人】：永恒_叶
[注释]:【发现版本号】：0.99.F1028A
[注释]:【影响范围】：影响带有AI的对局
[注释]:【产生原因】：AI新机制引入

snapshot-20220610-224130.rar
![image](https://user-images.githubusercontent.com/49360196/173169758-2384ab99-1dfa-4b75-9483-c476a1c852b9.png)

**Comment by Zero-Fanker** [comment]
目前只处理了盟军第一关，苏5

**Comment by shuiping233** [comment]
![PDXRFBU94U(W $HXKE 1{V](https://user-images.githubusercontent.com/49360196/173292587-91c2a372-771c-4c78-9708-73676c70a102.gif)
![L55BJX@ZTOQT`_13Y`2PP0K](https://user-images.githubusercontent.com/49360196/173292589-722861f5-bf39-419f-ad6f-eaa9cc9f261d.gif)
![HNB$K Q8Q)D0)CGHUO8K6JI](https://user-images.githubusercontent.com/49360196/173292600-c6405b09-3e31-4ead-b16a-1ee014138aa6.png)
经过NightSkyTS进行测试，确认在 0.99.914a2 的番外盟1和苏5中已经修复此问题

**Comment by shuiping233** [comment]
> 目前只处理了盟军第一关，苏5

这个单子什么时候归档

**Comment by Zero-Fanker** [comment]
那直接归档吧

**Comment by shuiping233** [comment]
番外任务其他中立塔不管了？还是说工头你记得很牢）

**Comment by Zero-Fanker** [comment]
按单子来不要发散，遇到了就提，提了就修。我后面会注意的，但不代表不会再有

**Comment by shuiping233** [comment]
好
