### ISSUE TITLE
#Bug#任何单位默认携带治疗（载具是维修）buff及动画但没有实际治疗效果

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#736]
【现象】：如题，如图
【反馈人】：shuiping233
【发现版本号】：0.99.914a2
【影响范围】：全局
【产生原因】：未知
![gif4](https://user-images.githubusercontent.com/49360196/173285024-4f7b11c5-f369-45e3-86dd-aabfc8ef97d1.gif)
![gif3](https://user-images.githubusercontent.com/49360196/173285032-ea6ca67b-dddf-4f94-b11a-8f1caa61732d.gif)

**Comment by Zero-Fanker** [comment]
0.99.914a3 已修复
