### ISSUE TITLE
#Bug#生化任务第一关“起源”的载入图文本与简报文本未被替换

### ISSUE THREAD

**Issue by NightSkyTS** [Zero-Fanker/RN_All_Issues#738]
【现象】：载入图阶段的任务介绍，包括游戏内简报界面的文本均为旧版生化一的任务文本
【发现版本号】：0.99.913
![1](https://user-images.githubusercontent.com/78950858/174263537-d60a14e3-4f79-48da-8fff-15a9e2131319.png)
![2](https://user-images.githubusercontent.com/78950858/174263571-e9156d3f-282b-4330-aa55-c87a4f1e7bac.png)

**Comment by Zero-Fanker** [comment]
@shuiping233 @kk7k7k558 @Renko-ji @Crossfield-ClassDestroyer   0.99.916a 已包含

**Comment by shuiping233** [comment]
0.99.916a测试通过，载入图和简报文本已经符合关卡内容
![image](https://github.com/user-attachments/assets/8bf196d7-bdf0-488c-8cc0-37ec75a28fd1)
![image](https://github.com/user-attachments/assets/2fe34557-b956-44f5-9f36-2fff92efdadb)
