### ISSUE TITLE
#Bug#雪地中科技重型近卫炮的图像不正常

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#743]
【现象】：如题，如图
【反馈人】：Zero Fanker
【发现版本号】：0.99.914a3
【影响范围】：雪地，视觉体验
【产生原因】：未知
![image](https://user-images.githubusercontent.com/49360196/175755650-6f2261d2-67d0-44e1-ae78-c164c3f17060.png)

**Comment by Zero-Fanker** [comment]
0.99.914a4 已修正 @shuiping233  @NightSky-TS

**Comment by NightSkyTS** [comment]
0.99.914a5测试通过
![1](https://user-images.githubusercontent.com/78950858/175954532-1e5bfc57-2dbc-4aa5-81b9-029c609d06e3.png)

**Comment by Zero-Fanker** [comment]
@klighting444 小碗帮忙归档
