### ISSUE TITLE
#Bug#载具可以在维修厂内部署

### ISSUE THREAD

**Issue by NightSkyTS** [Zero-Fanker/RN_All_Issues#744]
【现象】：如题，部署后维修厂会停止工作，需要载具重新进入才能继续维修
【发现版本号】：0.99.913
![维修厂内部署](https://user-images.githubusercontent.com/78950858/175949670-95dd9f98-50ff-4f98-8a3c-a0e8067f54ba.gif)

**Comment by Zero-Fanker** [comment]
0.99.914a7 已修复

**Comment by shuiping233** [comment]
NightSkyTS：0.99.914a7测试通过
灰熊，烈焰核心，突击艇，苏萌高级防空，毒蝎，超时空猎手，镭射坦克均以通过测试，不允许在维修厂内部署
![FNBT)EQ)8NBQTEEFU)ZV%SL](https://user-images.githubusercontent.com/49360196/179388844-7bbf1a8f-9165-49eb-bd2f-bf6e7cef651c.gif)

![8YQ}$CR~}WZ))U0_X~AMKB9](https://user-images.githubusercontent.com/49360196/179388845-8a9fdfe3-0a84-49c8-a599-7d1243755997.gif)
![H4SHI34}O@T2_GT~}6{ V{9](https://user-images.githubusercontent.com/49360196/179388849-c069cd9b-c724-496f-8f86-542ca495cda5.gif)
