### ISSUE TITLE
#Bug#AI可以变卖秘密科技实验室

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#745]
【现象】：如题，如图
【反馈人】：NightSkyTS
【发现版本号】：0.99.914a3
【影响范围】：全局
【产生原因】：未知
![gif24](https://user-images.githubusercontent.com/49360196/176076243-6078e925-1cd2-4924-ace6-f9e5fa69c051.gif)
![gif23](https://user-images.githubusercontent.com/49360196/176076251-a620833a-07a9-4158-927f-1f992fba0b9e.gif)

**Comment by Zero-Fanker** [comment]
0.99.914a6 已修复

**Comment by shuiping233** [comment]
![gif34](https://user-images.githubusercontent.com/49360196/177282677-05b8257e-8c69-412e-85cb-008244a7df05.gif)
0.99.914a6测试通过

**Comment by Zero-Fanker** [comment]
@klighting444  小碗帮忙归档
