### ISSUE TITLE
#Bug#科技反坦克炮能对哨戒炮产生减速效果

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#747]
【现象】：如题，如图
【反馈人】：shuiping233
【发现版本号】：0.99.914a5
【影响范围】：视觉体验
【产生原因】：未考虑到该场景
![gif26](https://user-images.githubusercontent.com/49360196/177025911-c5ee15f5-95b0-4b5f-924a-5454e0dbb498.gif)

**Comment by Zero-Fanker** [comment]
0.99.914a6 已调整 @NightSkyTS

**Comment by NightSkyTS** [comment]
0.99.914a6测试通过
![哨戒炮减速](https://user-images.githubusercontent.com/78950858/178149665-605bba94-399b-465a-9140-ae5624914588.gif)
