### ISSUE TITLE
#Bug#生化任务一“起源”中“闪瞎狗眼的聚光灯”没有模型帧

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#749]
【现象】：如题，如图 坐标：78,122
【反馈人】：NightSkyTS
【发现版本号】：0.99.914a6
【影响范围】：全局
【产生原因】：未知
  
![4ON(){IR HX@S~H0S{8DK0P](https://user-images.githubusercontent.com/49360196/177240600-582ec3ab-d3c2-48a2-80dd-a97f0f64d9ac.gif)

**Comment by Zero-Fanker** [comment]
0.99.914a7 已修复

**Comment by NightSkyTS** [comment]
0.99.914a7测试通过
![1](https://user-images.githubusercontent.com/78950858/179381185-2e3262f1-e040-42c8-8cae-e42eb3c6b870.jpg)
