### ISSUE TITLE
#bug##建议#飞机投弹改进

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#75]
【现象】飞机距离目标过近时不投弹或者盘旋一段时间后投弹，地毯轰炸机中途操作会打断投弹
【反馈人】：IEafeoN 
【产生范围】雷电轰炸机，核炸机，毒炸机等以一条线为目标的轰炸机
【产生原因】可能是一条线为目标会对飞行角度和距离有要求？

**Comment by Zero-Fanker** [comment]
TOOOOM看一下能不能先分析出当前WW预设的机制原理（根据经验和ROF Ammo机制 以及Cluster的设置有关系），然后可能的话，让弹药可以在飞行器开火的瞬间立刻减少数量，并将僵直飞行的这个特性用额外的标签剥离出来。

**Comment by Zero-Fanker** [comment]
TOOOOOOM已完成弹药改进，我已完成投弹机制优化，暂时没有剥离僵直逻辑，但已恢复为源码，待目前效果评估后做进一步考虑。

**Comment by shuiping233** [comment]
H0825测试结果：雷电轰炸机现在不会转圈不投蛋了，但是引出了其他的bug，靠近建筑时在控制雷电攻击建筑有较大概率使雷电丢炸弹丢不中建筑物，某些情况下雷电的炸弹并不能分裂只能造成一次伤害，其余轰炸机待测

**Comment by Zero-Fanker** [comment]
命中率降低的情况我之前就说了，不产生分裂弹是什么意思？ ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;shuiping&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月26日(星期三) 下午3:32
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;Zero Fanker&quot;<zcyfksn@vip.qq.com&gt;;&quot;Assign&quot;<assign@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #bug##建议#飞机投弹改进 (#75)

**Comment by shuiping233** [comment]
> 命中率降低的情况我之前就说了，不产生分裂弹是什么意思？ ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;shuiping&quot;<notifications@github.com&gt; 发送时间:&nbsp;2020年8月26日(星期三) 下午3:32 收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;; 抄送:&nbsp;&quot;Zero Fanker&quot;<zcyfksn@vip.qq.com&gt;;&quot;Assign&quot;<assign@noreply.github.com&gt;; 主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #bug##建议#飞机投弹改进 (#75)

就是炸弹碰建筑物或者地板直接炸掉了，炸弹没有分裂，伤害也低一些，雷电丢不中建筑的时候就会出现

**Comment by Zero-Fanker** [comment]
有时间搞个截图或者视频 ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;shuiping&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月26日(星期三) 下午3:54
收件人:&nbsp;&quot;Zero-Fanker/RN_All_Issues&quot;<RN_All_Issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;Zero Fanker&quot;<zcyfksn@vip.qq.com&gt;;&quot;Assign&quot;<assign@noreply.github.com&gt;;
主题:&nbsp;Re: [Zero-Fanker/RN_All_Issues] #bug##建议#飞机投弹改进 (#75)

**Comment by shuiping233** [comment]
![GIF109](https://user-images.githubusercontent.com/49360196/91418215-6e2d2180-e884-11ea-8285-a699f8255017.gif)
![GIF108](https://user-images.githubusercontent.com/49360196/91418265-7f762e00-e884-11ea-98bd-4603e442c9b7.gif)
![GIF107](https://user-images.githubusercontent.com/49360196/914182
![GIF102](https://user-images.githubusercontent.com/49360196/91418735-222eac80-e885-11ea-8cec-8c7c31828589.gif)
97-8866ff80-e884-11ea-9d7e-21423c41ca29.gif)
![GIF106](https://user-images.githubusercontent.com/49360196/91418317-9157d100-e884-11ea-9574-0716e8e43d78.gif)
![GIF105](https://user-images.githubusercontent.com/49360196/91418585-ebf12d00-e884-11ea-8f59-8bf68de393e3.gif)
![GIF104](https://user-images.githubusercontent.com/49360196/91418623-fb707600-e884-11ea-959c-cda5b74e2e68.gif)
![GIF103](https://user-images.githubusercontent.com/49360196/91418684-0cb98280-e885-11ea-9e4d-e78e5fe8372a.gif)

**Comment by shuiping233** [comment]
H0825测试结果：除了毒牙的弹药有问题会反复丢5轮弹药，雷电以及核子地毯轰炸机并未发现问题

**Comment by Zero-Fanker** [comment]
> H0825测试结果：除了毒牙的弹药有问题会反复丢5轮弹药，雷电以及核子地毯轰炸机并未发现问题

H0830给个结论

**Comment by shuiping233** [comment]
> 
> 
> > H0825测试结果：除了毒牙的弹药有问题会反复丢5轮弹药，雷电以及核子地毯轰炸机并未发现问题
> 
> H0830给个结论

H0830测试结果：毒牙问题依旧存在，并且比H0825更加严重，目前毒牙是腹泻式连续投弹，如图所示：

**Comment by Zero-Fanker** [comment]
> > > H0825测试结果：除了毒牙的弹药有问题会反复丢5轮弹药，雷电以及核子地毯轰炸机并未发现问题
> > 
> > 
> > H0830给个结论
> 
> H0830测试结果：毒牙问题依旧存在，并且比H0825更加严重，目前毒牙是腹泻式连续投弹，如图所示：
> 
> ![GIF1](https://user-images.githubusercontent.com/49360196/95164770-313a4000-07dd-11eb-8c21-eac52e6f10de.gif)

OK这个问题我又进一步调整了一下，原先有一个相关参数没改，等这两天更新后再试试。

**Comment by Zero-Fanker** [comment]
H1031已修正，请验证。

**Comment by shuiping233** [comment]
H1031B测试结果如图：
![GIF23](https://user-images.githubusercontent.com/49360196/97802083-147a1680-1c7c-11eb-9686-5d29764a81c3.gif)







毒牙弹药问题已经解决，但是靠近目标时更改轰炸目标会导致轰炸航线有毛病，不能很好的扔炸弹

**Comment by shuiping233** [comment]
经讨论，毒牙不适合炸建造，并且我测试了毒牙对静止单位的投弹，并没有什么问题
