### ISSUE TITLE
#Bug#生化任务一“起源”中“危险品”缺少破损帧

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#750]
【现象】：如题，如图
【反馈人】：NightSkyTS 
【发现版本号】：0.99.914a6
【影响范围】：全局
【产生原因】：未知
![B YN1~1WVIWYW}A5J~CUWCS](https://user-images.githubusercontent.com/49360196/177240850-7c31197e-b17f-4e4b-835f-39ead465e6a7.gif)
![C1DM_J8STA5}TFLU7MIGWGL](https://user-images.githubusercontent.com/49360196/177240856-fc876b91-aa55-4f55-a1eb-e91c79a223f5.gif)

**Comment by Zero-Fanker** [comment]
@NightSkyTS 0.99.914a7 已修复

**Comment by NightSkyTS** [comment]
0.99.914a7测试通过
![危险品1](https://user-images.githubusercontent.com/78950858/179381038-0deca861-57c7-43e3-9c1a-6850cdfb1cf2.gif)
![危险品2](https://user-images.githubusercontent.com/78950858/179381045-74e70e99-559c-4a91-8cf2-f6cbf7f7a242.gif)
