### ISSUE TITLE
#Bug#条顿II型残骸缺少模型帧

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#752]
【现象】：如题，说人话就是条2残骸没有图像
【反馈人】：Suli
【发现版本号】：0.99.914a6
【影响范围】：全局
【产生原因】：未知

**Comment by Zero-Fanker** [comment]
0.99.914a7 已修复

**Comment by shuiping233** [comment]
![gif47](https://user-images.githubusercontent.com/49360196/179381701-ad344ca4-e2ff-4206-b3a7-370a151feeab.gif)
0.99.914a7测试通过
