### ISSUE TITLE
#建议反馈#建议取消尤里AI使用基地车的隐形的能力

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#753]
【描述】如题
【原因】ai生产的基地车小队有可能因为某些原因不能部署而静止在某处，从而隐形起来，使得玩家需要花费大量时间清扫全图
【期望解决时间】soon

[注]:不按照格式填写会被视作无效。

**Comment by shuiping233** [comment]
![F31394F17D246C363DFC500EEB0D7F28](https://user-images.githubusercontent.com/49360196/177327918-cdf1065f-b0d0-484a-9a45-024e09399bf3.png)

**Comment by Zero-Fanker** [comment]
@NightSkyTS 0.99.914a7 已支持

**Comment by NightSkyTS** [comment]
0.99.914a7测试通过（左侧为玩家MCV）
![尤里MCV](https://user-images.githubusercontent.com/78950858/179380388-f40444fb-f58e-4bce-8afd-5f82d01b283c.png)
