### ISSUE TITLE
#Bug#“太空争霸”模式下开启和禁用基地高强度导致尤里建造页面发生差异

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#754]
【现象】：如题，如图
【反馈人】：Zero Fanker
【发现版本号】：0.99.914a6
【影响范围】：全局
【产生原因】：未知

**Comment by Zero-Fanker** [comment]
@NightSkyTS 0.99.914a7 已修复

**Comment by NightSkyTS** [comment]
0.99.914a7测试通过，现在开启“基地高强度”后可以正常建造建筑并使用“互联网交易”技能了
![尤里](https://user-images.githubusercontent.com/78950858/179380303-2afa05b6-633d-4f3d-9906-b1ef2ba318fc.png)
