### ISSUE TITLE
#Bug#单位部署后会失去原有的铁幕效果

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#759]
【现象】：如题，如图
【反馈人】：@koishiX233 
【发现版本号】：0.99.914a6
【影响范围】：全局
【产生原因】：部署后会生成一个新的单位
![部署重置铁幕](https://user-images.githubusercontent.com/49360196/177508409-fc1938f7-20e5-45db-9459-a2c2b83dd5d7.gif)

**Comment by Zero-Fanker** [comment]
0.99.914a7 已修复

**Comment by shuiping233** [comment]
![gif46](https://user-images.githubusercontent.com/49360196/179381409-a6d47a0b-1d37-4e8a-a9df-a072a36c565a.gif)
![gif45](https://user-images.githubusercontent.com/49360196/179381412-5a619c76-c0fe-4023-8f22-eba7ac401d25.gif)
0.99.914a7测试通过
