### ISSUE TITLE
#Bug#友方AI磁暴步兵会攻击玩家的单位和建筑

### ISSUE THREAD

**Issue by jukebox-www** [Zero-Fanker/RN_All_Issues#762]
【现象】：苏军AI的磁暴步兵，在AI家里时正常，在AI家放巨炮正常。但是在战场中央，如冰天雪地的矿区，离敌方8号位较近时，在那边放巨炮，友方AI磁暴步兵可能攻击我巨炮，直到打爆。
如图，在冰天雪地地图，我法国，其他全部是古巴，AI，4v4。我在中央宝石位置放两门巨炮。一段时间过后，黄色AI友军磁暴步兵攻击我巨炮，远处橙色敌方磁暴步兵赶来。AI敌军的磁暴步兵和AI友军的磁暴步兵一起拆我放在战场中央2个巨炮，两个都拆完后散伙。
【反馈人】：本人
【发现版本号】：0.99.913b5，903之前就遇到过，但当时以为是图的问题，没去测试官方地图
【影响范围】：官方地图或其他非官方地图
【产生原因】：认为是AI小队集结问题。

**Comment by jukebox-www** [comment]
https://s3.bmp.ovh/imgs/2022/07/08/d5458ce30fca5da9.bmp https://s3.bmp.ovh/imgs/2022/07/08/c1b813c9b6ba376a.bmp https://s3.bmp.ovh/imgs/2022/07/08/0f2b954e16ea45d7.bmp https://s3.bmp.ovh/imgs/2022/07/08/12da7f3c4047c1e2.bmp https://s3.bmp.ovh/imgs/2022/07/08/4b2fded7bf267bea.bmp https://s3.bmp.ovh/imgs/2022/07/08/499ee8a90645f463.bmp

**Comment by jukebox-www** [comment]
上面链接没复制全
https://s3.bmp.ovh/imgs/2022/07/08/d5458ce30fca5da9.bmp
https://s3.bmp.ovh/imgs/2022/07/08/c1b813c9b6ba376a.bmp
https://s3.bmp.ovh/imgs/2022/07/08/0f2b954e16ea45d7.bmp
https://s3.bmp.ovh/imgs/2022/07/08/12da7f3c4047c1e2.bmp
https://s3.bmp.ovh/imgs/2022/07/08/4b2fded7bf267bea.bmp
https://s3.bmp.ovh/imgs/2022/07/08/499ee8a90645f463.bmp

**Comment by shuiping233** [comment]
我无法复现，请提供复现方法

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/181011201-67da223d-7fdc-42a2-af49-adc4dcbf472a.png)
![磁暴](https://user-images.githubusercontent.com/49360196/181011227-34dbefb1-58eb-4499-a137-c24018743c6d.gif)
[SAVE6BF1.zip](https://github.com/Zero-Fanker/RN_All_Issues/files/9189952/SAVE6BF1.zip)
玩家提供了存档

**Comment by Zero-Fanker** [comment]
今天看相关代码的时候，分析出来的确有潜在的问题。不过是否彻底解决，需要验证。有可能导致这个小队的磁暴步兵无法正确攻击了。

**Comment by Zero-Fanker** [comment]
@shuiping233 @kk7k7k558 @Renko-ji @Crossfield-ClassDestroyer   0.99.916a 已包含

**Comment by Zero-Fanker** [comment]
> @shuiping233 @kk7k7k558 @Renko-ji @Crossfield-ClassDestroyer 0.99.916a 已包含

没人反馈就归档吧
