### ISSUE TITLE
#Bug#“工厂”建筑缺少图像帧

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#763]
【现象】：如题，如图，
【反馈人】：shuiping233
【发现版本号】：0.99.914a6
【影响范围】：视觉体验
【产生原因】：未知

![Snipaste_2022-07-08_11-29-52](https://user-images.githubusercontent.com/49360196/177912813-6860fde2-4fe7-49a6-b594-bc1079ed5849.png)
![Snipaste_2022-07-08_11-36-37](https://user-images.githubusercontent.com/49360196/177912808-284415b0-56ae-4aa9-939e-32d71a41d67d.png)

**Comment by Zero-Fanker** [comment]
确认打包失误

**Comment by Zero-Fanker** [comment]
0.99.914a7 已修复

**Comment by shuiping233** [comment]
注册名叫啥来着，我忘了

**Comment by Zero-Fanker** [comment]
> 注册名叫啥来着，我忘了

建筑列表其它里的前几个

**Comment by shuiping233** [comment]
![gif64](https://user-images.githubusercontent.com/49360196/179883441-fbfec0c5-44c2-4cea-8722-0e84c94cbc38.gif)
0.99.914a7测试通过

**Comment by Zero-Fanker** [comment]
@klighting444 小碗帮忙归档
