### ISSUE TITLE
#Bug#机枪子弹抛射体有时完全无法命中空中单位

### ISSUE THREAD

**Issue by jukebox-www** [Zero-Fanker/RN_All_Issues#766]
【现象】：（1280x720）![](https://s3.bmp.ovh/imgs/2022/07/10/30ccbbb8f46fb891.gif)
（1920x1080）![](https://s3.bmp.ovh/imgs/2022/07/10/52101929d8bfcf64.gif)
如图，在某种对空射击场景中，在坦克碉堡中的布伦载具射出的子弹是一条直线。如果旁边有飞行兵、狙击手或步兵驻防建筑在射击，子弹可能也会是一条直线。（似乎是布伦载具影响了其他单位子弹的动画）
【反馈人】：本人
【发现版本号】：913，之前版本也遇到过，但以为是显卡问题，发现换一台电脑也有
【影响范围】：遭遇战，全屏或窗口化都有此问题，修改分辨率仍有此问题
【产生原因】：可能是坦克碉堡增加射程

**Comment by Zero-Fanker** [comment]
我尝试做了防护，应该不再会出现“一条直线跨越屏幕”的现象

**Comment by Zero-Fanker** [comment]
@shuiping233 @kk7k7k558 @Renko-ji @Crossfield-ClassDestroyer   0.99.916a 已包含

**Comment by shuiping233** [comment]
> @shuiping233 @kk7k7k558 @Renko-ji @Crossfield-ClassDestroyer 0.99.916a 已包含

有无具体的可复现场景描述，这个bug我印象中暂且没有稳定复现的方法（

**Comment by shuiping233** [comment]
0.99.916a进过高强度子弹对空测试，无法复现此问题，故0.99.916a测试通过
