### ISSUE TITLE
#Bug#“春色小径”地图中有看起来可以通行但实际无法通过的区域

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#768]
【现象】：如题，如图
【反馈人】：我在等技能CD 你在等什么？（2228389199）
【发现版本号】：0.99.913b5
【影响范围】：全局
【产生原因】：未知
![TCUFST5_K$Q6AN LABR2%2H](https://user-images.githubusercontent.com/49360196/178145347-05d0fa4b-edf5-4268-b523-836c16365bff.jpg)

**Comment by Zero-Fanker** [comment]
请不要用这种俚语

**Comment by Zero-Fanker** [comment]
![image](https://user-images.githubusercontent.com/14891010/178152705-df6e299b-7958-4b24-bf20-fb4fd5b8ad3f.png)
这不是能走吗，只不过这个树挡在这容易卡树

**Comment by shuiping233** [comment]
赌一把，是空气墙

**Comment by Zero-Fanker** [comment]
0.99.914a7再去验证

**Comment by shuiping233** [comment]
0.99.914a7经过测试未发现此问题，估计是ai或者玩家的某种操作生成的空气墙
