### ISSUE TITLE
#Bug#建筑“聚光灯”缺失图像帧

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#769]
【现象】：如题，如图；原版建筑，注册名：CAURB03
【反馈人】：shuiping233
【发现版本号】：0.99.914a6
【影响范围】：全局
【产生原因】：未知

![Snipaste_2022-07-10_23-30-52](https://user-images.githubusercontent.com/49360196/178151498-e5d971fb-4e00-4d70-8f89-ace279bc5054.png)
![Snipaste_2022-07-10_23-28-25](https://user-images.githubusercontent.com/49360196/178151513-f75e8c73-40a1-49bf-b4f4-9fe6be51d196.png)

**Comment by Zero-Fanker** [comment]
#749 重复
