### ISSUE TITLE
#Bug#生化危机第二关不明生物无法进行，找到正确降落地点后会闪退或者弹框。

### ISSUE THREAD

**Issue by jiamankaer** [Zero-Fanker/RN_All_Issues#770]
【现象】：3个地点随机找到任何一个正确地点的时候，剧情进行到如图所示得时候会发生闪退或者弹框
![gamern 2022-07-12 13-35-22-743](https://user-images.githubusercontent.com/52826227/178416654-b8220f85-5786-4c3c-9803-448bb660a764.jpg)

【反馈人】：贾曼卡尔
【发现版本号】：0.99.914a3
【影响范围】:单关任务
【产生原因】：触发错误

**Comment by shuiping233** [comment]
![%RO})4INH@U5769@6(L1RR](https://user-images.githubusercontent.com/49360196/183559136-3d52b439-d121-43fb-8f53-695683466f1f.png)
[debug.log](https://github.com/Zero-Fanker/RN_All_Issues/files/9286582/debug.log)

**Comment by Zero-Fanker** [comment]
这玩意儿早就修过了啊，哪来的

**Comment by shuiping233** [comment]
测试版本：0.99.914a7

**Comment by Zero-Fanker** [comment]
确认了，后来生化武器更新了，这个反而没同步

**Comment by Zero-Fanker** [comment]
@shuiping233 @kk7k7k558 @Renko-ji @Crossfield-ClassDestroyer   0.99.916a 已包含

**Comment by shuiping233** [comment]
0.99.916a测试通过，现在生化危机第二关在玩家找到正确降落地点后不会闪退和弹框了
