### ISSUE TITLE
#Bug#遭遇战德国玩家载入时的国旗显示与其它位置国旗显示有差异

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#772]
【现象】：如题，如图
【反馈人】：沙丘Spice
【发现版本号】：0.99.914a6
【影响范围】：全局
【产生原因】：未知
![@}I791GH5KE$C2@F7C059RT](https://user-images.githubusercontent.com/49360196/179254414-aab9aca2-7671-4453-bf45-61e203fa89c1.png)
![L(SRGWPA(7G5EUYZM6KJ)AE](https://user-images.githubusercontent.com/49360196/179254434-3269cfe1-0eda-4406-8a19-08f5bbf26c7f.png)
![6NJASGXOSMA5Y)WE 4(PT B](https://user-images.githubusercontent.com/49360196/179254447-fef41fcb-5b59-4f0b-8970-87fb1addf036.png)

**Comment by Zero-Fanker** [comment]
0.99.914a7 已修复

**Comment by shuiping233** [comment]
0.99.914a7测试结果：地图实体物件“德国国旗”的颜色仍然不正确
![6J JP3R{CI$_})N`)B%FCU](https://user-images.githubusercontent.com/49360196/179380148-4aeb96e5-1935-4e0a-baf2-40e99f66784c.png)

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/179380301-7f7392cf-1e9b-4de9-8c51-3eb7ab5fc22b.png)
地图编辑器里的德国国旗颜色反倒是正确的

**Comment by Zero-Fanker** [comment]
单子只处理读条问题，国旗建筑有问题另外走单子

**Comment by shuiping233** [comment]
彳亍，那就归档
