### ISSUE TITLE
#Bug#地图“不速之礼”载入地图后游戏崩溃

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#779]
【现象】：如题
【反馈人】：shuiping233
【发现版本号】：0.99.911a2
【影响范围】：全局
【产生原因】：未知

**Comment by shuiping233** [comment]
@Zero-Fanker 这种我忘记换优先级了，对不起（

**Comment by Zero-Fanker** [comment]
@shuiping233 @kk7k7k558 @Renko-ji @Crossfield-ClassDestroyer   0.99.916a 已包含

**Comment by shuiping233** [comment]
0.99.916a测试通过，地图在标准模式和淘金热模式均可正常使用
