### ISSUE TITLE
#Bug#猛禽之城初始单位三星

### ISSUE THREAD

**Issue by NightSkyTS** [Zero-Fanker/RN_All_Issues#794]
【现象】：如题
![5](https://user-images.githubusercontent.com/78950858/183944353-9a67b853-5c34-4e54-b000-d0e2711de064.png)
【发现版本号】：0.99.914a9

**Comment by shuiping233** [comment]
已通过mr流程提交了修改过后的地图

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/184264704-44727c8a-f5de-44e6-8e6d-0c90ed86e802.png)
内部测试已经通过，下版本内测合并修改后将会再进行一次测试

**Comment by shuiping233** [comment]
@shuiping233 0.99.914b3待测

**Comment by shuiping233** [comment]
![image](https://github.com/user-attachments/assets/e9c88276-e7b0-4a36-b072-8a9ca0cb14e8)
0.99.915测试通过
