### ISSUE TITLE
#Bug#

### ISSUE THREAD

**Issue by pipi555555** [Zero-Fanker/RN_All_Issues#802]
【现象】：遭遇战：绝对巅峰地图，玩家为观察者，三国均为冷酷电脑，标准作战模式。美国苏联（2、3号位）结盟对抗尤里（1号位），在运行一段时间后崩溃，玩家并未进行除移动视角外的操作
【反馈人】：
【发现版本号】：0.99.913
【影响范围】：遭遇战
【产生原因】：

**Comment by shuiping233** [comment]
请按要求打包并发送debug文件到开发者邮箱，详细看这里：https://home.revengenow.top/#/QuestionNAnswer/debug

**Comment by shuiping233** [comment]
后续无法跟进，故关闭此issue
