### ISSUE TITLE
#Bug#东北朝向的高架桥头的影子位置异常

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#806]
【现象】：如题，如图
【反馈人】：shuiping233
【发现版本号】：0.99.914a9
【影响范围】：全局
【产生原因】：未知

![image](https://user-images.githubusercontent.com/49360196/187581968-5745123a-29a2-4ef5-a2e0-be2c2c2c6d3d.png)

**Comment by Zero-Fanker** [comment]
你看了几个地图就断定全局?

**Comment by NightSkyTS** [comment]
0.99.014a10，基本可以排除不是全局问题）
![1](https://user-images.githubusercontent.com/78950858/195380754-50f7bcdf-8396-454a-a768-29f45342a276.jpg)
![2](https://user-images.githubusercontent.com/78950858/195380780-13ff657f-b607-4d37-b64c-cfb78d3093c3.png)
![3](https://user-images.githubusercontent.com/78950858/195380788-31c47aa8-914c-4ccb-ab49-485b98f72aea.jpg)
![4](https://user-images.githubusercontent.com/78950858/195381517-c315818f-93d4-4c95-a91c-54a8732b61a5.png)

**Comment by Zero-Fanker** [comment]
那么就是地图问题，@shuiping233 请给出具体的地图清单

**Comment by shuiping233** [comment]
- #813 
以及工头你给我的盟军主线第六关

**Comment by Zero-Fanker** [comment]
没发布的地图找地图师直接改

**Comment by shuiping233** [comment]
桥头影子问题仅在部分地图出现，故关闭此issue
