### ISSUE TITLE
#Bug# Windows11更新至22H2版本后CNCNet客户端无法运行

### ISSUE THREAD

**Issue by zbc258** [Zero-Fanker/RN_All_Issues#809]
【现象】：在最新正式版系统中，复仇时刻的启动器无法运行，管理员权限、改兼容性都无法解决。
【反馈人】：周必成
【发现版本号】：0.99.913正式版
【影响范围】：整个游戏
【产生原因】：win11系统22h2正式版更新，一些低版本库不再被支持。

**Comment by shuiping233** [comment]
请提供客户端日志以便于开发者定位问题位置，请参考：https://home.revengenow.top/#/QuestionNAnswer/DTA-crash

**Comment by zbc258** [comment]
> 请提供客户端日志以便于开发者定位问题位置，请参考：https://home.revengenow.top/#/QuestionNAnswer/DTA-crash

因为客户端根本就没启动，所以也不存在崩溃，更没有日志产生了。

**Comment by shuiping233** [comment]
> > 请提供客户端日志以便于开发者定位问题位置，请参考：https://home.revengenow.top/#/QuestionNAnswer/DTA-crash
> 
> 因为客户端根本就没启动，所以也不存在崩溃，更没有日志产生了。

我这边还不能更新到22h2，暂且没法复现问题

**Comment by shuiping233** [comment]
已证实通过windows update 更新系统至22h2版本后，客户端无法正常启动
![GIF5](https://user-images.githubusercontent.com/49360196/193410107-5a4adb59-0089-4e67-9c94-b375ac5cc3e9.gif)

**Comment by Creling** [comment]
这个issue有什么后续吗？

**Comment by Zero-Fanker** [comment]
玩家群已更新群测



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月19日(星期四) 晚上9:14
收件人: ***@***.***&gt;;
抄送: "Zero ***@***.******@***.***&gt;;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug# Windows11更新至22H2版本后CNCNet客户端无法运行 (Issue #809)




 
这个issue有什么后续吗？

**Comment by shuiping233** [comment]
![GIF41](https://user-images.githubusercontent.com/49360196/213879504-90e47ac9-688e-42fe-831b-a78c9859eb65.gif)
0.99.914b1测试通过，win11 22h2版本已经可以启动复仇时刻客户端
