### ISSUE TITLE
#Bug#多人游戏下油井金钱提示字符串消失过快

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#810]
【现象】：字符串飘动特别快，还没来得及看清就没了
【反馈人】：
【发现版本号】：0.99.902
【影响范围】：多人对战
【产生原因】：浮动字符提示效果刷新机制有问题

**Comment by Zero-Fanker** [comment]
@shuiping233 0.99.914a10 已调整

**Comment by shuiping233** [comment]
0.99.914a10测试通过
![GIF12](https://user-images.githubusercontent.com/49360196/195965428-48909ab4-07c2-43cf-a548-346caa1800fe.gif)

**Comment by shuiping233** [comment]
@klighting444 请帮忙按0.99.914a10归档
