### ISSUE TITLE
#建议反馈#取消忠武级炮弹爆炸时的爆炸泛光以及降低其弹头爆炸产生火焰和爆炸碎片的概率

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#811]
【描述】如题
【原因】爆炸炫光过于耀眼，按照原版标准来看高伤害武器才使用爆炸炫光，取消爆炸炫光可以减少性能负担；爆炸产生的火焰过多也是同理
【期望解决时间】下一正式版

[注]:不按照格式填写会被视作无效。

**Comment by shuiping233** [comment]
![GIF8](https://user-images.githubusercontent.com/49360196/193995662-d29aed3f-48e2-4897-b4db-4d5974cbb5c4.gif)
内部版本测试中已取消爆炸泛光以及降低火焰产生概率，效果如图
效果待正式版实装

**Comment by Zero-Fanker** [comment]
@NightSkyTS 0.99.914a10 已调整

**Comment by shuiping233** [comment]
预期效果：炮弹爆炸只产生一个碎片，爆炸时没有白色的武器炫光

**Comment by NightSkyTS** [comment]
0.99.914a10测试完毕，基本符合预期，一发炮弹只会产生一个碎片，有时甚至不会产生碎片，爆炸时并未看到白色炫光
![忠武级2](https://user-images.githubusercontent.com/78950858/195480457-b43e33f1-2c63-44c4-ba37-d3fad228f285.gif)
![忠武级3](https://user-images.githubusercontent.com/78950858/195480523-eb3cdf39-08c3-4843-a3b5-bf5e57d20fd4.gif)

**Comment by Zero-Fanker** [comment]
@klighting444 小碗帮忙归档
