### ISSUE TITLE
#Bug#遭遇战地图“湛蓝群岛”中高架桥头的影子出现异常

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#812]
【现象】：如题，如图。坐标：123,210
【反馈人】：shuiping233
【发现版本号】：0.99.914a10
【影响范围】：全局
【产生原因】：地形问题，高架桥头画到悬崖上了

![image](https://user-images.githubusercontent.com/49360196/197116882-e2c77f59-53aa-4516-a0c8-67998a4c1e12.png)

![image](https://user-images.githubusercontent.com/49360196/197116631-57809a48-d808-4f8f-9f12-4d69d0592862.png)

**Comment by shuiping233** [comment]
![Snipaste_2022-10-23_01-17-18](https://user-images.githubusercontent.com/49360196/197353738-25709a24-7068-4d63-a560-8f29b59c9673.png)
![Snipaste_2022-10-23_01-17-11](https://user-images.githubusercontent.com/49360196/197353745-cd83906e-a3a1-48b8-b5e9-85d7b303f682.png)
![Snipaste_2022-10-23_01-17-04](https://user-images.githubusercontent.com/49360196/197353750-d872bbe6-1a31-4906-becb-a95076a5dd37.png)
![Snipaste_2022-10-23_01-16-58](https://user-images.githubusercontent.com/49360196/197353763-b1a3d8d3-9398-4ee8-9939-3133aa843787.png)
除此之外还发现此地图其他桥梁也有此问题，目前已修复所有桥梁。

**Comment by shuiping233** [comment]
> 这些个改动是不是早就发布出去了？

理论上是的

**Comment by Zero-Fanker** [comment]
> > 这些个改动是不是早就发布出去了？
> 
> 理论上是的

那你做下归档
