### ISSUE TITLE
#Bug#

### ISSUE THREAD

**Issue by youziQAQ** [Zero-Fanker/RN_All_Issues#814]
[【现象】：番外任务灯火之城，打到最后任务消灭所有盟军，科技巨炮打掉海岸巡防艇后闪退
【反馈人】：（如果是自己的帐户可以不填，代他人提交必填）
【发现版本号】：（0.99.911
【影响范围】：番外任务
【产生原因】：本关有友军“中立”盟军单位攻击敌军，帮忙打掉了一堆，后期任务“消灭所有敌人”不知道是否包括这些
[注释]:例子：
[debug.20221101-185407.log](https://github.com/Zero-Fanker/RN_All_Issues/files/9909931/debug.20221101-185407.log)
[](url)
[debug.20221101-185407.log](https://github.com/Zero-Fanker/RN_All_Issues/files/9909954/debug.20221101-185407.log)

**Comment by shuiping233** [comment]
> [【现象】：番外任务灯火之城，打到最后任务消灭所有盟军，科技巨炮打掉海岸巡防艇后闪退 【反馈人】：（如果是自己的帐户可以不填，代他人提交必填） 【发现版本号】：（0.99.911 【影响范围】：番外任务 【产生原因】：本关有友军“中立”盟军单位攻击敌军，帮忙打掉了一堆，后期任务“消灭所有敌人”不知道是否包括这些 [注释]:例子： [debug.20221101-185407.log](https://github.com/Zero-Fanker/RN_All_Issues/files/9909931/debug.20221101-185407.log) [debug.20221101-185407.log](https://github.com/Zero-Fanker/RN_All_Issues/files/9909954/debug.20221101-185407.log)

#733 已经提及相同问题，并且内部版本已经修复，敬请期待下一版本，故关闭此issue
