### ISSUE TITLE
#Bug#特别行动2-“烈性炸药”中需要摧毁“钻矿设备”才能通关

### ISSUE THREAD

**Issue by youziQAQ** [Zero-Fanker/RN_All_Issues#819]
【现象】：打了一会特别行动2-烈性炸药，都打完了怎么还不通关，水瓶给我圈出来这个玩意，钻矿设备也属于敌军，原来是剩这个没打掉
【反馈人】：狗柚子
影响通关
【发现版本号】：.99.913
【产生原因】：钻矿设备属于苏军阵营（）
![)QDD)`RJCQ$FIY2DQ1JZFVD](https://user-images.githubusercontent.com/117177025/199881087-df5ff69f-2605-45fd-9e85-e70bccd39f62.png)
![D74_ $N}} $FCNND)U4EZE](https://user-images.githubusercontent.com/117177025/199881094-dbaeabf9-6dd1-46f8-a35d-c62c6f03b1c9.png)

**Comment by youziQAQ** [comment]
建议做成炸掉所有生产建筑就一起卖掉，这个钻矿玩意还真不好注意

**Comment by shuiping233** [comment]
> 建议做成炸掉所有生产建筑就一起卖掉，这个钻矿玩意还真不好注意

我同意）

**Comment by shuiping233** [comment]
目前已经修改任务胜利条件：简单和中等难度下只需摧毁苏军所有生产建筑即可胜利，困难模式下需要摧毁除去钻矿设备之外的其他所有苏军建筑

**Comment by shuiping233** [comment]
经过讨论，钻矿设备保持原有苏俄所属不变，故关闭此issue
