### ISSUE TITLE
#Bug#特别行动2-烈性炸药通关会进入制作者名单而不是接下一关

### ISSUE THREAD

**Issue by youziQAQ** [Zero-Fanker/RN_All_Issues#820]
【现象】：（特别行动2-烈性炸药通关会进入制作者名单而不是接下一关
【反馈人】：狗柚子
【发现版本号】：0.99.913
【影响范围】：影响通关
![V)98QLBX(8GG2_}YKBGI8I9](https://user-images.githubusercontent.com/117177025/199881383-ef58f04c-7e01-49b6-9cfe-cbff0629442a.png)

**Comment by shuiping233** [comment]
特意这么做的，因为特别行动关卡的顺序没有剧情时间上的关联
