### ISSUE TITLE
#Bug#特别行动1-弹弹弹 通关会显示 无法读取情景，而不是接下一关

### ISSUE THREAD

**Issue by youziQAQ** [Zero-Fanker/RN_All_Issues#821]
【现象】：特别行动1-弹弹弹通关会显示 无法读取情景，而不是接下一关
【反馈人】：狗柚子
【发现版本号】：0.99.913
【影响范围】：影响通关

**Comment by shuiping233** [comment]
内部版本已经修复此问题，敬请期待
- https://github.com/Zero-Fanker/RN_Internal_Issues/issues/406
