### ISSUE TITLE
#Bug#离子轰炸机无法建造

### ISSUE THREAD

**Issue by youziQAQ** [Zero-Fanker/RN_All_Issues#826]
【现象】：偷t4偷到了离子轰炸机，但是我有一堆停机坪都无法建造(图标是黑的)
【反馈人】：狗柚子
【发现版本号】：0.99.913
【影响范围】：（遭遇战、多人联机
【产生原因】：是否有别的建造条件，或者是否要移除此单位但是忘记/移除失败，T4仍然可以偷到此单位

**Comment by youziQAQ** [comment]
![M7LKM 6{{$R~~33UL42H}AW](https://user-images.githubusercontent.com/117177025/200126581-2831d698-85bd-45ea-b936-dcd36b1a2d53.png)
补图

**Comment by Zero-Fanker** [comment]
因为这个只能在苏军机场造
