### ISSUE TITLE
#Bug#“石油大亨”模式下开启基地高强度选项导致尤里无法建造后续建筑

### ISSUE THREAD

**Issue by NightSkyTS** [Zero-Fanker/RN_All_Issues#833]
【现象】：如题所示，不开启基地高强度选项或选择其他阵营不会有这个问题
【发现版本号】：0.99.914a10
【影响范围】：遭遇战
![QQ图片20221112185220](https://user-images.githubusercontent.com/78950858/201470750-dcb8dc1f-644b-4e6d-82d4-9c04f095dd25.jpg)

**Comment by Zero-Fanker** [comment]
已证实，程序处理逻辑存在缺陷，已修正等待内测更新

**Comment by Zero-Fanker** [comment]
@Crossfield-ClassDestroyer shuiping这两天在忙，帮看下是不是忘记归档了

**Comment by shuiping233** [comment]
0.99.916a测试通过
![image](https://github.com/user-attachments/assets/16a63e20-e5eb-464b-989f-9767eedec140)
