### ISSUE TITLE
#Bug#载入画面的文本框不再是原版的半透明效果而变成了全黑

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#837]
【现象】：如标题
【反馈人】：
【发现版本号】：0.99.911
【影响范围】：载入图的文字背景框
【产生原因】：cncnet 代码缺陷 参考：https://github.com/CnCNet/yr-patches/commit/fd477cfcef14fe5a2c2d179ec1ead85bc62bc6d4

**Comment by shuiping233** [comment]
0.99.916b2测试通过
![image](https://github.com/user-attachments/assets/73501fae-39b3-4cf0-b4dd-c67d7d2c9fc3)
