### ISSUE TITLE
#Bug#【番外篇-超时空突袭战】困难，占领黑色实验室没有任务成功

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#84]
【现象】：【番外篇-超时空突袭战】困难，占领黑色实验室没有任务成功，之后卖掉也不行，导致任务无法完成
【反馈人】：奇奇
【影响范围】：任务过关
【产生原因】：使用工程师占领黑色实验室

**Comment by shuiping233** [comment]
Zero Fanker
assigned issue to   IEafeoN
指派人员

**Comment by Zero-Fanker** [comment]
H1024已调整，请验证 @shuiping233

**Comment by shuiping233** [comment]
H1024测试结果：
![image](https://user-images.githubusercontent.com/49360196/97100120-1fa4d380-16cb-11eb-8ef7-915191cbe5eb.png)该问题已经解决
