### ISSUE TITLE
#Bug#德国条顿Ⅱ型残骸无法正确显示名称

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#851]
【现象】：如题，如图
【反馈人】：shuiping233
【发现版本号】：0.99.914b
【影响范围】：全局
【产生原因】：缺少对应的csf文本内容

![GIF34](https://user-images.githubusercontent.com/49360196/211851313-23b8d43f-feb5-4ac9-910d-729964da01ae.gif)

**Comment by Zero-Fanker** [comment]
你这个有必要用动图吗？两个静态截图不就够了吗？

**Comment by Zero-Fanker** [comment]
0.99.914b1 已修正

**Comment by shuiping233** [comment]
> 你这个有必要用动图吗？两个静态截图不就够了吗？

这个是显示bug的锅，我鼠标放上去一会他只会突然显示一下文本然后立刻消失了，我用gif录下来才截到的

**Comment by Zero-Fanker** [comment]
键盘printscreen了解一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月14日(星期六) 晚上6:58
收件人: ***@***.***&gt;;
抄送: "Zero ***@***.******@***.***&gt;;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#德国条顿Ⅱ型残骸无法正确显示名称 (Issue #851)




  
你这个有必要用动图吗？两个静态截图不就够了吗？
  
这个是显示bug的锅，我鼠标放上去一会他只会突然显示一下文本然后立刻消失了，我用gif录下来才截到的

**Comment by shuiping233** [comment]
我咩有那个自信能截到只显示0.1s就消失的文本

**Comment by Zero-Fanker** [comment]
虽然偶尔会有那个文本闪烁很快的bug 但是大部分时候那个文本持续都是好几秒



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月14日(星期六) 晚上7:03
收件人: ***@***.***&gt;;
抄送: "Zero ***@***.******@***.***&gt;;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#德国条顿Ⅱ型残骸无法正确显示名称 (Issue #851)




 
我咩有那个自信能截到只显示0.1s就消失的文本

**Comment by shuiping233** [comment]
> 虽然偶尔会有那个文本闪烁很快的bug 但是大部分时候那个文本持续都是好几秒
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年1月14日(星期六) 晚上7:03 收件人: ***@***.***&gt;; 抄送: "Zero ***@***.******@***.***&gt;; 主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#德国条顿Ⅱ型残骸无法正确显示名称 (Issue #851) 我咩有那个自信能截到只显示0.1s就消失的文本 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

但是也是略微烦人的，哎呀下次我转截图就好了

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/212468976-84b64bdc-47d5-4e19-8747-329de45efba7.png)
0.99.914b1测试通过

**Comment by shuiping233** [comment]
@klighting444 请帮忙按0.99.914b1归档
