### ISSUE TITLE
#Bug#宣传飞艇的医疗效果对条顿残骸有效

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#86]
【现象】：宣传飞艇的医疗效果对条顿残骸有效（包括宣传中心）
【反馈人】：SHUIPING
【影响范围】：残骸可能会无法修复
【产生原因】：靠近宣传中心或者宣传飞艇
![image](https://user-images.githubusercontent.com/49360196/56089211-5426b500-5ec2-11e9-8fe1-ab254fe22ebb.png)

**Comment by shuiping233** [comment]
Zero Fanker
assigned issue to   Zero Fanker
edited description
2019-02-02
 Zero Fanker
changed status to open
已经着手修复，需要测试。

**Comment by shuiping233** [comment]
![QQ截图20190502093051](https://user-images.githubusercontent.com/49360196/57052908-0630f000-6cbd-11e9-817c-b36232fc90cf.png)
G0428E经过测试，该问题已经解决

**Comment by shuiping233** [comment]
![QQ截图20190502102122](https://user-images.githubusercontent.com/49360196/57053950-1dbfa700-6cc4-11e9-86bd-31ec38f7f6cd.png)
宣传飞艇对条顿残骸的医疗效果消失，不回复残骸的血量，但是医疗的显示效果仍然存在
