### ISSUE TITLE
#建议反馈#苏军主线第一关“红色沙文”中占领雷达站后增援的海军缺少使用场景

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#860]
【描述】如题
【原因】两潜艇加一无畏怎么打河道里一堆乌贼？而且对面一堆防空炮，无畏也打不出效果

【备注】：我只是希望这个援军有个合理的解释，因为是一个玩家转牛角尖问的问题

**Comment by Zero-Fanker** [comment]
牛角尖问题有啥好解释的，本来是彩蛋，难不成直接变成强拆? 过于好用于是变成逃课利器，反而成了攻略打法吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月2日(星期四) 上午10:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Zero-Fanker/RN_All_Issues] #建议反馈#苏军主线第一关“红色沙文”中占领雷达站后增援的海军缺少使用场景 (Issue #860)




 
【描述】如题
 【原因】两潜艇加一无畏怎么打河道里一堆乌贼？而且对面一堆防空炮，无畏也打不出效果
 
【备注】：我只是希望这个援军有个合理的解释，因为是一个玩家转牛角尖问的问题

**Comment by shuiping233** [comment]
![image](https://user-images.githubusercontent.com/49360196/216218138-9679f8bd-1cea-43e9-bfe0-2f7fdf1c6731.png)

**Comment by shuiping233** [comment]
既然工头已经解释了问题，那么我就关掉了）
