### ISSUE TITLE
#Bug#盟军暴风攻击队的炸弹爆炸动画没有了

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#87]
【现象】：盟军暴风攻击队的炸弹爆炸动画没有了，不过有伤害
【反馈人】：SHUIPING
【影响范围】：盟军阵营
【产生原因】：不知道

![image](https://user-images.githubusercontent.com/49360196/56089195-1a55ae80-5ec2-11e9-8484-a611795ba477.png)

**Comment by shuiping233** [comment]
Zero Fanker
assigned issue to   Zero Fanker
marked as minor
edited description
2019-02-02
 Zero Fanker
changed status to open
已经将缺失的文件打包

**Comment by Zero-Fanker** [comment]
需要测试验证

**Comment by shuiping233** [comment]
> 需要测试验证


经过测试（G0405），该问题已经解决

![QQ截图20190421145413](https://user-images.githubusercontent.com/49360196/56466480-5f8b5a80-6445-11e9-9741-7e2d1c5a44b6.png)
