### ISSUE TITLE
#Bug#尤里钻地车的混乱效果会触及到飞机上

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#88]
【现象】：钻地车的攻击能影响到飞行单位

【反馈人】：shuiping

【影响范围】：影响飞行单位

【产生原因】：武器效果的立体判定缺陷

**Comment by shuiping233** [comment]
Zero Fanker
assigned issue to   Zero Fanker
marked as minor
edited description
2019-02-02
 Zero Fanker
changed status to open
已经做了简单调整，待测试。

**Comment by Zero-Fanker** [comment]
需要测试验证

**Comment by shuiping233** [comment]
> 需要测试验证

需要我去验证么？

**Comment by Zero-Fanker** [comment]
有时间可以自己验证，也可以找其他内测人员验证。------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2019年4月21日(星期天) 中午1:03
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Assign"<assign@noreply.github.com>;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#尤里钻地车的混乱效果会触及到飞机上 (#88)


 
需要测试验证
  
需要我去验证么？
 
&mdash;

**Comment by shuiping233** [comment]
> >需要测试验证需要我去验证么？
> 有时间可以自己验证，也可以找其他内测人员验证。

![QQ截图20190501095942](https://user-images.githubusercontent.com/49360196/57003263-eb487800-6bf7-11e9-8bbc-d513414b1bb9.png)
G0428版本经过测试，该问题已经解决
