### ISSUE TITLE
#Bug#“指挥官的噩梦”合作任务第二关“黑精灵之森”加载地图时游戏进程无响应

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#885]
【现象】：如题，如图，0.99.914b3也是相同的情况
【反馈人】：shuiping233
【发现版本号】：0.99.914
【影响范围】：未知
【产生原因】：未知

![Snipaste_2023-06-30_08-52-41](https://github.com/Zero-Fanker/RN_All_Issues/assets/49360196/9492d697-fb9b-4160-914b-8d3b8def9026)

**Comment by Zero-Fanker** [comment]
这问题现在还有？

**Comment by shuiping233** [comment]
> 这问题现在还有？

已确认0.99.916a仍然存在此问题

**Comment by Zero-Fanker** [comment]
> > 这问题现在还有？
> 
> 已确认0.99.916a仍然存在此问题

奇怪我好像复现不出来，你有试过在另一个纯净安装的路径下测试吗

**Comment by shuiping233** [comment]
> > > 这问题现在还有？
> > 
> > 
> > 已确认0.99.916a仍然存在此问题
> 
> 奇怪我好像复现不出来，你有试过在另一个纯净安装的路径下测试吗

我在全新安装了一个0.99.915，然后使用0.99.916a更新包覆盖进去，还是有这个问题
![image](https://github.com/user-attachments/assets/979d8416-bcd6-4898-b076-74a14c369963)

**Comment by shuiping233** [comment]
0.99.916b2测试通过
![image](https://github.com/user-attachments/assets/a9e39256-e9e9-497f-9fe9-822a07092b16)
