### ISSUE TITLE
#Bug#切屏可能导致游戏内控件显示效果异常

### ISSUE THREAD

**Issue by youziQAQ** [Zero-Fanker/RN_All_Issues#887]
【现象】：切屏有时候会导致返回无法按键
【反馈人】：（狗柚子
【发现版本号】：914
【影响范围】：影响游戏
![image](https://github.com/Zero-Fanker/RN_All_Issues/assets/117177025/e1163124-5a86-411a-b160-d524bde8048f)

**Comment by shuiping233** [comment]
这要怎么复现呀，请提供一个能复现的方法，是全屏还是窗口化都有问题吗？

**Comment by youziQAQ** [comment]
> 这要怎么复现呀，请提供一个能复现的方法，是全屏还是窗口化都有问题吗？

目前全屏出现的，不知道为啥，BGM正常播放啥都按不了

**Comment by youziQAQ** [comment]
![image](https://github.com/Zero-Fanker/RN_All_Issues/assets/117177025/574bf605-37df-4a91-92af-dfc57f0c54d1)
又切了几次，闪退回来了……

**Comment by shuiping233** [comment]
你好好整理一下，完整的说点我能理解全貌的话）

**Comment by youziQAQ** [comment]
目前试着连续切屏，几次实验是：
有一次出现了如图什么都按不了，音乐继续
多次出现按键错位（正常ESC界面但右侧按键错位，原位置剩下黑条），音乐继续，但是卡一下后自动闪退

**Comment by shuiping233** [comment]
> 目前试着连续切屏，几次实验是： 有一次出现了如图什么都按不了，音乐继续 多次出现按键错位（正常ESC界面但右侧按键错位，原位置剩下黑条），音乐继续，但是卡一下后自动闪退

你是在全屏模式下切屏的对吧

**Comment by youziQAQ** [comment]
都是全屏，这个复现成功
![image](https://github.com/Zero-Fanker/RN_All_Issues/assets/117177025/97bce49d-94eb-46af-b342-57bcd685e237)

**Comment by youziQAQ** [comment]
**
![image](https://github.com/Zero-Fanker/RN_All_Issues/assets/117177025/ac70a9d8-df91-4fc8-be2d-e66c26f63e5e)
第二种情况复现图片

**Comment by youziQAQ** [comment]
全屏切屏这两种情况和正常情况随机出现（）

**Comment by youziQAQ** [comment]
> 全屏切屏这两种情况和正常情况随机出现（）

并且很容易闪退，目前已经三次了

**Comment by shuiping233** [comment]
使用0.99.914正式版全屏1366x768进行10次切屏测试，未发现游戏控件偏移和不显示的情况

**Comment by youziQAQ** [comment]
> 使用0.99.914正式版全屏1366x768进行10次切屏测试，未发现游戏控件偏移和不显示的情况

我的是1280*720全屏

**Comment by Zero-Fanker** [comment]
由于长时间无下文，且无法复现，故关闭
