### ISSUE TITLE
#Bug#

### ISSUE THREAD

**Issue by 85922126** [Zero-Fanker/RN_All_Issues#893]
【现象】：（无法正常登入游戏）
【反馈人】：（85922126
![屏幕截图 2024-08-10 175030](https://github.com/user-attachments/assets/73a67126-815a-4cfd-9300-c718c13160df)
）
【发现版本号】：（0.99.914）
【影响范围】：（无法正常登入游戏）
【产生原因】：（无法访问以释放的对象）

[注释]:例子：
[注释]:【现象】：韩国火炮、洲际导弹的信标可以被超时空传送、铁幕装置影响
[注释]:【反馈人】：永恒_叶
[注释]:【发现版本号】：0.99.F1028A
[注释]:【影响范围】：影响带有AI的对局
[注释]:【产生原因】：AI新机制引入

**Comment by shuiping233** [comment]
> 【现象】：（无法正常登入游戏） 【反馈人】：（85922126 ![屏幕截图 2024-08-10 175030](https://private-user-images.githubusercontent.com/178012050/356804747-73a67126-815a-4cfd-9300-c718c13160df.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzOTE1OTcsIm5iZiI6MTcyMzM5MTI5NywicGF0aCI6Ii8xNzgwMTIwNTAvMzU2ODA0NzQ3LTczYTY3MTI2LTgxNWEtNGNmZC05MzAwLWM3MThjMTMxNjBkZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMVQxNTQ4MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTA0YjAxNTU4N2ZkM2M3MmQ0NDg2MmZlOWViM2RjZTJjYTkwMTM3NTAyODRkMmFmNzQ2YjBjMGJlODE5ZjhhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tpyQhXr25B2-63MwY82xRWleh31yuGg82oHqcydVwbg) ） 【发现版本号】：（0.99.914） 【影响范围】：（无法正常登入游戏） 【产生原因】：（无法访问以释放的对象）

请提供client日志以供分析，日志具体位置请参考 [客户端崩溃后如何处理log文件](https://home.revengenow.top/QuestionNAnswer/DTA-crash#%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%B4%A9%E6%BA%83%E5%90%8E%E5%A6%82%E4%BD%95%E5%A4%84%E7%90%86log%E6%96%87%E4%BB%B6)

**Comment by Zero-Fanker** [comment]
缺乏有效信息
