### ISSUE TITLE
#Bug#磁暴线圈在过载模式下无法正确攻击射程边缘的目标

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#894]
【现象】：使用磁暴步兵给磁暴线圈充电，然后在攻击其射程边缘的地面，磁暴线圈会射不出来
【反馈人】：
【发现版本号】：0.99.914
【影响范围】：影响所有可充能过载的防御塔建筑，目前主要影响磁暴线圈本身
【产生原因】：洛林导弹发射器逻辑引入的新问题

![QQ图片20190623170354](https://user-images.githubusercontent.com/49360196/59973987-2902c500-95d9-11e9-80ae-851c1b04db90.gif)

**Comment by Zero-Fanker** [comment]
@shuiping233 @kk7k7k558 @Renko-ji @Crossfield-ClassDestroyer   0.99.916a 已包含

**Comment by shuiping233** [comment]
#170

**Comment by shuiping233** [comment]
0.99.916a 测试通过
![GIF113](https://github.com/user-attachments/assets/4554d7a0-bf21-4684-8ed9-b11650282374)
