### ISSUE TITLE
#Bug#军医步兵单位的鼠标动画错误

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#895]
【现象】：用了和电力管理一样的鼠标动画，而应该是一个治疗的动画
【反馈人】：
【发现版本号】：0.99.915
【影响范围】：生化危机第一关任务
【产生原因】：未正确指定鼠标动画

**Comment by Zero-Fanker** [comment]
@shuiping233 @kk7k7k558 @Renko-ji @Crossfield-ClassDestroyer   0.99.916a 已包含

**Comment by shuiping233** [comment]
> @shuiping233 @kk7k7k558 @Renko-ji @Crossfield-ClassDestroyer 0.99.916a 已包含

0.99.916a测试通过，军医治疗步兵显示的鼠标动画已经正常
![image](https://github.com/user-attachments/assets/5db20eb2-7326-412f-9f0b-45f6088edb2b)
