### ISSUE TITLE
#Bug#英国狙击手无法对油桶弹药箱等造成伤害

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#898]
【现象】：狙击手会把这些当成大型建筑设施，则会对其只使用辅助弹头而不产生实际伤害
【反馈人】：
【发现版本号】：0.99.914
【影响范围】：主要影响任务通关体验
【产生原因】：狙击手新的武器机制导致没有使用正确的弹头数据

**Comment by Zero-Fanker** [comment]
0.99.916a3 已修复 @shuiping233 @Crossfield-ClassDestroyer @Renko-ji

**Comment by shuiping233** [comment]
0.99.916a3测试通过
![GIF120](https://github.com/user-attachments/assets/d1d53f4d-b0bb-41e9-9d2f-1e75ba65421c)
