### ISSUE TITLE
#Bug#载具在造船厂维修时无法被选中和移开

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#899]
【现象】：潜艇/驱逐舰在船厂维修时不可被选中，不可被移开
【反馈人】：
【发现版本号】：0.99.914
【影响范围】：所有模式海军维修时的操作
【产生原因】：优化载具在工厂中的选中状态时引入的新体验问题
![GIF121](https://github.com/user-attachments/assets/00615ad2-ae19-4902-b9e8-cfb264ca8707)

**Comment by Zero-Fanker** [comment]
0.99.916a3 已修复 @shuiping233 @Suli1337 @RN-Hydra @Renko-ji @Crossfield-ClassDestroyer

**Comment by shuiping233** [comment]
0.99.916a3测试通过
![GIF122](https://github.com/user-attachments/assets/4609d6e6-17f4-4cce-b3b6-3cd2e52fd9e9)
