### ISSUE TITLE
#Bug#占领/心控敌方建筑时可能导致建筑动画消失

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#900]
【现象】：当敌我双方都有电时，占领对方耗电建筑或者心控，会导致对方建筑的动画消失，例如控制磁暴线圈和光棱塔
【反馈人】：
【发现版本号】：原版YR
【影响范围】：影响视觉体验
【产生原因】：WWSB

**Comment by Zero-Fanker** [comment]
0.99.916b2 已包含调整 @shuiping233

**Comment by shuiping233** [comment]
0.99.916b2测试通过

0.99.916a3效果：

![GIF132](https://github.com/user-attachments/assets/5503773a-fe63-4f45-892f-8463eda1f76f)

0.99.916b2效果：
![GIF133](https://github.com/user-attachments/assets/31de1b4a-b236-49d5-bd30-12db8d5e1c86)
