### ISSUE TITLE
#Bug#博瑞斯召唤的米格战机有时候无法正确开火

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#905]
【现象】：当Boris飞行器靠近目标后有一定概率会掠过目标而无法开火
【反馈人】：
【发现版本号】：0.99.911
【影响范围】：影响Boris召唤飞行器攻击建筑
【产生原因】：早年为修复其它问题引起的

**Comment by Zero-Fanker** [comment]
0.99.916b2 已包含调整 @shuiping233

**Comment by shuiping233** [comment]
> 0.99.916b2 已包含调整 @shuiping233

这个挺难测的，我已经用0.99.916b2打过番外苏5了，起码我打的时候米格战机都能正常开火了，0.99.916b2测试通过
