### ISSUE TITLE
#Bug#遭遇战地图“伊拉克之旅”中某个地块高度不正确以及悬崖不完整

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#908]
【现象】：如题
【反馈人】：handama
【发现版本号】：0.99.916b2
【影响范围】：遭遇战地图
【产生原因】：地编师没画好

![image](https://github.com/user-attachments/assets/33502777-5953-4781-b00e-fdad2a126972)
![image](https://github.com/user-attachments/assets/f63b8bc6-8e76-4a60-8dd7-05c12cb56bbf)

游戏内效果：
![image](https://github.com/user-attachments/assets/1d74251e-156e-4b58-b1d8-4fa555c53d05)

**Comment by shuiping233** [comment]
已提交修复
![image](https://github.com/user-attachments/assets/4562269b-943f-4020-91f5-cfa20499de9d)

**Comment by Zero-Fanker** [comment]
> 已提交修复 ![image](https://private-user-images.githubusercontent.com/49360196/389170229-4562269b-943f-4020-91f5-cfa20499de9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwODgzNzksIm5iZiI6MTczMzA4ODA3OSwicGF0aCI6Ii80OTM2MDE5Ni8zODkxNzAyMjktNDU2MjI2OWItOTQzZi00MDIwLTkxZjUtY2ZhMjA0OTlkZTlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDIxMjExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlODI3MmFjNGMxN2JhMTFmY2RhYWFkZjk3MzU2NjZlNmUyYWE5ZGJiYmMzYWUxN2ViMDllOWJiNjExYzdlNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.N4fDxg9bBe2GGhcFDKKk3DpZauABEZLqvy3rluZl_1w)

下次改完记得改对标签，new->resolved。另外，别忘了加进当前milestone

**Comment by Zero-Fanker** [comment]
@shuiping233  0.99.916b3 已调整

**Comment by shuiping233** [comment]
0.99.916b3测试通过
![image](https://github.com/user-attachments/assets/0da4a07c-97d7-4ab1-acd6-f09d62b9232e)
