### ISSUE TITLE
#Bug#谭雅部署冲锋后间隔很久才能攻击

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/RN_All_Issues#913]
【现象】：谭雅部署冲锋期间无法开火，手感不好
【反馈人】：
【发现版本号】：0.99.914
【影响范围】：主要影响任务操作，遭遇战也有少量手感影响
【产生原因】：机制设计问题

**Comment by Zero-Fanker** [comment]
@shuiping233  0.99.916b3 已调整

**Comment by shuiping233** [comment]
0.99.916b3测试通过
