### ISSUE TITLE
#Bug#喷吐胖子的抛射体爆炸动画和实际抛射体落点不匹配

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#914]
【现象】：如题
【反馈人】：鱼蛋
【发现版本号】：0.99.916b2
【影响范围】：视觉体验
【产生原因】：未知

**Comment by Zero-Fanker** [comment]
0.99.916b3 已调整

**Comment by shuiping233** [comment]
0.99.916b3测试通过
![GIF155](https://github.com/user-attachments/assets/a9e2e5ee-01fb-4fbe-bebb-cd0d04bf5d4d)
